var annotated_dup =
[
    [ "background", "structbackground.html", "structbackground" ],
    [ "bit_decoder", "structbit__decoder.html", "structbit__decoder" ],
    [ "cmp_cfg", "structcmp__cfg.html", "structcmp__cfg" ],
    [ "cmp_entity", "structcmp__entity.html", "structcmp__entity" ],
    [ "cmp_info", "structcmp__info.html", "structcmp__info" ],
    [ "cmp_max_used_bits", "structcmp__max__used__bits.html", "structcmp__max__used__bits" ],
    [ "cmp_status", "structcmp__status.html", "structcmp__status" ],
    [ "decoder_setup", "structdecoder__setup.html", "structdecoder__setup" ],
    [ "encoder_setupt", "structencoder__setupt.html", "structencoder__setupt" ],
    [ "f_fx", "structf__fx.html", "structf__fx" ],
    [ "f_fx_efx", "structf__fx__efx.html", "structf__fx__efx" ],
    [ "f_fx_efx_ncob_ecob", "structf__fx__efx__ncob__ecob.html", "structf__fx__efx__ncob__ecob" ],
    [ "f_fx_ncob", "structf__fx__ncob.html", "structf__fx__ncob" ],
    [ "fx_cob_par", "structfx__cob__par.html", "structfx__cob__par" ],
    [ "imagette_header", "structimagette__header.html", "structimagette__header" ],
    [ "l_fx", "structl__fx.html", "structl__fx" ],
    [ "l_fx_efx", "structl__fx__efx.html", "structl__fx__efx" ],
    [ "l_fx_efx_ncob_ecob", "structl__fx__efx__ncob__ecob.html", "structl__fx__efx__ncob__ecob" ],
    [ "l_fx_ncob", "structl__fx__ncob.html", "structl__fx__ncob" ],
    [ "list_head", "structlist__head.html", "structlist__head" ],
    [ "list_item", "structlist__item.html", "structlist__item" ],
    [ "multi_entry_hdr", "structmulti__entry__hdr.html", "structmulti__entry__hdr" ],
    [ "non_imagette_header", "structnon__imagette__header.html", "structnon__imagette__header" ],
    [ "offset", "structoffset.html", "structoffset" ],
    [ "rdcu_mirror", "structrdcu__mirror.html", "structrdcu__mirror" ],
    [ "rmap_instruction", "structrmap__instruction.html", "structrmap__instruction" ],
    [ "rmap_pkt", "structrmap__pkt.html", "structrmap__pkt" ],
    [ "s_fx", "structs__fx.html", "structs__fx" ],
    [ "s_fx_efx", "structs__fx__efx.html", "structs__fx__efx" ],
    [ "s_fx_efx_ncob_ecob", "structs__fx__efx__ncob__ecob.html", "structs__fx__efx__ncob__ecob" ],
    [ "s_fx_ncob", "structs__fx__ncob.html", "structs__fx__ncob" ],
    [ "smearing", "structsmearing.html", "structsmearing" ],
    [ "timestamp_cmp_ent", "structtimestamp__cmp__ent.html", "structtimestamp__cmp__ent" ]
];