cmp_tool: cmp_ent_get_lossy_cmp_par
cmp_ent_get_lossy_cmp_par()
uint16_t cmp_ent_get_lossy_cmp_par (const struct cmp_entity * ent)
get the used lossy compression parameter from the compression entity header
Parameters
ent pointer to a compression entity
Returns
the used lossy compression/round parameter on success, 0 on error
Definition at line 1268 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
         return be16_to_cpu(ent->lossy_cmp_par_used);
 }
References be16_to_cpu, and cmp_entity::lossy_cmp_par_used.
Referenced by cmp_ent_parse_generic_header(), cmp_ent_read_header(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), and test_ent_lossy_cmp_par().