cmp_tool: cmp_data_type_is_invalid
cmp_data_type_is_invalid()
int cmp_data_type_is_invalid (enum cmp_data_type data_type)
check if the compression entity data product type is supported
Parameters
data_type compression entity data product type to check
Returns
non-zero if data_type is invalid; zero if data_type is valid
Definition at line 70 of file cmp_support.c.
 {
         if (data_type <= DATA_TYPE_UNKNOWN || data_type > DATA_TYPE_F_CAM_BACKGROUND)
                 return 1;
         return 0;
 }
References DATA_TYPE_F_CAM_BACKGROUND.
Referenced by cmp_cfg_gen_par_is_invalid(), cmp_ent_cal_hdr_size(), and cmp_ent_read_header().