cmp_tool: compress_background
compress_background()
static int compress_background (const struct cmp_cfg * cfg) static
compress background data from the normal and fast cameras
Parameters
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 1986 of file cmp_icu.c.
 {
         int stream_len = 0;
         size_t i;
         struct background *data_buf = cfg->input_buf;
         struct background *model_buf = cfg->model_buf;
         struct background *up_model_buf = NULL;
         struct background *next_model_p;
         struct background model;
         struct encoder_setupt setup_mean, setup_var, setup_pix;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         stream_len = compress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                               (void **)&up_model_buf, cfg->icu_output_buf);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         {
                 unsigned int mean_used_bits, varinace_used_bits, pixels_error_used_bits;
                 switch (cfg->data_type) {
                 case DATA_TYPE_F_CAM_BACKGROUND:
                         mean_used_bits = cfg->max_used_bits->fc_background_mean;
                         varinace_used_bits = cfg->max_used_bits->fc_background_variance;
                         pixels_error_used_bits = cfg->max_used_bits->fc_background_outlier_pixels;
                         break;
                 case DATA_TYPE_BACKGROUND:
                 default:
                         mean_used_bits = cfg->max_used_bits->nc_background_mean;
                         varinace_used_bits = cfg->max_used_bits->nc_background_variance;
                         pixels_error_used_bits = cfg->max_used_bits->nc_background_outlier_pixels;
                         break;
                 }
                 configure_encoder_setup(&setup_mean, cfg->cmp_par_mean, cfg->spill_mean,
                                         cfg->round, mean_used_bits, cfg);
                 configure_encoder_setup(&setup_var, cfg->cmp_par_variance, cfg->spill_variance,
                                         cfg->round, varinace_used_bits, cfg);
                 configure_encoder_setup(&setup_pix, cfg->cmp_par_pixels_error, cfg->spill_pixels_error,
                                         cfg->round, pixels_error_used_bits, cfg);
         }
         for (i = 0;; i++) {
                 stream_len = encode_value(data_buf[i].mean, model.mean,
                                           stream_len, &setup_mean);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].variance, model.variance,
                                           stream_len, &setup_var);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].outlier_pixels, model.outlier_pixels,
                                           stream_len, &setup_pix);
                 if (stream_len <= 0)
                         return stream_len;
                 if (up_model_buf) {
                         up_model_buf[i].mean = cmp_up_model(data_buf[i].mean, model.mean,
                                 cfg->model_value, setup_mean.lossy_par);
                         up_model_buf[i].variance = cmp_up_model(data_buf[i].variance, model.variance,
                                 cfg->model_value, setup_var.lossy_par);
                         up_model_buf[i].outlier_pixels = cmp_up_model(data_buf[i].outlier_pixels, model.outlier_pixels,
                                 cfg->model_value, setup_pix.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return stream_len;
 }
References cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_up_model, compress_multi_entry_hdr(), configure_encoder_setup(), cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, encode_value(), cmp_max_used_bits::fc_background_mean, cmp_max_used_bits::fc_background_outlier_pixels, cmp_max_used_bits::fc_background_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, encoder_setupt::lossy_par, cmp_cfg::max_used_bits, mean, background::mean, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, cmp_max_used_bits::nc_background_mean, cmp_max_used_bits::nc_background_outlier_pixels, cmp_max_used_bits::nc_background_variance, outlier_pixels, background::outlier_pixels, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, cmp_cfg::spill_variance, variance, and background::variance.
Referenced by icu_compress_data().