cmp_tool: put_n_bits32
put_n_bits32()
static int put_n_bits32 (uint32_t value, unsigned int n_bits, int bit_offset, uint32_t * bitstream_adr, unsigned int max_stream_len) static
put the value of up to 32 bits into a big endian bitstream
Parameters
value the value to put into the bitstream
n_bits number of bits to put into the bitstream
bit_offset bit index where the bits will be put, seen from the very beginning of the bitstream
bitstream_adr this is the pointer to the beginning of the bitstream (can be NULL)
max_stream_len maximum length of the bitstream in bits; is ignored if bitstream_adr is NULL
Returns
length in bits of the generated bitstream on success; returns negative in case of erroneous input; returns CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 369 of file cmp_icu.c.
 {
         /*
          *                               UNSEGMENTED
          * |-----------|XXXXXX|---------------|--------------------------------|
          * |-bits_left-|n_bits|-------------------bits_right-------------------|
          * ^
          * local_adr
          *                               SEGMENTED
          * |-----------------------------|XXX|XXX|-----------------------------|
          * |----------bits_left----------|n_bits-|---------bits_right----------|
          */
         unsigned int bits_left = bit_offset & 0x1F;
         unsigned int bits_right = 64 - bits_left - n_bits;
         unsigned int shift_left = 32 - n_bits;
         int stream_len = (int)(n_bits + (unsigned int)bit_offset);
         uint32_t *local_adr;
         uint32_t mask;
         /* Leave in case of erroneous input */
         if (bit_offset < 0)
                 return -1;
         if (n_bits == 0)
                 return stream_len;
         if ((int)shift_left < 0)  /* check n_bits <= 32 */
                 return -1;
         if (!bitstream_adr)  /* Do we need to write data to the bitstream? */
                 return stream_len;
         /* Check if bitstream buffer is large enough */
         if ((unsigned int)stream_len > max_stream_len) {
                 debug_print("Error: The buffer for the compressed data is too small to hold the compressed data. Try a larger buffer_length parameter.\n");
                 return CMP_ERROR_SMALL_BUF;
         }
         local_adr = bitstream_adr + (bit_offset >> 5);
         /* clear the destination with inverse mask */
         mask = (0XFFFFFFFFU << shift_left) >> bits_left;
         *(local_adr) &= ~mask;
         /* put (the first part of) the value into the bitstream */
         *(local_adr) |= (value << shift_left) >> bits_left;
         /* Do we need to split the value over two words (SEGMENTED case) */
         if (bits_right < 32) {
                 local_adr++;  /* adjust address */
                 /* clear the destination */
                 mask = 0XFFFFFFFFU << bits_right;
                 *(local_adr) &= ~mask;
                 /* put the 2nd part of the value into the bitstream */
                 *(local_adr) |= value << bits_right;
         }
         return stream_len;
 }
References CMP_ERROR_SMALL_BUF, and debug_print.
Referenced by encode_normal(), encode_value_multi(), encode_value_none(), encode_value_zero(), pad_bitstream(), test_pad_bitstream(), and test_put_n_bits32().