cmp_tool: cmp_aux_data_type_is_used
cmp_aux_data_type_is_used()
int cmp_aux_data_type_is_used (enum cmp_data_type data_type)
check if an auxiliary science compression data type is used
Parameters
data_type compression data type
Returns
1 when data_type is an auxiliary science data type, otherwise 0
Definition at line 296 of file cmp_support.c.
 {
         switch (data_type) {
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_SMEARING:
         case DATA_TYPE_F_CAM_OFFSET:
         case DATA_TYPE_F_CAM_BACKGROUND:
                 return 1;
         default:
                 return 0;
         }
 }
References data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_OFFSET, and DATA_TYPE_SMEARING.
Referenced by cmp_cfg_aux_is_invalid(), cmp_cfg_icu_is_invalid(), and decompressed_data_internal().