cmp_tool: rice_encoder
rice_encoder()
static uint32_t rice_encoder (uint32_t value, uint32_t m, uint32_t log2_m, uint32_t * cw) static
forms the codeword according to the Rice code
Parameters
value value to be encoded (must be smaller or equal than cmp_ima_max_spill(m))
m Golomb parameter, only m's which are power of 2 are allowed maximum allowed Golomb parameter is 0x80000000
log2_m Rice parameter, is ilog_2(m) calculate outside function for better performance
cw address where the code word is stored
Warning
no check of the validity of the input parameters!
Returns
the length of the formed code word in bits; code word is invalid if the return value is greater than 32
Definition at line 447 of file cmp_icu.c.
 {
         uint32_t q = value >> log2_m;   /* quotient of value/m */
         uint32_t qc = (1U << q) - 1;    /* quotient code without ending zero */
         uint32_t r = value & (m-1);     /* remainder of value/m */
         uint32_t rl = log2_m + 1;       /* length of the remainder (+1 for the 0 in the quotient code) */
         *cw = (qc << (rl & 0x1FU)) | r; /* put the quotient and remainder code together */
         /*
          * NOTE: If log2_m = 31 -> rl = 32, (q << rl) leads to an undefined
          * behavior. However, in this case, a valid code with a maximum of 32
          * bits can only be formed if q = 0 and qc = 0. Any shift with 0 << x always
          * results in 0, which forms the correct codeword in this case. To prevent
          * undefined behavior, the right shift operand is masked (& 0x1FU)
          */
         return rl + q;  /* calculate the length of the code word */
 }
Referenced by configure_encoder_setup(), test_encode_value_zero(), and test_rice_encoder().