cmp_tool: cmp_ent_set_lossy_cmp_par
cmp_ent_set_lossy_cmp_par()
int cmp_ent_set_lossy_cmp_par (struct cmp_entity * ent, uint32_t lossy_cmp_par_used)
set the used lossy compression parameter in the compression entity header
Parameters
ent pointer to a compression entity
lossy_cmp_par_used used lossy compression parameter/round parameter
Returns
0 on success, otherwise error
Definition at line 479 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (lossy_cmp_par_used > UINT16_MAX)
                 return -1;
         ent->lossy_cmp_par_used = cpu_to_be16((uint16_t)lossy_cmp_par_used);
         return 0;
 }
References cpu_to_be16, lossy_cmp_par_used, and cmp_entity::lossy_cmp_par_used.
Referenced by cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), and test_ent_lossy_cmp_par().