cmp_tool: cmp_icu_max_spill
cmp_icu_max_spill()
uint32_t cmp_icu_max_spill (unsigned int cmp_par)
get the maximum valid spill threshold value for a non-imagette compression in diff or model mode
Parameters
cmp_par compression parameter
Returns
the highest still valid spill threshold value for diff or model mode compression; 0 if the cmp_par is not valid
Definition at line 348 of file cmp_support.c.
 {
         /* the ICU compressor can generate code words with a length of maximal 32 bits. */
         unsigned int const max_cw_bits = 32;
         unsigned int const cutoff = (0x2U << (ilog_2(cmp_par) & 0x1FU)) - cmp_par;
         unsigned int const max_n_sym_offset = max_cw_bits/2 - 1;
         if (!cmp_par || cmp_par > MAX_NON_IMA_GOLOMB_PAR)
                 return 0;
         return (max_cw_bits-1-ilog_2(cmp_par))*cmp_par + cutoff
                 - max_n_sym_offset - 1;
 }
References ilog_2(), and MAX_NON_IMA_GOLOMB_PAR.
Referenced by cmp_pars_are_invalid(), generate_random_cmp_par(), test_cmp_cfg_aux(), test_cmp_cfg_fx_cob(), test_compress_background_error_cases(), test_compress_l_fx_efx_error_cases(), test_compress_l_fx_efx_ncob_ecob_error_cases(), test_compress_l_fx_ncob_error_cases(), test_compress_offset_error_cases(), test_compress_s_fx_efx_error_cases(), test_compress_s_fx_efx_ncob_ecob_error_cases(), test_compress_s_fx_ncob_error_cases(), and test_compress_smearing_error_cases().