cmp_tool: cmp_cfg_icu_is_invalid
cmp_cfg_icu_is_invalid()
int cmp_cfg_icu_is_invalid (const struct cmp_cfg * cfg)
check if a compression configuration is invalid for a ICU compression
Parameters
cfg pointer to a compressor configuration
Returns
0 if the compression configuration is valid, otherwise invalid
Definition at line 910 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         if (!cfg)
                 return 1;
         cfg_invalid += cmp_cfg_gen_par_is_invalid(cfg, ICU_CHECK);
         cfg_invalid += cmp_cfg_icu_buffers_is_invalid(cfg);
         if (cfg->cmp_mode != CMP_MODE_RAW)
                 cfg_invalid += cmp_cfg_icu_max_used_bits_out_of_limit(cfg->max_used_bits);
         if (cmp_imagette_data_type_is_used(cfg->data_type))
                 cfg_invalid += cmp_cfg_imagette_is_invalid(cfg, ICU_CHECK);
         else if (cmp_fx_cob_data_type_is_used(cfg->data_type))
                 cfg_invalid += cmp_cfg_fx_cob_is_invalid(cfg);
         else if (cmp_aux_data_type_is_used(cfg->data_type))
                 cfg_invalid += cmp_cfg_aux_is_invalid(cfg);
         else
                 cfg_invalid++;
         return cfg_invalid;
 }
References cmp_aux_data_type_is_used(), cmp_cfg_aux_is_invalid(), cmp_cfg_fx_cob_is_invalid(), cmp_cfg_gen_par_is_invalid(), cmp_cfg_icu_buffers_is_invalid(), cmp_cfg_icu_max_used_bits_out_of_limit(), cmp_cfg_imagette_is_invalid(), cmp_fx_cob_data_type_is_used(), cmp_imagette_data_type_is_used(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, ICU_CHECK, and cmp_cfg::max_used_bits.
Referenced by icu_compress_data(), and test_support_function_call_NULL().