cmp_tool: cmp_ent_get_ima_golomb_par
cmp_ent_get_ima_golomb_par()
uint8_t cmp_ent_get_ima_golomb_par (const struct cmp_entity * ent)
get the used Golomb parameter from the (adaptive) imagette specific compression entity header
Parameters
ent pointer to a compression entity
Returns
the used Golomb parameter on success, 0 on error
Definition at line 1304 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
         return ent->ima.golomb_par_used;
 }
References imagette_header::golomb_par_used, and cmp_entity::ima.
Referenced by cmp_ent_parese_adaptive_imagette_header(), cmp_ent_parese_imagette_header(), cmp_ent_read_header(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), and test_ent_ima_golomb_par().