cmp_tool: pad_bitstream
pad_bitstream()
static int pad_bitstream (const struct cmp_cfg * cfg, int cmp_size) static
fill the last part of the bitstream with zeros
Parameters
cfg pointer to the compression configuration structure
cmp_size length of the bitstream in bits
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 2154 of file cmp_icu.c.
 {
         unsigned int output_buf_len_bits, n_pad_bits;
         if (cmp_size < 0)
                 return cmp_size;
         if (!cfg->icu_output_buf)
                 return cmp_size;
         /* no padding in RAW mode; ALWAYS BIG-ENDIAN */
         if (cfg->cmp_mode == CMP_MODE_RAW)
                 return cmp_size;
         /* maximum length of the bitstream/icu_output_buf in bits */
         output_buf_len_bits = cmp_buffer_length_to_bits(cfg->buffer_length, cfg->data_type);
         n_pad_bits = 32 - ((unsigned int)cmp_size & 0x1FU);
         if (n_pad_bits < 32) {
                 int n_bits = put_n_bits32(0, n_pad_bits, cmp_size, cfg->icu_output_buf,
                                           output_buf_len_bits);
                 if (n_bits < 0)
                         return n_bits;
         }
         return cmp_size;
 }
References cmp_cfg::buffer_length, cmp_buffer_length_to_bits(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, cmp_cfg::icu_output_buf, and put_n_bits32().
Referenced by icu_compress_data(), and test_pad_bitstream().