cmp_tool: configure_encoder_setup
configure_encoder_setup()
static void configure_encoder_setup (struct encoder_setupt * setup, uint32_t cmp_par, uint32_t spillover, uint32_t lossy_par, uint32_t max_data_bits, const struct cmp_cfg * cfg) static
configure an encoder setup structure to have a setup to encode a vale
Parameters
setup pointer to the encoder setup
cmp_par compression parameter
spillover spillover_par parameter
lossy_par lossy compression parameter
max_data_bits how many bits are needed to represent the highest possible value
cfg pointer to the compression configuration structure
Warning
input parameters are not checked for validity
Definition at line 736 of file cmp_icu.c.
 {
         memset(setup, 0, sizeof(struct encoder_setupt));
         setup->encoder_par1 = cmp_par;
         setup->max_data_bits = max_data_bits;
         setup->lossy_par = lossy_par;
         setup->bitstream_adr = cfg->icu_output_buf;
         setup->max_stream_len = cmp_buffer_length_to_bits(cfg->buffer_length, cfg->data_type);
         if (cfg->cmp_mode != CMP_MODE_STUFF) {
                 setup->encoder_par2 = ilog_2(cmp_par);
                 setup->spillover_par = spillover;
                 /* for encoder_par1 which are a power of two we can use the faster rice_encoder */
                 if (is_a_pow_of_2(setup->encoder_par1))
                         setup->generate_cw_f = &rice_encoder;
                 else
                         setup->generate_cw_f = &golomb_encoder;
         }
         switch (cfg->cmp_mode) {
         case CMP_MODE_MODEL_ZERO:
         case CMP_MODE_DIFF_ZERO:
                 setup->encode_method_f = &encode_value_zero;
                 break;
         case CMP_MODE_MODEL_MULTI:
         case CMP_MODE_DIFF_MULTI:
                 setup->encode_method_f = &encode_value_multi;
                 break;
         case CMP_MODE_STUFF:
                 setup->encode_method_f = &encode_value_none;
                 setup->max_data_bits = cmp_par;
                 break;
         /* LCOV_EXCL_START */
         case CMP_MODE_RAW:
                 /* CMP_MODE_RAW is already handled before; nothing to do here */
                 break;
         /* LCOV_EXCL_STOP */
         }
 }
References encoder_setupt::bitstream_adr, cmp_cfg::buffer_length, cmp_buffer_length_to_bits(), cmp_cfg::cmp_mode, CMP_MODE_DIFF_MULTI, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_MULTI, CMP_MODE_MODEL_ZERO, CMP_MODE_RAW, CMP_MODE_STUFF, cmp_cfg::data_type, encoder_setupt::encode_method_f, encode_value_multi(), encode_value_none(), encode_value_zero(), encoder_setupt::encoder_par1, encoder_setupt::encoder_par2, encoder_setupt::generate_cw_f, golomb_encoder(), cmp_cfg::icu_output_buf, ilog_2(), is_a_pow_of_2(), encoder_setupt::lossy_par, encoder_setupt::max_data_bits, encoder_setupt::max_stream_len, rice_encoder(), and encoder_setupt::spillover_par.
Referenced by compress_background(), compress_f_fx(), compress_f_fx_efx(), compress_f_fx_efx_ncob_ecob(), compress_f_fx_ncob(), compress_imagette(), compress_l_fx(), compress_l_fx_efx(), compress_l_fx_efx_ncob_ecob(), compress_l_fx_ncob(), compress_offset(), compress_s_fx(), compress_s_fx_efx(), compress_s_fx_efx_ncob_ecob(), compress_s_fx_ncob(), and compress_smearing().