cmp_tool: cmp_ent_create
cmp_ent_create()
uint32_t cmp_ent_create (struct cmp_entity * ent, enum cmp_data_type data_type, int raw_mode_flag, uint32_t cmp_size_byte)
create a compression entity by setting the size of the compression entity and the data product type in the entity header
Parameters
ent pointer to a compression entity; if NULL, the function returns the needed size
data_type compression data product type
raw_mode_flag set this flag if the raw compression mode (CMP_MODE_RAW) is used
cmp_size_byte size of the compressed data in bytes (should be a multiple of 4)
Note
if the entity size is smaller than the largest header, the function rounds up the entity size to the largest header
Returns
the size of the compression entity or 0 on error
Definition at line 2052 of file cmp_entity.c.
 {
         uint32_t hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
         uint32_t ent_size = hdr_size + cmp_size_byte;
         uint32_t ent_size_cpy = ent_size;
         if (!hdr_size)
                 return 0;
         /* catch overflows */
         if (cmp_size_byte > CMP_ENTITY_MAX_SIZE)
                 return 0;
         if (ent_size > CMP_ENTITY_MAX_SIZE)
                 return 0;
         /* to be safe a compression entity should be at least the size of the
          * largest entity header */
         if (ent_size < sizeof(struct cmp_entity))
                 ent_size = sizeof(struct cmp_entity);
         if (!ent)
                 return ent_size;
         memset(ent, 0, hdr_size);
         cmp_ent_set_size(ent, ent_size_cpy);
         cmp_ent_set_data_type(ent, data_type, raw_mode_flag);
         return ent_size;
 }
References cmp_ent_cal_hdr_size(), cmp_ent_set_data_type(), cmp_ent_set_size(), CMP_ENTITY_MAX_SIZE, and data_type.
Referenced by cmp_ent_build(), compression_decompression(), icu_compress_data_entity(), test_cmp_ent_create(), test_cmp_ent_get_cmp_data(), test_cmp_ent_get_data_buf(), test_cmp_ent_read_header_error_cases(), test_cmp_ent_write_cmp_pars(), and test_cmp_ent_write_rdcu_cmp_pars().