cmp_tool: encode_normal
encode_normal()
static int encode_normal (uint32_t value, int stream_len, const struct encoder_setupt * setup) static
generate a code word without an outlier mechanism and put in the bitstream
Parameters
value value to encode in the bitstream
stream_len length of the bitstream in bits
setup pointer to the encoder setup
Returns
the bit length of the bitstream with the added encoded value on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 518 of file cmp_icu.c.
 {
         uint32_t code_word, cw_len;
         cw_len = setup->generate_cw_f(value, setup->encoder_par1,
                                       setup->encoder_par2, &code_word);
         return put_n_bits32(code_word, cw_len, stream_len, setup->bitstream_adr,
                             setup->max_stream_len);
 }
References encoder_setupt::bitstream_adr, encoder_setupt::encoder_par1, encoder_setupt::encoder_par2, encoder_setupt::generate_cw_f, encoder_setupt::max_stream_len, and put_n_bits32().
Referenced by encode_value_multi(), and encode_value_zero().