cmp_tool: cmp_ent_set_size
cmp_ent_set_size()
int cmp_ent_set_size (struct cmp_entity * ent, uint32_t cmp_ent_size)
set the size of the compression entity in the entity header
Parameters
ent pointer to a compression entity
cmp_ent_size the compression entity size measured in bytes
Note
maximum size is CMP_ENTITY_MAX_SIZE
Returns
0 on success, otherwise error
Definition at line 144 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (cmp_ent_size > CMP_ENTITY_MAX_SIZE)
                 return -1;
 #ifdef __LITTLE_ENDIAN
         ent->cmp_ent_size = cpu_to_be32(cmp_ent_size) >> 8;
 #else
         ent->cmp_ent_size = cmp_ent_size;
 #endif /* __LITTLE_ENDIAN */
         return 0;
 }
References cmp_ent_size, cmp_entity::cmp_ent_size, CMP_ENTITY_MAX_SIZE, and cpu_to_be32.
Referenced by cmp_ent_create(), compression_decompression(), test_cmp_ent_get_cmp_data(), test_cmp_ent_get_cmp_data_size(), and test_ent_size().