cmp_tool: cmp_ent_set_original_size
cmp_ent_set_original_size()
int cmp_ent_set_original_size (struct cmp_entity * ent, uint32_t original_size)
set the original size of the compressed data in the entity header
Parameters
ent pointer to a compression entity
original_size the original size of the compressed data measured in bytes
Returns
0 on success, otherwise error
Definition at line 172 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (original_size > 0xFFFFFFUL)
                 return -1;
 #ifdef __LITTLE_ENDIAN
         ent->original_size = cpu_to_be32(original_size) >> 8;
 #else
         ent->original_size = original_size;
 #endif /* __LITTLE_ENDIAN */
         return 0;
 }
References cpu_to_be32, original_size, and cmp_entity::original_size.
Referenced by cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), test_cmp_ent_read_header_error_cases(), and test_ent_original_size().