cmp_tool: rdcu_cmp_cfg_is_invalid
rdcu_cmp_cfg_is_invalid()
int rdcu_cmp_cfg_is_invalid (const struct cmp_cfg * cfg)
check if the compressor configuration is invalid for an RDCU compression, see the user manual for more information (PLATO-UVIE-PL-UM-0001).
Parameters
cfg pointer to a compression configuration contains all parameters required for compression
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 369 of file cmp_rdcu_cfg.c.
 {
         int cfg_invalid = 0;
         if (!cfg) {
                 debug_print("Error: pointer to the compression configuration structure is NULL.\n");
                 return -1;
         }
         if (!cfg->input_buf)
                 debug_print("Warning: The data to compress buffer is set to NULL. No data will be transferred to the rdcu_data_adr in the RDCU SRAM.\n");
         if (model_mode_is_used(cfg->cmp_mode)) {
                 if (!cfg->model_buf)
                         debug_print("Warning: The model buffer is set to NULL. No model data will be transferred to the rdcu_model_adr in the RDCU SRAM.\n");
         }
         if (cfg->samples == 0)
                 debug_print("Warning: The samples parameter is set to 0. No data will be compressed.\n");
         if (cfg->icu_new_model_buf)
                 debug_print("Warning: ICU updated model buffer is set. This buffer is not used for an RDCU compression.\n");
         if (cfg->icu_output_buf)
                 debug_print("Warning: ICU compressed data buffer is set. This buffer is not used for an RDCU compression.\n");
         if (cfg->buffer_length == 0) {
                 debug_print("Error: The buffer_length is set to 0. There is no place to store the compressed data.\n");
                 cfg_invalid++;
         }
         cfg_invalid += cmp_cfg_gen_par_is_invalid(cfg, RDCU_CHECK);
         cfg_invalid += rdcu_cfg_buffers_is_invalid(cfg);
         cfg_invalid += cmp_cfg_imagette_is_invalid(cfg, RDCU_CHECK);
         return cfg_invalid;
 }
References cmp_cfg::buffer_length, cmp_cfg_gen_par_is_invalid(), cmp_cfg_imagette_is_invalid(), cmp_cfg::cmp_mode, debug_print, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_cfg::model_buf, model_mode_is_used(), rdcu_cfg_buffers_is_invalid(), RDCU_CHECK, and cmp_cfg::samples.
Referenced by rdcu_set_compression_register(), and test_rdcu_cmp_cfg_is_invalid().