cmp_tool: cmp_ent_get_non_ima_spill3
cmp_ent_get_non_ima_spill3()
uint32_t cmp_ent_get_non_ima_spill3 (const struct cmp_entity * ent)
get the used spillover threshold 3 parameter from the non-imagette specific compression entity header
Parameters
ent pointer to a compression entity
Returns
the used spillover threshold 3 parameter on success, 0 on error
Definition at line 1474 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
 #ifdef __LITTLE_ENDIAN
         return be32_to_cpu(ent->non_ima.spill_3_used) >> 8;
 #else
         return ent->non_ima.spill_3_used;
 #endif /* __LITTLE_ENDIAN */
 }
References be32_to_cpu, cmp_entity::non_ima, and non_imagette_header::spill_3_used.
Referenced by cmp_ent_read_header(), test_cmp_ent_write_cmp_pars(), and test_ent_non_ima_spill3().