cmp_tool: cmp_cfg_icu_buffers
cmp_cfg_icu_buffers()
uint32_t cmp_cfg_icu_buffers (struct cmp_cfg * cfg, void * data_to_compress, uint32_t data_samples, void * model_of_data, void * updated_model, uint32_t * compressed_data, uint32_t compressed_data_len_samples)
set up the different data buffers for an ICU compression
Parameters
cfg pointer to a compression configuration (created with the cmp_cfg_icu_create() function)
data_to_compress pointer to the data to be compressed
data_samples length of the data to be compressed measured in data samples/entities (collection header not included by imagette data)
model_of_data pointer to model data buffer (can be NULL if no model compression mode is used)
updated_model pointer to store the updated model for the next model mode compression (can be the same as the model_of_data buffer for in-place update or NULL if updated model is not needed)
compressed_data pointer to the compressed data buffer (can be NULL)
compressed_data_len_samples length of the compressed_data buffer in measured in the same units as the data_samples
Returns
the size of the compressed_data buffer on success; 0 if the parameters are invalid
Note
There is a difference in the data_samples parameter when compressing imagette data compared to compressing non-imagette data! When compressing non-imagette data, the compressor expects that the collection header will always prefix the non-imagette data. Therefore, the data_samples parameter is simply the number of entries in the collection. It is not intended to join multiple non-imagette collections and compress them together. When compressing imagette data, the length of the entire data to be compressed, including the collection header, is measured in 16-bit samples. The compressor makes in this case no distinction between header and imagette data. Therefore, the data_samples parameter is the number of 16-bit imagette pixels plus the length of the collection header, measured in 16-bit units. The compression of multiple joined collections is possible.
Definition at line 138 of file cmp_icu.c.
 {
         uint32_t cmp_data_size, hdr_size;
         if (!cfg) {
                 debug_print("Error: pointer to the compression configuration structure is NULL.\n");
                 return 0;
         }
         cfg->input_buf = data_to_compress;
         cfg->model_buf = model_of_data;
         cfg->samples = data_samples;
         cfg->icu_new_model_buf = updated_model;
         cfg->icu_output_buf = compressed_data;
         cfg->buffer_length = compressed_data_len_samples;
         if (cmp_cfg_icu_buffers_is_invalid(cfg))
                 return 0;
         cmp_data_size = cmp_cal_size_of_data(compressed_data_len_samples, cfg->data_type);
         hdr_size = cmp_ent_cal_hdr_size(cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW);
         if ((cmp_data_size + hdr_size) > CMP_ENTITY_MAX_SIZE || cmp_data_size > CMP_ENTITY_MAX_SIZE) {
                 debug_print("Error: The buffer for the compressed data is too large to fit in a compression entity.\n");
                 return 0;
         }
         return cmp_data_size;
 }
References cmp_cfg::buffer_length, cmp_cal_size_of_data(), cmp_cfg_icu_buffers_is_invalid(), cmp_ent_cal_hdr_size(), CMP_ENTITY_MAX_SIZE, cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, debug_print, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_cfg::model_buf, and cmp_cfg::samples.
Referenced by test_cmp_cfg_icu_buffers(), test_cmp_decmp_n_imagette_raw(), test_cmp_decmp_s_fx_diff(), test_compress_background_error_cases(), test_compress_f_fx_efx_error_cases(), test_compress_f_fx_efx_ncob_ecob(), test_compress_f_fx_error_cases(), test_compress_f_fx_ncob_error_cases(), test_compress_imagette_diff(), test_compress_imagette_model(), test_compress_imagette_stuff(), test_compress_l_fx_efx_error_cases(), test_compress_l_fx_efx_ncob_ecob_error_cases(), test_compress_l_fx_error_cases(), test_compress_l_fx_ncob_error_cases(), test_compress_offset_error_cases(), test_compress_s_fx_efx_error_cases(), test_compress_s_fx_efx_ncob_ecob_error_cases(), test_compress_s_fx_error_cases(), test_compress_s_fx_ncob_error_cases(), test_compress_smearing_error_cases(), test_random_compression_decompression(), and test_random_compression_decompression2().