cmp_tool: cmp_ent_parse_generic_header
cmp_ent_parse_generic_header()
static void cmp_ent_parse_generic_header (const struct cmp_entity * ent) static
parses the generic compressed entity header
Parameters
ent pointer to a compression entity
Definition at line 2294 of file cmp_entity.c.
 {
         uint32_t version_id, cmp_ent_size, original_size, cmp_mode_used,
                  model_value_used, model_id, model_counter, max_used_bits_version,
                  lossy_cmp_par_used, start_coarse_time, end_coarse_time;
         uint16_t start_fine_time, end_fine_time;
         enum cmp_data_type data_type;
         int raw_bit;
         version_id = cmp_ent_get_version_id(ent);
         if (version_id & CMP_TOOL_VERSION_ID_BIT) {
                 uint16_t major = (version_id & 0x7FFF0000U) >> 16U;
                 uint16_t minor = version_id & 0xFFFFU;
                 printf("Compressed with cmp_tool version: %u.%02u\n", major, minor);
         } else
                 printf("ICU ASW Version ID: %08" PRIx32 "\n", version_id);
         cmp_ent_size = cmp_ent_get_size(ent);
         printf("Compression Entity Size: %" PRIu32 " byte\n", cmp_ent_size);
         original_size = cmp_ent_get_original_size(ent);
         printf("Original Data Size: %" PRIu32 " byte\n", original_size);
         start_coarse_time = cmp_ent_get_coarse_start_time(ent);
         printf("Compression Coarse Start Time: %" PRIu32 "\n", start_coarse_time);
         start_fine_time = cmp_ent_get_fine_start_time(ent);
         printf("Compression Fine Start Time: %d\n", start_fine_time);
         end_coarse_time = cmp_ent_get_coarse_end_time(ent);
         printf("Compression Coarse End Time: %" PRIu32 "\n", end_coarse_time);
         end_fine_time = cmp_ent_get_fine_end_time(ent);
         printf("Compression Fine End Time: %d\n", end_fine_time);
 #ifdef HAS_TIME_H
         {
                 struct tm epoch_date = PLATO_EPOCH_DATE;
                 time_t time = my_timegm(&epoch_date) + start_coarse_time;
                 printf("Data were compressed on (local time): %s", ctime(&time));
         }
 #endif
         printf("The compression took %f second\n", end_coarse_time - start_coarse_time
                 + ((end_fine_time - start_fine_time)/256./256.));
         data_type = cmp_ent_get_data_type(ent);
         printf("Data Product Type: %d\n", data_type);
         raw_bit = cmp_ent_get_data_type_raw_bit(ent);
         printf("RAW bit in the Data Product Type is%s set\n", raw_bit ? "" : " not");
         cmp_mode_used = cmp_ent_get_cmp_mode(ent);
         printf("Used Compression Mode: %" PRIu32 "\n", cmp_mode_used);
         model_value_used = cmp_ent_get_model_value(ent);
         printf("Used Model Updating Weighing Value: %" PRIu32 "\n", model_value_used);
         model_id = cmp_ent_get_model_id(ent);
         printf("Model ID: %" PRIu32 "\n", model_id);
         model_counter = cmp_ent_get_model_counter(ent);
         printf("Model Counter: %" PRIu32 "\n", model_counter);
         max_used_bits_version = cmp_ent_get_max_used_bits_version(ent);
         printf("Maximum Used Bits Registry Version: %" PRIu32 "\n", max_used_bits_version);
         lossy_cmp_par_used = cmp_ent_get_lossy_cmp_par(ent);
         printf("Used Lossy Compression Parameters: %" PRIu32 "\n", lossy_cmp_par_used);
 }
References cmp_ent_get_cmp_mode(), cmp_ent_get_coarse_end_time(), cmp_ent_get_coarse_start_time(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_get_fine_end_time(), cmp_ent_get_fine_start_time(), cmp_ent_get_lossy_cmp_par(), cmp_ent_get_max_used_bits_version(), cmp_ent_get_model_counter(), cmp_ent_get_model_id(), cmp_ent_get_model_value(), cmp_ent_get_original_size(), cmp_ent_get_size(), cmp_ent_get_version_id(), cmp_ent_size, cmp_mode_used, CMP_TOOL_VERSION_ID_BIT, data_type, lossy_cmp_par_used, max_used_bits_version, model_counter, model_id, model_value_used, original_size, and version_id.
Referenced by cmp_ent_parse().