cmp_tool: rdcu_inject_edac_error
rdcu_inject_edac_error()
int rdcu_inject_edac_error (const struct cmp_cfg * cfg, uint32_t addr)
inject a SRAM edac multi bit error into the RDCU SRAM
Parameters
cfg configuration to inject error
addr SRAM address to inject edac error
Definition at line 504 of file cmp_rdcu.c.
 {
         uint32_t sub_chip_die_addr;
         uint8_t buf[4] = {0};
         if (rdcu_set_compression_register(cfg))
                 return -1;
         if (rdcu_transfer_sram(cfg))
                 return -1;
         /* disable edac */
         for (sub_chip_die_addr = 1; sub_chip_die_addr <= 4; sub_chip_die_addr++) {
                 rdcu_edac_set_sub_chip_die_addr(sub_chip_die_addr);
                 rdcu_edac_set_ctrl_reg_write_op();
                 rdcu_edac_set_bypass();
                 if (rdcu_sync_sram_edac_ctrl()) {
                         debug_print("Error: rdcu_sync_sram_edac_ctrl\n");
                         return -1;
                 }
                 rdcu_syncing();
                 /* verify bypass aktiv */
                 rdcu_edac_set_ctrl_reg_read_op();
                 if (rdcu_sync_sram_edac_ctrl()) {
                         debug_print("Error: rdcu_sync_sram_edac_ctrl\n");
                         return -1;
                 }
                 rdcu_syncing();
                 if (rdcu_sync_sram_edac_status()) {
                         printf("Error: rdcu_sync_sram_edac_status\n");
                         return -1;
                 }
                 rdcu_syncing();
                 if (rdcu_edac_get_sub_chip_die_addr() != sub_chip_die_addr) {
                         printf("Error: sub_chip_die_addr unexpected !\n");
                         return -1;
                 }
 #if 1
                 /* It looks like there is a bug when displaying the bypass status of the 2. and 4. SRAM chip. */
                 if (2 != sub_chip_die_addr && 4 != sub_chip_die_addr)
 #endif
                         if (rdcu_edac_get_bypass_status() == 0) {
                                 printf("Error: bypass status unexpected !\n");
                                 return -1;
                         }
         }
         /* inject multi bit error */
         if (rdcu_sync_sram_to_mirror(addr, sizeof(buf), rdcu_get_data_mtu()))
                 return -1;
         rdcu_syncing();
         if (rdcu_read_sram(buf, addr, sizeof(buf)) < 0)
                 return -1;
         buf[0] ^= 1 << 0;
         buf[1] ^= 1 << 1;
         buf[2] ^= 1 << 2;
         buf[3] ^= 1 << 3;
         if (rdcu_write_sram(buf, addr, sizeof(buf)) < 0)
                 return -1;
         if (rdcu_sync_mirror_to_sram(addr, sizeof(buf), rdcu_get_data_mtu())) {
                 debug_print("Error: The data to be compressed cannot be transferred to the SRAM of the RDCU.\n");
                 return -1;
         }
         rdcu_syncing();
         /* enable edac again */
         for (sub_chip_die_addr = 1; sub_chip_die_addr <= 4; sub_chip_die_addr++) {
                 if (rdcu_edac_set_sub_chip_die_addr(sub_chip_die_addr))
                         return -1;
                 rdcu_edac_set_ctrl_reg_write_op();
                 rdcu_edac_clear_bypass();
                 if (rdcu_sync_sram_edac_ctrl()) {
                         debug_print("Error: rdcu_sync_sram_edac_ctrl\n");
                         return -1;
                 }
                 rdcu_syncing();
                 /* verify bypass disable */
                 rdcu_edac_set_ctrl_reg_read_op();
                 if (rdcu_sync_sram_edac_ctrl()) {
                         debug_print("Error: rdcu_sync_sram_edac_ctrl\n");
                         return -1;
                 }
                 rdcu_syncing();
                 if (rdcu_sync_sram_edac_status()) {
                         printf("Error: rdcu_sync_sram_edac_status\n");
                         return -1;
                 }
                 rdcu_syncing();
                 if (rdcu_edac_get_sub_chip_die_addr() != sub_chip_die_addr) {
                         printf("Error: sub_chip_die_addr unexpected !\n");
                         return -1;
                 }
                 if (1 == rdcu_edac_get_bypass_status()) {
                         printf("Error: bypass status unexpected !\n");
                         return -1;
                 }
         }
         return 0;
 }
References debug_print, rdcu_edac_clear_bypass(), rdcu_edac_get_bypass_status(), rdcu_edac_get_sub_chip_die_addr(), rdcu_edac_set_bypass(), rdcu_edac_set_ctrl_reg_read_op(), rdcu_edac_set_ctrl_reg_write_op(), rdcu_edac_set_sub_chip_die_addr(), rdcu_get_data_mtu(), rdcu_read_sram(), rdcu_set_compression_register(), rdcu_sync_mirror_to_sram(), rdcu_sync_sram_edac_ctrl(), rdcu_sync_sram_edac_status(), rdcu_sync_sram_to_mirror(), rdcu_syncing(), rdcu_transfer_sram(), and rdcu_write_sram().