cmp_tool: cmp_fx_cob_data_type_is_used
cmp_fx_cob_data_type_is_used()
int cmp_fx_cob_data_type_is_used (enum cmp_data_type data_type)
check if a flux/center of brightness compression data type is used
Parameters
data_type compression data type
Returns
1 when data_type is a flux/center of brightness data type, otherwise 0
Definition at line 266 of file cmp_support.c.
 {
         switch (data_type) {
         case DATA_TYPE_S_FX:
         case DATA_TYPE_S_FX_EFX:
         case DATA_TYPE_S_FX_NCOB:
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_L_FX:
         case DATA_TYPE_L_FX_EFX:
         case DATA_TYPE_L_FX_NCOB:
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_F_FX:
         case DATA_TYPE_F_FX_EFX:
         case DATA_TYPE_F_FX_NCOB:
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 return 1;
         default:
                 return 0;
         }
 }
References data_type, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, and DATA_TYPE_S_FX_NCOB.
Referenced by cmp_cfg_fx_cob_is_invalid(), cmp_cfg_icu_is_invalid(), and decompressed_data_internal().