cmp_tool: cmp_ent_get_max_used_bits_version
cmp_ent_get_max_used_bits_version()
uint8_t cmp_ent_get_max_used_bits_version (const struct cmp_entity * ent)
get the version identifier for the maximum used bits registry from the compression entity header
Parameters
ent pointer to a compression entity
Returns
the version identifier for the maximum used bits registry on success, 0 on error
Definition at line 1251 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
         return ent->max_used_bits_version;
 }
References cmp_entity::max_used_bits_version.
Referenced by cmp_ent_parse_generic_header(), cmp_ent_read_header(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), and test_ent_max_used_bits_version().