cmp_tool: rdcu_cfg_imagette
rdcu_cfg_imagette()
int rdcu_cfg_imagette (struct cmp_cfg * cfg, uint32_t golomb_par, uint32_t spillover_par, uint32_t ap1_golomb_par, uint32_t ap1_spillover_par, uint32_t ap2_golomb_par, uint32_t ap2_spillover_par)
set up the configuration parameters for an RDCU imagette compression
Parameters
cfg pointer to a compression configuration (created with the rdcu_cfg_create() function)
golomb_par imagette compression parameter
spillover_par imagette spillover threshold parameter
ap1_golomb_par adaptive 1 imagette compression parameter
ap1_spillover_par adaptive 1 imagette spillover threshold parameter
ap2_golomb_par adaptive 2 imagette compression parameter
ap2_spillover_par adaptive 2 imagette spillover threshold parameter
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 305 of file cmp_rdcu_cfg.c.
 {
         if (!cfg) {
                 debug_print("Error: pointer to the compression configuration structure is NULL.\n");
                 return -1;
         }
         cfg->golomb_par = golomb_par;
         cfg->spill = spillover_par;
         cfg->ap1_golomb_par = ap1_golomb_par;
         cfg->ap1_spill = ap1_spillover_par;
         cfg->ap2_golomb_par = ap2_golomb_par;
         cfg->ap2_spill = ap2_spillover_par;
         return cmp_cfg_imagette_is_invalid(cfg, RDCU_CHECK);
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_cfg_imagette_is_invalid(), debug_print, cmp_cfg::golomb_par, RDCU_CHECK, and cmp_cfg::spill.
Referenced by rdcu_cfg_imagette_default(), test_rdcu_cfg_imagette(), and test_rdcu_cmp_cfg_is_invalid().