cmp_tool: cmp_cfg_fx_cob_is_invalid
cmp_cfg_fx_cob_is_invalid()
int cmp_cfg_fx_cob_is_invalid (const struct cmp_cfg * cfg)
check if the flux/center of brightness specific compression parameters are invalid
Parameters
cfg pointer to the compressor configuration
Returns
0 if the flux/center of brightness specific parameters are valid, otherwise invalid
Definition at line 830 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         struct fx_cob_par needed_pars;
         if (!cfg)
                 return 1;
         if (!cmp_fx_cob_data_type_is_used(cfg->data_type)) {
                 debug_print("Error: The compression data type is not a flux/center of brightness compression data type.\n");
                 cfg_invalid++;
         }
         cmp_cfg_fx_cob_get_need_pars(cfg->data_type, &needed_pars);
         if (needed_pars.fx) /* this is always true because every flux/center of brightness data type contains a flux parameter */
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_fx, cfg->spill_fx,
                                                     cfg->cmp_mode, cfg->data_type, "flux");
         if (needed_pars.exp_flags)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_exp_flags, cfg->spill_exp_flags,
                         cfg->cmp_mode, cfg->data_type, "exposure flags");
         if (needed_pars.ncob)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_ncob, cfg->spill_ncob,
                         cfg->cmp_mode, cfg->data_type, "center of brightness");
         if (needed_pars.efx)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_efx, cfg->spill_efx,
                         cfg->cmp_mode, cfg->data_type, "extended flux");
         if (needed_pars.ecob)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_ecob, cfg->spill_ecob,
                         cfg->cmp_mode, cfg->data_type, "extended center of brightness");
         if (needed_pars.fx_cob_variance)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_fx_cob_variance,
                         cfg->spill_fx_cob_variance, cfg->cmp_mode, cfg->data_type, "flux/COB variance");
         return cfg_invalid;
 }
References cmp_cfg_fx_cob_get_need_pars(), cmp_fx_cob_data_type_is_used(), cmp_cfg::cmp_mode, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, cmp_pars_are_invalid(), cmp_cfg::data_type, debug_print, fx_cob_par::ecob, fx_cob_par::efx, fx_cob_par::exp_flags, fx_cob_par::fx, fx_cob_par::fx_cob_variance, fx_cob_par::ncob, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, and cmp_cfg::spill_ncob.
Referenced by cmp_cfg_fx_cob(), cmp_cfg_icu_is_invalid(), decompressed_data_internal(), and test_support_function_call_NULL().