cmp_tool: cmp_ent_get_cmp_mode
cmp_ent_get_cmp_mode()
uint8_t cmp_ent_get_cmp_mode (const struct cmp_entity * ent)
get the used compression mode parameter from the compression entity header
Parameters
ent pointer to a compression entity
Returns
the used compression mode on success, 0 on error
Definition at line 1180 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
         return ent->cmp_mode_used;
 }
References cmp_entity::cmp_mode_used.
Referenced by cmp_ent_parse_generic_header(), cmp_ent_read_header(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), and test_ent_cmp_mode().