cmp_tool: cmp_ent_cal_hdr_size
cmp_ent_cal_hdr_size()
uint32_t cmp_ent_cal_hdr_size (enum cmp_data_type data_type, int raw_mode_flag)
calculate the size of the compression entity header based on a compression data product type
Parameters
data_type compression data product type
raw_mode_flag set this flag if the raw compression mode (CMP_MODE_RAW) is used
Returns
size of the compression entity header in bytes, 0 on unknown data type
Definition at line 65 of file cmp_entity.c.
 {
         uint32_t size = 0;
         if (raw_mode_flag) {
                 if (!cmp_data_type_is_invalid(data_type))
                         /* for raw data we do not need a specific header */
                         size = GENERIC_HEADER_SIZE;
         } else {
                 switch (data_type) {
                 case DATA_TYPE_IMAGETTE:
                 case DATA_TYPE_SAT_IMAGETTE:
                 case DATA_TYPE_F_CAM_IMAGETTE:
                         size = IMAGETTE_HEADER_SIZE;
                         break;
                 case DATA_TYPE_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                         size = IMAGETTE_ADAPTIVE_HEADER_SIZE;
                         break;
                 case DATA_TYPE_OFFSET:
                 case DATA_TYPE_BACKGROUND:
                 case DATA_TYPE_SMEARING:
                 case DATA_TYPE_S_FX:
                 case DATA_TYPE_S_FX_EFX:
                 case DATA_TYPE_S_FX_NCOB:
                 case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                 case DATA_TYPE_L_FX:
                 case DATA_TYPE_L_FX_EFX:
                 case DATA_TYPE_L_FX_NCOB:
                 case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                 case DATA_TYPE_F_FX:
                 case DATA_TYPE_F_FX_EFX:
                 case DATA_TYPE_F_FX_NCOB:
                 case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 case DATA_TYPE_F_CAM_OFFSET:
                 case DATA_TYPE_F_CAM_BACKGROUND:
                         size = NON_IMAGETTE_HEADER_SIZE;
                         break;
                 case DATA_TYPE_UNKNOWN:
                         size = 0;
                         break;
                 }
         }
         return size;
 }
References cmp_data_type_is_invalid(), data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, GENERIC_HEADER_SIZE, IMAGETTE_ADAPTIVE_HEADER_SIZE, IMAGETTE_HEADER_SIZE, and NON_IMAGETTE_HEADER_SIZE.
Referenced by cmp_cfg_icu_buffers(), cmp_ent_build(), cmp_ent_create(), cmp_ent_get_hdr_size(), test_cmp_ent_cal_hdr_size(), and test_cmp_ent_get_data_buf().