cmp_tool: cmp_ent_build
cmp_ent_build()
uint32_t cmp_ent_build (struct cmp_entity * ent, uint32_t version_id, uint64_t start_time, uint64_t end_time, uint16_t model_id, uint8_t model_counter, const struct cmp_cfg * cfg, int cmp_size_bits)
create a compression entity and set the header fields
Note
this function simplifies the entity set up by creating an entity and setting the header fields in one function call
no compressed data are put into the entity
Parameters
ent pointer to a compression entity; if NULL, the function returns the needed size
version_id applications software version identifier
start_time compression start timestamp (coarse and fine)
end_time compression end timestamp (coarse and fine)
model_id model identifier
model_counter model counter
cfg pointer to compression configuration (can be NULL)
cmp_size_bits length of the compressed data in bits
Returns
the size of the compression entity or 0 on error
Definition at line 2105 of file cmp_entity.c.
 {
         uint32_t cmp_size_bytes = cmp_bit_to_byte((unsigned int)cmp_size_bits);
         uint32_t hdr_size;
         if (!cfg)
                 return 0;
         if (cmp_size_bits < 0)
                 return 0;
         if (!cmp_ent_create(ent, cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW, cmp_size_bytes))
                 return 0;
         if (ent) {
                 cmp_ent_set_version_id(ent, version_id);
                 if (cmp_ent_set_start_timestamp(ent, start_time))
                         return 0;
                 if (cmp_ent_set_end_timestamp(ent, end_time))
                         return 0;
                 cmp_ent_set_model_id(ent, model_id);
                 cmp_ent_set_model_counter(ent, model_counter);
                 if (cmp_ent_write_cmp_pars(ent, cfg, cmp_size_bits))
                         return 0;
         }
         hdr_size = cmp_ent_cal_hdr_size(cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW);
         return hdr_size + cmp_size_bytes;
 }
References cmp_bit_to_byte(), cmp_ent_cal_hdr_size(), cmp_ent_create(), cmp_ent_set_end_timestamp(), cmp_ent_set_model_counter(), cmp_ent_set_model_id(), cmp_ent_set_start_timestamp(), cmp_ent_set_version_id(), cmp_ent_write_cmp_pars(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, end_time, model_counter, model_id, start_time, and version_id.
Referenced by compression_decompression(), test_cmp_decmp_n_imagette_raw(), test_cmp_ent_build(), test_cmp_ent_parse(), and test_cmp_ent_print().