cmp_tool: map_to_pos
map_to_pos()
static uint32_t map_to_pos (uint32_t value_to_map, unsigned int max_data_bits) static
map a signed value into a positive value range
Parameters
value_to_map signed value to map
max_data_bits how many bits are needed to represent the highest possible value
Returns
the positive mapped value
Definition at line 333 of file cmp_icu.c.
 {
         uint32_t result;
         uint32_t mask = (~0U >> (32 - max_data_bits)); /* mask the used bits */
         value_to_map &= mask;
         if (value_to_map >> (max_data_bits - 1)) { /* check the leading signed bit */
                 value_to_map |= ~mask; /* convert to 32-bit signed integer */
                 /* map negative values to uneven numbers */
                 result = (-value_to_map) * 2 - 1; /* possible integer overflow is intended */
         } else {
                 /* map positive values to even numbers */
                 result = value_to_map * 2; /* possible integer overflow is intended */
         }
         return result;
 }
Referenced by encode_value_multi(), encode_value_zero(), test_map_to_pos(), and test_re_map_to_pos().