cmp_tool: cmp_cfg_icu_create
cmp_cfg_icu_create()
struct cmp_cfg cmp_cfg_icu_create (enum cmp_data_type data_type, enum cmp_mode cmp_mode, uint32_t model_value, uint32_t lossy_par)
create an ICU compression configuration
Parameters
data_type compression data product type
cmp_mode compression mode
model_value model weighting parameter (only needed for model compression mode)
lossy_par lossy rounding parameter (use CMP_LOSSLESS for lossless compression)
Returns
a compression configuration containing the chosen parameters; on error the data_type record is set to DATA_TYPE_UNKNOWN
Definition at line 48 of file cmp_icu.c.
 {
         struct cmp_cfg cfg;
         memset(&cfg, 0, sizeof(cfg));
         cfg.data_type = data_type;
         cfg.cmp_mode = cmp_mode;
         cfg.model_value = model_value;
         cfg.round = lossy_par;
         cfg.max_used_bits = &MAX_USED_BITS_SAFE;
         if (cmp_cfg_gen_par_is_invalid(&cfg, ICU_CHECK))
                 cfg.data_type = DATA_TYPE_UNKNOWN;
         return cfg;
 }
Referenced by test_cmp_cfg_aux(), test_cmp_cfg_fx_cob(), test_cmp_cfg_icu_buffers(), test_cmp_cfg_icu_create(), test_cmp_cfg_icu_imagette(), test_cmp_cfg_icu_max_used_bits(), test_cmp_decmp_n_imagette_raw(), test_cmp_decmp_s_fx_diff(), test_compress_background_error_cases(), test_compress_f_fx_efx_error_cases(), test_compress_f_fx_efx_ncob_ecob(), test_compress_f_fx_error_cases(), test_compress_f_fx_ncob_error_cases(), test_compress_imagette_diff(), test_compress_imagette_model(), test_compress_imagette_stuff(), test_compress_l_fx_efx_error_cases(), test_compress_l_fx_efx_ncob_ecob_error_cases(), test_compress_l_fx_error_cases(), test_compress_l_fx_ncob_error_cases(), test_compress_offset_error_cases(), test_compress_s_fx_efx_error_cases(), test_compress_s_fx_efx_ncob_ecob_error_cases(), test_compress_s_fx_error_cases(), test_compress_s_fx_ncob_error_cases(), test_compress_smearing_error_cases(), test_random_compression_decompression(), test_random_compression_decompression2(), and test_support_function_call_NULL().