cmp_tool: cmp_ap_imagette_data_type_is_used
cmp_ap_imagette_data_type_is_used()
int cmp_ap_imagette_data_type_is_used (enum cmp_data_type data_type)
check if an adaptive imagette compression data type is used
Parameters
data_type compression data type
Returns
1 when data_type is an adaptive imagette data type, otherwise 0
Definition at line 245 of file cmp_support.c.
 {
         switch (data_type) {
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 return 1;
         default:
                 return 0;
         }
 }
References data_type, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_IMAGETTE_ADAPTIVE, and DATA_TYPE_SAT_IMAGETTE_ADAPTIVE.
Referenced by cmp_cfg_imagette_is_invalid(), cmp_ent_write_rdcu_cmp_pars(), and test_cmp_ent_cal_hdr_size().