cmp_tool: rdcu_compress_data_parallel
rdcu_compress_data_parallel()
int rdcu_compress_data_parallel (const struct cmp_cfg * cfg, const struct cmp_info * last_info)
compressing data with the help of the RDCU hardware compressor; read data from the last compression before starting compression
Parameters
cfg configuration contains all parameters required for compression
last_info compression information of last compression run
Note
when using the 1d-differencing mode or the raw mode (cmp_mode = 0,2,4), the model parameters (model_value, model_buf, rdcu_model_adr) are ignored
the overlapping of the different rdcu buffers is not checked
the validity of the cfg structure is checked before the compression is started
Returns
0 on success, error otherwise
Definition at line 624 of file cmp_rdcu.c.
 {
         uint32_t samples_4byte;
         if (!cfg)
                 return -1;
         if (!last_info)
                 return rdcu_compress_data(cfg);
         if (last_info->cmp_err)
                 return -1;
         rdcu_set_compression_register(cfg);
         /* round up needed size must be a multiple of 4 bytes */
         samples_4byte = (cfg->samples * IMA_SAM2BYT + 3) & ~3U;
         if (cfg->input_buf != NULL) {
                 uint32_t cmp_size_4byte;
                 /* now set the data in the local mirror... */
                 if (rdcu_write_sram_16(cfg->input_buf, cfg->rdcu_data_adr,
                                        cfg->samples * IMA_SAM2BYT) < 0)
                         return -1;
                 /* calculate the need bytes for the bitstream */
                 cmp_size_4byte = cmp_bit_to_4byte(last_info->cmp_size);
                 /* parallel read compressed data and write input data from sram
                  * to mirror */
                 if (rdcu_sync_sram_mirror_parallel(last_info->rdcu_cmp_adr_used,
                                 cmp_size_4byte, cfg->rdcu_data_adr, samples_4byte,
                                 rdcu_get_data_mtu()))
                         return -1;
                 /* wait for it */
                 rdcu_syncing();
                 if (cfg->icu_output_buf) {
                         if (rdcu_read_sram(cfg->icu_output_buf,
                                            last_info->rdcu_cmp_adr_used,
                                            cmp_size_4byte))
                                 return -1;
                 }
         } else {
                 debug_print("Warning: input_buf = NULL; input_buf is not written to the sram and compressed data is not read from the SRAM\n");
         }
         /* read model and write model in parallel */
         if (cfg->model_buf && model_mode_is_used(cfg->cmp_mode) && model_mode_is_used(last_info->cmp_mode_used)) {
                 if (cfg->rdcu_model_adr == last_info->rdcu_new_model_adr_used &&
                     cfg->samples == last_info->samples_used) {
                         printf("The last updated model buffer and the current model buffer overlap exactly in the SRAM of the RDCU. Skip model transfer.\n");
                 } else {
                         uint32_t new_model_size_4byte;
                         /* set the model in the local mirror... */
                         if (rdcu_write_sram_16(cfg->model_buf, cfg->rdcu_model_adr,
                                                cfg->samples * IMA_SAM2BYT) < 0)
                                 return -1;
                         new_model_size_4byte = last_info->samples_used * IMA_SAM2BYT;
                         if (rdcu_sync_sram_mirror_parallel(last_info->rdcu_new_model_adr_used,
                                                            (new_model_size_4byte+3) & ~0x3U,
                                                            cfg->rdcu_model_adr,
                                                            samples_4byte, rdcu_get_data_mtu()))
                                 return -1;
                         /* wait for it */
                         rdcu_syncing();
                         if (cfg->icu_new_model_buf) {
                                 if (rdcu_read_sram(cfg->icu_new_model_buf,
                                                    last_info->rdcu_new_model_adr_used,
                                                    new_model_size_4byte) < 0)
                                         return -1;
                         }
                 }
         /* write model */
         } else if (cfg->model_buf && model_mode_is_used(cfg->cmp_mode)) {
                 /* set the model in the local mirror... */
                 if (rdcu_write_sram_16(cfg->model_buf, cfg->rdcu_model_adr,
                                        cfg->samples * IMA_SAM2BYT) < 0)
                         return -1;
                 if (rdcu_sync_mirror_to_sram(cfg->rdcu_model_adr, samples_4byte,
                                              rdcu_get_data_mtu()))
                         return -1;
         /* read model */
         } else if (model_mode_is_used(last_info->cmp_mode_used)) {
                 if (rdcu_read_model(last_info, cfg->icu_new_model_buf) < 0)
                         return -1;
         }
         /* ...and wait for completion */
         rdcu_syncing();
         if (rdcu_start_compression())
                 return -1;
         return 0;
 }
References cmp_bit_to_4byte(), cmp_info::cmp_err, cmp_cfg::cmp_mode, cmp_info::cmp_mode_used, cmp_info::cmp_size, debug_print, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, IMA_SAM2BYT, cmp_cfg::input_buf, cmp_cfg::model_buf, model_mode_is_used(), cmp_info::rdcu_cmp_adr_used, rdcu_compress_data(), cmp_cfg::rdcu_data_adr, rdcu_get_data_mtu(), cmp_cfg::rdcu_model_adr, cmp_info::rdcu_new_model_adr_used, rdcu_read_model(), rdcu_read_sram(), rdcu_set_compression_register(), rdcu_start_compression(), rdcu_sync_mirror_to_sram(), rdcu_sync_sram_mirror_parallel(), rdcu_syncing(), rdcu_write_sram_16(), cmp_cfg::samples, and cmp_info::samples_used.