cmp_tool: rdcu_syncing
rdcu_syncing()
static void rdcu_syncing (void) static
save repeating 3 lines of code...
Note
This function depends on the SpW implantation and must be adjusted to it.
prints abort message if pending status is non-zero after 10 retries
Definition at line 57 of file cmp_rdcu.c.
 {
 #if 0
         not needed for packed generation
         int cnt = 0;
         printf("syncing...");
         while (rdcu_rmap_sync_status()) {
                 printf("pending: %d\n", rdcu_rmap_sync_status());
                 if (cnt++ > 10) {
                         printf("aborting; de");
                         break;
                 }
         }
         printf("synced\n");
 #endif
 }
References rdcu_rmap_sync_status().
Referenced by rdcu_compress_data_parallel(), rdcu_inject_edac_error(), rdcu_interrupt_compression(), rdcu_read_cmp_bitstream(), rdcu_read_cmp_info(), rdcu_read_cmp_status(), rdcu_read_model(), rdcu_set_compression_register(), rdcu_start_compression(), and rdcu_transfer_sram().