cmp_tool: cmp_ent_get_data_buf
cmp_ent_get_data_buf()
void* cmp_ent_get_data_buf (struct cmp_entity * ent)
get the start address of the compressed data in the compression entity
Parameters
ent pointer to a compression entity
Note
this only works if the data_type in the compression entity is set
Returns
a pointer to buffer where the compressed data are located in entity on success, NULL on error
Definition at line 1637 of file cmp_entity.c.
 {
         enum cmp_data_type data_type;
         if (!ent)
                 return NULL;
         data_type = cmp_ent_get_data_type(ent);
         if (data_type == DATA_TYPE_UNKNOWN) {
                 debug_print("Error: Compression data type not supported.\n");
                 return NULL;
         }
         if (cmp_ent_get_data_type_raw_bit(ent))
                 return (uint8_t *)ent + GENERIC_HEADER_SIZE;
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE:
                 return ent->ima.ima_cmp_dat;
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 return ent->ima.ap_ima_cmp_data;
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_SMEARING:
         case DATA_TYPE_S_FX:
         case DATA_TYPE_S_FX_EFX:
         case DATA_TYPE_S_FX_NCOB:
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_L_FX:
         case DATA_TYPE_L_FX_EFX:
         case DATA_TYPE_L_FX_NCOB:
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_F_FX:
         case DATA_TYPE_F_FX_EFX:
         case DATA_TYPE_F_FX_NCOB:
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_F_CAM_OFFSET:
         case DATA_TYPE_F_CAM_BACKGROUND:
                 return ent->non_ima.cmp_data;
         /* LCOV_EXCL_START */
         case DATA_TYPE_UNKNOWN:
         default:
                 return NULL;
         /* LCOV_EXCL_STOP */
         }
 }
References imagette_header::ap_ima_cmp_data, non_imagette_header::cmp_data, cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, GENERIC_HEADER_SIZE, cmp_entity::ima, imagette_header::ima_cmp_dat, and cmp_entity::non_ima.
Referenced by cmp_ent_get_cmp_data(), cmp_ent_print_data(), cmp_ent_read_header(), compression_decompression(), icu_compress_data_entity(), test_cmp_decmp_n_imagette_raw(), test_cmp_ent_get_cmp_data(), test_cmp_ent_get_data_buf(), and test_cmp_ent_write_cmp_pars().