cmp_tool: cmp_cal_size_of_data
cmp_cal_size_of_data()
uint32_t cmp_cal_size_of_data (uint32_t samples, enum cmp_data_type data_type)
calculate the need bytes for the data
Parameters
samples number of data samples
data_type compression data_type
Note
for non-imagette data program types the multi entry header size is added
Returns
the size in bytes to store the data sample; zero on failure
Definition at line 118 of file cmp_data_types.c.
 {
         size_t s = size_of_a_sample(data_type);
         uint64_t x; /* use 64 bit to catch overflow */
         if (!s)
                 return 0;
         x = (uint64_t)s*samples;
         if (!rdcu_supported_data_type_is_used(data_type))
                 x += MULTI_ENTRY_HDR_SIZE;
         if (x > UINT_MAX) /* catch overflow */
                 return 0;
         return (unsigned int)x;
 }
References data_type, MULTI_ENTRY_HDR_SIZE, rdcu_supported_data_type_is_used(), and size_of_a_sample().
Referenced by cmp_buffer_length_to_bits(), cmp_cfg_icu_buffers(), cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), compression_decompression(), decompressed_data_internal(), generate_random_test_data(), icu_compress_data(), icu_compress_data_entity(), test_cmp_cal_size_of_data(), test_cmp_decmp_s_fx_diff(), test_cmp_ent_build(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), test_cmp_input_size_to_samples(), test_compress_s_fx_model_multi(), test_compress_s_fx_raw(), test_compress_s_fx_staff(), test_random_compression_decompression(), and test_random_compression_decompression2().