cmp_tool: rdcu_supported_data_type_is_used
rdcu_supported_data_type_is_used()
int rdcu_supported_data_type_is_used (enum cmp_data_type data_type)
check if the data product data type is supported by the RDCU compressor
Parameters
data_type compression data product type
Returns
1 when the data type is supported by the RDCU, otherwise 0
Definition at line 147 of file cmp_support.c.
 {
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 return 1;
         default:
                 return 0;
         }
 }
References data_type, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_SAT_IMAGETTE, and DATA_TYPE_SAT_IMAGETTE_ADAPTIVE.
Referenced by cmp_cal_size_of_data(), cmp_data_to_big_endian(), cmp_ent_write_rdcu_cmp_pars(), cmp_imagette_data_type_is_used(), cmp_input_big_to_cpu_endianness(), cmp_input_size_to_samples(), and generate_random_test_data().