cmp_tool: cmp_ent_write_cmp_pars
cmp_ent_write_cmp_pars()
int cmp_ent_write_cmp_pars (struct cmp_entity * ent, const struct cmp_cfg * cfg, int cmp_size_bits)
write the compression parameters from a compression configuration into the compression entity header
Note
NO compressed data are put into the entity and NO change of the entity size
Parameters
ent pointer to a compression entity
cfg pointer to a compression configuration
cmp_size_bits size of the compressed data in bits
Returns
0 on success, negative on error
Definition at line 1795 of file cmp_entity.c.
 {
         uint32_t ent_cmp_data_size;
         if (!cfg)
                 return -1;
         if (cmp_size_bits < 0)
                 return -1;
         if (cfg->data_type != cmp_ent_get_data_type(ent)) {
                 debug_print("Error: The entity data product type dos not match the configuration data product type.\n");
                 return -1;
         }
         if (cmp_ent_get_data_type_raw_bit(ent) != (cfg->cmp_mode == CMP_MODE_RAW)) {
                 debug_print("Error: The entity's raw data bit does not match up with the compression mode.\n");
                 return -1;
         }
         ent_cmp_data_size = cmp_ent_get_cmp_data_size(ent);
         /* check if the entity can hold the compressed data */
         if (ent_cmp_data_size < cmp_bit_to_byte((unsigned int)cmp_size_bits)) {
                 debug_print("Error: The entity size is to small to hold the compressed data.\n");
                 return -2;
         }
         /* set compression parameter fields in the generic entity header */
         if (cmp_ent_set_original_size(ent, cmp_cal_size_of_data(cfg->samples,
                                                                 cfg->data_type)))
                 return -1;
         if (cmp_ent_set_cmp_mode(ent, cfg->cmp_mode))
                 return -1;
         if (cmp_ent_set_model_value(ent, cfg->model_value))
                 return -1;
         if (cfg->max_used_bits)
                 cmp_ent_set_max_used_bits_version(ent, cfg->max_used_bits->version);
         else
                 cmp_ent_set_max_used_bits_version(ent, 0);
         if (cmp_ent_set_lossy_cmp_par(ent, cfg->round))
                 return -1;
         if (cfg->cmp_mode == CMP_MODE_RAW) /* no specific header is used for raw data we are done */
                 return 0;
         switch (cmp_ent_get_data_type(ent)) {
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 if (cmp_ent_set_ima_ap1_spill(ent, cfg->ap1_spill))
                         return -1;
                 if (cmp_ent_set_ima_ap1_golomb_par(ent, cfg->ap1_golomb_par))
                         return -1;
                 if (cmp_ent_set_ima_ap2_spill(ent, cfg->ap2_spill))
                         return -1;
                 if (cmp_ent_set_ima_ap2_golomb_par(ent, cfg->ap2_golomb_par))
                         return -1;
                 /* fall through */
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE:
                 if (cmp_ent_set_ima_spill(ent, cfg->spill))
                         return -1;
                 if (cmp_ent_set_ima_golomb_par(ent, cfg->golomb_par))
                         return -1;
                 break;
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_F_CAM_OFFSET:
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_F_CAM_BACKGROUND:
         case DATA_TYPE_SMEARING:
                 if (cmp_ent_set_non_ima_cmp_par1(ent, cfg->cmp_par_mean))
                         return -1;
                 if (cmp_ent_set_non_ima_spill1(ent, cfg->spill_mean))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par2(ent, cfg->cmp_par_variance))
                         return -1;
                 if (cmp_ent_set_non_ima_spill2(ent, cfg->spill_variance))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par3(ent, cfg->cmp_par_pixels_error))
                         return -1;
                 if (cmp_ent_set_non_ima_spill3(ent, cfg->spill_pixels_error))
                         return -1;
                 cmp_ent_set_non_ima_cmp_par4(ent, 0);
                 cmp_ent_set_non_ima_spill4(ent, 0);
                 cmp_ent_set_non_ima_cmp_par5(ent, 0);
                 cmp_ent_set_non_ima_spill5(ent, 0);
                 cmp_ent_set_non_ima_cmp_par6(ent, 0);
                 cmp_ent_set_non_ima_spill6(ent, 0);
                 break;
         case DATA_TYPE_S_FX:
         case DATA_TYPE_S_FX_EFX:
         case DATA_TYPE_S_FX_NCOB:
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_L_FX:
         case DATA_TYPE_L_FX_EFX:
         case DATA_TYPE_L_FX_NCOB:
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_F_FX:
         case DATA_TYPE_F_FX_EFX:
         case DATA_TYPE_F_FX_NCOB:
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 if (cmp_ent_set_non_ima_cmp_par1(ent, cfg->cmp_par_exp_flags))
                         return -1;
                 if (cmp_ent_set_non_ima_spill1(ent, cfg->spill_exp_flags))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par2(ent, cfg->cmp_par_fx))
                         return -1;
                 if (cmp_ent_set_non_ima_spill2(ent, cfg->spill_fx))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par3(ent, cfg->cmp_par_ncob))
                         return -1;
                 if (cmp_ent_set_non_ima_spill3(ent, cfg->spill_ncob))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par4(ent, cfg->cmp_par_efx))
                         return -1;
                 if (cmp_ent_set_non_ima_spill4(ent, cfg->spill_efx))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par5(ent, cfg->cmp_par_ecob))
                         return -1;
                 if (cmp_ent_set_non_ima_spill5(ent, cfg->spill_ecob))
                         return -1;
                 if (cmp_ent_set_non_ima_cmp_par6(ent, cfg->cmp_par_fx_cob_variance))
                         return -1;
                 if (cmp_ent_set_non_ima_spill6(ent, cfg->spill_fx_cob_variance))
                         return -1;
                 break;
         case DATA_TYPE_UNKNOWN:
         default:
                 return -1;
         }
         return 0;
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_bit_to_byte(), cmp_cal_size_of_data(), cmp_ent_get_cmp_data_size(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_set_cmp_mode(), cmp_ent_set_ima_ap1_golomb_par(), cmp_ent_set_ima_ap1_spill(), cmp_ent_set_ima_ap2_golomb_par(), cmp_ent_set_ima_ap2_spill(), cmp_ent_set_ima_golomb_par(), cmp_ent_set_ima_spill(), cmp_ent_set_lossy_cmp_par(), cmp_ent_set_max_used_bits_version(), cmp_ent_set_model_value(), cmp_ent_set_non_ima_cmp_par1(), cmp_ent_set_non_ima_cmp_par2(), cmp_ent_set_non_ima_cmp_par3(), cmp_ent_set_non_ima_cmp_par4(), cmp_ent_set_non_ima_cmp_par5(), cmp_ent_set_non_ima_cmp_par6(), cmp_ent_set_non_ima_spill1(), cmp_ent_set_non_ima_spill2(), cmp_ent_set_non_ima_spill3(), cmp_ent_set_non_ima_spill4(), cmp_ent_set_non_ima_spill5(), cmp_ent_set_non_ima_spill6(), cmp_ent_set_original_size(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_ncob, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, cmp_cfg::golomb_par, cmp_cfg::max_used_bits, cmp_cfg::model_value, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, cmp_cfg::spill_mean, cmp_cfg::spill_ncob, cmp_cfg::spill_pixels_error, cmp_cfg::spill_variance, and cmp_max_used_bits::version.
Referenced by cmp_ent_build(), icu_compress_data_entity(), test_cmp_ent_write_cmp_pars(), and test_cmp_ent_write_rdcu_cmp_pars().