cmp_tool: cmp_ent_get_cmp_data
cmp_ent_get_cmp_data()
int32_t cmp_ent_get_cmp_data (struct cmp_entity * ent, uint32_t * data_buf, uint32_t data_buf_size)
copy the data from a compression entity to a buffer
Parameters
ent pointer to the compression entity containing the compressed data
data_buf pointer to the destination data buffer to which the compressed data are copied (can be NULL)
data_buf_size size of the destination data buffer
Returns
the size in bytes to store the compressed data; negative on error
Note
converts the data to the system endianness
Definition at line 1702 of file cmp_entity.c.
 {
         uint32_t *cmp_ent_data_adr;
         uint32_t cmp_size_byte;
         if (!ent)
                 return -1;
         cmp_ent_data_adr = cmp_ent_get_data_buf(ent);
         if (!cmp_ent_data_adr) {
                 debug_print("Error: Compression data type is not supported.\n");
                 return -1;
         }
         cmp_size_byte = cmp_ent_get_cmp_data_size(ent);
         if (cmp_size_byte & 0x3) {
                 debug_print("Error: The compressed data are not correct formatted. Expected multiple of 4 hex words.\n");
                 return -1;
         }
         if (data_buf) {
                 uint32_t i;
                 uint32_t cmp_data_len_32;
                 if (cmp_size_byte > data_buf_size) {
                         debug_print("Error: data_buf size to small to hold the data.\n");
                         return -1;
                 }
                 memcpy(data_buf, cmp_ent_data_adr, cmp_size_byte);
                 cmp_data_len_32 = cmp_size_byte/sizeof(uint32_t);
                 for (i = 0; i < cmp_data_len_32; i++)
                         be32_to_cpus(&data_buf[i]);
         }
         return (int32_t)cmp_size_byte;
 }
References be32_to_cpus, cmp_ent_get_cmp_data_size(), cmp_ent_get_data_buf(), and debug_print.
Referenced by test_cmp_ent_get_cmp_data().