cmp_tool: golomb_encoder
golomb_encoder()
static uint32_t golomb_encoder (uint32_t value, uint32_t m, uint32_t log2_m, uint32_t * cw) static
forms a codeword according to the Golomb code
Parameters
value value to be encoded (must be smaller or equal than cmp_ima_max_spill(m))
m Golomb parameter (have to be bigger than 0)
log2_m is ilog_2(m) calculate outside function for better performance
cw address where the code word is stored
Warning
no check of the validity of the input parameters!
Returns
the length of the formed code word in bits; code word is invalid if the return value is greater than 32
Definition at line 482 of file cmp_icu.c.
 {
         uint32_t len = log2_m + 1;               /* codeword length in group 0 */
         uint32_t cutoff = (0x2U << log2_m) - m;  /* members in group 0 */
         if (value < cutoff) { /* group 0 */
                 *cw = value;
         } else { /* other groups */
                 uint32_t const reg_mask = 0x1FU;  /* mask for the right shift operand to prevent undefined behavior */
                 uint32_t g = (value-cutoff) / m;  /* group number of same cw length */
                 uint32_t r = (value-cutoff) - g * m; /* member in the group */
                 uint32_t gc = (1U << (g & reg_mask)) - 1; /* prepare the left side in unary */
                 uint32_t b = cutoff << 1;         /* form the base codeword */
                 *cw = gc << ((len+1) & reg_mask);  /* composed codeword part 1 */
                 *cw += b + r;                      /* composed codeword part 2 */
                 len += 1 + g;                      /* length of the codeword */
         }
         return len;
 }
Referenced by configure_encoder_setup(), test_encode_value_multi(), and test_golomb_encoder().