cmp_tool: cmp_ent_set_data_type
cmp_ent_set_data_type()
int cmp_ent_set_data_type (struct cmp_entity * ent, enum cmp_data_type data_type, int raw_mode_flag)
set the compression data product type in the compression entity header
Parameters
ent pointer to a compression entity
data_type compression data product type
raw_mode_flag set this flag if the raw compression mode (CMP_MODE_RAW) is used
Returns
0 on success, otherwise error
Definition at line 338 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (data_type > 0x7FF)
                 return -1;
         if (raw_mode_flag)
                 data_type |= 1U << RAW_BIT_DATA_TYPE_POS;
         ent->data_type = cpu_to_be16((uint16_t)data_type);
         return 0;
 }
References cpu_to_be16, data_type, cmp_entity::data_type, and RAW_BIT_DATA_TYPE_POS.
Referenced by cmp_ent_create(), test_cmp_ent_data_type(), test_cmp_ent_get_cmp_data(), test_cmp_ent_get_cmp_data_size(), test_cmp_ent_get_data_buf(), test_cmp_ent_read_header_error_cases(), test_cmp_ent_write_cmp_pars(), and test_cmp_ent_write_rdcu_cmp_pars().