cmp_tool: cmp_max_used_bits_list_get
cmp_max_used_bits_list_get()
const struct cmp_max_used_bits* cmp_max_used_bits_list_get (uint8_t version)
get an item from the max_used_bits list
Parameters
version version identifier of the max_used_bits list item
Returns
a pointer to the max_used_bits structure with the corresponding version on success; NULL if no list item has the version number
Definition at line 46 of file cmp_max_used_bits_list.c.
 {
         struct list_item *list_ptr = NULL;
         switch (version) {
         case 0:
                 return &MAX_USED_BITS_SAFE;
         case 1:
                 return &MAX_USED_BITS_V1;
         }
         list_for_each_entry(list_ptr, &max_used_bits_list, list) {
                 if (list_ptr->data.version == version)
                         return &list_ptr->data;
         }
         return NULL;
 }
References list_item::data, list_item::list, list_for_each_entry, MAX_USED_BITS_SAFE, MAX_USED_BITS_V1, and cmp_max_used_bits::version.
Referenced by cmp_ent_read_header(), test_cmp_ent_write_cmp_pars(), and test_cmp_max_used_bits_list().