cmp_tool: rdcu_read_cmp_info
rdcu_read_cmp_info()
int rdcu_read_cmp_info (struct cmp_info * info)
read out the metadata of an RDCU compression
Parameters
info compression information contains the metadata of a compression
Note
the compression information registers cannot be accessed during a compression
Returns
0 on success, error otherwise
Definition at line 344 of file cmp_rdcu.c.
 {
         /* read out the compressor information register*/
         if (rdcu_sync_used_param1())
                 return -1;
         if (rdcu_sync_used_param2())
                 return -1;
         if (rdcu_sync_compr_data_start_addr())
                 return -1;
         if (rdcu_sync_compr_data_size())
                 return -1;
         if (rdcu_sync_compr_data_adaptive_1_size())
                 return -1;
         if (rdcu_sync_compr_data_adaptive_2_size())
                 return -1;
         if (rdcu_sync_compr_error())
                 return -1;
         if (rdcu_sync_new_model_addr_used())
                 return -1;
         if (rdcu_sync_samples_used())
                 return -1;
         rdcu_syncing();
         if (info) {
                 /* put the data in the cmp_info structure */
                 info->cmp_mode_used = rdcu_get_compression_mode();
                 info->golomb_par_used = rdcu_get_golomb_param();
                 info->spill_used = rdcu_get_spillover_threshold();
                 info->model_value_used = (uint8_t)rdcu_get_weighting_param();
                 info->round_used = (uint8_t)rdcu_get_noise_bits_rounded();
                 info->rdcu_new_model_adr_used = rdcu_get_new_model_addr_used();
                 info->samples_used = rdcu_get_samples_used();
                 info->rdcu_cmp_adr_used = rdcu_get_compr_data_start_addr();
                 info->cmp_size = rdcu_get_compr_data_size_bit();
                 info->ap1_cmp_size = rdcu_get_compr_data_adaptive_1_size_bit();
                 info->ap2_cmp_size = rdcu_get_compr_data_adaptive_2_size_bit();
                 info->cmp_err = rdcu_get_compr_error();
 #ifdef FPGA_VERSION_0_7
                 /* There is a bug up to RDCU FPGA version 0.7 where the
                  * compressed size is not updated accordingly in RAW mode.
                  */
                 if (info->cmp_mode_used == CMP_MODE_RAW) {
                         info->cmp_size = info->samples_used * IMA_SAM2BYT * 8;
                         info->ap1_cmp_size = info->cmp_size;
                         info->ap2_cmp_size = info->cmp_size;
                 }
 #endif
 #if 1
                 /* There is a bug in RDCU FPGA version 1.1 where the compressed
                  * size is not updated accordingly in RAW mode when the samples
                  * parameter is smaller than 3.
                  */
                 if (info->cmp_mode_used == CMP_MODE_RAW && info->samples_used < 3) {
                         info->cmp_size = info->samples_used * IMA_SAM2BYT * 8;
                         info->ap1_cmp_size = info->cmp_size;
                         info->ap2_cmp_size = info->cmp_size;
                 }
 #endif
         }
         return 0;
 }
References cmp_info::ap1_cmp_size, cmp_info::ap2_cmp_size, cmp_info::cmp_err, CMP_MODE_RAW, cmp_info::cmp_mode_used, cmp_info::cmp_size, cmp_info::golomb_par_used, IMA_SAM2BYT, cmp_info::model_value_used, cmp_info::rdcu_cmp_adr_used, rdcu_get_compr_data_adaptive_1_size_bit(), rdcu_get_compr_data_adaptive_2_size_bit(), rdcu_get_compr_data_size_bit(), rdcu_get_compr_data_start_addr(), rdcu_get_compr_error(), rdcu_get_compression_mode(), rdcu_get_golomb_param(), rdcu_get_new_model_addr_used(), rdcu_get_noise_bits_rounded(), rdcu_get_samples_used(), rdcu_get_spillover_threshold(), rdcu_get_weighting_param(), cmp_info::rdcu_new_model_adr_used, rdcu_sync_compr_data_adaptive_1_size(), rdcu_sync_compr_data_adaptive_2_size(), rdcu_sync_compr_data_size(), rdcu_sync_compr_data_start_addr(), rdcu_sync_compr_error(), rdcu_sync_new_model_addr_used(), rdcu_sync_samples_used(), rdcu_sync_used_param1(), rdcu_sync_used_param2(), rdcu_syncing(), cmp_info::round_used, cmp_info::samples_used, and cmp_info::spill_used.