cmp_tool: cmp_cfg_gen_par_is_invalid
cmp_cfg_gen_par_is_invalid()
int cmp_cfg_gen_par_is_invalid (const struct cmp_cfg * cfg, enum check_opt opt)
check if the compression data type, compression mode, model value and the lossy rounding parameters are invalid for a RDCU or ICU compression
Parameters
cfg pointer to a compression configuration containing the compression data product type, compression mode, model value and the rounding parameters
opt check options: RDCU_CHECK for RDCU compression check ICU_CHECK for ICU compression check
Returns
0 if the compression data type, compression mode, model value and the lossy rounding parameters are valid for an RDCU or ICU compression, non-zero if parameters are invalid
Definition at line 407 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         int invalid_data_type = 1;
         int unsupported_cmp_mode = 1;
         int check_model_value = 1;
         uint32_t max_round_value = 0;
         const char *str = "";
         if (!cfg)
                 return 1;
         switch (opt) {
         case RDCU_CHECK:
                 /* the RDCU can only compress imagette data */
                 invalid_data_type = !cmp_imagette_data_type_is_used(cfg->data_type);
                 unsupported_cmp_mode = !rdcu_supported_cmp_mode_is_used(cfg->cmp_mode);
                 max_round_value = MAX_RDCU_ROUND;
                 /* for the RDCU the model vale has to be always in the allowed range */
                 check_model_value = 1;
                 str = " for a RDCU compression";
                 break;
         case ICU_CHECK:
                 invalid_data_type = cmp_data_type_is_invalid(cfg->data_type);
                 unsupported_cmp_mode = !cmp_mode_is_supported(cfg->cmp_mode);
                 max_round_value = MAX_ICU_ROUND;
                 check_model_value = model_mode_is_used(cfg->cmp_mode);
                 break;
         default:
                 return 1;
         }
         if (invalid_data_type) {
                 debug_print("Error: selected compression data type is not supported%s.\n", str);
                 cfg_invalid++;
         }
         if (unsupported_cmp_mode) {
                 debug_print("Error: selected cmp_mode: %i is not supported%s.\n", cfg->cmp_mode, str);
                 cfg_invalid++;
         }
         if (check_model_value) {
                 if (cfg->model_value > MAX_MODEL_VALUE) {
                         debug_print("Error: selected model_value: %" PRIu32 " is invalid. The largest supported value is: %u.\n",
                                     cfg->model_value, MAX_MODEL_VALUE);
                         cfg_invalid++;
                 }
         }
         if (cfg->round > max_round_value) {
                 debug_print("Error: selected lossy parameter: %" PRIu32 " is not supported%s. The largest supported value is: %" PRIu32 ".\n",
                             cfg->round, str, max_round_value);
                 cfg_invalid++;
         }
 #ifdef SKIP_CMP_PAR_CHECK
         return 0;
 #endif
         return cfg_invalid;
 }
References cmp_data_type_is_invalid(), cmp_imagette_data_type_is_used(), cmp_cfg::cmp_mode, cmp_mode_is_supported(), cmp_cfg::data_type, debug_print, ICU_CHECK, MAX_ICU_ROUND, MAX_MODEL_VALUE, MAX_RDCU_ROUND, model_mode_is_used(), cmp_cfg::model_value, RDCU_CHECK, rdcu_supported_cmp_mode_is_used(), and cmp_cfg::round.
Referenced by cmp_cfg_icu_is_invalid(), rdcu_cfg_create(), rdcu_cmp_cfg_is_invalid(), and test_support_function_call_NULL().