cmp_tool: cmp_cfg_fx_cob
cmp_cfg_fx_cob()
int cmp_cfg_fx_cob (struct cmp_cfg * cfg, uint32_t cmp_par_exp_flags, uint32_t spillover_exp_flags, uint32_t cmp_par_fx, uint32_t spillover_fx, uint32_t cmp_par_ncob, uint32_t spillover_ncob, uint32_t cmp_par_efx, uint32_t spillover_efx, uint32_t cmp_par_ecob, uint32_t spillover_ecob, uint32_t cmp_par_fx_cob_variance, uint32_t spillover_fx_cob_variance)
set up the configuration parameters for a flux/COB compression
Note
not all parameters are needed for every flux/COB compression data type
Parameters
cfg pointer to a compression configuration (created by the cmp_cfg_icu_create() function)
cmp_par_exp_flags exposure flags compression parameter
spillover_exp_flags exposure flags spillover threshold parameter
cmp_par_fx normal flux compression parameter
spillover_fx normal flux spillover threshold parameter
cmp_par_ncob normal center of brightness compression parameter
spillover_ncob normal center of brightness spillover threshold parameter
cmp_par_efx extended flux compression parameter
spillover_efx extended flux spillover threshold parameter
cmp_par_ecob extended center of brightness compression parameter
spillover_ecob extended center of brightness spillover threshold parameter
cmp_par_fx_cob_variance flux/COB variance compression parameter
spillover_fx_cob_variance flux/COB variance spillover threshold parameter
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 250 of file cmp_icu.c.
 {
         if (!cfg)
                 return -1;
         cfg->cmp_par_exp_flags = cmp_par_exp_flags;
         cfg->cmp_par_fx = cmp_par_fx;
         cfg->cmp_par_ncob = cmp_par_ncob;
         cfg->cmp_par_efx = cmp_par_efx;
         cfg->cmp_par_ecob = cmp_par_ecob;
         cfg->cmp_par_fx_cob_variance = cmp_par_fx_cob_variance;
         cfg->spill_exp_flags = spillover_exp_flags;
         cfg->spill_fx = spillover_fx;
         cfg->spill_ncob = spillover_ncob;
         cfg->spill_efx = spillover_efx;
         cfg->spill_ecob = spillover_ecob;
         cfg->spill_fx_cob_variance = spillover_fx_cob_variance;
         if (cmp_cfg_fx_cob_is_invalid(cfg))
                 return -1;
         return 0;
 }
References cmp_cfg_fx_cob_is_invalid(), cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, and cmp_cfg::spill_ncob.
Referenced by test_cmp_cfg_fx_cob(), test_cmp_decmp_s_fx_diff(), test_compress_f_fx_efx_error_cases(), test_compress_f_fx_efx_ncob_ecob(), test_compress_f_fx_error_cases(), test_compress_f_fx_ncob_error_cases(), test_compress_l_fx_efx_error_cases(), test_compress_l_fx_efx_ncob_ecob_error_cases(), test_compress_l_fx_error_cases(), test_compress_l_fx_ncob_error_cases(), test_compress_s_fx_efx_error_cases(), test_compress_s_fx_efx_ncob_ecob_error_cases(), test_compress_s_fx_error_cases(), and test_compress_s_fx_ncob_error_cases().