cmp_tool: cmp_cfg_icu_buffers_is_invalid
cmp_cfg_icu_buffers_is_invalid()
int cmp_cfg_icu_buffers_is_invalid (const struct cmp_cfg * cfg)
check if the ICU buffer parameters are invalid
Parameters
cfg pointer to the compressor configuration
Returns
0 if the buffer parameters are valid, otherwise invalid
Definition at line 478 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         if (!cfg)
                 return 1;
         if (cfg->input_buf == NULL) {
                 debug_print("Error: The data_to_compress buffer for the data to be compressed is NULL.\n");
                 cfg_invalid++;
         }
         if (cfg->samples == 0)
                 debug_print("Warning: The samples parameter is 0. No data are compressed. This behavior may not be intended.\n");
         if (cfg->icu_output_buf) {
                 if (cfg->buffer_length == 0 && cfg->samples != 0) {
                         debug_print("Error: The buffer_length is set to 0. There is no space to store the compressed data.\n");
                         cfg_invalid++;
                 }
                 if (raw_mode_is_used(cfg->cmp_mode) && cfg->buffer_length < cfg->samples) {
                         debug_print("Error: The compressed_data_len_samples is to small to hold the data form the data_to_compress.\n");
                         cfg_invalid++;
                 }
                 if (cfg->icu_output_buf == cfg->input_buf) {
                         debug_print("Error: The compressed_data buffer is the same as the data_to_compress buffer.\n");
                         cfg_invalid++;
                 }
         }
         if (model_mode_is_used(cfg->cmp_mode)) {
                 if (cfg->model_buf == NULL) {
                         debug_print("Error: The model_of_data buffer for the model data is NULL.\n");
                         cfg_invalid++;
                 }
                 if (cfg->model_buf == cfg->input_buf) {
                         debug_print("Error: The model_of_data buffer is the same as the data_to_compress buffer.\n");
                         cfg_invalid++;
                 }
                 if (cfg->model_buf == cfg->icu_output_buf) {
                         debug_print("Error: The model_of_data buffer is the same as the compressed_data buffer.\n");
                         cfg_invalid++;
                 }
                 if (cfg->icu_new_model_buf) {
                         if (cfg->icu_new_model_buf == cfg->input_buf) {
                                 debug_print("Error: The updated_model buffer is the same as the data_to_compress buffer.\n");
                                 cfg_invalid++;
                         }
                         if (cfg->icu_new_model_buf == cfg->icu_output_buf) {
                                 debug_print("Error: The compressed_data buffer is the same as the compressed_data buffer.\n");
                                 cfg_invalid++;
                         }
                 }
         }
         return cfg_invalid;
 }
References cmp_cfg::buffer_length, cmp_cfg::cmp_mode, debug_print, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_cfg::model_buf, model_mode_is_used(), raw_mode_is_used(), and cmp_cfg::samples.
Referenced by cmp_cfg_icu_buffers(), cmp_cfg_icu_is_invalid(), and test_support_function_call_NULL().