cmp_tool: rdcu_cfg_create
rdcu_cfg_create()
struct cmp_cfg rdcu_cfg_create (enum cmp_data_type data_type, enum cmp_mode cmp_mode, uint32_t model_value, uint32_t lossy_par)
create an RDCU compression configuration
Parameters
data_type compression data product type
cmp_mode compression mode
model_value model weighting parameter (only needed for model compression mode)
lossy_par lossy rounding parameter (use CMP_LOSSLESS for lossless compression)
Returns
a compression configuration containing the chosen parameters; on error the data_type record is set to DATA_TYPE_UNKNOWN
Definition at line 1 of file cmp_rdcu_cfg.c.
 {
         struct cmp_cfg cfg;
         memset(&cfg, 0, sizeof(cfg));
         cfg.data_type = data_type;
         cfg.cmp_mode = cmp_mode;
         cfg.model_value = model_value;
         cfg.round = lossy_par;
         cfg.max_used_bits = &MAX_USED_BITS_SAFE;
         if (cmp_cfg_gen_par_is_invalid(&cfg, RDCU_CHECK))
                 cfg.data_type = DATA_TYPE_UNKNOWN;
         return cfg;
 }
References cmp_cfg_gen_par_is_invalid(), cmp_cfg::cmp_mode, cmp_cfg::data_type, DATA_TYPE_UNKNOWN, cmp_cfg::max_used_bits, MAX_USED_BITS_SAFE, cmp_cfg::model_value, RDCU_CHECK, and cmp_cfg::round.
Referenced by test_rdcu_cfg_buffers_model(), test_rdcu_cfg_buffers_raw_diff(), test_rdcu_cfg_create(), test_rdcu_cfg_imagette(), test_rdcu_cfg_imagette_default(), and test_rdcu_cmp_cfg_is_invalid().