cmp_tool: compress_offset
compress_offset()
static int compress_offset (const struct cmp_cfg * cfg) static
compress offset data from the normal and fast cameras
Parameters
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 1905 of file cmp_icu.c.
 {
         int stream_len = 0;
         size_t i;
         struct offset *data_buf = cfg->input_buf;
         struct offset *model_buf = cfg->model_buf;
         struct offset *up_model_buf = NULL;
         struct offset *next_model_p;
         struct offset model;
         struct encoder_setupt setup_mean, setup_var;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         stream_len = compress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                               (void **)&up_model_buf, cfg->icu_output_buf);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         {
                 unsigned int mean_bits_used, variance_bits_used;
                 switch (cfg->data_type) {
                 case DATA_TYPE_F_CAM_OFFSET:
                         mean_bits_used = cfg->max_used_bits->fc_offset_mean;
                         variance_bits_used = cfg->max_used_bits->fc_offset_variance;
                         break;
                 case DATA_TYPE_OFFSET:
                 default:
                         mean_bits_used = cfg->max_used_bits->nc_offset_mean;
                         variance_bits_used = cfg->max_used_bits->nc_offset_variance;
                         break;
                 }
                 configure_encoder_setup(&setup_mean, cfg->cmp_par_mean, cfg->spill_mean,
                                         cfg->round, mean_bits_used, cfg);
                 configure_encoder_setup(&setup_var, cfg->cmp_par_variance, cfg->spill_variance,
                                         cfg->round, variance_bits_used, cfg);
         }
         for (i = 0;; i++) {
                 stream_len = encode_value(data_buf[i].mean, model.mean,
                                           stream_len, &setup_mean);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].variance, model.variance,
                                           stream_len, &setup_var);
                 if (stream_len <= 0)
                         return stream_len;
                 if (up_model_buf) {
                         up_model_buf[i].mean = cmp_up_model(data_buf[i].mean, model.mean,
                                 cfg->model_value, setup_mean.lossy_par);
                         up_model_buf[i].variance = cmp_up_model(data_buf[i].variance, model.variance,
                                 cfg->model_value, setup_var.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return stream_len;
 }
References cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_variance, cmp_up_model, compress_multi_entry_hdr(), configure_encoder_setup(), cmp_cfg::data_type, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_OFFSET, encode_value(), cmp_max_used_bits::fc_offset_mean, cmp_max_used_bits::fc_offset_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, encoder_setupt::lossy_par, cmp_cfg::max_used_bits, mean, offset::mean, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, cmp_max_used_bits::nc_offset_mean, cmp_max_used_bits::nc_offset_variance, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_mean, cmp_cfg::spill_variance, variance, and offset::variance.
Referenced by icu_compress_data().