cmp_tool: cmp_cfg_icu_imagette
cmp_cfg_icu_imagette()
int cmp_cfg_icu_imagette (struct cmp_cfg * cfg, uint32_t cmp_par, uint32_t spillover_par)
set up the configuration parameters for an ICU imagette compression
Parameters
cfg pointer to a compression configuration (created by the cmp_cfg_icu_create() function)
cmp_par imagette compression parameter (Golomb parameter)
spillover_par imagette spillover threshold parameter
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 212 of file cmp_icu.c.
 {
         if (!cfg)
                 return -1;
         cfg->golomb_par = cmp_par;
         cfg->spill = spillover_par;
         if (cmp_cfg_imagette_is_invalid(cfg, ICU_CHECK))
                 return -1;
         return 0;
 }
References cmp_cfg_imagette_is_invalid(), cmp_cfg::golomb_par, ICU_CHECK, and cmp_cfg::spill.
Referenced by test_cmp_cfg_icu_imagette(), test_compress_imagette_diff(), test_compress_imagette_model(), and test_compress_imagette_stuff().