cmp_tool: cmp_ent_parese_specific_header
cmp_ent_parese_specific_header()
static void cmp_ent_parese_specific_header (const struct cmp_entity * ent) static
parse the specific compressed entity header
Parameters
ent pointer to a compression entity
Definition at line 2422 of file cmp_entity.c.
 {
         enum cmp_data_type data_type = cmp_ent_get_data_type(ent);
         if (cmp_ent_get_data_type_raw_bit(ent)) {
                 printf("Uncompressed data bit is set. No specific header is used.\n");
                 return;
         }
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE:
                 cmp_ent_parese_imagette_header(ent);
                 break;
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 cmp_ent_parese_adaptive_imagette_header(ent);
                 break;
         default:
                 printf("For this data product type no parse functions is implemented!\n");
                 break;
         }
 }
References cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_parese_adaptive_imagette_header(), cmp_ent_parese_imagette_header(), data_type, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_SAT_IMAGETTE, and DATA_TYPE_SAT_IMAGETTE_ADAPTIVE.
Referenced by cmp_ent_parse().