cmp_tool: rdcu_transfer_sram
rdcu_transfer_sram()
static int rdcu_transfer_sram (const struct cmp_cfg * cfg) static
set up RDCU SRAM for compression
Parameters
cfg pointer to a compression configuration
Returns
0 on success, error otherwise
Definition at line 236 of file cmp_rdcu.c.
 {
         if (cfg->input_buf != NULL) {
                 /* round up needed size must be a multiple of 4 bytes */
                 uint32_t size = (cfg->samples * 2 + 3) & ~3U;
                 /* now set the data in the local mirror... */
                 if (rdcu_write_sram_16(cfg->input_buf, cfg->rdcu_data_adr, cfg->samples * 2) < 0) {
                         debug_print("Error: The data to be compressed cannot be transferred to the SRAM of the RDCU.\n");
                         return -1;
                 }
                 if (rdcu_sync_mirror_to_sram(cfg->rdcu_data_adr, size, rdcu_get_data_mtu())) {
                         debug_print("Error: The data to be compressed cannot be transferred to the SRAM of the RDCU.\n");
                         return -1;
                 }
         }
         /*...and the model when needed */
         if (cfg->model_buf != NULL) {
                 /* set model only when model mode is used */
                 if (model_mode_is_used(cfg->cmp_mode)) {
                         /* round up needed size must be a multiple of 4 bytes */
                         uint32_t size = (cfg->samples * 2 + 3) & ~3U;
                         /* set the model in the local mirror... */
                         if (rdcu_write_sram_16(cfg->model_buf, cfg->rdcu_model_adr, cfg->samples * 2) < 0) {
                                 debug_print("Error: The model buffer cannot be transferred to the SRAM of the RDCU.\n");
                                 return -1;
                         }
                         if (rdcu_sync_mirror_to_sram(cfg->rdcu_model_adr, size, rdcu_get_data_mtu())) {
                                 debug_print("Error: The model buffer cannot be transferred to the SRAM of the RDCU.\n");
                                 return -1;
                         }
                 }
         }
         /* ...and wait for completion */
         rdcu_syncing();
         return 0;
 }
References cmp_cfg::cmp_mode, debug_print, cmp_cfg::input_buf, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::rdcu_data_adr, rdcu_get_data_mtu(), cmp_cfg::rdcu_model_adr, rdcu_sync_mirror_to_sram(), rdcu_syncing(), rdcu_write_sram_16(), and cmp_cfg::samples.
Referenced by rdcu_compress_data(), and rdcu_inject_edac_error().