cmp_tool: cmp_data_to_big_endian
cmp_data_to_big_endian()
static int cmp_data_to_big_endian (const struct cmp_cfg * cfg, int cmp_size) static
change the endianness of the compressed data to big-endian
Parameters
cfg pointer to the compression configuration structure
cmp_size length of the bitstream in bits
Returns
0 on success; non-zero on failure
Definition at line 2192 of file cmp_icu.c.
 {
 #if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
         size_t i;
         uint32_t *p;
         uint32_t s = (uint32_t)cmp_size;
         if (cmp_size < 0)
                 return cmp_size;
         if (!cfg->icu_output_buf)
                 return cmp_size;
         if (cfg->cmp_mode == CMP_MODE_RAW) {
                 if (s & 0x7) /* size must be a multiple of 8 in RAW mode */
                         return -1;
                 if (cmp_input_big_to_cpu_endianness(cfg->icu_output_buf,
                                                     s/CHAR_BIT, cfg->data_type))
                         cmp_size = -1;
         } else {
                 if (rdcu_supported_data_type_is_used(cfg->data_type)) {
                         p = cfg->icu_output_buf;
                 } else {
                         p = &cfg->icu_output_buf[MULTI_ENTRY_HDR_SIZE/sizeof(uint32_t)];
                         s -= MULTI_ENTRY_HDR_SIZE * CHAR_BIT;
                 }
                 for (i = 0; i < cmp_bit_to_4byte(s)/sizeof(uint32_t); i++)
                         cpu_to_be32s(&p[i]);
         }
 #else
         /* do nothing data are already in big-endian */
         (void)cfg;
 #endif /*__BYTE_ORDER__ */
         return cmp_size;
 }
References cmp_bit_to_4byte(), cmp_input_big_to_cpu_endianness(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cpu_to_be32s, cmp_cfg::data_type, cmp_cfg::icu_output_buf, MULTI_ENTRY_HDR_SIZE, and rdcu_supported_data_type_is_used().
Referenced by icu_compress_data(), and test_cmp_data_to_big_endian_error_cases().