cmp_tool: cmp_ent_parese_adaptive_imagette_header
cmp_ent_parese_adaptive_imagette_header()
static void cmp_ent_parese_adaptive_imagette_header (const struct cmp_entity * ent) static
parse the adaptive imagette specific compressed entity header
Parameters
ent pointer to a compression entity
Definition at line 2391 of file cmp_entity.c.
 {
         uint32_t spill_used, golomb_par_used, ap1_spill_used,
                  ap1_golomb_par_used, ap2_spill_used, ap2_golomb_par_used;
         spill_used = cmp_ent_get_ima_spill(ent);
         printf("Used Spillover Threshold Parameter: %" PRIu32 "\n", spill_used);
         golomb_par_used = cmp_ent_get_ima_golomb_par(ent);
         printf("Used Golomb Parameter: %" PRIu32 "\n", golomb_par_used);
         ap1_spill_used = cmp_ent_get_ima_ap1_spill(ent);
         printf("Used Adaptive 1 Spillover Threshold Parameter: %" PRIu32 "\n", ap1_spill_used);
         ap1_golomb_par_used = cmp_ent_get_ima_ap1_golomb_par(ent);
         printf("Used Adaptive 1 Golomb Parameter: %" PRIu32 "\n", ap1_golomb_par_used);
         ap2_spill_used = cmp_ent_get_ima_ap2_spill(ent);
         printf("Used Adaptive 2 Spillover Threshold Parameter: %" PRIu32 "\n", ap2_spill_used);
         ap2_golomb_par_used = cmp_ent_get_ima_ap2_golomb_par(ent);
         printf("Used Adaptive 2 Golomb Parameter: %" PRIu32 "\n", ap2_golomb_par_used);
 }
References ap1_golomb_par_used, ap1_spill_used, ap2_golomb_par_used, ap2_spill_used, cmp_ent_get_ima_ap1_golomb_par(), cmp_ent_get_ima_ap1_spill(), cmp_ent_get_ima_ap2_golomb_par(), cmp_ent_get_ima_ap2_spill(), cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), golomb_par_used, and spill_used.
Referenced by cmp_ent_parese_specific_header().