cmp_tool: rdcu_set_compression_register
rdcu_set_compression_register()
static int rdcu_set_compression_register (const struct cmp_cfg * cfg) static
set up RDCU compression register
Parameters
cfg pointer to a compression configuration contains all parameters required for compression
Returns
0 on success, error otherwise
Definition at line 112 of file cmp_rdcu.c.
 {
         if (rdcu_cmp_cfg_is_invalid(cfg))
                 return -1;
 #if 1
         /*
          * There is a bug in the RDCU HW data compressor, when a non-raw mode
          * compression is performed after a raw mode compression, the compressor
          * gets stuck due to a deadlock condition. Performing a compression
          * interrupt after a raw mode compression work around this bug.
          */
         if (rdcu_sync_used_param1())
                 return -1;
         rdcu_syncing();
         if (rdcu_get_compression_mode() == CMP_MODE_RAW)
                 rdcu_interrupt_compression();
 #endif
         /* first, set compression parameters in local mirror registers */
         if (rdcu_set_compression_mode(cfg->cmp_mode))
                 return -1;
         if (rdcu_set_golomb_param(cfg->golomb_par))
                 return -1;
         if (rdcu_set_spillover_threshold(cfg->spill))
                 return -1;
         if (rdcu_set_weighting_param(cfg->model_value))
                 return -1;
         if (rdcu_set_noise_bits_rounded(cfg->round))
                 return -1;
         if (rdcu_set_adaptive_1_golomb_param(cfg->ap1_golomb_par))
                 return -1;
         if (rdcu_set_adaptive_1_spillover_threshold(cfg->ap1_spill))
                 return -1;
         if (rdcu_set_adaptive_2_golomb_param(cfg->ap2_golomb_par))
                 return -1;
         if (rdcu_set_adaptive_2_spillover_threshold(cfg->ap2_spill))
                 return -1;
         if (rdcu_set_data_start_addr(cfg->rdcu_data_adr))
                 return -1;
         if (rdcu_set_model_start_addr(cfg->rdcu_model_adr))
                 return -1;
         if (rdcu_set_num_samples(cfg->samples))
                 return -1;
         if (rdcu_set_new_model_start_addr(cfg->rdcu_new_model_adr))
                 return -1;
         if (rdcu_set_compr_data_buf_start_addr(cfg->rdcu_buffer_adr))
                 return -1;
         if (rdcu_set_compr_data_buf_len(cfg->buffer_length))
                 return -1;
         /* now sync the configuration registers to the RDCU... */
         if (rdcu_sync_compressor_param1())
                 return -1;
         if (rdcu_sync_compressor_param2())
                 return -1;
         if (rdcu_sync_adaptive_param1())
                 return -1;
         if (rdcu_sync_adaptive_param2())
                 return -1;
         if (rdcu_sync_data_start_addr())
                 return -1;
         if (rdcu_sync_model_start_addr())
                 return -1;
         if (rdcu_sync_num_samples())
                 return -1;
         if (rdcu_sync_new_model_start_addr())
                 return -1;
         if (rdcu_sync_compr_data_buf_start_addr())
                 return -1;
         if (rdcu_sync_compr_data_buf_len())
                 return -1;
         /* wait for it */
         rdcu_syncing();
         return 0;
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_cfg::buffer_length, cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::golomb_par, cmp_cfg::model_value, cmp_cfg::rdcu_buffer_adr, rdcu_cmp_cfg_is_invalid(), cmp_cfg::rdcu_data_adr, rdcu_get_compression_mode(), rdcu_interrupt_compression(), cmp_cfg::rdcu_model_adr, cmp_cfg::rdcu_new_model_adr, rdcu_set_adaptive_1_golomb_param(), rdcu_set_adaptive_1_spillover_threshold(), rdcu_set_adaptive_2_golomb_param(), rdcu_set_adaptive_2_spillover_threshold(), rdcu_set_compr_data_buf_len(), rdcu_set_compr_data_buf_start_addr(), rdcu_set_compression_mode(), rdcu_set_data_start_addr(), rdcu_set_golomb_param(), rdcu_set_model_start_addr(), rdcu_set_new_model_start_addr(), rdcu_set_noise_bits_rounded(), rdcu_set_num_samples(), rdcu_set_spillover_threshold(), rdcu_set_weighting_param(), rdcu_sync_adaptive_param1(), rdcu_sync_adaptive_param2(), rdcu_sync_compr_data_buf_len(), rdcu_sync_compr_data_buf_start_addr(), rdcu_sync_compressor_param1(), rdcu_sync_compressor_param2(), rdcu_sync_data_start_addr(), rdcu_sync_model_start_addr(), rdcu_sync_new_model_start_addr(), rdcu_sync_num_samples(), rdcu_sync_used_param1(), rdcu_syncing(), cmp_cfg::round, cmp_cfg::samples, and cmp_cfg::spill.
Referenced by rdcu_compress_data(), rdcu_compress_data_parallel(), and rdcu_inject_edac_error().