cmp_tool: encode_value_multi
encode_value_multi()
static int encode_value_multi (uint32_t data, uint32_t model, int stream_len, const struct encoder_setupt * setup) static
subtract the model from the data, encode the result and put it into bitstream, for encoding outlier use the multi escape symbol mechanism
Parameters
data data to encode
model model of the data (0 if not used)
stream_len length of the bitstream in bits
setup pointer to the encoder setup
Returns
the bit length of the bitstream with the added encoded value on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Note
no check if the data or model are in the allowed range
no check if the setup->spillover_par is in the allowed range
Definition at line 598 of file cmp_icu.c.
 {
         uint32_t unencoded_data;
         unsigned int unencoded_data_len;
         uint32_t escape_sym, escape_sym_offset;
         data -= model; /* possible underflow is intended */
         data = map_to_pos(data, setup->max_data_bits);
         if (data < setup->spillover_par) /* detect non-outlier */
                 return  encode_normal(data, stream_len, setup);
         /*
          * In this mode we put the difference between the data and the spillover
          * threshold value (unencoded_data) after an encoded escape symbol, which
          * indicate that the next codeword is unencoded.
          * We use different escape symbol depended on the size the needed bit of
          * unencoded data:
          * 0, 1, 2 bits needed for unencoded data -> escape symbol is spillover_par + 0
          * 3, 4 bits needed for unencoded data -> escape symbol is spillover_par + 1
          * 5, 6 bits needed for unencoded data -> escape symbol is spillover_par + 2
          * and so on
          */
         unencoded_data = data - setup->spillover_par;
         if (!unencoded_data) /* catch __builtin_clz(0) because the result is undefined.*/
                 escape_sym_offset = 0;
         else
                 escape_sym_offset = (31U - (uint32_t)__builtin_clz(unencoded_data)) >> 1;
         escape_sym = setup->spillover_par + escape_sym_offset;
         unencoded_data_len = (escape_sym_offset + 1U) << 1;
         /* put the escape symbol in the bitstream */
         stream_len = encode_normal(escape_sym, stream_len, setup);
         if (stream_len <= 0)
                 return stream_len;
         /* put the unencoded data in the bitstream */
         stream_len = put_n_bits32(unencoded_data, unencoded_data_len, stream_len,
                                   setup->bitstream_adr, setup->max_stream_len);
         return stream_len;
 }
References encoder_setupt::bitstream_adr, encode_normal(), map_to_pos(), encoder_setupt::max_data_bits, encoder_setupt::max_stream_len, put_n_bits32(), and encoder_setupt::spillover_par.
Referenced by configure_encoder_setup(), and test_encode_value_multi().