cmp_tool: cmp_cfg_aux_is_invalid
cmp_cfg_aux_is_invalid()
int cmp_cfg_aux_is_invalid (const struct cmp_cfg * cfg)
check if the auxiliary science specific compression parameters are invalid
Parameters
cfg pointer to the compressor configuration
Returns
0 if the auxiliary science specific parameters are valid, otherwise invalid
Definition at line 877 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         if (!cfg)
                 return 1;
         if (!cmp_aux_data_type_is_used(cfg->data_type)) {
                 debug_print("Error: The compression data type is not an auxiliary science compression data type.\n");
                 cfg_invalid++;
         }
         cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_mean, cfg->spill_mean,
                                             cfg->cmp_mode, cfg->data_type, "mean");
         cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_variance, cfg->spill_variance,
                                             cfg->cmp_mode, cfg->data_type, "variance");
         if (cfg->data_type != DATA_TYPE_OFFSET && cfg->data_type != DATA_TYPE_F_CAM_OFFSET)
                 cfg_invalid += cmp_pars_are_invalid(cfg->cmp_par_pixels_error, cfg->spill_pixels_error,
                                                     cfg->cmp_mode, cfg->data_type, "outlier pixls num");
         return cfg_invalid;
 }
References cmp_aux_data_type_is_used(), cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_pars_are_invalid(), cmp_cfg::data_type, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_OFFSET, debug_print, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, and cmp_cfg::spill_variance.
Referenced by cmp_cfg_aux(), cmp_cfg_icu_is_invalid(), decompressed_data_internal(), and test_support_function_call_NULL().