cmp_tool: cmp_up_model32
cmp_up_model32()
static uint32_t cmp_up_model32 (uint32_t data, uint32_t model, unsigned int model_value, unsigned int round) inline static
Definition at line 101 of file cmp_cal_up_model.h.
 {
         /* round and round back input because for decompression the accurate
          * data values are not available
          * cast to uint64_t to prevent overflow in the multiplication
          */
         uint64_t const weighted_data = (uint64_t)round_inv(round_fwd(data, round), round)
                 * (MAX_MODEL_VALUE - model_value);
         uint64_t const weighted_model = (uint64_t)model * model_value;
         /* truncation is intended */
         return (uint32_t)((weighted_model + weighted_data) / MAX_MODEL_VALUE);
 }
References MAX_MODEL_VALUE, round_fwd, and round_inv.
Referenced by compress_l_fx(), compress_l_fx_efx(), compress_l_fx_efx_ncob_ecob(), compress_l_fx_ncob(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), and decompress_l_fx_ncob().