cmp_tool: rdcu_cfg_buffers_is_invalid
rdcu_cfg_buffers_is_invalid()
static int rdcu_cfg_buffers_is_invalid (const struct cmp_cfg * cfg) static
check if RDCU buffer settings are invalid
Parameters
cfg a pointer to a compression configuration
Returns
0 if buffers configuration is valid, otherwise the configuration is invalid
Definition at line 118 of file cmp_rdcu_cfg.c.
 {
         int cfg_invalid = 0;
         if (cfg->cmp_mode == CMP_MODE_RAW) {
                 if (cfg->buffer_length < cfg->samples) {
                         debug_print("rdcu_buffer_length is smaller than the samples parameter. There is not enough space to copy the data in RAW mode.\n");
                         cfg_invalid++;
                 }
         }
         if (cfg->rdcu_data_adr & 0x3) {
                 debug_print("Error: The RDCU data to compress start address is not 4-Byte aligned.\n");
                 cfg_invalid++;
         }
         if (cfg->rdcu_buffer_adr & 0x3) {
                 debug_print("Error: The RDCU compressed data start address is not 4-Byte aligned.\n");
                 cfg_invalid++;
         }
         if (outside_sram_range(cfg->rdcu_data_adr, cfg->samples * IMA_SAM2BYT)) {
                 debug_print("Error: The RDCU data to compress buffer is outside the RDCU SRAM address space.\n");
                 cfg_invalid++;
         }
         if (outside_sram_range(cfg->rdcu_buffer_adr, cfg->buffer_length * IMA_SAM2BYT)) {
                 debug_print("Error: The RDCU compressed data buffer is outside the RDCU SRAM address space.\n");
                 cfg_invalid++;
         }
         if (buffers_overlap(cfg->rdcu_data_adr,
                             cfg->rdcu_data_adr + cfg->samples * IMA_SAM2BYT,
                             cfg->rdcu_buffer_adr,
                             cfg->rdcu_buffer_adr + cfg->buffer_length * IMA_SAM2BYT)) {
                 debug_print("Error: The RDCU data to compress buffer and the RDCU compressed data buffer are overlapping.\n");
                 cfg_invalid++;
         }
         if (model_mode_is_used(cfg->cmp_mode)) {
                 if (cfg->model_buf && cfg->model_buf == cfg->input_buf) {
                         debug_print("Error: The model buffer (model_buf) and the data to be compressed (input_buf) are equal.\n");
                         cfg_invalid++;
                 }
                 if (cfg->rdcu_model_adr & 0x3) {
                         debug_print("Error: The RDCU model start address is not 4-Byte aligned.\n");
                         cfg_invalid++;
                 }
                 if (outside_sram_range(cfg->rdcu_model_adr, cfg->samples * IMA_SAM2BYT)) {
                         debug_print("Error: The RDCU model buffer is outside the RDCU SRAM address space.\n");
                         cfg_invalid++;
                 }
                 if (buffers_overlap(
                             cfg->rdcu_model_adr,
                             cfg->rdcu_model_adr + cfg->samples * IMA_SAM2BYT,
                             cfg->rdcu_data_adr,
                             cfg->rdcu_data_adr + cfg->samples * IMA_SAM2BYT)) {
                         debug_print("Error: The model buffer and the data to compress buffer are overlapping.\n");
                         cfg_invalid++;
                 }
                 if (buffers_overlap(
                         cfg->rdcu_model_adr,
                         cfg->rdcu_model_adr + cfg->samples * IMA_SAM2BYT,
                         cfg->rdcu_buffer_adr,
                         cfg->rdcu_buffer_adr + cfg->buffer_length * IMA_SAM2BYT)
                     ) {
                         debug_print("Error: The model buffer and the compressed data buffer are overlapping.\n");
                         cfg_invalid++;
                 }
                 if (cfg->rdcu_model_adr != cfg->rdcu_new_model_adr) {
                         if (cfg->rdcu_new_model_adr & 0x3) {
                                 debug_print("Error: The RDCU updated model start address (rdcu_new_model_adr) is not 4-Byte aligned.\n");
                                 cfg_invalid++;
                         }
                         if (outside_sram_range(cfg->rdcu_new_model_adr,
                                            cfg->samples * IMA_SAM2BYT)) {
                                 debug_print("Error: The RDCU updated model buffer is outside the RDCU SRAM address space.\n");
                                 cfg_invalid++;
                         }
                         if (buffers_overlap(
                                 cfg->rdcu_new_model_adr,
                                 cfg->rdcu_new_model_adr + cfg->samples * IMA_SAM2BYT,
                                 cfg->rdcu_data_adr,
                                 cfg->rdcu_data_adr + cfg->samples * IMA_SAM2BYT)
                             ) {
                                 debug_print("Error: The updated model buffer and the data to compress buffer are overlapping.\n");
                                 cfg_invalid++;
                         }
                         if (buffers_overlap(
                                 cfg->rdcu_new_model_adr,
                                 cfg->rdcu_new_model_adr + cfg->samples * IMA_SAM2BYT,
                                 cfg->rdcu_buffer_adr,
                                 cfg->rdcu_buffer_adr + cfg->buffer_length * IMA_SAM2BYT)
                             ) {
                                 debug_print("Error: The updated model buffer and the compressed data buffer are overlapping.\n");
                                 cfg_invalid++;
                         }
                         if (buffers_overlap(
                                 cfg->rdcu_new_model_adr,
                                 cfg->rdcu_new_model_adr + cfg->samples * IMA_SAM2BYT,
                                 cfg->rdcu_model_adr,
                                 cfg->rdcu_model_adr + cfg->samples * IMA_SAM2BYT)
                             ) {
                                 debug_print("Error: The updated model buffer and the model buffer are overlapping.\n");
                                 cfg_invalid++;
                         }
                 }
         }
 #ifdef SKIP_CMP_PAR_CHECK
         return 0;
 #endif
         return cfg_invalid;
 }
References cmp_cfg::buffer_length, buffers_overlap(), cmp_cfg::cmp_mode, CMP_MODE_RAW, debug_print, IMA_SAM2BYT, cmp_cfg::input_buf, cmp_cfg::model_buf, model_mode_is_used(), outside_sram_range(), cmp_cfg::rdcu_buffer_adr, cmp_cfg::rdcu_data_adr, cmp_cfg::rdcu_model_adr, cmp_cfg::rdcu_new_model_adr, and cmp_cfg::samples.
Referenced by rdcu_cfg_buffers(), and rdcu_cmp_cfg_is_invalid().