cmp_tool: encode_value_zero
encode_value_zero()
static int encode_value_zero (uint32_t data, uint32_t model, int stream_len, const struct encoder_setupt * setup) static
subtract the model from the data, encode the result and put it into bitstream, for encoding outlier use the zero escape symbol mechanism
Parameters
data data to encode
model model of the data (0 if not used)
stream_len length of the bitstream in bits
setup pointer to the encoder setup
Returns
the bit length of the bitstream with the added encoded value on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Note
no check if the data or model are in the allowed range
no check if the setup->spillover_par is in the allowed range
Definition at line 548 of file cmp_icu.c.
 {
         data -= model; /* possible underflow is intended */
         data = map_to_pos(data, setup->max_data_bits);
         /* For performance reasons, we check to see if there is an outlier
          * before adding one, rather than the other way around:
          * data++;
          * if (data < setup->spillover_par && data != 0)
          *      return ...
          */
         if (data < (setup->spillover_par - 1)) { /* detect non-outlier */
                 data++; /* add 1 to every value so we can use 0 as escape symbol */
                 return encode_normal(data, stream_len, setup);
         }
         data++; /* add 1 to every value so we can use 0 as escape symbol */
         /* use zero as escape symbol */
         stream_len = encode_normal(0, stream_len, setup);
         if (stream_len <= 0)
                 return stream_len;
         /* put the data unencoded in the bitstream */
         stream_len = put_n_bits32(data, setup->max_data_bits, stream_len,
                                   setup->bitstream_adr, setup->max_stream_len);
         return stream_len;
 }
References encoder_setupt::bitstream_adr, encode_normal(), map_to_pos(), encoder_setupt::max_data_bits, encoder_setupt::max_stream_len, put_n_bits32(), and encoder_setupt::spillover_par.
Referenced by configure_encoder_setup(), and test_encode_value_zero().