cmp_tool: encode_value
encode_value()
static int encode_value (uint32_t data, uint32_t model, int stream_len, const struct encoder_setupt * setup) static
encodes the data with the model and the given setup and put it into the bitstream
Parameters
data data to encode
model model of the data (0 if not used)
stream_len length of the bitstream in bits
setup pointer to the encoder setup
Returns
the bit length of the bitstream with the added encoded value on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream, CMP_ERROR_HIGH_VALUE if the value or the model is bigger than the max_used_bits parameter allows
Definition at line 687 of file cmp_icu.c.
 {
         uint32_t mask = ~(0xFFFFFFFFU >> (32-setup->max_data_bits));
         /* lossy rounding of the data if lossy_par > 0 */
         data = round_fwd(data, setup->lossy_par);
         model = round_fwd(model, setup->lossy_par);
         if (data & mask || model & mask) {
                 debug_print("Error: The data or the model of the data are bigger than expected.\n");
                 return CMP_ERROR_HIGH_VALUE;
         }
         return setup->encode_method_f(data, model, stream_len, setup);
 }
References CMP_ERROR_HIGH_VALUE, debug_print, encoder_setupt::encode_method_f, encoder_setupt::lossy_par, encoder_setupt::max_data_bits, and round_fwd.
Referenced by compress_background(), compress_f_fx(), compress_f_fx_efx(), compress_f_fx_efx_ncob_ecob(), compress_f_fx_ncob(), compress_imagette(), compress_l_fx(), compress_l_fx_efx(), compress_l_fx_efx_ncob_ecob(), compress_l_fx_ncob(), compress_offset(), compress_s_fx(), compress_s_fx_efx(), compress_s_fx_efx_ncob_ecob(), compress_s_fx_ncob(), compress_smearing(), and test_encode_value().