cmp_tool: rdcu_read_model
rdcu_read_model()
int rdcu_read_model (const struct cmp_info * info, void * updated_model)
read the updated model from the RDCU SRAM
Parameters
info compression information contains the metadata of a compression
updated_model the buffer to store the updated model (if NULL, the required size is returned)
Returns
the number of bytes read, < 0 on error
Definition at line 453 of file cmp_rdcu.c.
 {
         uint32_t s;
         if (info == NULL)
                 return -1;
         /* calculate the need bytes for the model */
         s = info->samples_used * IMA_SAM2BYT;
         if (updated_model == NULL)
                 return (int)s;
         if (rdcu_sync_sram_to_mirror(info->rdcu_new_model_adr_used, (s+3) & ~3U,
                                      rdcu_get_data_mtu()))
                 return -1;
         /* wait for it */
         rdcu_syncing();
         return rdcu_read_sram(updated_model, info->rdcu_new_model_adr_used, s);
 }
References IMA_SAM2BYT, rdcu_get_data_mtu(), cmp_info::rdcu_new_model_adr_used, rdcu_read_sram(), rdcu_sync_sram_to_mirror(), rdcu_syncing(), and cmp_info::samples_used.
Referenced by rdcu_compress_data_parallel().