cmp_tool: size_of_a_sample
size_of_a_sample()
size_t size_of_a_sample (enum cmp_data_type data_type)
calculate the size of a sample for the different compression data type
Parameters
data_type compression data_type
Returns
the size of a data sample in bytes for the selected compression data type; zero on unknown data type
Definition at line 38 of file cmp_data_types.c.
 {
         size_t sample_size = 0;
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 sample_size = sizeof(uint16_t);
                 break;
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_F_CAM_OFFSET:
                 sample_size = sizeof(struct offset);
                 break;
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_F_CAM_BACKGROUND:
                 sample_size = sizeof(struct background);
                 break;
         case DATA_TYPE_SMEARING:
                 sample_size = sizeof(struct smearing);
                 break;
         case DATA_TYPE_S_FX:
                 sample_size = sizeof(struct s_fx);
                 break;
         case DATA_TYPE_S_FX_EFX:
                 sample_size = sizeof(struct s_fx_efx);
                 break;
         case DATA_TYPE_S_FX_NCOB:
                 sample_size = sizeof(struct s_fx_ncob);
                 break;
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                 sample_size = sizeof(struct s_fx_efx_ncob_ecob);
                 break;
         case DATA_TYPE_L_FX:
                 sample_size = sizeof(struct l_fx);
                 break;
         case DATA_TYPE_L_FX_EFX:
                 sample_size = sizeof(struct l_fx_efx);
                 break;
         case DATA_TYPE_L_FX_NCOB:
                 sample_size = sizeof(struct l_fx_ncob);
                 break;
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                 sample_size = sizeof(struct l_fx_efx_ncob_ecob);
                 break;
         case DATA_TYPE_F_FX:
                 sample_size = sizeof(struct f_fx);
                 break;
         case DATA_TYPE_F_FX_EFX:
                 sample_size = sizeof(struct f_fx_efx);
                 break;
         case DATA_TYPE_F_FX_NCOB:
                 sample_size = sizeof(struct f_fx_ncob);
                 break;
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 sample_size = sizeof(struct f_fx_efx_ncob_ecob);
                 break;
         case DATA_TYPE_UNKNOWN:
         default:
                 debug_print("Error: Compression data type is not supported.\n");
                 break;
         }
         return sample_size;
 }
References data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, and debug_print.
Referenced by cmp_cal_size_of_data(), cmp_input_size_to_samples(), and test_size_of_a_sample().