cmp_tool: cmp_ima_max_spill
cmp_ima_max_spill()
uint32_t cmp_ima_max_spill (unsigned int golomb_par)
get the maximum valid spill threshold value for a imagette compression in diff or model mode
Parameters
golomb_par Golomb parameter
Returns
the highest still valid spill threshold value for a diff of model mode compression; 0 if golomb_par is invalid
Definition at line 321 of file cmp_support.c.
 {
         /* the RDCU can only generate 16 bit long code words -> lower max spill needed */
         const uint32_t LUT_MAX_RDCU[MAX_IMA_GOLOMB_PAR+1] = { 0, 8, 22, 35, 48,
                 60, 72, 84, 96, 107, 118, 129, 140, 151, 162, 173, 184, 194,
                 204, 214, 224, 234, 244, 254, 264, 274, 284, 294, 304, 314, 324,
                 334, 344, 353, 362, 371, 380, 389, 398, 407, 416, 425, 434, 443,
                 452, 461, 470, 479, 488, 497, 506, 515, 524, 533, 542, 551, 560,
                 569, 578, 587, 596, 605, 614, 623 };
         if (golomb_par >= ARRAY_SIZE(LUT_MAX_RDCU))
                 return 0;
         return LUT_MAX_RDCU[golomb_par];
 }
References ARRAY_SIZE, and MAX_IMA_GOLOMB_PAR.
Referenced by cmp_pars_are_invalid(), generate_random_cmp_par(), test_cmp_cfg_icu_imagette(), and test_rdcu_cfg_imagette().