cmp_tool: cmp_cfg_imagette_is_invalid
cmp_cfg_imagette_is_invalid()
int cmp_cfg_imagette_is_invalid (const struct cmp_cfg * cfg, enum check_opt opt)
check if the imagette specific compression parameters are invalid
Parameters
cfg pointer to a compressor configuration
opt check options: RDCU_CHECK for a imagette RDCU compression check ICU_CHECK for a imagette ICU compression check
Returns
0 if the imagette specific parameters are valid, otherwise invalid
Definition at line 701 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         enum cmp_mode cmp_mode;
         if (!cfg)
                 return 1;
         if (!cmp_imagette_data_type_is_used(cfg->data_type)) {
                 debug_print("Error: The compression data type is not an imagette compression data type.\n");
                 cfg_invalid++;
         }
         /* The RDCU needs valid compression parameters also in RAW_MODE */
         if (opt == RDCU_CHECK && cfg->cmp_mode == CMP_MODE_RAW)
                 cmp_mode = CMP_MODE_MODEL_ZERO;
         else
                 cmp_mode = cfg->cmp_mode;
         cfg_invalid += cmp_pars_are_invalid(cfg->golomb_par, cfg->spill, cmp_mode,
                                             cfg->data_type, "imagette");
         /* for the RDCU the adaptive parameters have to be always valid */
         if (opt == RDCU_CHECK || cmp_ap_imagette_data_type_is_used(cfg->data_type)) {
                 cfg_invalid += cmp_pars_are_invalid(cfg->ap1_golomb_par, cfg->ap1_spill,
                                 cmp_mode, cfg->data_type, "adaptive 1 imagette");
                 cfg_invalid += cmp_pars_are_invalid(cfg->ap2_golomb_par, cfg->ap2_spill,
                                 cmp_mode, cfg->data_type, "adaptive 2 imagette");
         }
         return cfg_invalid;
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_ap_imagette_data_type_is_used(), cmp_imagette_data_type_is_used(), cmp_cfg::cmp_mode, CMP_MODE_MODEL_ZERO, CMP_MODE_RAW, cmp_pars_are_invalid(), cmp_cfg::data_type, debug_print, cmp_cfg::golomb_par, RDCU_CHECK, and cmp_cfg::spill.
Referenced by cmp_cfg_icu_imagette(), cmp_cfg_icu_is_invalid(), decompressed_data_internal(), rdcu_cfg_imagette(), rdcu_cmp_cfg_is_invalid(), and test_support_function_call_NULL().