cmp_tool: cmp_ent_parse
cmp_ent_parse()
void cmp_ent_parse (struct cmp_entity * ent)
parse the compressed entity header
Parameters
ent pointer to a compression entity
Definition at line 2455 of file cmp_entity.c.
 {
         cmp_ent_parse_generic_header(ent);
         cmp_ent_parese_specific_header(ent);
 }
References cmp_ent_parese_specific_header(), and cmp_ent_parse_generic_header().
Referenced by test_cmp_ent_parse().