cmp_tool: rdcu_start_compression
rdcu_start_compression()
int rdcu_start_compression (void)
start the RDCU data compressor
Returns
0 on success, error otherwise
Definition at line 202 of file cmp_rdcu.c.
 {
         if (interrupt_signal_enabled) {
                 /* enable the interrupt signal to the ICU */
                 rdcu_set_rdcu_interrupt();
         } else {
                 /* disable the interrupt signal to the ICU */
                 rdcu_clear_rdcu_interrupt();
         }
         /* start the compression */
         rdcu_set_data_compr_start();
         if (rdcu_sync_compr_ctrl())
                 return -1;
         rdcu_syncing();
         /* clear local bit immediately, this is a write-only register.
          * we would not want to restart compression by accidentally calling
          * rdcu_sync_compr_ctrl() again
          */
         rdcu_clear_data_compr_start();
         return 0;
 }
References interrupt_signal_enabled, rdcu_clear_data_compr_start(), rdcu_clear_rdcu_interrupt(), rdcu_set_data_compr_start(), rdcu_set_rdcu_interrupt(), rdcu_sync_compr_ctrl(), and rdcu_syncing().
Referenced by rdcu_compress_data(), and rdcu_compress_data_parallel().