cmp_tool: cmp_ent_write_rdcu_cmp_pars
cmp_ent_write_rdcu_cmp_pars()
int cmp_ent_write_rdcu_cmp_pars (struct cmp_entity * ent, const struct cmp_info * info, const struct cmp_cfg * cfg)
write the parameters from the RDCU decompression information structure in the compression entity header
Note
no compressed data are put into the entity and no change of the entity size
Parameters
ent pointer to a compression entity
info pointer to a decompression information structure
cfg pointer to a compression configuration structure for adaptive compression parameters (can be NULL if non adaptive data_type is used)
Returns
0 on success, negative on error
Definition at line 1958 of file cmp_entity.c.
 {
         uint32_t ent_cmp_data_size;
         enum cmp_data_type data_type;
         if (!ent)
                 return -1;
         if (!info)
                 return -1;
         if (info->cmp_err) {
                 debug_print("Error: The decompression information contains an compression error.\n");
                 return -1;
         }
         data_type = cmp_ent_get_data_type(ent);
         if (!rdcu_supported_data_type_is_used(data_type)) {
                 debug_print("Error: The compression data type is not one of the types supported by the RDCU.\n");
                 return -1;
         }
         if (cmp_ent_get_data_type_raw_bit(ent) != raw_mode_is_used(info->cmp_mode_used)) {
                 debug_print("Error: The entity's raw data bit does not match up with the compression mode.\n");
                 return -1;
         }
         /* check if the entity can hold the compressed data */
         ent_cmp_data_size = cmp_ent_get_cmp_data_size(ent);
         if (ent_cmp_data_size < cmp_bit_to_byte(info->cmp_size)) {
                 debug_print("Error: The entity size is to small to hold the compressed data.\n");
                 return -2;
         }
         /* set compression parameter fields in the generic entity header */
         if (cmp_ent_set_original_size(ent, cmp_cal_size_of_data(info->samples_used, DATA_TYPE_IMAGETTE)))
                 return -1;
         if (cmp_ent_set_cmp_mode(ent, info->cmp_mode_used))
                 return -1;
         cmp_ent_set_model_value(ent, info->model_value_used);
         /* The RDCU data compressor does not have the maximum used bit feature,
          * so the field is set to 0. */
         cmp_ent_set_max_used_bits_version(ent, 0);
         cmp_ent_set_lossy_cmp_par(ent, info->round_used);
         if (raw_mode_is_used(info->cmp_mode_used))
                 /* no specific header is used for raw data we are done */
                 return 0;
         if (cmp_ent_set_ima_spill(ent, info->spill_used))
                 return -1;
         if (cmp_ent_set_ima_golomb_par(ent, info->golomb_par_used))
                 return -1;
         /* use the adaptive imagette parameter from the compression configuration
          * if an adaptive imagette compression data type is ent in the entity
          */
         if (cmp_ap_imagette_data_type_is_used(data_type)) {
                 if (!cfg) {
                         debug_print("Error: Need the compression configuration to get the adaptive parameters.\n");
                         return -1;
                 }
                 if (cmp_ent_set_ima_ap1_spill(ent, cfg->ap1_spill))
                         return -1;
                 if (cmp_ent_set_ima_ap1_golomb_par(ent, cfg->ap1_golomb_par))
                         return -1;
                 if (cmp_ent_set_ima_ap2_spill(ent, cfg->ap2_spill))
                         return -1;
                 if (cmp_ent_set_ima_ap2_golomb_par(ent, cfg->ap2_golomb_par))
                         return -1;
         }
         return 0;
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_ap_imagette_data_type_is_used(), cmp_bit_to_byte(), cmp_cal_size_of_data(), cmp_ent_get_cmp_data_size(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_set_cmp_mode(), cmp_ent_set_ima_ap1_golomb_par(), cmp_ent_set_ima_ap1_spill(), cmp_ent_set_ima_ap2_golomb_par(), cmp_ent_set_ima_ap2_spill(), cmp_ent_set_ima_golomb_par(), cmp_ent_set_ima_spill(), cmp_ent_set_lossy_cmp_par(), cmp_ent_set_max_used_bits_version(), cmp_ent_set_model_value(), cmp_ent_set_original_size(), cmp_info::cmp_err, cmp_info::cmp_mode_used, cmp_info::cmp_size, data_type, DATA_TYPE_IMAGETTE, debug_print, cmp_info::golomb_par_used, cmp_info::model_value_used, raw_mode_is_used(), rdcu_supported_data_type_is_used(), cmp_info::round_used, cmp_info::samples_used, and cmp_info::spill_used.
Referenced by test_cmp_ent_write_rdcu_cmp_pars().