cmp_tool: icu_compress_data
icu_compress_data()
int icu_compress_data (const struct cmp_cfg * cfg)
compress data on the ICU in software
Parameters
cfg pointer to a compression configuration (created with the cmp_cfg_icu_create() function, setup with the cmp_cfg_xxx() functions)
Note
the validity of the cfg structure is checked before the compression is started
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF (-2) if the compressed data buffer is too small to hold the whole compressed data, CMP_ERROR_HIGH_VALUE (-3) if a data or model value is bigger than the max_used_bits parameter allows (set with the cmp_set_max_used_bits() function)
Definition at line 2246 of file cmp_icu.c.
 {
         int bitsize = 0;
         if (!cfg)
                 return -1;
         if (cfg->samples == 0) /* nothing to compress we are done*/
                 return 0;
         if (raw_mode_is_used(cfg->cmp_mode))
                 if (cfg->samples > cfg->buffer_length)
                         return CMP_ERROR_SMALL_BUF;
         if (cmp_cfg_icu_is_invalid(cfg))
                 return -1;
         if (raw_mode_is_used(cfg->cmp_mode)) {
                 uint32_t raw_size = cmp_cal_size_of_data(cfg->samples, cfg->data_type);
                 if (cfg->icu_output_buf)
                         memcpy(cfg->icu_output_buf, cfg->input_buf, raw_size);
                 bitsize = (int)raw_size * CHAR_BIT; /* convert to bits */
         } else {
                 if (cfg->icu_output_buf && cfg->samples/3 > cfg->buffer_length)
                         debug_print("Warning: The size of the compressed_data buffer is 3 times smaller than the data_to_compress. This is probably unintended.\n");
                 switch (cfg->data_type) {
                 case DATA_TYPE_IMAGETTE:
                 case DATA_TYPE_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_SAT_IMAGETTE:
                 case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_F_CAM_IMAGETTE:
                 case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                         bitsize = compress_imagette(cfg);
                         break;
                 case DATA_TYPE_S_FX:
                         bitsize = compress_s_fx(cfg);
                         break;
                 case DATA_TYPE_S_FX_EFX:
                         bitsize = compress_s_fx_efx(cfg);
                         break;
                 case DATA_TYPE_S_FX_NCOB:
                         bitsize = compress_s_fx_ncob(cfg);
                         break;
                 case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                         bitsize = compress_s_fx_efx_ncob_ecob(cfg);
                         break;
                 case DATA_TYPE_F_FX:
                         bitsize = compress_f_fx(cfg);
                         break;
                 case DATA_TYPE_F_FX_EFX:
                         bitsize = compress_f_fx_efx(cfg);
                         break;
                 case DATA_TYPE_F_FX_NCOB:
                         bitsize = compress_f_fx_ncob(cfg);
                         break;
                 case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                         bitsize = compress_f_fx_efx_ncob_ecob(cfg);
                         break;
                 case DATA_TYPE_L_FX:
                         bitsize = compress_l_fx(cfg);
                         break;
                 case DATA_TYPE_L_FX_EFX:
                         bitsize = compress_l_fx_efx(cfg);
                         break;
                 case DATA_TYPE_L_FX_NCOB:
                         bitsize = compress_l_fx_ncob(cfg);
                         break;
                 case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                         bitsize = compress_l_fx_efx_ncob_ecob(cfg);
                         break;
                 case DATA_TYPE_OFFSET:
                 case DATA_TYPE_F_CAM_OFFSET:
                         bitsize = compress_offset(cfg);
                         break;
                 case DATA_TYPE_BACKGROUND:
                 case DATA_TYPE_F_CAM_BACKGROUND:
                         bitsize = compress_background(cfg);
                         break;
                 case DATA_TYPE_SMEARING:
                         bitsize = compress_smearing(cfg);
                         break;
                 /* LCOV_EXCL_START */
                 case DATA_TYPE_UNKNOWN:
                 default:
                         debug_print("Error: Data type not supported.\n");
                         bitsize = -1;
                 }
                 /* LCOV_EXCL_STOP */
         }
         bitsize = pad_bitstream(cfg, bitsize);
         bitsize = cmp_data_to_big_endian(cfg, bitsize);
         return bitsize;
 }
References cmp_cfg::buffer_length, cmp_cal_size_of_data(), cmp_cfg_icu_is_invalid(), cmp_data_to_big_endian(), CMP_ERROR_SMALL_BUF, cmp_cfg::cmp_mode, compress_background(), compress_f_fx(), compress_f_fx_efx(), compress_f_fx_efx_ncob_ecob(), compress_f_fx_ncob(), compress_imagette(), compress_l_fx(), compress_l_fx_efx(), compress_l_fx_efx_ncob_ecob(), compress_l_fx_ncob(), compress_offset(), compress_s_fx(), compress_s_fx_efx(), compress_s_fx_efx_ncob_ecob(), compress_s_fx_ncob(), compress_smearing(), cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, pad_bitstream(), raw_mode_is_used(), and cmp_cfg::samples.
Referenced by compression_decompression(), icu_compress_data_entity(), test_cmp_decmp_n_imagette_raw(), test_compress_background_error_cases(), test_compress_f_fx_efx_error_cases(), test_compress_f_fx_efx_ncob_ecob(), test_compress_f_fx_error_cases(), test_compress_f_fx_ncob_error_cases(), test_compress_imagette_diff(), test_compress_imagette_error_cases(), test_compress_imagette_model(), test_compress_imagette_raw(), test_compress_imagette_stuff(), test_compress_l_fx_efx_error_cases(), test_compress_l_fx_efx_ncob_ecob_error_cases(), test_compress_l_fx_error_cases(), test_compress_l_fx_ncob_error_cases(), test_compress_offset_error_cases(), test_compress_s_fx_efx_error_cases(), test_compress_s_fx_efx_ncob_ecob_error_cases(), test_compress_s_fx_error_cases(), test_compress_s_fx_model_multi(), test_compress_s_fx_ncob_error_cases(), test_compress_s_fx_raw(), test_compress_s_fx_staff(), test_compress_smearing_error_cases(), test_icu_compress_data_error_cases(), and test_random_compression_decompression2().