cmp_tool: rdcu_read_cmp_bitstream
rdcu_read_cmp_bitstream()
int rdcu_read_cmp_bitstream (const struct cmp_info * info, void * compressed_data)
read the compressed bitstream from the RDCU SRAM
Parameters
info compression information contains the metadata of a compression
compressed_data the buffer to store the bitstream (if NULL, the required size is returned)
Returns
the number of bytes read, < 0 on error
Definition at line 418 of file cmp_rdcu.c.
 {
         uint32_t s;
         if (info == NULL)
                 return -1;
         /* calculate the need bytes for the bitstream */
         s = cmp_bit_to_4byte(info->cmp_size);
         if (compressed_data == NULL)
                 return (int)s;
         if (rdcu_sync_sram_to_mirror(info->rdcu_cmp_adr_used, s,
                                      rdcu_get_data_mtu()))
                 return -1;
         /* wait for it */
         rdcu_syncing();
         return rdcu_read_sram(compressed_data, info->rdcu_cmp_adr_used, s);
 }
References cmp_bit_to_4byte(), cmp_info::cmp_size, cmp_info::rdcu_cmp_adr_used, rdcu_get_data_mtu(), rdcu_read_sram(), rdcu_sync_sram_to_mirror(), and rdcu_syncing().