cmp_tool: cmp_max_used_bits_list_add
cmp_max_used_bits_list_add()
int cmp_max_used_bits_list_add (struct cmp_max_used_bits const * item)
add a max_used_bits item to the list
Parameters
item pointer to the cmp_max_used_bits struct to add to the list
Note
if there is an item in the list with the same version number, it will be overwritten
Returns
0 on success; 1 if an existing entry is overwritten; -1 on error
Definition at line 76 of file cmp_max_used_bits_list.c.
 {
         struct list_item *item_ptr = NULL;
         if (!item)
                 return -1;
         if (item->version < CMP_MAX_USED_BITS_RESERVED_VERSIONS)
                 return -1;
         /* check for an existing entry */
         list_for_each_entry(item_ptr, &max_used_bits_list, list) {
                 if (item_ptr->data.version == item->version) {
                         item_ptr->data = *item; /* replace existing list entry */
                         return 1;
                 }
         }
         item_ptr = (struct list_item *)malloc(sizeof(struct list_item));
         if (!item_ptr)
                 return -1;
         item_ptr->data = *item;
         list_add(&item_ptr->list, &max_used_bits_list);
         return 0;
 }
References CMP_MAX_USED_BITS_RESERVED_VERSIONS, list_item::data, list_item::list, list_add(), list_for_each_entry, malloc(), and cmp_max_used_bits::version.
Referenced by test_cmp_ent_write_cmp_pars(), and test_cmp_max_used_bits_list().