cmp_tool: cmp_ent_get_cmp_data_size
cmp_ent_get_cmp_data_size()
uint32_t cmp_ent_get_cmp_data_size (const struct cmp_entity * ent)
get the size of the compressed data based on the set data product type and compressed entity size in the compression entity
Parameters
ent pointer to a compression entity
Returns
the size of the compressed data in bytes on success, 0 on error
Definition at line 1768 of file cmp_entity.c.
 {
         uint32_t cmp_ent_size, header_size;
         header_size = cmp_ent_get_hdr_size(ent);
         cmp_ent_size = cmp_ent_get_size(ent);
         if (header_size > cmp_ent_size)
                 return 0;
         return cmp_ent_size - header_size;
 }
References cmp_ent_get_hdr_size(), cmp_ent_get_size(), and cmp_ent_size.
Referenced by cmp_ent_get_cmp_data(), cmp_ent_print_data(), cmp_ent_read_header(), cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_get_cmp_data_size(), test_cmp_ent_write_cmp_pars(), and test_cmp_ent_write_rdcu_cmp_pars().