cmp_tool: cmp_ent_get_non_ima_cmp_par4
cmp_ent_get_non_ima_cmp_par4()
uint16_t cmp_ent_get_non_ima_cmp_par4 (const struct cmp_entity * ent)
get the used compression parameter 4 from the non-imagette specific compression entity header
Parameters
ent pointer to a compression entity
Returns
the used compression parameter 4 on success, 0 on error
Definition at line 1536 of file cmp_entity.c.
 {
         if (!ent)
                 return 0;
         return be16_to_cpu(ent->non_ima.cmp_par_4_used);
 }
References be16_to_cpu, non_imagette_header::cmp_par_4_used, and cmp_entity::non_ima.
Referenced by cmp_ent_read_header(), test_cmp_ent_write_cmp_pars(), and test_ent_non_ima_cmp_par4().