cmp_tool: rdcu_cfg_imagette_default
rdcu_cfg_imagette_default()
int rdcu_cfg_imagette_default (struct cmp_cfg * cfg)
set up the default configuration parameters for an RDCU imagette compression based on the set compression mode
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 333 of file cmp_rdcu_cfg.c.
 {
         if (!cfg) {
                 debug_print("Error: pointer to the compression configuration structure is NULL.\n");
                 return -1;
         }
         if (model_mode_is_used(cfg->cmp_mode)) {
                 return rdcu_cfg_imagette(cfg, CMP_DEF_IMA_MODEL_GOLOMB_PAR,
                                          CMP_DEF_IMA_MODEL_SPILL_PAR,
                                          CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR,
                                          CMP_DEF_IMA_MODEL_AP1_SPILL_PAR,
                                          CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR,
                                          CMP_DEF_IMA_MODEL_AP2_SPILL_PAR);
         } else {
                 return rdcu_cfg_imagette(cfg, CMP_DEF_IMA_DIFF_GOLOMB_PAR,
                                          CMP_DEF_IMA_DIFF_SPILL_PAR,
                                          CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR,
                                          CMP_DEF_IMA_DIFF_AP1_SPILL_PAR,
                                          CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR,
                                          CMP_DEF_IMA_DIFF_AP2_SPILL_PAR);
         }
 }
References CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR, CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR, CMP_DEF_IMA_DIFF_GOLOMB_PAR, CMP_DEF_IMA_DIFF_SPILL_PAR, CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP1_SPILL_PAR, CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP2_SPILL_PAR, CMP_DEF_IMA_MODEL_GOLOMB_PAR, CMP_DEF_IMA_MODEL_SPILL_PAR, cmp_cfg::cmp_mode, debug_print, model_mode_is_used(), and rdcu_cfg_imagette().
Referenced by test_rdcu_cfg_imagette_default().