cmp_tool: cmp_cfg_aux
cmp_cfg_aux()
int cmp_cfg_aux (struct cmp_cfg * cfg, uint32_t cmp_par_mean, uint32_t spillover_mean, uint32_t cmp_par_variance, uint32_t spillover_variance, uint32_t cmp_par_pixels_error, uint32_t spillover_pixels_error)
set up the configuration parameters for an auxiliary science data compression
Note
auxiliary compression data types are: DATA_TYPE_OFFSET, DATA_TYPE_BACKGROUND, DATA_TYPE_SMEARING, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_CAM_BACKGROUND
not all parameters are needed for the every auxiliary compression data type
Parameters
cfg pointer to a compression configuration (created with the cmp_cfg_icu_create() function)
cmp_par_mean mean compression parameter
spillover_mean mean spillover threshold parameter
cmp_par_variance variance compression parameter
spillover_variance variance spillover threshold parameter
cmp_par_pixels_error outlier pixels number compression parameter
spillover_pixels_error outlier pixels number spillover threshold parameter
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 300 of file cmp_icu.c.
 {
         if (!cfg)
                 return -1;
         cfg->cmp_par_mean = cmp_par_mean;
         cfg->cmp_par_variance = cmp_par_variance;
         cfg->cmp_par_pixels_error = cmp_par_pixels_error;
         cfg->spill_mean = spillover_mean;
         cfg->spill_variance = spillover_variance;
         cfg->spill_pixels_error = spillover_pixels_error;
         if (cmp_cfg_aux_is_invalid(cfg))
                 return -1;
         return 0;
 }
References cmp_cfg_aux_is_invalid(), cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, and cmp_cfg::spill_variance.
Referenced by test_cmp_cfg_aux(), test_compress_background_error_cases(), test_compress_offset_error_cases(), and test_compress_smearing_error_cases().