cmp_tool: cmp_input_big_to_cpu_endianness
cmp_input_big_to_cpu_endianness()
int cmp_input_big_to_cpu_endianness (void * data, uint32_t data_size_byte, enum cmp_data_type data_type)
swap the endianness of uncompressed data form big endian to the cpu endianness (or the other way around) in place
Parameters
data pointer to a data sample
data_size_byte size of the data in bytes
data_type compression data type
Returns
0 on success; non-zero on failure
Definition at line 383 of file cmp_data_types.c.
 {
         int32_t samples = cmp_input_size_to_samples(data_size_byte, data_type);
         if (!data) /* nothing to do */
                 return 0;
         if (samples < 0) {
                 debug_print("Error: Can not convert data size in samples.\n");
                 return -1;
         }
         /* we do not convert the endianness of the multi entry header */
         if (!rdcu_supported_data_type_is_used(data_type))
                 data = (uint8_t *)data + MULTI_ENTRY_HDR_SIZE;
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 be_to_cpus_16(data, samples);
                 break;
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_F_CAM_OFFSET:
                 be_to_cpus_offset(data, samples);
                 break;
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_F_CAM_BACKGROUND:
                 be_to_cpus_background(data, samples);
                 break;
         case DATA_TYPE_SMEARING:
                 be_to_cpus_smearing(data, samples);
                 break;
         case DATA_TYPE_S_FX:
                 be_to_cpus_s_fx(data, samples);
                 break;
         case DATA_TYPE_S_FX_EFX:
                 be_to_cpus_s_fx_efx(data, samples);
                 break;
         case DATA_TYPE_S_FX_NCOB:
                 be_to_cpus_s_fx_ncob(data, samples);
                 break;
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                 be_to_cpus_s_fx_efx_ncob_ecob(data, samples);
                 break;
         case DATA_TYPE_L_FX:
                 be_to_cpus_l_fx(data, samples);
                 break;
         case DATA_TYPE_L_FX_EFX:
                 be_to_cpus_l_fx_efx(data, samples);
                 break;
         case DATA_TYPE_L_FX_NCOB:
                 be_to_cpus_l_fx_ncob(data, samples);
                 break;
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                 be_to_cpus_l_fx_efx_ncob_ecob(data, samples);
                 break;
         case DATA_TYPE_F_FX:
                 be_to_cpus_f_fx(data, samples);
                 break;
         case DATA_TYPE_F_FX_EFX:
                 be_to_cpus_f_fx_efx(data, samples);
                 break;
         case DATA_TYPE_F_FX_NCOB:
                 be_to_cpus_f_fx_ncob(data, samples);
                 break;
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 be_to_cpus_f_fx_efx_ncob_ecob(data, samples);
                 break;
         /* LCOV_EXCL_START */
         case DATA_TYPE_UNKNOWN:
         default:
                 debug_print("Error: Can not swap endianness for this compression data type.\n");
                 return -1;
         /* LCOV_EXCL_STOP */
         }
         return 0;
 }
References be_to_cpus_16(), be_to_cpus_background(), be_to_cpus_f_fx(), be_to_cpus_f_fx_efx(), be_to_cpus_f_fx_efx_ncob_ecob(), be_to_cpus_f_fx_ncob(), be_to_cpus_l_fx(), be_to_cpus_l_fx_efx(), be_to_cpus_l_fx_efx_ncob_ecob(), be_to_cpus_l_fx_ncob(), be_to_cpus_offset(), be_to_cpus_s_fx(), be_to_cpus_s_fx_efx(), be_to_cpus_s_fx_efx_ncob_ecob(), be_to_cpus_s_fx_ncob(), be_to_cpus_smearing(), cmp_input_size_to_samples(), data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, MULTI_ENTRY_HDR_SIZE, and rdcu_supported_data_type_is_used().
Referenced by check_endianness(), cmp_data_to_big_endian(), decompressed_data_internal(), test_cmp_input_big_to_cpu_endianness(), and test_cmp_input_big_to_cpu_endianness_error_cases().