cmp_tool: rdcu_cfg_buffers
rdcu_cfg_buffers()
int rdcu_cfg_buffers (struct cmp_cfg * cfg, uint16_t * data_to_compress, uint32_t data_samples, uint16_t * model_of_data, uint32_t rdcu_data_adr, uint32_t rdcu_model_adr, uint32_t rdcu_new_model_adr, uint32_t rdcu_buffer_adr, uint32_t rdcu_buffer_lenght)
setup of the different data buffers for an RDCU compression
Parameters
cfg pointer to a compression configuration (created with the rdcu_cfg_create() function)
data_to_compress pointer to the data to be compressed (if NULL no data transfer to the RDCU)
data_samples length of the data to be compressed (plus the collection header) measured in 16-bit data samples
model_of_data pointer to the model data buffer (only needed for model compression mode, if NULL no model data is transferred to the RDCU)
rdcu_data_adr RDCU SRAM data to compress start address
rdcu_model_adr RDCU SRAM model start address (only needed for model compression mode)
rdcu_new_model_adr RDCU SRAM new/updated model start address (can be the same as rdcu_model_adr for in-place model update)
rdcu_buffer_adr RDCU SRAM compressed data start address
rdcu_buffer_lenght length of the RDCU compressed data SRAM buffer measured in 16-bit units (same as data_samples)
Returns
0 if parameters are valid, non-zero if parameters are invalid
Definition at line 266 of file cmp_rdcu_cfg.c.
 {
         if (!cfg) {
                 debug_print("Error: pointer to the compression configuration structure is NULL.\n");
                 return -1;
         }
         cfg->input_buf = data_to_compress;
         cfg->samples = data_samples;
         cfg->model_buf = model_of_data;
         cfg->rdcu_data_adr = rdcu_data_adr;
         cfg->rdcu_model_adr = rdcu_model_adr;
         cfg->rdcu_new_model_adr = rdcu_new_model_adr;
         cfg->rdcu_buffer_adr = rdcu_buffer_adr;
         cfg->buffer_length = rdcu_buffer_lenght;
         return rdcu_cfg_buffers_is_invalid(cfg);
 }
References cmp_cfg::buffer_length, debug_print, cmp_cfg::input_buf, cmp_cfg::model_buf, cmp_cfg::rdcu_buffer_adr, rdcu_cfg_buffers_is_invalid(), cmp_cfg::rdcu_data_adr, cmp_cfg::rdcu_model_adr, cmp_cfg::rdcu_new_model_adr, and cmp_cfg::samples.
Referenced by test_rdcu_cfg_buffers_model(), test_rdcu_cfg_buffers_raw_diff(), and test_rdcu_cmp_cfg_is_invalid().