cmp_tool: compress_l_fx
compress_l_fx()
static int compress_l_fx (const struct cmp_cfg * cfg) static
compress L_FX data
Parameters
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 1516 of file cmp_icu.c.
 {
         int stream_len = 0;
         size_t i;
         struct l_fx *data_buf = cfg->input_buf;
         struct l_fx *model_buf = cfg->model_buf;
         struct l_fx *up_model_buf = NULL;
         struct l_fx *next_model_p;
         struct l_fx model;
         struct encoder_setupt setup_exp_flag, setup_fx, setup_fx_var;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         stream_len = compress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                               (void **)&up_model_buf, cfg->icu_output_buf);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         configure_encoder_setup(&setup_exp_flag, cfg->cmp_par_exp_flags, cfg->spill_exp_flags,
                                 cfg->round, cfg->max_used_bits->l_exp_flags, cfg);
         configure_encoder_setup(&setup_fx, cfg->cmp_par_fx, cfg->spill_fx,
                                 cfg->round, cfg->max_used_bits->l_fx, cfg);
         configure_encoder_setup(&setup_fx_var, cfg->cmp_par_fx_cob_variance, cfg->spill_fx_cob_variance,
                                 cfg->round, cfg->max_used_bits->l_fx_variance, cfg);
         for (i = 0;; i++) {
                 stream_len = encode_value(data_buf[i].exp_flags, model.exp_flags,
                                           stream_len, &setup_exp_flag);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].fx, model.fx, stream_len,
                                           &setup_fx);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].fx_variance, model.fx_variance,
                                           stream_len, &setup_fx_var);
                 if (stream_len <= 0)
                         return stream_len;
                 if (up_model_buf) {
                         up_model_buf[i].exp_flags = cmp_up_model32(data_buf[i].exp_flags, model.exp_flags,
                                 cfg->model_value, setup_exp_flag.lossy_par);
                         up_model_buf[i].fx = cmp_up_model(data_buf[i].fx, model.fx,
                                 cfg->model_value, setup_fx.lossy_par);
                         up_model_buf[i].fx_variance = cmp_up_model(data_buf[i].fx_variance, model.fx_variance,
                                 cfg->model_value, setup_fx_var.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return stream_len;
 }
References cmp_cfg::cmp_mode, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_up_model, cmp_up_model32(), compress_multi_entry_hdr(), configure_encoder_setup(), encode_value(), exp_flags, l_fx::exp_flags, fx, l_fx::fx, fx_variance, l_fx::fx_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_max_used_bits::l_exp_flags, cmp_max_used_bits::l_fx, cmp_max_used_bits::l_fx_variance, encoder_setupt::lossy_par, cmp_cfg::max_used_bits, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, and cmp_cfg::spill_fx_cob_variance.
Referenced by icu_compress_data().