cmp_tool: cmp_ent_set_ima_ap1_golomb_par
cmp_ent_set_ima_ap1_golomb_par()
int cmp_ent_set_ima_ap1_golomb_par (struct cmp_entity * ent, uint32_t ap1_golomb_par_used)
set adaptive 1 Golomb parameter in the adaptive imagette specific compression entity header
Parameters
ent pointer to a compression entity
ap1_golomb_par_used used adaptive 1 Golomb parameter for semi-adaptive compression feature
Returns
0 on success, otherwise error
Definition at line 578 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (ap1_golomb_par_used > UINT8_MAX)
                 return -1;
         ent->ima.ap1_golomb_par_used = (uint8_t)ap1_golomb_par_used;
         return 0;
 }
References ap1_golomb_par_used, imagette_header::ap1_golomb_par_used, and cmp_entity::ima.
Referenced by cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), and test_ent_ima_ap1_golomb_par().