cmp_tool: rdcu_read_cmp_status
rdcu_read_cmp_status()
int rdcu_read_cmp_status (struct cmp_status * status)
read out the status register of the RDCU compressor
Parameters
status compressor status contains the stats of the HW compressor
Note
access to the status registers is also possible during compression
Returns
0 on success, error otherwise
Definition at line 315 of file cmp_rdcu.c.
 {
         if (rdcu_sync_compr_status())
                 return -1;
         rdcu_syncing();
         if (status) {
                 status->data_valid = (uint8_t)rdcu_get_compr_status_valid();
                 status->cmp_ready = (uint8_t)rdcu_get_data_compr_ready();
                 status->cmp_interrupted = (uint8_t)rdcu_get_data_compr_interrupted();
                 status->cmp_active = (uint8_t)rdcu_get_data_compr_active();
                 status->rdcu_interrupt_en = (uint8_t)rdcu_get_rdcu_interrupt_enabled();
         }
         return 0;
 }
References cmp_status::cmp_active, cmp_status::cmp_interrupted, cmp_status::cmp_ready, cmp_status::data_valid, rdcu_get_compr_status_valid(), rdcu_get_data_compr_active(), rdcu_get_data_compr_interrupted(), rdcu_get_data_compr_ready(), rdcu_get_rdcu_interrupt_enabled(), cmp_status::rdcu_interrupt_en, rdcu_sync_compr_status(), and rdcu_syncing().