cmp_tool: cmp_ent_parese_imagette_header
cmp_ent_parese_imagette_header()
static void cmp_ent_parese_imagette_header (const struct cmp_entity * ent) static
parse the imagette specific compressed entity header
Parameters
ent pointer to a compression entity
Definition at line 2373 of file cmp_entity.c.
 {
         uint32_t spill_used, golomb_par_used;
         spill_used = cmp_ent_get_ima_spill(ent);
         printf("Used Spillover Threshold Parameter: %" PRIu32 "\n", spill_used);
         golomb_par_used = cmp_ent_get_ima_golomb_par(ent);
         printf("Used Golomb Parameter: %" PRIu32 "\n", golomb_par_used);
 }
References cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), golomb_par_used, and spill_used.
Referenced by cmp_ent_parese_specific_header().