cmp_tool: cmp_input_size_to_samples
cmp_input_size_to_samples()
int32_t cmp_input_size_to_samples (uint32_t size, enum cmp_data_type data_type)
calculates the number of samples for a given data size for the different compression modes
Parameters
size size of the data in bytes
data_type compression data type
Returns
the number samples for the given compression mode; negative on error
Definition at line 148 of file cmp_data_types.c.
 {
         uint32_t samples_size = (uint32_t)size_of_a_sample(data_type);
         if (!samples_size)
                 return -1;
         if (!rdcu_supported_data_type_is_used(data_type)) {
                 if (size < MULTI_ENTRY_HDR_SIZE)
                         return -1;
                 size -= MULTI_ENTRY_HDR_SIZE;
         }
         if (size % samples_size)
                 return -1;
         return (int)(size/samples_size);
 }
References data_type, MULTI_ENTRY_HDR_SIZE, rdcu_supported_data_type_is_used(), and size_of_a_sample().
Referenced by cmp_ent_read_header(), cmp_input_big_to_cpu_endianness(), and test_cmp_input_size_to_samples().