cmp_tool: compress_l_fx_efx_ncob_ecob
compress_l_fx_efx_ncob_ecob()
static int compress_l_fx_efx_ncob_ecob (const struct cmp_cfg * cfg) static
compress L_FX_EFX_NCOB_ECOB data
Parameters
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream
Definition at line 1779 of file cmp_icu.c.
 {
         int stream_len = 0;
         size_t i;
         struct l_fx_efx_ncob_ecob *data_buf = cfg->input_buf;
         struct l_fx_efx_ncob_ecob *model_buf = cfg->model_buf;
         struct l_fx_efx_ncob_ecob *up_model_buf = NULL;
         struct l_fx_efx_ncob_ecob *next_model_p;
         struct l_fx_efx_ncob_ecob model;
         struct encoder_setupt setup_exp_flag, setup_fx, setup_ncob, setup_efx,
                               setup_ecob, setup_fx_var, setup_cob_var;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         stream_len = compress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                               (void **)&up_model_buf, cfg->icu_output_buf);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         configure_encoder_setup(&setup_exp_flag, cfg->cmp_par_exp_flags, cfg->spill_exp_flags,
                                 cfg->round, cfg->max_used_bits->l_exp_flags, cfg);
         configure_encoder_setup(&setup_fx, cfg->cmp_par_fx, cfg->spill_fx,
                                 cfg->round, cfg->max_used_bits->l_fx, cfg);
         configure_encoder_setup(&setup_ncob, cfg->cmp_par_ncob, cfg->spill_ncob,
                                 cfg->round, cfg->max_used_bits->l_ncob, cfg);
         configure_encoder_setup(&setup_efx, cfg->cmp_par_efx, cfg->spill_efx,
                                 cfg->round, cfg->max_used_bits->l_efx, cfg);
         configure_encoder_setup(&setup_ecob, cfg->cmp_par_ecob, cfg->spill_ecob,
                                 cfg->round, cfg->max_used_bits->l_ecob, cfg);
         /* we use compression parameter for both variance data fields */
         configure_encoder_setup(&setup_fx_var, cfg->cmp_par_fx_cob_variance, cfg->spill_fx_cob_variance,
                                 cfg->round, cfg->max_used_bits->l_fx_variance, cfg);
         configure_encoder_setup(&setup_cob_var, cfg->cmp_par_fx_cob_variance, cfg->spill_fx_cob_variance,
                                 cfg->round, cfg->max_used_bits->l_cob_variance, cfg);
         for (i = 0;; i++) {
                 stream_len = encode_value(data_buf[i].exp_flags, model.exp_flags,
                                           stream_len, &setup_exp_flag);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].fx, model.fx, stream_len,
                                           &setup_fx);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].ncob_x, model.ncob_x,
                                           stream_len, &setup_ncob);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].ncob_y, model.ncob_y,
                                           stream_len, &setup_ncob);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].efx, model.efx,
                                           stream_len, &setup_efx);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].ecob_x, model.ecob_x,
                                           stream_len, &setup_ecob);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].ecob_y, model.ecob_y,
                                           stream_len, &setup_ecob);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].fx_variance, model.fx_variance,
                                           stream_len, &setup_fx_var);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].cob_x_variance, model.cob_x_variance,
                                           stream_len, &setup_cob_var);
                 if (stream_len <= 0)
                         return stream_len;
                 stream_len = encode_value(data_buf[i].cob_y_variance, model.cob_y_variance,
                                           stream_len, &setup_cob_var);
                 if (stream_len <= 0)
                         return stream_len;
                 if (up_model_buf) {
                         up_model_buf[i].exp_flags = cmp_up_model32(data_buf[i].exp_flags, model.exp_flags,
                                 cfg->model_value, setup_exp_flag.lossy_par);
                         up_model_buf[i].fx = cmp_up_model(data_buf[i].fx, model.fx,
                                 cfg->model_value, setup_fx.lossy_par);
                         up_model_buf[i].ncob_x = cmp_up_model(data_buf[i].ncob_x, model.ncob_x,
                                 cfg->model_value, setup_ncob.lossy_par);
                         up_model_buf[i].ncob_y = cmp_up_model(data_buf[i].ncob_y, model.ncob_y,
                                 cfg->model_value, setup_ncob.lossy_par);
                         up_model_buf[i].efx = cmp_up_model(data_buf[i].efx, model.efx,
                                 cfg->model_value, setup_efx.lossy_par);
                         up_model_buf[i].ecob_x = cmp_up_model(data_buf[i].ecob_x, model.ecob_x,
                                 cfg->model_value, setup_ecob.lossy_par);
                         up_model_buf[i].ecob_y = cmp_up_model(data_buf[i].ecob_y, model.ecob_y,
                                 cfg->model_value, setup_ecob.lossy_par);
                         up_model_buf[i].fx_variance = cmp_up_model(data_buf[i].fx_variance, model.fx_variance,
                                 cfg->model_value, setup_fx_var.lossy_par);
                         up_model_buf[i].cob_x_variance = cmp_up_model(data_buf[i].cob_x_variance, model.cob_x_variance,
                                 cfg->model_value, setup_cob_var.lossy_par);
                         up_model_buf[i].cob_y_variance = cmp_up_model(data_buf[i].cob_y_variance, model.cob_y_variance,
                                 cfg->model_value, setup_cob_var.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return stream_len;
 }
References cmp_cfg::cmp_mode, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, cmp_up_model, cmp_up_model32(), cob_x_variance, l_fx_efx_ncob_ecob::cob_x_variance, cob_y_variance, l_fx_efx_ncob_ecob::cob_y_variance, compress_multi_entry_hdr(), configure_encoder_setup(), ecob_x, l_fx_efx_ncob_ecob::ecob_x, ecob_y, l_fx_efx_ncob_ecob::ecob_y, efx, l_fx_efx_ncob_ecob::efx, encode_value(), exp_flags, l_fx_efx_ncob_ecob::exp_flags, fx, l_fx_efx_ncob_ecob::fx, fx_variance, l_fx_efx_ncob_ecob::fx_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_max_used_bits::l_cob_variance, cmp_max_used_bits::l_ecob, cmp_max_used_bits::l_efx, cmp_max_used_bits::l_exp_flags, cmp_max_used_bits::l_fx, cmp_max_used_bits::l_fx_variance, cmp_max_used_bits::l_ncob, encoder_setupt::lossy_par, cmp_cfg::max_used_bits, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, ncob_x, l_fx_efx_ncob_ecob::ncob_x, ncob_y, l_fx_efx_ncob_ecob::ncob_y, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, and cmp_cfg::spill_ncob.
Referenced by icu_compress_data().