cmp_tool: cmp_ent_set_max_used_bits_version
cmp_ent_set_max_used_bits_version()
int cmp_ent_set_max_used_bits_version (struct cmp_entity * ent, uint8_t max_used_bits_version)
set version identifier for the maximum used bits registry in the compression entity header
Parameters
ent pointer to a compression entity
max_used_bits_version the identifier for the maximum used bits registry
Returns
0 on success, otherwise error
Definition at line 458 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         ent->max_used_bits_version = max_used_bits_version;
         return 0;
 }
References max_used_bits_version, and cmp_entity::max_used_bits_version.
Referenced by cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), and test_ent_max_used_bits_version().