cmp_tool: cmp_pars_are_invalid
cmp_pars_are_invalid()
static int cmp_pars_are_invalid (uint32_t cmp_par, uint32_t spill, enum cmp_mode cmp_mode, enum cmp_data_type data_type, const char * par_name) static
check if the combination of the different compression parameters is invalid
Parameters
cmp_par compression parameter
spill spillover threshold parameter
cmp_mode compression mode
data_type compression data type
par_name string describing the use of the compression par. for debug messages (can be NULL)
Returns
0 if the parameter combination is valid, otherwise the combination is invalid
Definition at line 621 of file cmp_support.c.
 {
         int cfg_invalid = 0;
         uint32_t min_golomb_par;
         uint32_t max_golomb_par;
         uint32_t min_spill;
         uint32_t max_spill;
         /* The maximum compression parameter for imagette data are smaller to
          * fit into the imagette compression entity header */
         if (cmp_imagette_data_type_is_used(data_type)) {
                 min_golomb_par = MIN_IMA_GOLOMB_PAR;
                 max_golomb_par = MAX_IMA_GOLOMB_PAR;
                 min_spill = MIN_IMA_SPILL;
                 max_spill = cmp_ima_max_spill(cmp_par);
         } else {
                 min_golomb_par = MIN_NON_IMA_GOLOMB_PAR;
                 max_golomb_par = MAX_NON_IMA_GOLOMB_PAR;
                 min_spill = MIN_NON_IMA_SPILL;
                 max_spill = cmp_icu_max_spill(cmp_par);
         }
         switch (cmp_mode) {
         case CMP_MODE_RAW:
                 /* no checks needed */
                 break;
         case CMP_MODE_DIFF_ZERO:
         case CMP_MODE_DIFF_MULTI:
         case CMP_MODE_MODEL_ZERO:
         case CMP_MODE_MODEL_MULTI:
                 if (cmp_par < min_golomb_par || cmp_par > max_golomb_par) {
                         debug_print("Error: The selected %s compression parameter: %" PRIu32 " is not supported in the selected compression mode. The compression parameter has to be between [%" PRIu32 ", %" PRIu32 "] in this mode.\n",
                                     par_name, cmp_par, min_golomb_par, max_golomb_par);
                         cfg_invalid++;
                 }
                 if (spill < min_spill) {
                         debug_print("Error: The selected %s spillover threshold value: %" PRIu32 " is too small. The smallest possible spillover value is: %" PRIu32 ".\n",
                                     par_name, spill, min_spill);
                         cfg_invalid++;
                 }
                 if (spill > max_spill) {
                         debug_print("Error: The selected %s spillover threshold value: %" PRIu32 " is too large for the selected %s compression parameter: %" PRIu32 ". The largest possible spillover value in the selected compression mode is: %" PRIu32 ".\n",
                                     par_name, spill, par_name, cmp_par, max_spill);
                         cfg_invalid++;
                 }
                 break;
         case CMP_MODE_STUFF:
                 if (cmp_par > MAX_STUFF_CMP_PAR) {
                         debug_print("Error: The selected %s stuff mode compression parameter: %" PRIu32 " is too large. The largest possible value in the selected compression mode is: %u.\n",
                                     par_name, cmp_par, MAX_STUFF_CMP_PAR);
                         cfg_invalid++;
                 }
                 break;
         default:
                 debug_print("Error: The compression mode is not supported.\n");
                 cfg_invalid++;
                 break;
         }
 #ifdef SKIP_CMP_PAR_CHECK
         return 0;
 #endif
         return cfg_invalid;
 }
References cmp_icu_max_spill(), cmp_ima_max_spill(), cmp_imagette_data_type_is_used(), CMP_MODE_DIFF_MULTI, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_MULTI, CMP_MODE_MODEL_ZERO, CMP_MODE_RAW, CMP_MODE_STUFF, data_type, debug_print, MAX_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR, MAX_STUFF_CMP_PAR, MIN_IMA_GOLOMB_PAR, MIN_IMA_SPILL, MIN_NON_IMA_GOLOMB_PAR, and MIN_NON_IMA_SPILL.
Referenced by cmp_cfg_aux_is_invalid(), cmp_cfg_fx_cob_is_invalid(), and cmp_cfg_imagette_is_invalid().