cmp_tool: compress_imagette
compress_imagette()
static int compress_imagette (const struct cmp_cfg * cfg) static
compress imagette data
Parameters
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success; negative on error, CMP_ERROR_SMALL_BUF if the bitstream buffer is too small to put the value in the bitstream, CMP_ERROR_HIGH_VALUE if the value or the model is bigger than the max_used_bits parameter allows
Definition at line 793 of file cmp_icu.c.
 {
         int stream_len = 0;
         size_t i;
         struct encoder_setupt setup;
         uint32_t max_data_bits;
         uint16_t *data_buf = cfg->input_buf;
         uint16_t *model_buf = cfg->model_buf;
         uint16_t model = 0;
         uint16_t *next_model_p = data_buf;
         uint16_t *up_model_buf = NULL;
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
                 up_model_buf = cfg->icu_new_model_buf;
         }
         switch (cfg->data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
                 max_data_bits = cfg->max_used_bits->nc_imagette;
                 break;
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
                 max_data_bits = cfg->max_used_bits->saturated_imagette;
                 break;
         default:
         case DATA_TYPE_F_CAM_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 max_data_bits = cfg->max_used_bits->fc_imagette;
                 break;
         }
         configure_encoder_setup(&setup, cfg->golomb_par, cfg->spill, cfg->round,
                                 max_data_bits, cfg);
         for (i = 0;; i++) {
                 stream_len = encode_value(data_buf[i], model, stream_len, &setup);
                 if (stream_len <= 0)
                         break;
                 if (up_model_buf)
                         up_model_buf[i] = cmp_up_model(data_buf[i], model, cfg->model_value,
                                                        setup.lossy_par);
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return stream_len;
 }
References cmp_cfg::cmp_mode, cmp_up_model, configure_encoder_setup(), cmp_cfg::data_type, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, encode_value(), cmp_max_used_bits::fc_imagette, cmp_cfg::golomb_par, cmp_cfg::icu_new_model_buf, cmp_cfg::input_buf, encoder_setupt::lossy_par, encoder_setupt::max_data_bits, cmp_cfg::max_used_bits, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, cmp_max_used_bits::nc_imagette, cmp_cfg::round, cmp_cfg::samples, cmp_max_used_bits::saturated_imagette, and cmp_cfg::spill.
Referenced by icu_compress_data().