cmp_tool: cmp_ent_set_ima_golomb_par
cmp_ent_set_ima_golomb_par()
int cmp_ent_set_ima_golomb_par (struct cmp_entity * ent, uint32_t golomb_par_used)
set used Golomb parameter in the (adaptive) imagette specific compression entity header
Parameters
ent pointer to a compression entity
golomb_par_used used Golomb parameter used for imagette data_type
Returns
0 on success, otherwise error
Definition at line 528 of file cmp_entity.c.
 {
         if (!ent)
                 return -1;
         if (golomb_par_used > UINT8_MAX)
                 return -1;
         ent->ima.golomb_par_used = (uint8_t)golomb_par_used;
         return 0;
 }
References golomb_par_used, imagette_header::golomb_par_used, and cmp_entity::ima.
Referenced by cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), and test_ent_ima_golomb_par().