cmp_tool: select_decoder
select_decoder()
static decoder_ptr select_decoder (uint32_t golomb_par) static
select the decoder based on the used Golomb parameter
Parameters
golomb_par Golomb parameter, have to be bigger than 0
Note
if the Golomb parameter is a power of 2 we can use the faster Rice decoder
if the Golomb parameter is 1 we can use the even faster unary decoder
Returns
function pointer to the select code word decoder function
Definition at line 180 of file decmp.c.
 {
         assert(golomb_par > 0);
         if (golomb_par == 1)
                 return &unary_decoder;
         if (is_a_pow_of_2(golomb_par))
                 return &rice_decoder;
         else
                 return &golomb_decoder;
 }
References golomb_decoder(), is_a_pow_of_2(), rice_decoder(), and unary_decoder().
Referenced by configure_decoder_setup(), and test_select_decoder().