cmp_tool: rice_decoder
rice_decoder()
static uint32_t rice_decoder (struct bit_decoder * dec, uint32_t m, uint32_t log2_m) static
decode the next Rice code word in the bitstream
Parameters
dec a pointer to a bit_decoder context
m Golomb parameter, must be the same used for encoding
log2_m Rice parameter, is ilog_2(m), must be larger than 0
Note
the Golomb parameter (m) must be a power of 2
Warning
the Rice parameter (log2_m) must be greater than 0! If you want to use a Rice parameter equal to 0, use the unary_decoder instead.
Returns
the decoded value
Definition at line 111 of file decmp.c.
 {
         uint32_t q;  /* quotient */
         uint32_t r;  /* remainder */
         assert(log2_m > 0 && log2_m < 32);
         q = unary_decoder(dec, m, log2_m); /* decode quotient unary code part */
         r = bit_read_bits32(dec, log2_m); /* get remainder */
         return (q << log2_m) + r; /* calculate decoded value (q*m+r) */
 }
References bit_read_bits32(), and unary_decoder().
Referenced by select_decoder(), test_rice_decoder(), and test_select_decoder().