cmp_tool: decode_none
decode_none()
static int decode_none (const struct decoder_setup * setup, uint32_t * decoded_value) static
get the value unencoded with setup->cmp_par_1 bits without any additional changes from the bitstream
Parameters
setup pointer to the decoder setup
decoded_value points to the location where the decoded value is stored
Returns
0 on success; otherwise error
Definition at line 285 of file decmp.c.
 {
         *decoded_value = bit_read_bits32(setup->dec, setup->encoder_par1);
         return bit_refill(setup->dec) == BIT_OVERFLOW;
 }
References BIT_OVERFLOW, bit_read_bits32(), bit_refill(), decoder_setup::dec, and decoder_setup::encoder_par1.
Referenced by configure_decoder_setup(), and decode_value().