cmp_tool: cmp_ent_read_header
cmp_ent_read_header()
static int cmp_ent_read_header (struct cmp_entity * ent, struct cmp_cfg * cfg) static
read in an imagette compression entity header to a compression configuration
Parameters
ent pointer to a compression entity
cfg pointer to a compression configuration
Returns
0 on success; otherwise error
Definition at line 1974 of file decmp.c.
 {
         int32_t samples;
         if (!cfg)
                 return -1;
         cfg->data_type = cmp_ent_get_data_type(ent);
         if (cmp_data_type_is_invalid(cfg->data_type)) {
                 debug_print("Error: Compression data type not supported.\n");
                 return -1;
         }
         cfg->cmp_mode = cmp_ent_get_cmp_mode(ent);
         if (cmp_ent_get_data_type_raw_bit(ent) != (cfg->cmp_mode == CMP_MODE_RAW)) {
                 debug_print("Error: The entity's raw data bit does not match up with the compression mode.\n");
                 return -1;
         }
         cfg->model_value = cmp_ent_get_model_value(ent);
         cfg->round = cmp_ent_get_lossy_cmp_par(ent);
         cfg->buffer_length = cmp_ent_get_cmp_data_size(ent);
         samples = cmp_input_size_to_samples(cmp_ent_get_original_size(ent), cfg->data_type);
         if (samples < 0) {
                 debug_print("Error: original_size and data product type in the compression header are not compatible.\n");
                 cfg->samples = 0;
                 return -1;
         }
         cfg->samples = (uint32_t)samples;
         cfg->icu_output_buf = cmp_ent_get_data_buf(ent);
         cfg->max_used_bits = cmp_max_used_bits_list_get(cmp_ent_get_max_used_bits_version(ent));
         if (!cfg->max_used_bits) {
                 debug_print("Error: The Max. Used Bits Registry Version in the compression header is unknown.\n");
                 return -1;
         }
         if (cfg->cmp_mode == CMP_MODE_RAW)
                 /* no specific header is used for raw data we are done */
                 return 0;
         switch (cfg->data_type) {
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 cfg->ap1_golomb_par = cmp_ent_get_ima_ap1_golomb_par(ent);
                 cfg->ap1_spill = cmp_ent_get_ima_ap1_spill(ent);
                 cfg->ap2_golomb_par = cmp_ent_get_ima_ap2_golomb_par(ent);
                 cfg->ap2_spill = cmp_ent_get_ima_ap2_spill(ent);
                 /* fall through */
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE:
                 cfg->spill = cmp_ent_get_ima_spill(ent);
                 cfg->golomb_par = cmp_ent_get_ima_golomb_par(ent);
                 break;
         case DATA_TYPE_OFFSET:
         case DATA_TYPE_F_CAM_OFFSET:
         case DATA_TYPE_BACKGROUND:
         case DATA_TYPE_F_CAM_BACKGROUND:
         case DATA_TYPE_SMEARING:
                 cfg->cmp_par_mean = cmp_ent_get_non_ima_cmp_par1(ent);
                 cfg->spill_mean = cmp_ent_get_non_ima_spill1(ent);
                 cfg->cmp_par_variance = cmp_ent_get_non_ima_cmp_par2(ent);
                 cfg->spill_variance = cmp_ent_get_non_ima_spill2(ent);
                 cfg->cmp_par_pixels_error = cmp_ent_get_non_ima_cmp_par3(ent);
                 cfg->spill_pixels_error = cmp_ent_get_non_ima_spill3(ent);
                 break;
         case DATA_TYPE_S_FX:
         case DATA_TYPE_S_FX_EFX:
         case DATA_TYPE_S_FX_NCOB:
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_L_FX:
         case DATA_TYPE_L_FX_EFX:
         case DATA_TYPE_L_FX_NCOB:
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
         case DATA_TYPE_F_FX:
         case DATA_TYPE_F_FX_EFX:
         case DATA_TYPE_F_FX_NCOB:
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 cfg->cmp_par_exp_flags = cmp_ent_get_non_ima_cmp_par1(ent);
                 cfg->spill_exp_flags = cmp_ent_get_non_ima_spill1(ent);
                 cfg->cmp_par_fx = cmp_ent_get_non_ima_cmp_par2(ent);
                 cfg->spill_fx = cmp_ent_get_non_ima_spill2(ent);
                 cfg->cmp_par_ncob = cmp_ent_get_non_ima_cmp_par3(ent);
                 cfg->spill_ncob = cmp_ent_get_non_ima_spill3(ent);
                 cfg->cmp_par_efx = cmp_ent_get_non_ima_cmp_par4(ent);
                 cfg->spill_efx = cmp_ent_get_non_ima_spill4(ent);
                 cfg->cmp_par_ecob = cmp_ent_get_non_ima_cmp_par5(ent);
                 cfg->spill_ecob = cmp_ent_get_non_ima_spill5(ent);
                 cfg->cmp_par_fx_cob_variance = cmp_ent_get_non_ima_cmp_par6(ent);
                 cfg->spill_fx_cob_variance = cmp_ent_get_non_ima_spill6(ent);
                 break;
         /* LCOV_EXCL_START */
         case DATA_TYPE_UNKNOWN:
         default:
                 return -1;
         /* LCOV_EXCL_STOP */
         }
         return 0;
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_cfg::buffer_length, cmp_data_type_is_invalid(), cmp_ent_get_cmp_data_size(), cmp_ent_get_cmp_mode(), cmp_ent_get_data_buf(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_get_ima_ap1_golomb_par(), cmp_ent_get_ima_ap1_spill(), cmp_ent_get_ima_ap2_golomb_par(), cmp_ent_get_ima_ap2_spill(), cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), cmp_ent_get_lossy_cmp_par(), cmp_ent_get_max_used_bits_version(), cmp_ent_get_model_value(), cmp_ent_get_non_ima_cmp_par1(), cmp_ent_get_non_ima_cmp_par2(), cmp_ent_get_non_ima_cmp_par3(), cmp_ent_get_non_ima_cmp_par4(), cmp_ent_get_non_ima_cmp_par5(), cmp_ent_get_non_ima_cmp_par6(), cmp_ent_get_non_ima_spill1(), cmp_ent_get_non_ima_spill2(), cmp_ent_get_non_ima_spill3(), cmp_ent_get_non_ima_spill4(), cmp_ent_get_non_ima_spill5(), cmp_ent_get_non_ima_spill6(), cmp_ent_get_original_size(), cmp_input_size_to_samples(), cmp_max_used_bits_list_get(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_ncob, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, cmp_cfg::golomb_par, cmp_cfg::icu_output_buf, cmp_cfg::max_used_bits, cmp_cfg::model_value, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, cmp_cfg::spill_mean, cmp_cfg::spill_ncob, cmp_cfg::spill_pixels_error, and cmp_cfg::spill_variance.
Referenced by decompress_cmp_entiy(), test_cmp_ent_read_header_error_cases(), and test_cmp_ent_write_cmp_pars().