cmp_tool: decompressed_data_internal
decompressed_data_internal()
static int decompressed_data_internal (struct cmp_cfg * cfg) static
decompress the data based on a compression configuration
Parameters
cfg pointer to a compression configuration
Note
cfg->buffer_length is measured in bytes
Returns
the size of the decompressed data on success; returns negative on failure
Definition at line 1823 of file decmp.c.
 {
         int err;
         uint32_t data_size;
         if (!cfg)
                 return -1;
         if (!cfg->icu_output_buf)
                 return -1;
         if (!cfg->max_used_bits)
                 return -1;
         if (cmp_imagette_data_type_is_used(cfg->data_type)) {
                 if (cmp_cfg_imagette_is_invalid(cfg, ICU_CHECK))
                         return -1;
         } else if (cmp_fx_cob_data_type_is_used(cfg->data_type)) {
                 if (cmp_cfg_fx_cob_is_invalid(cfg))
                         return -1;
         } else if (cmp_aux_data_type_is_used(cfg->data_type))
                 if (cmp_cfg_aux_is_invalid(cfg))
                         return -1;
         data_size = cmp_cal_size_of_data(cfg->samples, cfg->data_type);
         if (!cfg->input_buf || !data_size)
                 return (int)data_size;
         if (model_mode_is_used(cfg->cmp_mode))
                 if (!cfg->model_buf)
                         return -1;
         if (cfg->cmp_mode == CMP_MODE_RAW) {
                 if (data_size < cfg->buffer_length/CHAR_BIT)
                         return -1;
                 if (cfg->input_buf) {
                         memcpy(cfg->input_buf, cfg->icu_output_buf, data_size);
                         if (cmp_input_big_to_cpu_endianness(cfg->input_buf, data_size, cfg->data_type))
                                 return -1;
                 }
                 err = 0;
         } else {
                 struct bit_decoder dec;
                 bit_init_decoder(&dec, cfg->icu_output_buf, cfg->buffer_length);
                 switch (cfg->data_type) {
                 case DATA_TYPE_IMAGETTE:
                 case DATA_TYPE_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_SAT_IMAGETTE:
                 case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
                 case DATA_TYPE_F_CAM_IMAGETTE:
                 case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                         err = decompress_imagette(cfg, &dec);
                         break;
                 case DATA_TYPE_S_FX:
                         err = decompress_s_fx(cfg, &dec);
                         break;
                 case DATA_TYPE_S_FX_EFX:
                         err = decompress_s_fx_efx(cfg, &dec);
                         break;
                 case DATA_TYPE_S_FX_NCOB:
                         err = decompress_s_fx_ncob(cfg, &dec);
                         break;
                 case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                         err = decompress_s_fx_efx_ncob_ecob(cfg, &dec);
                         break;
                 case DATA_TYPE_F_FX:
                         err = decompress_f_fx(cfg, &dec);
                         break;
                 case DATA_TYPE_F_FX_EFX:
                         err = decompress_f_fx_efx(cfg, &dec);
                         break;
                 case DATA_TYPE_F_FX_NCOB:
                         err = decompress_f_fx_ncob(cfg, &dec);
                         break;
                 case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                         err = decompress_f_fx_efx_ncob_ecob(cfg, &dec);
                         break;
                 case DATA_TYPE_L_FX:
                         err = decompress_l_fx(cfg, &dec);
                         break;
                 case DATA_TYPE_L_FX_EFX:
                         err = decompress_l_fx_efx(cfg, &dec);
                         break;
                 case DATA_TYPE_L_FX_NCOB:
                         err = decompress_l_fx_ncob(cfg, &dec);
                         break;
                 case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                         err = decompress_l_fx_efx_ncob_ecob(cfg, &dec);
                         break;
                 case DATA_TYPE_OFFSET:
                 case DATA_TYPE_F_CAM_OFFSET:
                         err = decompress_offset(cfg, &dec);
                         break;
                 case DATA_TYPE_BACKGROUND:
                 case DATA_TYPE_F_CAM_BACKGROUND:
                         err = decompress_background(cfg, &dec);
                         break;
                 case DATA_TYPE_SMEARING:
                         err = decompress_smearing(cfg, &dec);
                         break;
                 case DATA_TYPE_UNKNOWN:
                 default:
                         err = -1;
                         debug_print("Error: Compressed data type not supported.\n");
                         break;
                 }
                 switch (bit_refill(&dec)) {
                 case BIT_OVERFLOW:
                         if (dec.cursor == dec.limit_ptr)
                                 debug_print("Error: The end of the compressed bit stream has been exceeded. Please check that the compression parameters match those used to compress the data and that the compressed data are not corrupted.\n");
                         else
                                 debug_print("Error: Data consistency check failed. %s", please_check_str);
                         break;
                 case BIT_END_OF_BUFFER:
                         /* check if non consumed bit are zero */
                         if (bit_read_bits(&dec, sizeof(dec.bit_container)*8 - dec.bits_consumed) == 0)
                                 break;
                         /* fall through */
                 case BIT_UNFINISHED:
                         debug_print("Warning: Not all compressed data are processed.\n");
                         break;
                 }
         }
         if (err)
                 return -1;
         return (int)data_size;
 }
References bit_decoder::bit_container, BIT_END_OF_BUFFER, bit_init_decoder(), BIT_OVERFLOW, bit_read_bits(), bit_refill(), BIT_UNFINISHED, bit_decoder::bits_consumed, cmp_cfg::buffer_length, cmp_aux_data_type_is_used(), cmp_cal_size_of_data(), cmp_cfg_aux_is_invalid(), cmp_cfg_fx_cob_is_invalid(), cmp_cfg_imagette_is_invalid(), cmp_fx_cob_data_type_is_used(), cmp_imagette_data_type_is_used(), cmp_input_big_to_cpu_endianness(), cmp_cfg::cmp_mode, CMP_MODE_RAW, bit_decoder::cursor, cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, debug_print, decompress_background(), decompress_f_fx(), decompress_f_fx_efx(), decompress_f_fx_efx_ncob_ecob(), decompress_f_fx_ncob(), decompress_imagette(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), decompress_l_fx_ncob(), decompress_offset(), decompress_s_fx(), decompress_s_fx_efx(), decompress_s_fx_efx_ncob_ecob(), decompress_s_fx_ncob(), decompress_smearing(), ICU_CHECK, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, bit_decoder::limit_ptr, cmp_cfg::max_used_bits, cmp_cfg::model_buf, model_mode_is_used(), please_check_str, and cmp_cfg::samples.
Referenced by decompress_cmp_entiy(), and decompress_rdcu_data().