cmp_tool: decompress_cmp_entiy
decompress_cmp_entiy()
int decompress_cmp_entiy (struct cmp_entity * ent, void * model_of_data, void * up_model_buf, void * decompressed_data)
decompress a compression entity
Parameters
ent pointer to the compression entity to be decompressed
model_of_data pointer to model data buffer (can be NULL if no model compression mode is used)
up_model_buf pointer to store the updated model for the next model mode compression (can be the same as the model_of_data buffer for an in-place update or NULL if updated model is not needed)
decompressed_data pointer to the decompressed data buffer (can be NULL)
Returns
the size of the decompressed data on success; returns negative on failure
Definition at line 2094 of file decmp.c.
 {
         int err;
         struct cmp_cfg cfg;
         memset(&cfg, 0, sizeof(struct cmp_cfg));
         cfg.model_buf = model_of_data;
         cfg.icu_new_model_buf = up_model_buf;
         cfg.input_buf = decompressed_data;
         if (!ent)
                 return -1;
         err = cmp_ent_read_header(ent, &cfg);
         if (err)
                 return -1;
         return decompressed_data_internal(&cfg);
 }
References cmp_ent_read_header(), decompressed_data_internal(), cmp_cfg::icu_new_model_buf, cmp_cfg::input_buf, and cmp_cfg::model_buf.
Referenced by compression_decompression(), test_cmp_decmp_n_imagette_raw(), test_cmp_decmp_s_fx_diff(), test_s_fx_diff(), and test_s_fx_model().