cmp_tool: decompress_smearing
decompress_smearing()
static int decompress_smearing (const struct cmp_cfg * cfg, struct bit_decoder * dec) static
decompress N-CAM smearing data
Parameters
cfg pointer to the compression configuration structure
dec a pointer to a bit_decoder context
Returns
0 on success; otherwise error
Definition at line 1745 of file decmp.c.
 {
         size_t i;
         int err;
         uint32_t decoded_value;
         struct decoder_setup setup_mean, setup_var, setup_pix;
         struct smearing *data_buf = cfg->input_buf;
         struct smearing *model_buf = cfg->model_buf;
         struct smearing *up_model_buf = NULL;
         struct smearing *next_model_p;
         struct smearing model;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         decompress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                    (void **)&up_model_buf, cfg);
         bit_init_decoder(dec, (uint8_t *)cfg->icu_output_buf+MULTI_ENTRY_HDR_SIZE, cfg->buffer_length-MULTI_ENTRY_HDR_SIZE);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         configure_decoder_setup(&setup_mean, dec, cfg->cmp_mode, cfg->cmp_par_mean, cfg->spill_mean,
                                 cfg->round, cfg->max_used_bits->smearing_mean);
         configure_decoder_setup(&setup_var, dec, cfg->cmp_mode, cfg->cmp_par_variance, cfg->spill_variance,
                                 cfg->round, cfg->max_used_bits->smearing_variance_mean);
         configure_decoder_setup(&setup_pix, dec, cfg->cmp_mode, cfg->cmp_par_pixels_error, cfg->spill_pixels_error,
                                 cfg->round, cfg->max_used_bits->smearing_outlier_pixels);
         for (i = 0; ; i++) {
                 err = decode_value(&setup_mean, &decoded_value, model.mean);
                 if (err)
                         break;
                 data_buf[i].mean = decoded_value;
                 err = decode_value(&setup_var, &decoded_value, model.variance_mean);
                 if (err)
                         break;
                 data_buf[i].variance_mean = (__typeof__(data_buf[i].variance_mean))decoded_value;
                 err = decode_value(&setup_pix, &decoded_value, model.outlier_pixels);
                 if (err)
                         break;
                 data_buf[i].outlier_pixels = (__typeof__(data_buf[i].outlier_pixels))decoded_value;
                 if (up_model_buf) {
                         up_model_buf[i].mean = cmp_up_model(data_buf[i].mean,
                                 model.mean, cfg->model_value, setup_mean.lossy_par);
                         up_model_buf[i].variance_mean = cmp_up_model(data_buf[i].variance_mean,
                                 model.variance_mean, cfg->model_value, setup_var.lossy_par);
                         up_model_buf[i].outlier_pixels = cmp_up_model(data_buf[i].outlier_pixels,
                                 model.outlier_pixels, cfg->model_value, setup_pix.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return err;
 }
References bit_init_decoder(), cmp_cfg::buffer_length, cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_up_model, configure_decoder_setup(), decode_value(), decompress_multi_entry_hdr(), cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, decoder_setup::lossy_par, cmp_cfg::max_used_bits, mean, smearing::mean, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, MULTI_ENTRY_HDR_SIZE, outlier_pixels, smearing::outlier_pixels, cmp_cfg::round, cmp_cfg::samples, cmp_max_used_bits::smearing_mean, cmp_max_used_bits::smearing_outlier_pixels, cmp_max_used_bits::smearing_variance_mean, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, cmp_cfg::spill_variance, variance_mean, and smearing::variance_mean.
Referenced by decompressed_data_internal().