cmp_tool: configure_decoder_setup
configure_decoder_setup()
static void configure_decoder_setup (struct decoder_setup * setup, struct bit_decoder * dec, enum cmp_mode cmp_mode, uint32_t cmp_par, uint32_t spillover, uint32_t lossy_par, uint32_t max_data_bits) static
configure a decoder setup structure to have a setup to decode a vale
Parameters
setup pointer to the decoder setup
dec pointer to a bit_decoder context
cmp_mode compression mode
cmp_par compression parameter
spillover spillover_par parameter
lossy_par lossy compression parameter
max_data_bits how many bits are needed to represent the highest possible value
Definition at line 364 of file decmp.c.
 {
         assert(setup != NULL);
         assert(dec != NULL);
         assert(cmp_par != 0);
         assert(max_data_bits > 0 && max_data_bits <= 32);
         if (multi_escape_mech_is_used(cmp_mode))
                 setup->decode_method_f = &decode_multi;
         else if (zero_escape_mech_is_used(cmp_mode))
                 setup->decode_method_f = &decode_zero;
         else if (cmp_mode == CMP_MODE_STUFF)
                 setup->decode_method_f = &decode_none;
         else {
                 debug_print("Error: Compression mode not supported.\n");
                 assert(0);
         }
         setup->decode_cw_f = select_decoder(cmp_par);
         setup->dec = dec;
         setup->encoder_par1 = cmp_par; /* encoding parameter 1 */
         setup->encoder_par2 = ilog_2(cmp_par); /* encoding parameter 2 */
         setup->outlier_par = spillover; /* outlier parameter */
         setup->lossy_par = lossy_par; /* lossy compression parameter */
         setup->max_data_bits = max_data_bits; /* how many bits are needed to represent the highest possible value */
 }
References CMP_MODE_STUFF, debug_print, decoder_setup::dec, decoder_setup::decode_cw_f, decoder_setup::decode_method_f, decode_multi(), decode_none(), decode_zero(), decoder_setup::encoder_par1, decoder_setup::encoder_par2, ilog_2(), decoder_setup::lossy_par, decoder_setup::max_data_bits, multi_escape_mech_is_used(), decoder_setup::outlier_par, select_decoder(), and zero_escape_mech_is_used().
Referenced by decompress_background(), decompress_f_fx(), decompress_f_fx_efx(), decompress_f_fx_efx_ncob_ecob(), decompress_f_fx_ncob(), decompress_imagette(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), decompress_l_fx_ncob(), decompress_offset(), decompress_s_fx(), decompress_s_fx_efx(), decompress_s_fx_efx_ncob_ecob(), decompress_s_fx_ncob(), decompress_smearing(), test_decode_multi(), test_decode_zero(), test_multi_refill_needed(), and test_zero_refill_needed().