cmp_tool: decode_value
decode_value()
static int decode_value (const struct decoder_setup * setup, uint32_t * decoded_value, uint32_t model) static
decompress the next code word in the bitstream and decorate it with the model
Parameters
setup pointer to the decoder setup
decoded_value points to the location where the decoded value is stored
model model of the decoded_value (0 if not used)
Returns
0 on success; otherwise error
Definition at line 326 of file decmp.c.
 {
         /* decode the next value from the bitstream */
         int err = setup->decode_method_f(setup, decoded_value);
         if (setup->decode_method_f == decode_none)
                 /* we are done here in stuff mode */
                 return err;
         /* map the unsigned decode value back to a signed value */
         *decoded_value = re_map_to_pos(*decoded_value);
         /* decorate data the data with the model */
         *decoded_value += round_fwd(model, setup->lossy_par);
         /* we mask only the used bits in case there is an overflow when adding the model */
         *decoded_value &= BIT_MASK[setup->max_data_bits];
         /* inverse step of the lossy compression */
         *decoded_value = round_inv(*decoded_value, setup->lossy_par);
         return err;
 }
References BIT_MASK, decoder_setup::decode_method_f, decode_none(), decoder_setup::lossy_par, decoder_setup::max_data_bits, re_map_to_pos(), round_fwd, and round_inv.
Referenced by decompress_background(), decompress_f_fx(), decompress_f_fx_efx(), decompress_f_fx_efx_ncob_ecob(), decompress_f_fx_ncob(), decompress_imagette(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), decompress_l_fx_ncob(), decompress_offset(), decompress_s_fx(), decompress_s_fx_efx(), decompress_s_fx_efx_ncob_ecob(), decompress_s_fx_ncob(), and decompress_smearing().