cmp_tool: decompress_multi_entry_hdr
decompress_multi_entry_hdr()
static int decompress_multi_entry_hdr (void ** data, void ** model, void ** up_model, const struct cmp_cfg * cfg) static
decompress the multi-entry packet header structure and sets the data, model and up_model pointers to the data after the header
Parameters
data pointer to a pointer pointing to the data to be compressed
model pointer to a pointer pointing to the model of the data
up_model pointer to a pointer pointing to the updated model buffer
cfg pointer to the compression configuration structure
Returns
the bit length of the bitstream on success
Note
the (void **) cast relies on all pointer types having the same internal representation which is common, but not universal; http://www.c-faq.com/ptrs/genericpp.html
Definition at line 479 of file decmp.c.
 {
         if (cfg->buffer_length < MULTI_ENTRY_HDR_SIZE)
                 return -1;
         if (*data) {
                 if (cfg->icu_output_buf)
                         memcpy(*data, cfg->icu_output_buf, MULTI_ENTRY_HDR_SIZE);
                 *data = (uint8_t *)*data + MULTI_ENTRY_HDR_SIZE;
         }
         if (*model) {
                 if (cfg->icu_output_buf)
                         memcpy(*model, cfg->icu_output_buf, MULTI_ENTRY_HDR_SIZE);
                 *model = (uint8_t *)*model + MULTI_ENTRY_HDR_SIZE;
         }
         if (*up_model) {
                 if (cfg->icu_output_buf)
                         memcpy(*up_model, cfg->icu_output_buf, MULTI_ENTRY_HDR_SIZE);
                 *up_model = (uint8_t *)*up_model + MULTI_ENTRY_HDR_SIZE;
         }
         return MULTI_ENTRY_HDR_SIZE * CHAR_BIT;
 }
References cmp_cfg::buffer_length, cmp_cfg::icu_output_buf, and MULTI_ENTRY_HDR_SIZE.
Referenced by decompress_background(), decompress_f_fx(), decompress_f_fx_efx(), decompress_f_fx_efx_ncob_ecob(), decompress_f_fx_ncob(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), decompress_l_fx_ncob(), decompress_offset(), decompress_s_fx(), decompress_s_fx_efx(), decompress_s_fx_efx_ncob_ecob(), decompress_s_fx_ncob(), and decompress_smearing().