cmp_tool: decompress_background
decompress_background()
static int decompress_background (const struct cmp_cfg * cfg, struct bit_decoder * dec) static
decompress N-CAM background data
Parameters
cfg pointer to the compression configuration structure
dec a pointer to a bit_decoder context
Returns
0 on success; otherwise error
Definition at line 1648 of file decmp.c.
 {
         size_t i;
         int err;
         uint32_t decoded_value;
         struct decoder_setup setup_mean, setup_var, setup_pix;
         struct background *data_buf = cfg->input_buf;
         struct background *model_buf = cfg->model_buf;
         struct background *up_model_buf = NULL;
         struct background *next_model_p;
         struct background model;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         decompress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                    (void **)&up_model_buf, cfg);
         bit_init_decoder(dec, (uint8_t *)cfg->icu_output_buf+MULTI_ENTRY_HDR_SIZE, cfg->buffer_length-MULTI_ENTRY_HDR_SIZE);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         {
                 unsigned int mean_used_bits, variance_used_bits, outlier_pixels_used_bits;
                 switch (cfg->data_type) {
                 case DATA_TYPE_F_CAM_BACKGROUND:
                         mean_used_bits = cfg->max_used_bits->fc_background_mean;
                         variance_used_bits = cfg->max_used_bits->fc_background_variance;
                         outlier_pixels_used_bits = cfg->max_used_bits->fc_background_outlier_pixels;
                         break;
                 case DATA_TYPE_BACKGROUND:
                 default:
                         mean_used_bits = cfg->max_used_bits->nc_background_mean;
                         variance_used_bits = cfg->max_used_bits->nc_background_variance;
                         outlier_pixels_used_bits = cfg->max_used_bits->nc_background_outlier_pixels;
                         break;
                 }
                 configure_decoder_setup(&setup_mean, dec, cfg->cmp_mode, cfg->cmp_par_mean, cfg->spill_mean,
                                         cfg->round, mean_used_bits);
                 configure_decoder_setup(&setup_var, dec, cfg->cmp_mode, cfg->cmp_par_variance, cfg->spill_variance,
                                         cfg->round, variance_used_bits);
                 configure_decoder_setup(&setup_pix, dec, cfg->cmp_mode, cfg->cmp_par_pixels_error, cfg->spill_pixels_error,
                                         cfg->round, outlier_pixels_used_bits);
         }
         for (i = 0; ; i++) {
                 err = decode_value(&setup_mean, &decoded_value, model.mean);
                 if (err)
                         break;
                 data_buf[i].mean = decoded_value;
                 err = decode_value(&setup_var, &decoded_value, model.variance);
                 if (err)
                         break;
                 data_buf[i].variance = decoded_value;
                 err = decode_value(&setup_pix, &decoded_value, model.outlier_pixels);
                 if (err)
                         break;
                 data_buf[i].outlier_pixels = (__typeof__(data_buf[i].outlier_pixels))decoded_value;
                 if (up_model_buf) {
                         up_model_buf[i].mean = cmp_up_model(data_buf[i].mean,
                                 model.mean, cfg->model_value, setup_mean.lossy_par);
                         up_model_buf[i].variance = cmp_up_model(data_buf[i].variance,
                                 model.variance, cfg->model_value, setup_var.lossy_par);
                         up_model_buf[i].outlier_pixels = cmp_up_model(data_buf[i].outlier_pixels,
                                 model.outlier_pixels, cfg->model_value, setup_pix.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return err;
 }
References bit_init_decoder(), cmp_cfg::buffer_length, cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_up_model, configure_decoder_setup(), cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, decode_value(), decompress_multi_entry_hdr(), cmp_max_used_bits::fc_background_mean, cmp_max_used_bits::fc_background_outlier_pixels, cmp_max_used_bits::fc_background_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, decoder_setup::lossy_par, cmp_cfg::max_used_bits, mean, background::mean, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::nc_background_mean, cmp_max_used_bits::nc_background_outlier_pixels, cmp_max_used_bits::nc_background_variance, outlier_pixels, background::outlier_pixels, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, cmp_cfg::spill_variance, variance, and background::variance.
Referenced by decompressed_data_internal().