cmp_tool: golomb_decoder
golomb_decoder()
static uint32_t golomb_decoder (struct bit_decoder * dec, uint32_t m, uint32_t log2_m) static
decode the next Golomb code word in the bitstream
Parameters
dec a pointer to a bit_decoder context
m Golomb parameter (have to be bigger than 0)
log2_m is ilog_2(m) calculate outside function for better performance
Returns
the decoded value
Definition at line 136 of file decmp.c.
 {
         uint32_t q;  /* quotient */
         uint32_t r1; /* remainder case 1 */
         uint32_t r2; /* remainder case 2 */
         uint32_t r;  /* remainder */
         uint32_t cutoff; /* cutoff between group 1 and 2 */
         assert(m > 0);
         assert(log2_m == ilog_2(m));
         /* decode quotient unary code part */
         q = unary_decoder(dec, m, log2_m);
         /* get the remainder code for both cases */
         r2 = (uint32_t)bit_peek_bits(dec, log2_m+1);
         r1 = r2 >> 1;
         /* calculate cutoff between case 1 and 2 */
         cutoff = (0x2U << log2_m) - m; /* = 2^(log2_m+1)-m */
         if (r1 < cutoff) { /* remainder case 1: remainder length=log2_m */
                 bit_consume_bits(dec, log2_m);
                 r = r1;
         } else { /* remainder case 2: remainder length = log2_m+1 */
                 bit_consume_bits(dec, log2_m+1);
                 r = r2 - cutoff;
         }
         return q*m + r;
 }
References bit_consume_bits(), bit_peek_bits(), ilog_2(), and unary_decoder().
Referenced by select_decoder(), test_golomb_decoder(), and test_select_decoder().