cmp_tool: decode_multi
decode_multi()
static int decode_multi (const struct decoder_setup * setup, uint32_t * decoded_value) static
decode the next code word with the multi escape mechanism from the bitstream
Parameters
setup pointer to the decoder setup
decoded_value points to the location where the decoded value is stored
Returns
0 on success; otherwise error
Definition at line 238 of file decmp.c.
 {
         /* Decode the next value in the bitstream with the Golomb/Rice/unary decoder */
         *decoded_value = setup->decode_cw_f(setup->dec, setup->encoder_par1, setup->encoder_par2);
         if (*decoded_value >= setup->outlier_par) { /* escape symbol mechanism detected */
                 uint32_t const unencoded_len = (*decoded_value - setup->outlier_par + 1) << 1;
                 if (unencoded_len > ((setup->max_data_bits+1) & -2U)) { /* round up max_data_bits to the nearest multiple of 2 */
                         debug_print("Error: Data consistency check failed. Multi escape symbol higher than expected. %s", please_check_str);
                         return CORRUPTION_DETECTED;
                 }
                 /* read unencoded value */
                 bit_refill(setup->dec);
                 *decoded_value = bit_read_bits32(setup->dec, unencoded_len);
                 if (*decoded_value >> (unencoded_len-2) == 0) { /* check if at least one bit of the two highest is set. */
                         if (unencoded_len > 2) { /* Exception: if we code outlier_par as outlier, no set bit is expected */
                                 if (bit_refill(setup->dec) != BIT_OVERFLOW)
                                         debug_print("Error: Data consistency check failed. Unencoded data after multi escape symbol to small. %s", please_check_str);
                                 return CORRUPTION_DETECTED;
                         }
                 }
                 *decoded_value += setup->outlier_par;
                 if ((*decoded_value & BIT_MASK[setup->max_data_bits]) < setup->outlier_par) { /* check for overflow in addition */
                         if (bit_refill(setup->dec) != BIT_OVERFLOW)
                                 debug_print("Error: Data consistency check failed. Outlier small than the outlier parameter. %s", please_check_str);
                         return CORRUPTION_DETECTED;
                 }
         }
         return bit_refill(setup->dec) == BIT_OVERFLOW;
 }
References BIT_MASK, BIT_OVERFLOW, bit_read_bits32(), bit_refill(), CORRUPTION_DETECTED, debug_print, decoder_setup::dec, decoder_setup::decode_cw_f, decoder_setup::encoder_par1, decoder_setup::encoder_par2, decoder_setup::max_data_bits, decoder_setup::outlier_par, and please_check_str.
Referenced by configure_decoder_setup(), test_decode_multi(), and test_multi_refill_needed().