cmp_tool: decompress_offset
decompress_offset()
static int decompress_offset (const struct cmp_cfg * cfg, struct bit_decoder * dec) static
decompress N-CAM and F-CAM offset data
Parameters
cfg pointer to the compression configuration structure
dec a pointer to a bit_decoder context
Returns
0 on success; otherwise error
Definition at line 1563 of file decmp.c.
 {
         size_t i;
         int err;
         uint32_t decoded_value;
         struct decoder_setup setup_mean, setup_var;
         struct offset *data_buf = cfg->input_buf;
         struct offset *model_buf = cfg->model_buf;
         struct offset *up_model_buf = NULL;
         struct offset *next_model_p;
         struct offset model;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         decompress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                    (void **)&up_model_buf, cfg);
         bit_init_decoder(dec, (uint8_t *)cfg->icu_output_buf+MULTI_ENTRY_HDR_SIZE, cfg->buffer_length-MULTI_ENTRY_HDR_SIZE);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         {
                 unsigned int mean_bits_used, variance_bits_used;
                 switch (cfg->data_type) {
                 case DATA_TYPE_F_CAM_OFFSET:
                         mean_bits_used = cfg->max_used_bits->fc_offset_mean;
                         variance_bits_used = cfg->max_used_bits->fc_offset_variance;
                         break;
                 case DATA_TYPE_OFFSET:
                 default:
                         mean_bits_used = cfg->max_used_bits->nc_offset_mean;
                         variance_bits_used = cfg->max_used_bits->nc_offset_variance;
                         break;
                 }
                 configure_decoder_setup(&setup_mean, dec, cfg->cmp_mode, cfg->cmp_par_mean, cfg->spill_mean,
                                         cfg->round, mean_bits_used);
                 configure_decoder_setup(&setup_var, dec, cfg->cmp_mode, cfg->cmp_par_variance, cfg->spill_variance,
                                         cfg->round, variance_bits_used);
         }
         for (i = 0; ; i++) {
                 err = decode_value(&setup_mean, &decoded_value, model.mean);
                 if (err)
                         break;
                 data_buf[i].mean = decoded_value;
                 err = decode_value(&setup_var, &decoded_value, model.variance);
                 if (err)
                         break;
                 data_buf[i].variance = decoded_value;
                 if (up_model_buf) {
                         up_model_buf[i].mean = cmp_up_model(data_buf[i].mean,
                                 model.mean, cfg->model_value, setup_mean.lossy_par);
                         up_model_buf[i].variance = cmp_up_model(data_buf[i].variance,
                                 model.variance, cfg->model_value, setup_var.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return err;
 }
References bit_init_decoder(), cmp_cfg::buffer_length, cmp_cfg::cmp_mode, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_variance, cmp_up_model, configure_decoder_setup(), cmp_cfg::data_type, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_OFFSET, decode_value(), decompress_multi_entry_hdr(), cmp_max_used_bits::fc_offset_mean, cmp_max_used_bits::fc_offset_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, decoder_setup::lossy_par, cmp_cfg::max_used_bits, mean, offset::mean, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::nc_offset_mean, cmp_max_used_bits::nc_offset_variance, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_mean, cmp_cfg::spill_variance, variance, and offset::variance.
Referenced by decompressed_data_internal().