cmp_tool: decode_zero
decode_zero()
static int decode_zero (const struct decoder_setup * setup, uint32_t * decoded_value) static
decode the next code word with zero escape system mechanism from the bitstream
Parameters
setup pointer to the decoder setup
decoded_value points to the location where the decoded value is stored
Returns
0 on success; otherwise error
Definition at line 203 of file decmp.c.
 {
         /* Decode the next value in the bitstream with the Golomb/Rice/unary decoder */
         *decoded_value = setup->decode_cw_f(setup->dec, setup->encoder_par1, setup->encoder_par2);
         if (*decoded_value != 0) { /* no escape symbol detected */
                 if (*decoded_value >= setup->outlier_par) {
                         debug_print("Error: Data consistency check failed. Non-outlier decoded value greater or equal than the outlier parameter. %s", please_check_str);
                         return CORRUPTION_DETECTED;
                 }
                 *decoded_value -= 1;
         } else {
                 /* the zero escape symbol mechanism was used; read unencoded value */
                 bit_refill(setup->dec);
                 *decoded_value = bit_read_bits32_sub_1(setup->dec, setup->max_data_bits);
                 if (*decoded_value < setup->outlier_par - 1) { /* -1 because we subtract -1 from the *decoded_value */
                         if (bit_refill(setup->dec) != BIT_OVERFLOW)
                                 debug_print("Error: Data consistency check failed. Outlier small than the outlier parameter. %s", please_check_str);
                         return CORRUPTION_DETECTED;
                 }
         }
         return bit_refill(setup->dec) == BIT_OVERFLOW;
 }
References BIT_OVERFLOW, bit_read_bits32_sub_1(), bit_refill(), CORRUPTION_DETECTED, debug_print, decoder_setup::dec, decoder_setup::decode_cw_f, decoder_setup::encoder_par1, decoder_setup::encoder_par2, decoder_setup::max_data_bits, decoder_setup::outlier_par, and please_check_str.
Referenced by configure_decoder_setup(), test_decode_zero(), and test_zero_refill_needed().