cmp_tool: unary_decoder
unary_decoder()
static __inline uint32_t unary_decoder (struct bit_decoder * dec, uint32_t unused_1, uint32_t unused_2) static
decode the next unary code word in the bitstream
Parameters
dec a pointer to a bit_decoder context
unused_1 this parameter is not used
unused_2 this parameter is not used
Note
: Can be used to decode a code word with compression parameter m = 1 (log2_m = 0)
Returns
the decoded value
Definition at line 83 of file decmp.c.
 {
         uint32_t const decoded_cw = bit_peek_leading_ones(dec); /* decode unary coding */
         uint32_t const cw_len = decoded_cw + 1; /* Number of 1's + following 0 */
         UNUSED(unused_1); /* we don't need this parameter */
         UNUSED(unused_2); /* and this parameter */
         bit_consume_bits(dec, cw_len);
         return decoded_cw;
 }
References bit_consume_bits(), bit_peek_leading_ones(), and UNUSED.
Referenced by golomb_decoder(), rice_decoder(), select_decoder(), test_rice_decoder(), test_select_decoder(), and test_unary_decoder().