cmp_tool: decompress_l_fx_efx_ncob_ecob
decompress_l_fx_efx_ncob_ecob()
static int decompress_l_fx_efx_ncob_ecob (const struct cmp_cfg * cfg, struct bit_decoder * dec) static
decompress L_FX_EFX_NCOB_ECOB data
Parameters
cfg pointer to the compression configuration structure
dec a pointer to a bit_decoder context
Returns
0 on success; otherwise error
Definition at line 1428 of file decmp.c.
 {
         size_t i;
         int err;
         uint32_t decoded_value;
         struct decoder_setup setup_exp_flags, setup_fx, setup_ncob, setup_efx,
                              setup_ecob, setup_fx_var, setup_cob_var;
         struct l_fx_efx_ncob_ecob *data_buf = cfg->input_buf;
         struct l_fx_efx_ncob_ecob *model_buf = cfg->model_buf;
         struct l_fx_efx_ncob_ecob *up_model_buf = NULL;
         struct l_fx_efx_ncob_ecob *next_model_p;
         struct l_fx_efx_ncob_ecob model;
         if (model_mode_is_used(cfg->cmp_mode))
                 up_model_buf = cfg->icu_new_model_buf;
         decompress_multi_entry_hdr((void **)&data_buf, (void **)&model_buf,
                                    (void **)&up_model_buf, cfg);
         bit_init_decoder(dec, (uint8_t *)cfg->icu_output_buf+MULTI_ENTRY_HDR_SIZE, cfg->buffer_length-MULTI_ENTRY_HDR_SIZE);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 model = model_buf[0];
                 next_model_p = &model_buf[1];
         } else {
                 memset(&model, 0, sizeof(model));
                 next_model_p = data_buf;
         }
         configure_decoder_setup(&setup_exp_flags, dec, cfg->cmp_mode, cfg->cmp_par_exp_flags, cfg->spill_exp_flags,
                                 cfg->round, cfg->max_used_bits->l_exp_flags);
         configure_decoder_setup(&setup_fx, dec, cfg->cmp_mode, cfg->cmp_par_fx, cfg->spill_fx,
                                 cfg->round, cfg->max_used_bits->l_fx);
         configure_decoder_setup(&setup_ncob, dec, cfg->cmp_mode, cfg->cmp_par_ncob, cfg->spill_ncob,
                                 cfg->round, cfg->max_used_bits->l_ncob);
         configure_decoder_setup(&setup_efx, dec, cfg->cmp_mode, cfg->cmp_par_efx, cfg->spill_efx,
                                 cfg->round, cfg->max_used_bits->l_efx);
         configure_decoder_setup(&setup_ecob, dec, cfg->cmp_mode, cfg->cmp_par_ecob, cfg->spill_ecob,
                                 cfg->round, cfg->max_used_bits->l_ecob);
         configure_decoder_setup(&setup_fx_var, dec, cfg->cmp_mode, cfg->cmp_par_fx_cob_variance, cfg->spill_fx_cob_variance,
                                 cfg->round, cfg->max_used_bits->l_fx_variance);
         configure_decoder_setup(&setup_cob_var, dec, cfg->cmp_mode, cfg->cmp_par_fx_cob_variance, cfg->spill_fx_cob_variance,
                                 cfg->round, cfg->max_used_bits->l_cob_variance);
         for (i = 0; ; i++) {
                 err = decode_value(&setup_exp_flags, &decoded_value, model.exp_flags);
                 if (err)
                         break;
                 data_buf[i].exp_flags = decoded_value;
                 err = decode_value(&setup_fx, &decoded_value, model.fx);
                 if (err)
                         break;
                 data_buf[i].fx = decoded_value;
                 err = decode_value(&setup_ncob, &decoded_value, model.ncob_x);
                 if (err)
                         break;
                 data_buf[i].ncob_x = decoded_value;
                 err = decode_value(&setup_ncob, &decoded_value, model.ncob_y);
                 if (err)
                         break;
                 data_buf[i].ncob_y = decoded_value;
                 err = decode_value(&setup_efx, &decoded_value, model.efx);
                 if (err)
                         break;
                 data_buf[i].efx = decoded_value;
                 err = decode_value(&setup_ecob, &decoded_value, model.ecob_x);
                 if (err)
                         break;
                 data_buf[i].ecob_x = decoded_value;
                 err = decode_value(&setup_ecob, &decoded_value, model.ecob_y);
                 if (err)
                         break;
                 data_buf[i].ecob_y = decoded_value;
                 err = decode_value(&setup_fx_var, &decoded_value, model.fx_variance);
                 if (err)
                         break;
                 data_buf[i].fx_variance = decoded_value;
                 err = decode_value(&setup_cob_var, &decoded_value, model.cob_x_variance);
                 if (err)
                         break;
                 data_buf[i].cob_x_variance = decoded_value;
                 err = decode_value(&setup_cob_var, &decoded_value, model.cob_y_variance);
                 if (err)
                         break;
                 data_buf[i].cob_y_variance = decoded_value;
                 if (up_model_buf) {
                         up_model_buf[i].exp_flags = cmp_up_model32(data_buf[i].exp_flags, model.exp_flags,
                                 cfg->model_value, setup_exp_flags.lossy_par);
                         up_model_buf[i].fx = cmp_up_model(data_buf[i].fx, model.fx,
                                 cfg->model_value, setup_fx.lossy_par);
                         up_model_buf[i].ncob_x = cmp_up_model(data_buf[i].ncob_x, model.ncob_x,
                                 cfg->model_value, setup_ncob.lossy_par);
                         up_model_buf[i].ncob_y = cmp_up_model(data_buf[i].ncob_y, model.ncob_y,
                                 cfg->model_value, setup_ncob.lossy_par);
                         up_model_buf[i].efx = cmp_up_model(data_buf[i].efx, model.efx,
                                 cfg->model_value, setup_efx.lossy_par);
                         up_model_buf[i].ecob_x = cmp_up_model(data_buf[i].ecob_x, model.ecob_x,
                                 cfg->model_value, setup_ecob.lossy_par);
                         up_model_buf[i].ecob_y = cmp_up_model(data_buf[i].ecob_y, model.ecob_y,
                                 cfg->model_value, setup_ecob.lossy_par);
                         up_model_buf[i].fx_variance = cmp_up_model(data_buf[i].fx_variance, model.fx_variance,
                                 cfg->model_value, setup_fx_var.lossy_par);
                         up_model_buf[i].cob_x_variance = cmp_up_model(data_buf[i].cob_x_variance, model.cob_x_variance,
                                 cfg->model_value, setup_cob_var.lossy_par);
                         up_model_buf[i].cob_y_variance = cmp_up_model(data_buf[i].cob_y_variance, model.cob_y_variance,
                                 cfg->model_value, setup_cob_var.lossy_par);
                 }
                 if (i >= cfg->samples-1)
                         break;
                 model = next_model_p[i];
         }
         return err;
 }
References bit_init_decoder(), cmp_cfg::buffer_length, cmp_cfg::cmp_mode, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, cmp_up_model, cmp_up_model32(), cob_x_variance, l_fx_efx_ncob_ecob::cob_x_variance, cob_y_variance, l_fx_efx_ncob_ecob::cob_y_variance, configure_decoder_setup(), decode_value(), decompress_multi_entry_hdr(), ecob_x, l_fx_efx_ncob_ecob::ecob_x, ecob_y, l_fx_efx_ncob_ecob::ecob_y, efx, l_fx_efx_ncob_ecob::efx, exp_flags, l_fx_efx_ncob_ecob::exp_flags, fx, l_fx_efx_ncob_ecob::fx, fx_variance, l_fx_efx_ncob_ecob::fx_variance, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, cmp_max_used_bits::l_cob_variance, cmp_max_used_bits::l_ecob, cmp_max_used_bits::l_efx, cmp_max_used_bits::l_exp_flags, cmp_max_used_bits::l_fx, cmp_max_used_bits::l_fx_variance, cmp_max_used_bits::l_ncob, decoder_setup::lossy_par, cmp_cfg::max_used_bits, cmp_cfg::model_buf, model_mode_is_used(), cmp_cfg::model_value, MULTI_ENTRY_HDR_SIZE, ncob_x, l_fx_efx_ncob_ecob::ncob_x, ncob_y, l_fx_efx_ncob_ecob::ncob_y, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, and cmp_cfg::spill_ncob.
Referenced by decompressed_data_internal().