cmp_tool: __list_del_entry
__list_del_entry()
static void __list_del_entry (struct list_head * entry) inline static
deletes entry from list.
Parameters
entry the element to delete from the list.
Note
list_empty() on entry does not return true after this, the entry is in an undefined state.
Definition at line 310 of file list.h.
 {
         __list_del(entry->prev, entry->next);
 }
References __list_del(), and entry.
Referenced by list_del_init(), and list_move().