cmp_tool: list_swap
list_swap()
static void list_swap (struct list_head * entry1, struct list_head * entry2) inline static
replace entry1 with entry2 and re-add entry1 at entry2's position
Parameters
entry1 the location to place entry2
entry2 the location to place entry1
Definition at line 375 of file list.h.
 {
         struct list_head *pos = entry2->prev;
         list_del(entry2);
         list_replace(entry1, entry2);
         if (pos == entry1)
                 pos = entry2;
         list_add(entry1, pos);
 }
References list_add(), list_del(), list_replace(), and list_head::prev.