cmp_tool: rdcu_submit_tx
rdcu_submit_tx()
int rdcu_submit_tx (const uint8_t * cmd, uint32_t cmd_size, const uint8_t * data, uint32_t data_size)
submit an rmap command transaction
Parameters
cmd the rmap command
cmd_size the size of the rmap command
data the payload (may be NULL)
data_size the size of the payload
Returns
0 on success, otherwise error
Definition at line 339 of file rdcu_rmap.c.
 {
         /* try to process pending responses */
         rdcu_process_rx();
         if (!rmap_tx)
                 return -1;
         if (RDCU_CONFIG_DEBUG)
                 printf("Transmitting RMAP command\n");
         if (rmap_tx(cmd, cmd_size, dpath_len, data, data_size)) {
                 printf("rmap_tx() returned error!\n");
                 return -1;
         }
         return 0;
 }
References cmd, rmap_pkt::data, dpath_len, RDCU_CONFIG_DEBUG, rdcu_process_rx(), and rmap_tx.
Referenced by rdcu_sync(), and rdcu_sync_data().