cmp_tool: rdcu_rmap_sync_status
rdcu_rmap_sync_status()
int rdcu_rmap_sync_status (void)
get the RDCU <-> ICU mirror RMAP synchronisation status
Returns
0: synchronised, > 0: operations pending
Definition at line 768 of file rdcu_rmap.c.
 {
         /* try to process pending responses */
         rdcu_process_rx();
         return trans_log.pending;
 }
References rdcu_process_rx(), and trans_log.
Referenced by rdcu_sync_sram_mirror_parallel(), rdcu_sync_sram_to_mirror(), and rdcu_syncing().