cmp_tool: rdcu_sync_mirror_to_sram
rdcu_sync_mirror_to_sram()
int rdcu_sync_mirror_to_sram (uint32_t addr, uint32_t size, uint32_t mtu)
sync a range of 32 bit words of the local mirror to the remote SRAM
Parameters
addr and address within the remote SRAM
size the number of bytes to sync
mtu the maximum transport unit per RMAP packet; choose wisely
Note
due to restrictions, the number of bytes and mtu must be a multiple of 4; the address must be aligned to 32-bits as well
Returns
0 on success, otherwise error
Definition at line 2240 of file rdcu_ctrl.c.
 {
         int ret;
         uint32_t sent = 0;
         uint32_t tx_bytes;
         if (mtu & 0x3)
                 return -1;
         if (addr & 0x3)
                 return -1;
         if (size & 0x3)
                 return -1;
         if (addr > RDCU_SRAM_END)
                 return -1;
         if (size > RDCU_SRAM_SIZE)
                 return -1;
         if (addr + size > RDCU_SRAM_START + RDCU_SRAM_SIZE)
                 return -1;
         tx_bytes = size;
         while (tx_bytes >= mtu) {
                 ret = rdcu_sync_data(rdcu_write_cmd_data, addr + sent,
                                      &rdcu->sram[addr + sent], mtu, 0);
                 if (ret > 0)
                         continue;
                 if (ret < 0)
                         return -1;
                 sent     += mtu;
                 tx_bytes -= mtu;
         }
         while (tx_bytes) {
                 ret = rdcu_sync_data(rdcu_write_cmd_data, addr + sent,
                                      &rdcu->sram[addr + sent], tx_bytes, 0);
                 if (ret > 0)
                         continue;
                 if (ret < 0)
                         return -1;
                 tx_bytes = 0;
         }
         return 0;
 }
References rdcu, RDCU_SRAM_END, RDCU_SRAM_SIZE, RDCU_SRAM_START, rdcu_sync_data(), rdcu_write_cmd_data(), and rdcu_mirror::sram.
Referenced by rdcu_compress_data_parallel(), rdcu_inject_edac_error(), and rdcu_transfer_sram().