cmp_tool: rdcu_sync_sram_to_mirror
rdcu_sync_sram_to_mirror()
int rdcu_sync_sram_to_mirror (uint32_t addr, uint32_t size, uint32_t mtu)
sync a range of 32 bit words of the remote SRAM to the local mirror
Parameters
addr an address within the remote SRAM
size the number of bytes to sync
mtu the maximum transport unit per RMAP packet; choose wisely
Note
due to restrictions, the number of bytes and mtu must be a multiple of 4; the address must be aligned to 32-bits as well
Returns
0 on success, otherwise error
Definition at line 2314 of file rdcu_ctrl.c.
 {
         int ret;
         uint32_t recv = 0;
         uint32_t rx_bytes;
         if (mtu & 0x3)
                 return -1;
         if (addr & 0x3)
                 return -1;
         if (size & 0x3)
                 return -1;
         if (addr > RDCU_SRAM_END)
                 return -1;
         if (size > RDCU_SRAM_SIZE)
                 return -1;
         if (addr + size > RDCU_SRAM_START + RDCU_SRAM_SIZE)
                 return -1;
         rx_bytes = size;
         while (rx_bytes >= mtu) {
                 ret = rdcu_sync_data(rdcu_read_cmd_data, addr + recv,
                                      &rdcu->sram[addr + recv], mtu, 1);
 #if 0
                 while (rdcu_rmap_sync_status() > 3)
                         ;
 #endif
                 if (ret > 0)
                         continue;
                 if (ret < 0)
                         return -1;
                 recv     += mtu;
                 rx_bytes -= mtu;
         }
         while (rx_bytes) {
                 ret = rdcu_sync_data(rdcu_read_cmd_data, addr + recv,
                                      &rdcu->sram[addr + recv], rx_bytes, 1);
                 if (ret > 0)
                         continue;
                 if (ret < 0)
                         return -1;
                 rx_bytes = 0;
         }
         return 0;
 }
References rdcu, rdcu_read_cmd_data(), rdcu_rmap_sync_status(), RDCU_SRAM_END, RDCU_SRAM_SIZE, RDCU_SRAM_START, rdcu_sync_data(), and rdcu_mirror::sram.
Referenced by rdcu_inject_edac_error(), rdcu_read_cmp_bitstream(), and rdcu_read_model().