cmp_tool: rdcu_sync
rdcu_sync()
int rdcu_sync (int(*)(uint16_t trans_id, uint8_t *cmd) fn, void * addr, uint32_t data_len)
submit a sync command
Parameters
fn the RDCU command generation function
addr the local address of the corresponding remote address
data_len the length of the data payload (0 for read commands)
Note
data_len must be a multiple of 4
all data is treated (and byte swapped) as 32 bit words
Returns
0 on success, otherwise error
Definition at line 435 of file rdcu_rmap.c.
 {
         int n;
         int slot;
         uint8_t *rmap_cmd;
         if (data_len & 0x3)
                 return -1;
         slot = trans_log_grab_slot(addr);
         if (slot < 0 || slot > UINT16_MAX)
                 return -1;
         /* determine size of command */
         n = fn((uint16_t)slot, NULL);
         if (n <= 0) {
                 printf("Error creating command packet\n");
                 return -1;
         }
         rmap_cmd = (uint8_t *)malloc((size_t)n);
         if (!rmap_cmd) {
                 printf("Error allocating rmap cmd");
                 return -1;
         }
         /* now fill actual command */
         n = fn((uint16_t)slot, rmap_cmd);
         if (n <= 0) {
                 printf("Error creating command packet\n");
                 free(rmap_cmd);
                 return -1;
         }
         /* convert endianness if needed */
 #if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
         if (data_len) {
                 uint32_t i;
                 uint32_t *tmp_buf = alloca(data_len);
                 uint32_t *p = (uint32_t *)addr;
                 for (i = 0; i < (data_len / 4); i++)
                         tmp_buf[i] = cpu_to_be32(p[i]);
                 addr = tmp_buf;
         }
 #endif /* __BYTE_ORDER__ */
         n = rdcu_submit_tx(rmap_cmd, (uint32_t)n, addr, data_len);
         free(rmap_cmd);
         return n;
 }
References rmap_pkt::addr, cpu_to_be32, rmap_pkt::data_len, malloc(), rdcu_submit_tx(), and trans_log_grab_slot().
Referenced by rdcu_sync_adaptive_param1(), rdcu_sync_adaptive_param2(), rdcu_sync_adc_ctrl(), rdcu_sync_adc_status(), rdcu_sync_adc_values(), rdcu_sync_compr_ctrl(), rdcu_sync_compr_data_adaptive_1_size(), rdcu_sync_compr_data_adaptive_2_size(), rdcu_sync_compr_data_buf_len(), rdcu_sync_compr_data_buf_start_addr(), rdcu_sync_compr_data_size(), rdcu_sync_compr_data_start_addr(), rdcu_sync_compr_error(), rdcu_sync_compr_status(), rdcu_sync_compressor_param1(), rdcu_sync_compressor_param2(), rdcu_sync_core_ctrl(), rdcu_sync_data_start_addr(), rdcu_sync_fpga_version(), rdcu_sync_lvds_core_status(), rdcu_sync_lvds_ctrl(), rdcu_sync_model_start_addr(), rdcu_sync_new_model_addr_used(), rdcu_sync_new_model_start_addr(), rdcu_sync_num_samples(), rdcu_sync_rdcu_reset(), rdcu_sync_rdcu_status(), rdcu_sync_rmap_last_err(), rdcu_sync_rmap_no_reply_err_cntrs(), rdcu_sync_rmap_pckt_err_cntrs(), rdcu_sync_samples_used(), rdcu_sync_spw_err_cntrs(), rdcu_sync_spw_link_ctrl(), rdcu_sync_spw_link_status(), rdcu_sync_sram_edac_ctrl(), rdcu_sync_sram_edac_status(), rdcu_sync_used_param1(), and rdcu_sync_used_param2().