cmp_tool: rdcu_sync_data
rdcu_sync_data()
int rdcu_sync_data (int(*)(uint16_t trans_id, uint8_t *cmd, uint32_t addr, uint32_t data_len) fn, uint32_t addr, void * data, uint32_t data_len, int read)
submit a data sync command
Parameters
fn an RDCU data transfer generation function
addr the remote address
data the local data address
data_len the length of the data payload
read 0: write, otherwise read
Returns
0 on success, < 0: error, > 0: retry
Note
this one is a little redundant, but otherwise we'd have a lot of unused parameters on most of the control functions
XXX need a parameter for read...meh...must think of something else
Definition at line 513 of file rdcu_rmap.c.
 {
         int n;
         int slot;
         uint8_t *rmap_cmd;
         rdcu_process_rx();
         slot = trans_log_grab_slot(data);
         if (slot < 0 || slot > UINT16_MAX) {
                 if (RDCU_CONFIG_DEBUG)
                         printf("Error: all slots busy!\n");
                 return 1;
         }
         /* determine size of command */
         n = fn((uint16_t)slot, NULL, addr, data_len);
         if (n <= 0) {
                 printf("Error creating command packet\n");
                 return -1;
         }
         rmap_cmd = (uint8_t *)malloc((size_t)n);
         if (!rmap_cmd) {
                 printf("Error allocating rmap cmd");
                 return -1;
         }
         /* now fill actual command */
         n = fn((uint16_t)slot, rmap_cmd, addr, data_len);
         if (n <= 0) {
                 printf("Error creating command packet\n");
                 free(rmap_cmd);
                 return -1;
         }
         if (read)
                 n = rdcu_submit_tx(rmap_cmd, (uint32_t)n, NULL, 0);
         else
                 n = rdcu_submit_tx(rmap_cmd, (uint32_t)n, data, data_len);
         free(rmap_cmd);
         return n;
 }
References rmap_pkt::addr, rmap_pkt::data, rmap_pkt::data_len, malloc(), RDCU_CONFIG_DEBUG, rdcu_process_rx(), rdcu_submit_tx(), and trans_log_grab_slot().
Referenced by rdcu_sync_mirror_to_sram(), rdcu_sync_sram_mirror_parallel(), and rdcu_sync_sram_to_mirror().