cmp_tool: rdcu_write_sram_16
rdcu_write_sram_16()
int rdcu_write_sram_16 (const uint16_t * buf, uint32_t addr, uint32_t size)
write uint16_t formatted data to the local SRAM mirror. This function is endian-safe.
Parameters
buf the buffer to read from
addr an address within the RDCU SRAM
size the number of bytes read
Returns
the number of bytes written, < 0 on error
Definition at line 1639 of file rdcu_ctrl.c.
 {
         if (!buf)
                 return 0;
         if (size & 0x1)
                 return -1;
         if (addr > RDCU_SRAM_END)
                 return -1;
         if (size > RDCU_SRAM_SIZE)
                 return -1;
         if (addr + size > RDCU_SRAM_START + RDCU_SRAM_SIZE)
                 return -1;
 #if !(__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
         return rdcu_write_sram(buf, addr, size);
 #else
         {
                 uint32_t i;
                 for (i = 0; i < size/sizeof(uint16_t); i++) {
                         uint16_t tmp = cpu_to_be16(buf[i]);
                         memcpy(&rdcu->sram[addr+i*sizeof(tmp)], &tmp, sizeof(tmp));
                 }
         }
         return (int)size; /* lol */
 #endif /* __BYTE_ORDER__ */
 }
References cpu_to_be16, rdcu, RDCU_SRAM_END, RDCU_SRAM_SIZE, RDCU_SRAM_START, rdcu_write_sram(), and rdcu_mirror::sram.
Referenced by rdcu_compress_data_parallel(), and rdcu_transfer_sram().