cmp_tool: rdcu_read_cmd_register_internal
rdcu_read_cmd_register_internal()
static int rdcu_read_cmd_register_internal (uint16_t trans_id, uint8_t * cmd, uint32_t addr) static
generate a read command for an arbitrary register (internal)
Parameters
trans_id a transaction identifier
cmd the command buffer; if NULL, the function returns the needed size
addr the register address
Note
this will configure a multi-address, 4 byte wide read command, because the IWF RMAP core does not support single address read commands
Definition at line 39 of file rdcu_cmd.c.
 {
         return rdcu_gen_cmd(trans_id, cmd, RMAP_READ_ADDR_INC, addr, 4);
 }
References cmd, rdcu_gen_cmd(), and RMAP_READ_ADDR_INC.
Referenced by rdcu_read_cmd_adc_status(), rdcu_read_cmd_adc_values_1(), rdcu_read_cmd_adc_values_2(), rdcu_read_cmd_adc_values_3(), rdcu_read_cmd_adc_values_4(), rdcu_read_cmd_compr_data_adaptive_1_size(), rdcu_read_cmd_compr_data_adaptive_2_size(), rdcu_read_cmd_compr_data_size(), rdcu_read_cmd_compr_data_start_addr(), rdcu_read_cmd_compr_error(), rdcu_read_cmd_compr_status(), rdcu_read_cmd_fpga_version(), rdcu_read_cmd_lvds_core_status(), rdcu_read_cmd_new_model_addr_used(), rdcu_read_cmd_rdcu_status(), rdcu_read_cmd_register(), rdcu_read_cmd_rmap_last_err(), rdcu_read_cmd_rmap_no_reply_err_cntrs(), rdcu_read_cmd_rmap_pckt_err_cntrs(), rdcu_read_cmd_samples_used(), rdcu_read_cmd_spw_err_cntrs(), rdcu_read_cmd_spw_link_status(), rdcu_read_cmd_sram_edac_status(), rdcu_read_cmd_used_param1(), and rdcu_read_cmd_used_param2().