cmp_tool: rdcu_gen_cmd
rdcu_gen_cmd()
int rdcu_gen_cmd (uint16_t trans_id, uint8_t * cmd, uint8_t rmap_cmd_type, uint32_t addr, uint32_t size)
generate an rmap command packet
Parameters
trans_id a transaction identifier
cmd the command buffer; if NULL, the function returns the needed size
rmap_cmd_type the rmap command type of the packet
addr the address to read from or write to
size the number of bytes to read or write
Returns
the size of the command data buffer or 0 on error
Definition at line 376 of file rdcu_rmap.c.
 {
         int n;
         struct rmap_pkt *pkt;
         pkt = rmap_create_packet();
         if (!pkt) {
                 printf("Error creating packet\n");
                 return 0;
         }
         rmap_set_dst(pkt, rdcu_addr);
         rmap_set_src(pkt, icu_addr);
         rmap_set_dest_path(pkt, dpath, dpath_len);
         rmap_set_reply_path(pkt, rpath, rpath_len);
         rmap_set_key(pkt, dst_key);
         rmap_set_cmd(pkt, rmap_cmd_type);
         rmap_set_tr_id(pkt, trans_id);
         rmap_set_data_addr(pkt, addr);
         rmap_set_data_len(pkt, size);
         /* determine header size */
         n = rmap_build_hdr(pkt, NULL);
         if (!cmd || n <= 0) {
                 rmap_erase_packet(pkt);
                 return n;
         }
         memset(cmd, 0, (size_t)n);  /* clear command buffer */
         n = rmap_build_hdr(pkt, cmd);
         rmap_erase_packet(pkt);
         return n;
 }
References rmap_pkt::addr, cmd, dpath, dpath_len, dst_key, icu_addr, rdcu_addr, rmap_build_hdr(), rmap_create_packet(), rmap_erase_packet(), rmap_set_cmd(), rmap_set_data_addr(), rmap_set_data_len(), rmap_set_dest_path(), rmap_set_dst(), rmap_set_key(), rmap_set_reply_path(), rmap_set_src(), rmap_set_tr_id(), rpath, and rpath_len.
Referenced by rdcu_read_cmd_data_internal(), rdcu_read_cmd_register_internal(), rdcu_write_cmd_data_internal(), and rdcu_write_cmd_register_internal().