cmp_tool: rdcu_read_cmd_data
rdcu_read_cmd_data()
int rdcu_read_cmd_data (uint16_t trans_id, uint8_t * cmd, uint32_t addr, uint32_t size)
create a command to read arbitrary data to the RDCU
Parameters
trans_id a transaction identifier
cmd the command buffer; if NULL, the function returns the needed size
addr the address to read from
size the number of bytes to read
Returns
the size of the command data buffer or 0 on error
Note
this will configure a multi-address read command
Definition at line 156 of file rdcu_cmd.c.
 {
         return rdcu_read_cmd_data_internal(trans_id, cmd, addr, size);
 }
References cmd, and rdcu_read_cmd_data_internal().
Referenced by rdcu_sync_sram_mirror_parallel(), and rdcu_sync_sram_to_mirror().