cmp_tool: rdcu_sync_compr_data_buf_len
rdcu_sync_compr_data_buf_len()
int rdcu_sync_compr_data_buf_len (void)
sync the Compressed Data Buffer Length (write only)
Returns
0 on success, otherwise error
Definition at line 2079 of file rdcu_ctrl.c.
 {
         return rdcu_sync(rdcu_write_cmd_compr_data_buf_len,
                          &rdcu->compr_data_buf_len, 4);
 }
References rdcu_mirror::compr_data_buf_len, rdcu, rdcu_sync(), and rdcu_write_cmd_compr_data_buf_len().
Referenced by rdcu_set_compression_register().