cmp_tool: rdcu_write_sram
rdcu_write_sram()
int rdcu_write_sram (const void * buf, uint32_t addr, uint32_t size)
write arbitrary big-endian data to the local SRAM mirror
Parameters
buf the buffer to read from
addr an address within the RDCU SRAM
size the number of bytes read
Returns
the number of bytes written, < 0 on error
Definition at line 1588 of file rdcu_ctrl.c.
 {
         if (!buf)
                 return 0;
         if (addr > RDCU_SRAM_END)
                 return -1;
         if (size > RDCU_SRAM_SIZE)
                 return -1;
         if (addr + size > RDCU_SRAM_START + RDCU_SRAM_SIZE)
                 return -1;
         if (buf)
                 memcpy(&rdcu->sram[addr], buf, size);
         return (int)size; /* lol */
 }
References rdcu, RDCU_SRAM_END, RDCU_SRAM_SIZE, RDCU_SRAM_START, and rdcu_mirror::sram.
Referenced by rdcu_inject_edac_error(), rdcu_write_sram_16(), rdcu_write_sram_32(), and rdcu_write_sram_8().