cmp_tool: rdcu_read_sram
rdcu_read_sram()
int rdcu_read_sram (void * buf, uint32_t addr, uint32_t size)
read data from the local SRAM mirror
Parameters
buf the buffer to read to (if NULL, the required size is returned)
addr an address within the RDCU SRAM
size the number of bytes read
Returns
the number of bytes read, < 0 on error
Definition at line 1559 of file rdcu_ctrl.c.
 {
         if (addr > RDCU_SRAM_END)
                 return -1;
         if (size > RDCU_SRAM_SIZE)
                 return -1;
         if (addr + size > RDCU_SRAM_START + RDCU_SRAM_SIZE)
                 return -1;
         if (buf)
                 memcpy(buf, &rdcu->sram[addr], size);
         return (int)size; /* lol */
 }
References rdcu, RDCU_SRAM_END, RDCU_SRAM_SIZE, RDCU_SRAM_START, and rdcu_mirror::sram.
Referenced by rdcu_compress_data_parallel(), rdcu_inject_edac_error(), rdcu_read_cmp_bitstream(), and rdcu_read_model().