cmp_tool: rdcu_process_rx
rdcu_process_rx()
static int rdcu_process_rx (void) static
n rmap command transaction
Returns
number of packets processed or < 0 on error
Definition at line 229 of file rdcu_rmap.c.
 {
         uint32_t n;
         int cnt = 0;
         uint32_t *local_addr;
         uint8_t *spw_pckt;
         struct rmap_pkt *rp;
         if (!rmap_rx)
                 return -1;
         /* process all pending responses */
         while ((n = rmap_rx(NULL))) {
                 /* we received something, allocate enough space for the packet */
                 spw_pckt = (uint8_t *) malloc(n);
                 if (!spw_pckt) {
                         printf("malloc() for packet failed!\n");
                         return -1;
                 }
                 /* read the packet */
                 n = rmap_rx(spw_pckt);
                 if (!n) {
                         printf("Unknown error in rmap_rx()\n");
                         free(spw_pckt);
                         return -1;
                 }
                 cnt++;
                 if (RDCU_CONFIG_DEBUG)
                         rmap_parse_pkt(spw_pckt);
                 /* convert format */
                 rp = rmap_pkt_from_buffer(spw_pckt, n);
                 free(spw_pckt);
                 if (!rp) {
                         printf("Error converting to RMAP packet\n");
                         continue;
                 }
                 local_addr = trans_log_get_addr(rp->tr_id);
                 if (!local_addr) {
                         printf("Warning: response packet received not in transaction log\n");
                         rmap_erase_packet(rp);
                         continue;
                 }
                 if (rp->data_len & 0x3) {
                         printf("Error: response packet data size is not a multiple of 4, transaction dropped\n");
                         trans_log_release_slot(rp->tr_id);
                         rmap_erase_packet(rp);
                         return -1;
                 }
                 if (rp->data_len) {
                         uint8_t crc8;
                         /* convert endianness in-place if needed */
 #if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
{
                                 uint32_t i, tmp;
                                 for (i = 0; i < rp->data_len; i += sizeof(tmp)) {
                                         memcpy(&tmp, &rp->data[i], sizeof(tmp));
                                         be32_to_cpus(&tmp);
                                         memcpy(&rp->data[i], &tmp, sizeof(tmp));
                                 }
                         }
 #endif /* __BYTE_ORDER__ */
                         crc8 = rmap_crc8(rp->data, rp->data_len);
                         if (crc8 != rp->data_crc) {
                                 printf("Error: data CRC8 mismatch, data invalid or packet truncated. Transaction dropped\n");
                                 trans_log_release_slot(rp->tr_id);
                                 rmap_erase_packet(rp);
                                 return -1;
                         }
                         memcpy(local_addr, rp->data, rp->data_len);
                 }
                 trans_log_release_slot(rp->tr_id);
                 rmap_erase_packet(rp);
         }
         return cnt;
 }
References be32_to_cpus, rmap_pkt::data, rmap_pkt::data_crc, rmap_pkt::data_len, local_addr, malloc(), RDCU_CONFIG_DEBUG, rmap_crc8(), rmap_erase_packet(), rmap_parse_pkt(), rmap_pkt_from_buffer(), rmap_rx, rmap_pkt::tr_id, trans_log_get_addr(), and trans_log_release_slot().
Referenced by rdcu_rmap_sync_status(), rdcu_submit_tx(), and rdcu_sync_data().