cmp_tool: rdcu_write_cmd_register_internal
rdcu_write_cmd_register_internal()
static int rdcu_write_cmd_register_internal (uint16_t trans_id, uint8_t * cmd, uint32_t addr) static
generate a write command for an arbitrary register (internal)
Parameters
trans_id a transaction identifier
cmd the command buffer; if NULL, the function returns the needed size
addr the register address
Returns
the size of the command data buffer or 0 on error
Note
this will configure a multi-address, 4 byte wide write command, because the IWF RMAP core does not support single address write commands with reply and CRC check enabled
Definition at line 62 of file rdcu_cmd.c.
 {
         return rdcu_gen_cmd(trans_id, cmd, RMAP_WRITE_ADDR_INC_VERIFY_REPLY,
                             addr, 4);
 }
References cmd, rdcu_gen_cmd(), and RMAP_WRITE_ADDR_INC_VERIFY_REPLY.
Referenced by rdcu_write_cmd_adaptive_param1(), rdcu_write_cmd_adaptive_param2(), rdcu_write_cmd_adc_ctrl(), rdcu_write_cmd_compr_ctrl(), rdcu_write_cmd_compr_data_buf_len(), rdcu_write_cmd_compr_data_buf_start_addr(), rdcu_write_cmd_compressor_param1(), rdcu_write_cmd_compressor_param2(), rdcu_write_cmd_core_ctrl(), rdcu_write_cmd_data_start_addr(), rdcu_write_cmd_lvds_ctrl(), rdcu_write_cmd_model_start_addr(), rdcu_write_cmd_new_model_start_addr(), rdcu_write_cmd_num_samples(), rdcu_write_cmd_rdcu_reset(), rdcu_write_cmd_register(), rdcu_write_cmd_spw_link_ctrl(), and rdcu_write_cmd_sram_edac_ctrl().