cmp_tool: rdcu_sync_adc_values
rdcu_sync_adc_values()
int rdcu_sync_adc_values (int id)
sync an ADC values register (read only)
Parameters
id the ADC value register id (1-4)
Returns
0 on success, otherwise error
Definition at line 1830 of file rdcu_ctrl.c.
 {
         switch (id) {
         case '1':
                 return rdcu_sync(rdcu_read_cmd_adc_values_1,
                                  &rdcu->adc_values_1, 0);
         case '2':
                 return rdcu_sync(rdcu_read_cmd_adc_values_2,
                                  &rdcu->adc_values_2, 0);
         case '3':
                 return rdcu_sync(rdcu_read_cmd_adc_values_3,
                                  &rdcu->adc_values_3, 0);
         case '4':
                 return rdcu_sync(rdcu_read_cmd_adc_values_4,
                                  &rdcu->adc_values_4, 0);
         default:
                 break;
         }
         return -1;
 }
References rdcu_mirror::adc_values_1, rdcu_mirror::adc_values_2, rdcu_mirror::adc_values_3, rdcu_mirror::adc_values_4, rdcu, rdcu_read_cmd_adc_values_1(), rdcu_read_cmd_adc_values_2(), rdcu_read_cmd_adc_values_3(), rdcu_read_cmd_adc_values_4(), and rdcu_sync().