cmp_tool: bit_read_bits32
bit_read_bits32()
static __inline uint32_t bit_read_bits32 (struct bit_decoder * dec, unsigned int nb_bits) static
same as bit_read_bits32() but only returns 32 bit
Warning
do not read more bits than the local register has unconsumed bits. If you do this, the bit_refill function will return the BIT_OVERFLOW status the next time the register is refilled.
Parameters
dec pointer to a bit_decoder context
nb_bits number of bits to read; only works if 1 <= nb_bits <= 32
Returns
extracted 32 bit value
Definition at line 263 of file read_bitstream.h.
 {
         assert(nb_bits <= 32);
         return (uint32_t)bit_read_bits(dec, nb_bits);
 }
References bit_read_bits().
Referenced by decode_multi(), decode_none(), rice_decoder(), and test_bitstream().