cmp_tool: bit_init_decoder
bit_init_decoder()
static __inline size_t bit_init_decoder (struct bit_decoder * dec, const void * buf, size_t buf_size) static
initialize a bit_decoder
Parameters
dec a pointer to an already allocated bit_decoder structure
buf start address of the bitstream buffer
buf_size size of the bitstream in bytes
Returns
size of stream (== src_size), or zero if a problem is detected
Definition at line 123 of file read_bitstream.h.
 {
         if (buf_size < 1) {
                 memset(dec, 0, sizeof(*dec));
                 dec->bits_consumed = sizeof(dec->bit_container)*8;
                 return 0;
         }
         dec->cursor = (const uint8_t *)buf;
         if (buf_size >= sizeof(dec->bit_container)) {  /* normal case */
                 dec->bits_consumed = 0;
                 dec->bit_container = bit_read_unaligned_64be(dec->cursor);
                 dec->limit_ptr = dec->cursor + buf_size - sizeof(dec->bit_container);
         } else {
                 const uint8_t *ui8_p = (const uint8_t *)(buf);
                 dec->bits_consumed = (unsigned int)(sizeof(dec->bit_container) - buf_size) * 8;
                 dec->bit_container = (uint64_t)ui8_p[0] << 56;
                 switch (buf_size) {
                 case 7:
                         dec->bit_container += (uint64_t)ui8_p[6] <<  8;
                         /* fall-through */
                 case 6:
                         dec->bit_container += (uint64_t)ui8_p[5] << 16;
                         /* fall-through */
                 case 5:
                         dec->bit_container += (uint64_t)ui8_p[4] << 24;
                         /* fall-through */
                 case 4:
                         dec->bit_container += (uint64_t)ui8_p[3] << 32;
                         /* fall-through */
                 case 3:
                         dec->bit_container += (uint64_t)ui8_p[2] << 40;
                         /* fall-through */
                 case 2:
                         dec->bit_container += (uint64_t)ui8_p[1] << 48;
                         /* fall-through */
                 default:
                         break;
                 }
                 dec->bit_container >>= dec->bits_consumed;
                 dec->limit_ptr = dec->cursor;
         }
         return buf_size;
 }
References bit_decoder::bit_container, bit_read_unaligned_64be(), bit_decoder::bits_consumed, bit_decoder::cursor, and bit_decoder::limit_ptr.
Referenced by decompress_background(), decompress_f_fx(), decompress_f_fx_efx(), decompress_f_fx_efx_ncob_ecob(), decompress_f_fx_ncob(), decompress_l_fx(), decompress_l_fx_efx(), decompress_l_fx_efx_ncob_ecob(), decompress_l_fx_ncob(), decompress_offset(), decompress_s_fx(), decompress_s_fx_efx(), decompress_s_fx_efx_ncob_ecob(), decompress_s_fx_ncob(), decompress_smearing(), decompressed_data_internal(), test_bitstream(), test_decode_multi(), test_decode_zero(), test_decompress_imagette_model(), test_golomb_decoder(), test_multi_refill_needed(), test_rice_decoder(), test_unary_decoder(), and test_zero_refill_needed().