cmp_tool: bit_refill
bit_refill()
static __inline int bit_refill (struct bit_decoder * dec) static
refill the local register from the buffer previously set in bit_init_decoder()
Parameters
dec a bitstream decoding context
Note
this function is safe, it guarantees that it does not read beyond initialize buffer
Returns
the status of bit_decoder internal register; BIT_UNFINISHED: internal register is filled with at least 57-bits BIT_END_OF_BUFFER: reached the end of the buffer, only some bits are left in the bitstream BIT_ALL_READ_IN: all bits of the buffer have been consumed BIT_OVERFLOW: more bits have been consumed than contained in the local register
Definition at line 319 of file read_bitstream.h.
 {
         unsigned int const bytes_consumed = dec->bits_consumed >> 3;
         if (dec->bits_consumed > sizeof(dec->bit_container)*8)
                 return BIT_OVERFLOW;
         if (dec->cursor + bytes_consumed < dec->limit_ptr) {
                 /* Advance the pointer by the number of full bytes we consumed */
                 dec->cursor += bytes_consumed;
                 /* Refill the bit container */
                 dec->bit_container = bit_read_unaligned_64be(dec->cursor);
                 /* The number of bits that we have already consumed in the
                  * current byte, excluding the bits that formed a complete byte
                  * and were already processed.
                  */
                 dec->bits_consumed &= 0x7;
                 return BIT_UNFINISHED;
         }
         if (dec->cursor == dec->limit_ptr) {
                 if (dec->bits_consumed == sizeof(dec->bit_container)*8)
                         return BIT_ALL_READ_IN;
                 return BIT_END_OF_BUFFER;
         }
         /* limit_ptr < (cursor + bytes_consumed) < end */
         dec->bits_consumed -= (dec->limit_ptr - dec->cursor)*8;
         dec->cursor = dec->limit_ptr;
         dec->bit_container = bit_read_unaligned_64be(dec->cursor);
         return BIT_END_OF_BUFFER;
 }
References BIT_ALL_READ_IN, bit_decoder::bit_container, BIT_END_OF_BUFFER, BIT_OVERFLOW, bit_read_unaligned_64be(), BIT_UNFINISHED, bit_decoder::bits_consumed, bit_decoder::cursor, and bit_decoder::limit_ptr.
Referenced by decode_multi(), decode_none(), decode_zero(), decompressed_data_internal(), test_bitstream(), test_decode_zero(), test_golomb_decoder(), test_rice_decoder(), and test_unary_decoder().