cmp_tool: bit_consume_bits
bit_consume_bits()
static __inline void bit_consume_bits (struct bit_decoder * dec, unsigned int nb_bits) static
mark next n bits in the local register as consumed
Parameters
dec pointer to a bit_decoder context
nb_bits number of bits to skip
Definition at line 224 of file read_bitstream.h.
 {
         dec->bits_consumed += nb_bits;
 }
References bit_decoder::bits_consumed.
Referenced by bit_read_bits(), bit_read_bits32_sub_1(), golomb_decoder(), test_decode_zero(), and unary_decoder().