cmp_tool: rmap_parse_pkt
rmap_parse_pkt()
void rmap_parse_pkt (uint8_t * pkt)
parse an RMAP packet:
expected format: <logical address> <protocol id> ...
Definition at line 743 of file rmap.c.
 {
         struct rmap_instruction *ri;
         if (pkt[RMAP_PROTOCOL_ID] != RMAP_PROTOCOL_ID) {
                 printf("\nNot an RMAP packet, got %x but expected %x\n",
                        pkt[RMAP_PROTOCOL_ID], RMAP_PROTOCOL_ID);
                 return;
         }
         ri = (struct rmap_instruction *)&pkt[RMAP_INSTRUCTION];
         if (ri->cmd_resp) {
                 printf("This is a command packet\n");
                 if (!rmap_check_status(pkt[RMAP_REPLY_STATUS]))
                         rmap_parse_cmd_pkt(pkt);
         } else {
                 printf("This is a reply packet\n");
                 if (!rmap_check_status(pkt[RMAP_REPLY_STATUS]))
                         rmap_parse_reply_pkt(pkt);
         }
 }
References rmap_instruction::cmd_resp, rmap_check_status(), RMAP_INSTRUCTION, rmap_parse_cmd_pkt(), rmap_parse_reply_pkt(), RMAP_PROTOCOL_ID, and RMAP_REPLY_STATUS.
Referenced by rdcu_process_rx().