cmp_tool: rmap_pkt_from_buffer
rmap_pkt_from_buffer()
struct rmap_pkt* rmap_pkt_from_buffer (uint8_t * buf, uint32_t len)
create an rmap packet from a buffer
Parameters
buf the buffer, with the target path stripped away, i.e. starting with <logical address>, <protocol id>, ...
len the data length of the buffer (in bytes)
Returns
an rmap packet, containing the decoded buffer including any data, NULL on error
Definition at line 487 of file rmap.c.
 {
         size_t n = 0;
         size_t i;
         int min_hdr_size;
         struct rmap_pkt *pkt = NULL;
         if (!buf)
                 goto error;
         if (len < RMAP_HDR_MIN_SIZE_WRITE_REP) {
                 printf("buffer len is smaller than the smallest RMAP packet\n");
                 goto error;
         }
         if (buf[RMAP_PROTOCOL_ID] != RMAP_PROTOCOL_ID) {
                 printf("Not an RMAP packet, got %x but expected %x\n",
                        buf[RMAP_PROTOCOL_ID], RMAP_PROTOCOL_ID);
                 goto error;
         }
         pkt = rmap_create_packet();
         if (!pkt) {
                 printf("Error creating packet\n");
                 goto error;
         }
         pkt->dst         = buf[RMAP_DEST_ADDRESS];
         pkt->proto_id    = buf[RMAP_PROTOCOL_ID];
         pkt->instruction = buf[RMAP_INSTRUCTION];
         pkt->key         = buf[RMAP_CMD_DESTKEY];
         min_hdr_size = rmap_get_min_hdr_size(pkt);
         if (min_hdr_size < 0)
                 goto error;
         if (len < (uint32_t)min_hdr_size) {
                 printf("buffer len is smaller than the contained RMAP packet\n");
                 goto error;
         }
         if (pkt->ri.cmd_resp) {
                 pkt->rpath_len = (pkt->ri.reply_addr_len << 2) & 0xFF;
                 if (len < (uint32_t)min_hdr_size + pkt->rpath_len) {
                         printf("buffer is smaller than the contained RMAP packet\n");
                         goto error;
                 }
                 pkt->rpath = (uint8_t *)malloc(pkt->rpath_len);
                 if (!pkt->rpath)
                         goto error;
                 for (i = 0; i < pkt->rpath_len; i++)
                         pkt->rpath[i] = buf[RMAP_REPLY_ADDR_START + i];
                 n = pkt->rpath_len; /* rpath skip */
         }
         pkt->src   = buf[RMAP_SRC_ADDR + n];
         pkt->tr_id = (((uint16_t)buf[RMAP_TRANS_ID_BYTE0 + n] << 8) & 0xFF00) |
                       (uint16_t)buf[RMAP_TRANS_ID_BYTE1 + n];
         /* commands have a data address */
         if (pkt->ri.cmd_resp) {
                 pkt->addr = ((uint32_t)buf[RMAP_ADDR_BYTE0 + n] << 24) |
                             ((uint32_t)buf[RMAP_ADDR_BYTE1 + n] << 16) |
                             ((uint32_t)buf[RMAP_ADDR_BYTE2 + n] <<  8) |
                              (uint32_t)buf[RMAP_ADDR_BYTE3 + n];
                 n += 4; /* addr skip, extended byte is incorporated in define */
         }
         /* all headers have data length unless they are a write reply */
         if (!(!pkt->ri.cmd_resp && (pkt->ri.cmd & (RMAP_CMD_BIT_WRITE)))) {
                 pkt->data_len = ((uint32_t)buf[RMAP_DATALEN_BYTE0 + n] << 16) |
                                 ((uint32_t)buf[RMAP_DATALEN_BYTE1 + n] <<  8) |
                                  (uint32_t)buf[RMAP_DATALEN_BYTE2 + n];
         }
         pkt->hdr_crc  = buf[RMAP_HEADER_CRC];
         if (pkt->data_len) {
                 size_t pkt_size = RMAP_DATA_START + n + pkt->data_len + 1; /* +1 for data CRC */
                 if (len < pkt_size) {
                         printf("buffer len is smaller than the contained RMAP packet; buf len: %" PRIu32 " bytes vs RMAP: %zu bytes needed\n",
                                 len, pkt_size);
                         goto error;
                 }
                 if (len > pkt_size)
                         printf("warning: the buffer is larger than the included RMAP packet\n");
                 pkt->data = (uint8_t *)malloc(pkt->data_len);
                 if (!pkt->data)
                         goto error;
                 for (i = 0; i < pkt->data_len; i++)
                         pkt->data[i] = buf[RMAP_DATA_START + n + i];
                 /* final byte is data crc */
                 pkt->data_crc = buf[RMAP_DATA_START + n + i];
         }
         return pkt;
 error:
         if (pkt) {
                 free(pkt->data);
                 free(pkt->rpath);
                 free(pkt);
         }
         return NULL;
 }
References rmap_pkt::addr, rmap_instruction::cmd, rmap_instruction::cmd_resp, rmap_pkt::data, rmap_pkt::data_crc, rmap_pkt::data_len, rmap_pkt::dst, rmap_pkt::hdr_crc, rmap_pkt::instruction, rmap_pkt::key, malloc(), rmap_pkt::proto_id, rmap_instruction::reply_addr_len, rmap_pkt::ri, RMAP_ADDR_BYTE0, RMAP_ADDR_BYTE1, RMAP_ADDR_BYTE2, RMAP_ADDR_BYTE3, RMAP_CMD_BIT_WRITE, RMAP_CMD_DESTKEY, rmap_create_packet(), RMAP_DATA_START, RMAP_DATALEN_BYTE0, RMAP_DATALEN_BYTE1, RMAP_DATALEN_BYTE2, RMAP_DEST_ADDRESS, rmap_get_min_hdr_size(), RMAP_HDR_MIN_SIZE_WRITE_REP, RMAP_HEADER_CRC, RMAP_INSTRUCTION, RMAP_PROTOCOL_ID, RMAP_REPLY_ADDR_START, RMAP_SRC_ADDR, RMAP_TRANS_ID_BYTE0, RMAP_TRANS_ID_BYTE1, rmap_pkt::rpath, rmap_pkt::rpath_len, rmap_pkt::src, and rmap_pkt::tr_id.
Referenced by rdcu_process_rx().