cmp_tool: compression_decompression
compression_decompression()
void compression_decompression (struct cmp_cfg * cfg)
compress the given configuration and decompress it afterwards; finally compare the results
Parameters
cfg pointer to a compression configuration
Definition at line 476 of file test_cmp_decmp.c.
 {
         int cmp_size_bits, s, error;
         uint32_t data_size, cmp_data_size, cmp_ent_size;
         struct cmp_entity *ent;
         void *decompressed_data;
         static void *model_of_data;
         void *updated_model = NULL;
         if (!cfg) {
                 free(model_of_data);
                 return;
         }
         TEST_ASSERT_NOT_NULL(cfg);
         TEST_ASSERT_NULL(cfg->icu_output_buf);
         data_size = cmp_cal_size_of_data(cfg->samples, cfg->data_type);
         /* create a compression entity */
         cmp_data_size = cmp_cal_size_of_data(cfg->buffer_length, cfg->data_type);
         cmp_data_size &= ~0x3U; /* the size of the compressed data should be a multiple of 4 */
         TEST_ASSERT_NOT_EQUAL_INT(0, cmp_data_size);
         cmp_ent_size = cmp_ent_create(NULL, cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW, cmp_data_size);
         TEST_ASSERT_NOT_EQUAL_UINT(0, cmp_ent_size);
         ent = malloc(cmp_ent_size); TEST_ASSERT_TRUE(ent);
         cmp_ent_size = cmp_ent_create(ent, cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW, cmp_data_size);
         TEST_ASSERT_NOT_EQUAL_UINT(0, cmp_ent_size);
         /* we put the coompressed data direct into the compression entity */
         cfg->icu_output_buf = cmp_ent_get_data_buf(ent);
         TEST_ASSERT_NOT_NULL(cfg->icu_output_buf);
         /* now compress the data */
         cmp_size_bits = icu_compress_data(cfg);
         TEST_ASSERT(cmp_size_bits > 0);
         /* put the compression parameters in the entity header */
         {
                 /* mock values */
                 uint32_t version_id = ~0U;
                 uint64_t start_time = 32;
                 uint64_t end_time = 42;
                 uint16_t model_id = 0xCAFE;
                 uint8_t model_counter = 0;
                 uint32_t ent_size;
                 ent_size = cmp_ent_build(ent, version_id, start_time, end_time,
                                          model_id, model_counter, cfg, cmp_size_bits);
                 TEST_ASSERT_NOT_EQUAL_UINT(0, ent_size);
                 error = cmp_ent_set_size(ent, ent_size);
                 TEST_ASSERT_FALSE(error);
         }
         /* allocate the buffers for decompression */
         TEST_ASSERT_NOT_EQUAL_INT(0, data_size);
         s = decompress_cmp_entiy(ent, model_of_data, NULL, NULL);
         decompressed_data = malloc((size_t)s); TEST_ASSERT_NOT_NULL(decompressed_data);
         if (model_mode_is_used(cfg->cmp_mode)) {
                 updated_model = malloc(data_size);
                 TEST_ASSERT_NOT_NULL(updated_model);
         }
         /* now we try to decompress the data */
         s = decompress_cmp_entiy(ent, model_of_data, updated_model, decompressed_data);
         TEST_ASSERT_EQUAL_INT(data_size, s);
         TEST_ASSERT_FALSE(memcmp(decompressed_data, cfg->input_buf, data_size));
         if (model_mode_is_used(cfg->cmp_mode)) {
                 TEST_ASSERT_NOT_NULL(updated_model);
                 TEST_ASSERT_NOT_NULL(model_of_data);
                 TEST_ASSERT_FALSE(memcmp(updated_model, cfg->icu_new_model_buf, data_size));
                 memcpy(model_of_data, updated_model, data_size);
         } else { /* non-model mode */
                 /* reset model */
                 free(model_of_data);
                 model_of_data = malloc(data_size);
                 memcpy(model_of_data, decompressed_data, data_size);
         }
         cfg->icu_output_buf = NULL;
         free(ent);
         free(decompressed_data);
         free(updated_model);
 }
References cmp_cfg::buffer_length, cmp_cal_size_of_data(), cmp_ent_build(), cmp_ent_create(), cmp_ent_get_data_buf(), cmp_ent_set_size(), cmp_ent_size, cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, decompress_cmp_entiy(), end_time, icu_compress_data(), cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, malloc(), model_counter, model_id, model_mode_is_used(), cmp_cfg::samples, start_time, and version_id.
Referenced by test_random_compression_decompression().