cmp_tool: test_ent_start_timestamp
test_ent_start_timestamp()
void test_ent_start_timestamp (void)
Test:
cmp_ent_set_start_timestamp
cmp_ent_get_start_timestamp
Definition at line 201 of file test_cmp_entity.c.
 {
         int error;
         struct cmp_entity ent = {0};
         uint64_t start_timestamp;
         uint64_t start_timestamp_read;
         uint32_t coarse_start_timestamp_read;
         uint16_t fine_start_timestamp_read;
         uint8_t *entity_p = (uint8_t *)&ent;
         start_timestamp = 0x123456789ABCULL;
         error = cmp_ent_set_start_timestamp(&ent, start_timestamp);
         TEST_ASSERT_FALSE(error);
         start_timestamp_read = cmp_ent_get_start_timestamp(&ent);
         TEST_ASSERT_EQUAL_UINT64(start_timestamp, start_timestamp_read);
         /* check the right position in the header */
         TEST_ASSERT_EQUAL_HEX(0x12, entity_p[10]);
         TEST_ASSERT_EQUAL_HEX(0x34, entity_p[11]);
         TEST_ASSERT_EQUAL_HEX(0x56, entity_p[12]);
         TEST_ASSERT_EQUAL_HEX(0x78, entity_p[13]);
         TEST_ASSERT_EQUAL_HEX(0x9A, entity_p[14]);
         TEST_ASSERT_EQUAL_HEX(0xBC, entity_p[15]);
         coarse_start_timestamp_read = cmp_ent_get_coarse_start_time(&ent);
         TEST_ASSERT_EQUAL_UINT64(0x12345678, coarse_start_timestamp_read);
         fine_start_timestamp_read = cmp_ent_get_fine_start_time(&ent);
         TEST_ASSERT_EQUAL_UINT64(0x9ABC, fine_start_timestamp_read);
         /* error cases */
         start_timestamp = 0x1000000000000ULL;
         error = cmp_ent_set_start_timestamp(&ent, start_timestamp);
         TEST_ASSERT_TRUE(error);
         error = cmp_ent_set_start_timestamp(NULL, start_timestamp);
         TEST_ASSERT_TRUE(error);
         start_timestamp_read = cmp_ent_get_start_timestamp(NULL);
         TEST_ASSERT_EQUAL_UINT32(0, start_timestamp_read);
 }
References cmp_ent_get_coarse_start_time(), cmp_ent_get_fine_start_time(), cmp_ent_get_start_timestamp(), cmp_ent_set_start_timestamp(), and start_timestamp.