cmp_tool: test_cmp_ent_data_type
test_cmp_ent_data_type()
void test_cmp_ent_data_type (void)
Test:
cmp_ent_set_data_type
cmp_ent_get_data_type
cmp_ent_get_data_type_raw_bit
Definition at line 426 of file test_cmp_entity.c.
 {
         int error;
         struct cmp_entity ent = {0};
         enum cmp_data_type data_type, data_type_read;
         int raw_mode_flag, raw_mode_flag_read;
         uint8_t *entity_p = (uint8_t *)&ent;
         /* test non raw_mode */
         raw_mode_flag = 0;
         data_type = DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE;
         error = cmp_ent_set_data_type(&ent, data_type, raw_mode_flag);
         TEST_ASSERT_FALSE(error);
         data_type_read = cmp_ent_get_data_type(&ent);
         TEST_ASSERT_EQUAL_HEX32(data_type, data_type_read);
         raw_mode_flag_read = cmp_ent_get_data_type_raw_bit(&ent);
         TEST_ASSERT_EQUAL(raw_mode_flag, raw_mode_flag_read);
         /* check the right position in the header */
         TEST_ASSERT_EQUAL_HEX(0, entity_p[22]);
         TEST_ASSERT_EQUAL_HEX(21, entity_p[23]);
         /* test raw_mode */
         raw_mode_flag = 1;
         data_type = DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE;
         error = cmp_ent_set_data_type(&ent, data_type, raw_mode_flag);
         TEST_ASSERT_FALSE(error);
         data_type_read = cmp_ent_get_data_type(&ent);
         TEST_ASSERT_EQUAL_HEX32(data_type, data_type_read);
         raw_mode_flag_read = cmp_ent_get_data_type_raw_bit(&ent);
         TEST_ASSERT_EQUAL(raw_mode_flag, raw_mode_flag_read);
         /* check the right position in the header */
         TEST_ASSERT_EQUAL_HEX(0x80, entity_p[22]);
         TEST_ASSERT_EQUAL_HEX(21, entity_p[23]);
         /* error cases */
         raw_mode_flag = 0;
         data_type = 0x8000;
         error = cmp_ent_set_data_type(&ent, data_type, raw_mode_flag);
         TEST_ASSERT_TRUE(error);
         error = cmp_ent_set_data_type(NULL, data_type, raw_mode_flag);
         TEST_ASSERT_TRUE(error);
         data_type_read = cmp_ent_get_data_type(NULL);
         TEST_ASSERT_EQUAL_UINT32(0, data_type_read);
         raw_mode_flag_read = cmp_ent_get_data_type_raw_bit(NULL);
         TEST_ASSERT_EQUAL_UINT32(0, raw_mode_flag_read);
 }
References cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_set_data_type(), data_type, and DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE.