cmp_tool: test_multi_refill_needed
test_multi_refill_needed()
void test_multi_refill_needed (void)
Test:
decode_multi
Definition at line 850 of file test_decmp.c.
 {
         uint32_t decoded_value = ~0U;
         uint8_t cmp_data[] = {0x7F, 0xFF, 0xFF, 0xFF, 0x7F, 0xFF, 0xFF, 0xF7, 0xFF, 0xFF, 0xFF, 0xFF, 0x00};
         uint32_t cmp_data2[2];
         struct bit_decoder dec = {0};
         struct decoder_setup setup = {0};
         uint32_t spillover = 16;
         uint32_t m = 1;
         int err;
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_ZERO, m, spillover, CMP_LOSSLESS, 32);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(0, decoded_value);
         /* this only works with a 2nd refill */
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, decoded_value);
         /* 2nd refill should fail */
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_TRUE(err);
         /* decoded value smaller that outlier */
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_ZERO, m, spillover, CMP_LOSSLESS, 16);
         cmp_data2[0] = cpu_to_be32(0xFF7FFFFF);
         cmp_data2[1] = cpu_to_be32(0x7FFF8000);
         bit_init_decoder(&dec, cmp_data2, 6); /* bitstream is to short */
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(8, decoded_value);
         /* 2nd refill should fail and outlier small than the outlier trigger */
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(CORRUPTION_DETECTED, err);
 }
References bit_init_decoder(), cmp_data, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, configure_decoder_setup(), CORRUPTION_DETECTED, cpu_to_be32, decoder_setup::dec, and decode_multi().