cmp_tool: test_decode_zero
test_decode_zero()
void test_decode_zero (void)
Test:
decode_zero
Definition at line 645 of file test_decmp.c.
 {
         uint32_t decoded_value = ~0U;
         uint64_t cmp_data = {0x88449FC000800000};
         struct bit_decoder dec = {0};
         struct decoder_setup setup = {0};
         uint32_t spillover = 8;
         int err;
         cpu_to_be64s(&cmp_data);
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_ZERO, 1, spillover, CMP_LOSSLESS, 16);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(0, decoded_value);
         TEST_ASSERT_FALSE(err);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(0x4223, decoded_value);
         TEST_ASSERT_FALSE(err);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(6, decoded_value);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(7, decoded_value);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(0xFFFF, decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         /* error case: read over the cmp_data buffer 1 */
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_TRUE(err);
         /* error case: read over the cmp_data buffer 2 */
         cmp_data = cpu_to_be64(0x0001000000000000); /* 8 encoded > spill_over */
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         bit_consume_bits(&dec, 64);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_TRUE(err);
          /* error case: decoded value larger than the outlier parameter */
         cmp_data = cpu_to_be64(0xFF00000000000000); /* 7 encoded > spill_over */
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_TRUE(err);
         /* this should work */
         cmp_data = cpu_to_be64(0xFE00000000000000); /* 8 encoded > spill_over */
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(6, decoded_value);
         /* error case: value after escape symbol smaller that spillover */
         cmp_data = cpu_to_be64(0x003000000000000); /* 0 encoded + 6 unencoded < spill_over */
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_TRUE(err);
         /* this should work */
         cmp_data = cpu_to_be64(0x004000000000000); /* 0 encoded + 7 unencoded < spill_over */
         bit_init_decoder(&dec, &cmp_data, sizeof(cmp_data));
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(7, decoded_value);
         TEST_ASSERT_FALSE(err);
 }
References bit_consume_bits(), BIT_END_OF_BUFFER, bit_init_decoder(), bit_refill(), cmp_data, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, configure_decoder_setup(), cpu_to_be64, cpu_to_be64s, decoder_setup::dec, and decode_zero().