cmp_tool: test_compress_s_fx_error_cases
test_compress_s_fx_error_cases()
void test_compress_s_fx_error_cases (void)
Test:
compress_s_fx
Definition at line 2983 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_exp_flags = 6;
         uint32_t cmp_par_fx = 2;
         uint32_t spillover_fx = 8;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct s_fx)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct s_fx)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct s_fx *data_p = (struct s_fx *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 3, NULL,
                                                    NULL, (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 21;
         error = cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         TEST_ASSERT_FALSE(error);
         /* test if data are higher than max used bits value */
         data_p[0].fx = 0x200000; /* has more than 21 bits (my_max_used_bits.s_fx) */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         /* compressed data are to small for the compressed_data buffer */
         my_max_used_bits.s_exp_flags = 8;
         my_max_used_bits.s_fx = 32;
         error = cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         TEST_ASSERT_FALSE(error);
         memset(data_to_compress, 0xff, sizeof(data_to_compress));
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, cmp_bits);
         my_max_used_bits.s_exp_flags = 33; /* more than 32 bits are not allowed */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.s_exp_flags = 32;
         my_max_used_bits.s_fx = 33; /* more than 32 bits are not allowed */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_ERROR_SMALL_BUF, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_S_FX, DATA_TYPE_UNKNOWN, s_fx::fx, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::s_exp_flags, and cmp_max_used_bits::s_fx.