cmp_tool: test_support_function_call_NULL
test_support_function_call_NULL()
void test_support_function_call_NULL (void)
Definition at line 4419 of file test_cmp_icu.c.
 {
         struct cmp_cfg cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_DIFF_ZERO, 16, CMP_LOSSLESS);
         TEST_ASSERT_TRUE(cmp_cfg_gen_par_is_invalid(NULL, ICU_CHECK));
         TEST_ASSERT_TRUE(cmp_cfg_gen_par_is_invalid(&cfg, RDCU_CHECK+1));
         TEST_ASSERT_TRUE(cmp_cfg_icu_buffers_is_invalid(NULL));
         TEST_ASSERT_TRUE(cmp_cfg_imagette_is_invalid(NULL, RDCU_CHECK));
         TEST_ASSERT_TRUE(cmp_cfg_fx_cob_is_invalid(NULL));
         TEST_ASSERT_TRUE(cmp_cfg_aux_is_invalid(NULL));
         TEST_ASSERT_TRUE(cmp_cfg_icu_is_invalid(NULL));
         TEST_ASSERT_TRUE(cmp_cfg_fx_cob_get_need_pars(DATA_TYPE_S_FX, NULL));
 }
References cmp_cfg_aux_is_invalid(), cmp_cfg_fx_cob_get_need_pars(), cmp_cfg_fx_cob_is_invalid(), cmp_cfg_gen_par_is_invalid(), cmp_cfg_icu_buffers_is_invalid(), cmp_cfg_icu_create(), cmp_cfg_icu_is_invalid(), cmp_cfg_imagette_is_invalid(), CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, DATA_TYPE_IMAGETTE, DATA_TYPE_S_FX, ICU_CHECK, and RDCU_CHECK.