cmp_tool: test_rdcu_cfg_imagette
test_rdcu_cfg_imagette()
void test_rdcu_cfg_imagette (void)
Test:
rdcu_cfg_imagette
Definition at line 426 of file test_cmp_rdcu_cfg.c.
 {
         int error;
         struct cmp_cfg cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW,
                                              10, CMP_LOSSLESS);
         uint32_t golomb_par, spillover_par, ap1_golomb_par, ap1_spillover_par,
                  ap2_golomb_par, ap2_spillover_par;
         golomb_par = MIN_IMA_GOLOMB_PAR;
         spillover_par = MIN_IMA_SPILL;
         ap1_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap1_spillover_par = MIN_IMA_SPILL;
         ap2_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap2_spillover_par = MIN_IMA_SPILL;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong golomb_par */
         golomb_par = MIN_IMA_GOLOMB_PAR - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         golomb_par = MAX_IMA_GOLOMB_PAR + 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         golomb_par = MAX_IMA_GOLOMB_PAR;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong ap1_golomb_par */
         ap1_golomb_par = MIN_IMA_GOLOMB_PAR - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         ap1_golomb_par = MAX_IMA_GOLOMB_PAR + 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         ap1_golomb_par = MAX_IMA_GOLOMB_PAR;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong ap2_golomb_par */
         cfg.cmp_mode = CMP_MODE_DIFF_ZERO;
         ap2_golomb_par = MIN_IMA_GOLOMB_PAR - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         ap2_golomb_par = MAX_IMA_GOLOMB_PAR + 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         ap2_golomb_par = MAX_IMA_GOLOMB_PAR;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong spillover_par */
         golomb_par = MIN_IMA_GOLOMB_PAR;
         spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         golomb_par = MAX_IMA_GOLOMB_PAR;
         spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         golomb_par = MIN_IMA_GOLOMB_PAR;
         spillover_par = MIN_IMA_SPILL - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         /* this should work */
         golomb_par = MAX_IMA_GOLOMB_PAR;
         spillover_par = cmp_ima_max_spill(golomb_par);
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong ap1_spillover_par */
         ap1_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap1_spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         ap1_golomb_par = MAX_IMA_GOLOMB_PAR;
         ap1_spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         ap1_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap1_spillover_par = MIN_IMA_SPILL - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         /* this should work */
         ap1_golomb_par = MAX_IMA_GOLOMB_PAR;
         ap1_spillover_par = cmp_ima_max_spill(golomb_par);
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* wrong ap2_spillover_par */
         ap2_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap2_spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         ap2_golomb_par = MAX_IMA_GOLOMB_PAR;
         ap2_spillover_par = cmp_ima_max_spill(golomb_par)+1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         ap2_golomb_par = MIN_IMA_GOLOMB_PAR;
         ap2_spillover_par = MIN_IMA_SPILL - 1;
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(1, error);
         /* this should work */
         ap2_golomb_par = MAX_IMA_GOLOMB_PAR;
         ap2_spillover_par = cmp_ima_max_spill(golomb_par);
         error = rdcu_cfg_imagette(&cfg, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par,
                                   ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL(golomb_par, cfg.golomb_par);
         TEST_ASSERT_EQUAL(spillover_par, cfg.spill);
         TEST_ASSERT_EQUAL(ap1_golomb_par, cfg.ap1_golomb_par);
         TEST_ASSERT_EQUAL(ap1_spillover_par, cfg.ap1_spill);
         TEST_ASSERT_EQUAL(ap2_golomb_par, cfg.ap2_golomb_par);
         TEST_ASSERT_EQUAL(ap2_spillover_par, cfg.ap2_spill);
         /* cfg = NULL test */
         error = rdcu_cfg_imagette(NULL, golomb_par, spillover_par,
                                   ap1_golomb_par, ap1_spillover_par, ap2_golomb_par, ap2_spillover_par);
         TEST_ASSERT_EQUAL(-1, error);
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_ima_max_spill(), CMP_LOSSLESS, cmp_cfg::cmp_mode, CMP_MODE_DIFF_ZERO, CMP_MODE_RAW, DATA_TYPE_IMAGETTE, cmp_cfg::golomb_par, MAX_IMA_GOLOMB_PAR, MIN_IMA_GOLOMB_PAR, MIN_IMA_SPILL, rdcu_cfg_create(), rdcu_cfg_imagette(), and cmp_cfg::spill.