cmp_tool: test_compress_f_fx_ncob_error_cases
test_compress_f_fx_ncob_error_cases()
void test_compress_f_fx_ncob_error_cases (void)
Test:
compress_f_fx_ncob
Definition at line 3435 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_fx = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_ncob = 1;
         uint32_t spillover_ncob = 8;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+2*sizeof(struct f_fx_ncob)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct f_fx_ncob)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct f_fx_ncob *data_p = (struct f_fx_ncob *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         my_max_used_bits.f_fx = 31;
         my_max_used_bits.f_ncob = 23;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_NCOB, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 2, NULL, NULL,
                                                    (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         /* compressed data are to small for the compressed_data buffer */
         data_p[0].fx = 42;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, cmp_bits);
         /* value is to big for the max used bits values */
         data_p[0].ncob_x = 0x800000;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].ncob_x = 0x7FFFFF;
         data_p[0].ncob_y = 0x800000;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].ncob_y = 0x7FFFFF;
         my_max_used_bits.f_fx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.f_fx = 32;
         my_max_used_bits.f_ncob = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_ERROR_SMALL_BUF, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_ncob, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_F_FX_NCOB, DATA_TYPE_UNKNOWN, cmp_max_used_bits::f_fx, cmp_max_used_bits::f_ncob, f_fx_ncob::fx, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, f_fx_ncob::ncob_x, and f_fx_ncob::ncob_y.