cmp_tool: test_rdcu_cmp_cfg_is_invalid
test_rdcu_cmp_cfg_is_invalid()
void test_rdcu_cmp_cfg_is_invalid (void)
Test:
rdcu_cmp_cfg_is_invalid
Definition at line 696 of file test_cmp_rdcu_cfg.c.
 {
         int error;
         struct cmp_cfg cfg;
         uint16_t data[1] = {1};
         uint16_t model[1] = {2};
         /* diff test */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_DIFF_CMP_MODE,
                               CMP_DEF_IMA_DIFF_MODEL_VALUE, CMP_DEF_IMA_DIFF_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, data, 1, NULL, CMP_DEF_IMA_DIFF_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_MODEL_ADR, CMP_DEF_IMA_DIFF_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_DIFF_GOLOMB_PAR, CMP_DEF_IMA_DIFF_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_FALSE(error);
         /* model test */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_MODEL_CMP_MODE,
                               CMP_DEF_IMA_MODEL_MODEL_VALUE, CMP_DEF_IMA_MODEL_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, data, 1, model, CMP_DEF_IMA_MODEL_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_MODEL_ADR, CMP_DEF_IMA_MODEL_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_MODEL_GOLOMB_PAR, CMP_DEF_IMA_MODEL_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_FALSE(error);
         /* test warnings */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_MODEL_CMP_MODE,
                               CMP_DEF_IMA_MODEL_MODEL_VALUE, CMP_DEF_IMA_MODEL_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, NULL, 0, NULL, CMP_DEF_IMA_MODEL_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_MODEL_ADR, CMP_DEF_IMA_MODEL_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_MODEL_GOLOMB_PAR, CMP_DEF_IMA_MODEL_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         cfg.icu_new_model_buf = data;
         cfg.icu_output_buf = (void *)model;
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_FALSE(error);
         /* error: cfg is NULL */
         error = rdcu_cmp_cfg_is_invalid(NULL);
         TEST_ASSERT_TRUE(error);
         /* error: buffer length = 0 */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_MODEL_CMP_MODE,
                               CMP_DEF_IMA_MODEL_MODEL_VALUE, CMP_DEF_IMA_MODEL_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, data, 1, model, CMP_DEF_IMA_MODEL_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_MODEL_ADR, CMP_DEF_IMA_MODEL_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_MODEL_RDCU_BUFFER_ADR, 0);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_MODEL_GOLOMB_PAR, CMP_DEF_IMA_MODEL_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_TRUE(error);
         /* error: wrong gen par */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_DIFF_CMP_MODE,
                               MAX_MODEL_VALUE+1, CMP_DEF_IMA_DIFF_LOSSY_PAR);
         cfg.data_type = DATA_TYPE_IMAGETTE;
         error = rdcu_cfg_buffers(&cfg, data, 1, NULL, CMP_DEF_IMA_DIFF_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_MODEL_ADR, CMP_DEF_IMA_DIFF_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_DIFF_GOLOMB_PAR, CMP_DEF_IMA_DIFF_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_TRUE(error);
         /* error: wrong buffers config */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_DIFF_CMP_MODE,
                               CMP_DEF_IMA_DIFF_MODEL_VALUE, CMP_DEF_IMA_DIFF_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, data, 1, NULL, RDCU_SRAM_END+4,
                                  CMP_DEF_IMA_DIFF_RDCU_MODEL_ADR, CMP_DEF_IMA_DIFF_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_TRUE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   CMP_DEF_IMA_DIFF_GOLOMB_PAR, CMP_DEF_IMA_DIFF_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_TRUE(error);
         /* error: wrong compression parameter test */
         cfg = rdcu_cfg_create(DATA_TYPE_IMAGETTE, CMP_DEF_IMA_DIFF_CMP_MODE,
                               CMP_DEF_IMA_DIFF_MODEL_VALUE, CMP_DEF_IMA_DIFF_LOSSY_PAR);
         error = rdcu_cfg_buffers(&cfg, data, 1, NULL, CMP_DEF_IMA_DIFF_RDCU_DATA_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_MODEL_ADR, CMP_DEF_IMA_DIFF_RDCU_UP_MODEL_ADR,
                                  CMP_DEF_IMA_DIFF_RDCU_BUFFER_ADR, 1);
         TEST_ASSERT_FALSE(error);
         error = rdcu_cfg_imagette(&cfg,
                                   MAX_IMA_GOLOMB_PAR+1, CMP_DEF_IMA_DIFF_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR,
                                   CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR);
         TEST_ASSERT_TRUE(error);
         error = rdcu_cmp_cfg_is_invalid(&cfg);
         TEST_ASSERT_TRUE(error);
 }
References CMP_DEF_IMA_DIFF_AP1_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP1_SPILL_PAR, CMP_DEF_IMA_DIFF_AP2_GOLOMB_PAR, CMP_DEF_IMA_DIFF_AP2_SPILL_PAR, CMP_DEF_IMA_DIFF_CMP_MODE, CMP_DEF_IMA_DIFF_GOLOMB_PAR, CMP_DEF_IMA_DIFF_LOSSY_PAR, CMP_DEF_IMA_DIFF_MODEL_VALUE, CMP_DEF_IMA_DIFF_RDCU_BUFFER_ADR, CMP_DEF_IMA_DIFF_RDCU_DATA_ADR, CMP_DEF_IMA_DIFF_RDCU_MODEL_ADR, CMP_DEF_IMA_DIFF_RDCU_UP_MODEL_ADR, CMP_DEF_IMA_DIFF_SPILL_PAR, CMP_DEF_IMA_MODEL_AP1_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP1_SPILL_PAR, CMP_DEF_IMA_MODEL_AP2_GOLOMB_PAR, CMP_DEF_IMA_MODEL_AP2_SPILL_PAR, CMP_DEF_IMA_MODEL_CMP_MODE, CMP_DEF_IMA_MODEL_GOLOMB_PAR, CMP_DEF_IMA_MODEL_LOSSY_PAR, CMP_DEF_IMA_MODEL_MODEL_VALUE, CMP_DEF_IMA_MODEL_RDCU_BUFFER_ADR, CMP_DEF_IMA_MODEL_RDCU_DATA_ADR, CMP_DEF_IMA_MODEL_RDCU_MODEL_ADR, CMP_DEF_IMA_MODEL_RDCU_UP_MODEL_ADR, CMP_DEF_IMA_MODEL_SPILL_PAR, cmp_cfg::data_type, DATA_TYPE_IMAGETTE, cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, MAX_IMA_GOLOMB_PAR, MAX_MODEL_VALUE, rdcu_cfg_buffers(), rdcu_cfg_create(), rdcu_cfg_imagette(), rdcu_cmp_cfg_is_invalid(), and RDCU_SRAM_END.