cmp_tool: malloc
malloc()
void* malloc (size_t size)
Definition at line 40 of file test_cmp_max_used_bits_list.c.
 {
         static void* (*real_malloc)(size_t size) = NULL;
         if(malloc_fail)
                 return NULL;
         if (!real_malloc) {
                 *(void **)(&real_malloc) = dlsym(RTLD_NEXT, "malloc");
                 /* The cast removes a gcc warning https://stackoverflow.com/a/31528674 */
                 TEST_ASSERT_NOT_NULL(real_malloc);
         }
         return real_malloc(size);
 }
References malloc_fail.
Referenced by cmp_max_used_bits_list_add(), compression_decompression(), generate_random_test_data(), rdcu_ctrl_init(), rdcu_process_rx(), rdcu_sync(), rdcu_sync_data(), rmap_pkt_from_buffer(), rmap_set_dest_path(), rmap_set_reply_path(), test_cmp_decmp_n_imagette_raw(), test_cmp_decmp_s_fx_diff(), test_cmp_ent_build(), test_cmp_ent_create(), test_cmp_ent_get_cmp_data(), test_cmp_ent_read_header_error_cases(), test_cmp_ent_write_cmp_pars(), test_cmp_ent_write_rdcu_cmp_pars(), test_compress_imagette_raw(), test_compress_s_fx_model_multi(), test_compress_s_fx_raw(), test_compress_s_fx_staff(), test_random_compression_decompression2(), and test_s_fx_diff().