cmp_tool: test_compress_s_fx_model_multi
test_compress_s_fx_model_multi()
void test_compress_s_fx_model_multi (void)
Definition at line 2876 of file test_cmp_icu.c.
 {
         struct s_fx data[6], model[6];
         struct s_fx *up_model_buf;
         struct cmp_cfg cfg = {0};
         int cmp_size;
         struct multi_entry_hdr *hdr;
         uint32_t *cmp_data;
         struct cmp_max_used_bits my_max_used_bits;
         /* setup configuration */
         cfg.data_type = DATA_TYPE_S_FX;
         cfg.cmp_mode = CMP_MODE_MODEL_MULTI;
         cfg.model_value = 11;
         cfg.samples = 6;
         cfg.input_buf = malloc(cmp_cal_size_of_data(cfg.samples, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.input_buf);
         cfg.model_buf = malloc(cmp_cal_size_of_data(cfg.samples, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.model_buf);
         cfg.icu_new_model_buf = malloc(cmp_cal_size_of_data(cfg.samples, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.icu_new_model_buf);
         cfg.buffer_length = 6;
         cfg.icu_output_buf = malloc(cmp_cal_size_of_data(cfg.buffer_length, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.icu_output_buf);
         cfg.cmp_par_exp_flags = 1;
         cfg.spill_exp_flags = 8;
         cfg.cmp_par_fx = 3;
         cfg.spill_fx = 35;
         /* generate input data */
         hdr = cfg.input_buf;
         /* use dummy data for the header */
         memset(hdr, 0x42, sizeof(struct multi_entry_hdr));
         data[0].exp_flags = 0x0;
         data[0].fx = 0x0;
         data[1].exp_flags = 0x1;
         data[1].fx = 0x1;
         data[2].exp_flags = 0x2;
         data[2].fx = 0x23;
         data[3].exp_flags = 0x3;
         data[3].fx = 0x42;
         data[4].exp_flags = 0x0;
         data[4].fx = 0x001FFFFF;
         data[5].exp_flags = 0x0;
         data[5].fx = 0x0;
         memcpy(hdr->entry, data, sizeof(data));
         /* generate model data */
         hdr = cfg.model_buf;
         /* use dummy data for the header */
         memset(hdr, 0x41, sizeof(struct multi_entry_hdr));
         model[0].exp_flags = 0x0;
         model[0].fx = 0x0;
         model[1].exp_flags = 0x3;
         model[1].fx = 0x1;
         model[2].exp_flags = 0x0;
         model[2].fx = 0x42;
         model[3].exp_flags = 0x0;
         model[3].fx = 0x23;
         model[4].exp_flags = 0x3;
         model[4].fx = 0x0;
         model[5].exp_flags = 0x2;
         model[5].fx = 0x001FFFFF;
         memcpy(hdr->entry, model, sizeof(model));
         my_max_used_bits = MAX_USED_BITS_SAFE;
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 21;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(166, cmp_size);
         TEST_ASSERT_FALSE(memcmp(cfg.input_buf, cfg.icu_output_buf, MULTI_ENTRY_HDR_SIZE));
         cmp_data = &cfg.icu_output_buf[MULTI_ENTRY_HDR_SIZE/sizeof(uint32_t)];
         TEST_ASSERT_EQUAL_HEX(0x1C77FFA6, be32_to_cpu(cmp_data[0]));
         TEST_ASSERT_EQUAL_HEX(0xAFFF4DE5, be32_to_cpu(cmp_data[1]));
         TEST_ASSERT_EQUAL_HEX(0xCC000000, be32_to_cpu(cmp_data[2]));
         hdr = cfg.icu_new_model_buf;
         up_model_buf = (struct s_fx *)hdr->entry;
         TEST_ASSERT_FALSE(memcmp(hdr, cfg.icu_output_buf, MULTI_ENTRY_HDR_SIZE));
         TEST_ASSERT_EQUAL_HEX(0x0, up_model_buf[0].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x0, up_model_buf[0].fx);
         TEST_ASSERT_EQUAL_HEX(0x2, up_model_buf[1].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x1, up_model_buf[1].fx);
         TEST_ASSERT_EQUAL_HEX(0x0, up_model_buf[2].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x38, up_model_buf[2].fx);
         TEST_ASSERT_EQUAL_HEX(0x0, up_model_buf[3].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x2C, up_model_buf[3].fx);
         TEST_ASSERT_EQUAL_HEX(0x2, up_model_buf[4].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x9FFFF, up_model_buf[4].fx);
         TEST_ASSERT_EQUAL_HEX(0x1, up_model_buf[5].exp_flags);
         TEST_ASSERT_EQUAL_HEX(0x15FFFF, up_model_buf[5].fx);
         free(cfg.input_buf);
         free(cfg.model_buf);
         free(cfg.icu_new_model_buf);
         free(cfg.icu_output_buf);
 }
References be32_to_cpu, cmp_cfg::buffer_length, cmp_cal_size_of_data(), cmp_cfg_icu_max_used_bits(), cmp_data, cmp_cfg::cmp_mode, CMP_MODE_MODEL_MULTI, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::data_type, DATA_TYPE_S_FX, multi_entry_hdr::entry, exp_flags, s_fx::exp_flags, fx, s_fx::fx, icu_compress_data(), cmp_cfg::icu_new_model_buf, cmp_cfg::icu_output_buf, cmp_cfg::input_buf, malloc(), MAX_USED_BITS_SAFE, cmp_cfg::model_buf, cmp_cfg::model_value, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::s_exp_flags, cmp_max_used_bits::s_fx, cmp_cfg::samples, cmp_cfg::spill_exp_flags, and cmp_cfg::spill_fx.