cmp_tool: test_golomb_decoder
test_golomb_decoder()
void test_golomb_decoder (void)
Test:
golomb_decoder
Definition at line 389 of file test_decmp.c.
 {
         struct bit_decoder dec;
         uint32_t bitstream;
         unsigned int m;
         unsigned int log2_m;
         uint32_t decoded_cw;
         /* m = 1 test */
         m = 1;
         log2_m = ilog_2(m);
         bitstream = 0;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(1, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(0x7FFFFFFF); /* 0b0111...11 */
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(1, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(0x80000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be32(0xFFFFFFFE);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(31, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = 0xFFFFFFFF;
         golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         /* m = 2 test */
         m = 2;
         log2_m = ilog_2(m);
         bitstream = 0;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(0x40000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be32(0xFFFFFFFC);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(60, decoded_cw);
         bitstream = cpu_to_be32(0xFFFFFFFD);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(61, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be32(0xFFFFFFFE);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         /* m = 3 test */
         m = 3;
         log2_m = ilog_2(m);
         bitstream = 0;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(0x40000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(3, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be32(0x60000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(3, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(2, decoded_cw);
         bitstream = cpu_to_be32(0x80000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(3, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(3, decoded_cw);
         bitstream = cpu_to_be32(0xA0000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(4, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(4, decoded_cw);
         bitstream = cpu_to_be32(0xFFFFFFFB);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(89, decoded_cw);
         bitstream = cpu_to_be32(0xFFFFFFFC);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(90, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be32(0xFFFFFFFD);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         /* m = 0x7FFFFFFF test */
         m = 0x7FFFFFFF;
         log2_m = ilog_2(m);
         bitstream = 0;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(31, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(0x2);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be32(0x7FFFFFFF);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0x7FFFFFFE, decoded_cw);
         bitstream = cpu_to_be32(0x80000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0x7FFFFFFF, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be32(0X80000001);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         /* m = 0x80000000 test */
         m = 0x80000000;
         log2_m = ilog_2(m);
         bitstream = 0;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be32(1);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be32(0x7FFFFFFE);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0x7FFFFFFE, decoded_cw);
         bitstream = cpu_to_be32(0x7FFFFFFD);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL(0x7FFFFFFD, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be32(0x80000000);
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed-32);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
 #if 0
         this case is prevented by an assert
         /* test log_2 to big */
         bitstream = 0x00000000;
         bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         log2_m = 33;
         decoded_cw = golomb_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(0, dec.bits_consumed-32);
 #endif
 }
References bit_init_decoder(), BIT_OVERFLOW, bit_refill(), bit_decoder::bits_consumed, cpu_to_be32, golomb_decoder(), ilog_2(), and MAX_VALID_CW_LEM.