cmp_tool: test_rice_decoder
test_rice_decoder()
void test_rice_decoder (void)
Test:
rice_decoder
Definition at line 222 of file test_decmp.c.
 {
         struct bit_decoder dec;
         uint64_t bitstream;
         uint32_t m, log2_m, decoded_cw;
         size_t buf_size;
         /* log2_m = 0 test */
         log2_m = 0; m = 1U << log2_m;
         bitstream = 0;
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(1, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be64(0x7FFFFFFFFFFFFFFF); /* 0b0111...11 */
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(1, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be64(0x8000000000000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be64(0xFFFFFFFE00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(31, decoded_cw);
         bitstream = cpu_to_be64(0xFFFFFFFFFFFFFFFE);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(64, dec.bits_consumed);
         TEST_ASSERT_EQUAL(63, decoded_cw);
         TEST_ASSERT_EQUAL_INT(BIT_ALL_READ_IN, bit_refill(&dec));
         bitstream = cpu_to_be64(0xFFFFFFFF00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(33, dec.bits_consumed);
         TEST_ASSERT_EQUAL(32, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be64(0xFFFFFFFFFFFFFFFF);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = unary_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(65, dec.bits_consumed);
         TEST_ASSERT_EQUAL(64, decoded_cw);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         /* log2_m = 1 test */
         log2_m = 1; m = 1U << log2_m;
         bitstream = 0;
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be64(0x4000000000000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(2, dec.bits_consumed);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be64(0xFFFFFFFC00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(60, decoded_cw);
         bitstream = cpu_to_be64(0xFFFFFFFD00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(61, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be64(0xFFFFFFFE00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(33, dec.bits_consumed);
         TEST_ASSERT_EQUAL(62, decoded_cw);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed);
         /* log2_m = 31 test */
         log2_m = 31; m = 1U << log2_m;
         bitstream = 0;
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0, decoded_cw);
         bitstream = cpu_to_be64(0x0000000100000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(1, decoded_cw);
         bitstream = cpu_to_be64(0x7FFFFFFE00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0X7FFFFFFE, decoded_cw);
         bitstream = cpu_to_be64(0x7FFFFFFD00000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_EQUAL(32, dec.bits_consumed);
         TEST_ASSERT_EQUAL(0X7FFFFFFD, decoded_cw);
         /* invalid code word (longer than 32 bit) */
         bitstream = cpu_to_be64(0x8000000000000000);
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         TEST_ASSERT_EQUAL_size_t(sizeof(bitstream), buf_size);
         rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed);
 #if 0
 /* this case is prevented by an assert */
         /* test log_2 to big */
         log2_m = 32; m = 1 << log2_m;
         bitstream = 0x00000000;
         buf_size = bit_init_decoder(&dec, &bitstream, sizeof(bitstream));
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed);
         bitstream = cpu_to_be32(0xE000000000000000);
         log2_m = 33; m = 1 << log2_m;
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed);
         log2_m = UINT_MAX; m = 1 << log2_m;
         decoded_cw = rice_decoder(&dec, m, log2_m);
         TEST_ASSERT_GREATER_THAN_UINT(MAX_VALID_CW_LEM, dec.bits_consumed);
 #endif
 }
References BIT_ALL_READ_IN, bit_init_decoder(), BIT_OVERFLOW, bit_refill(), bit_decoder::bits_consumed, cpu_to_be32, cpu_to_be64, MAX_VALID_CW_LEM, rice_decoder(), and unary_decoder().