cmp_tool: test_compress_imagette_diff
test_compress_imagette_diff()
void test_compress_imagette_diff (void)
Test:
compress_imagette
Definition at line 2325 of file test_cmp_icu.c.
 {
         uint16_t data[] = {0xFFFF, 1, 0, 42, 0x8000, 0x7FFF, 0xFFFF};
         uint32_t output_buf[3] = {0xFFFF, 0xFFFF, 0xFFFF};
         uint32_t output_buf_size;
         struct cmp_cfg cfg = {0};
         int error, cmp_size;
         uint32_t golomb_par = 1;
         uint32_t spill = 8;
         uint32_t samples = 7;
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_DIFF_ZERO,
                                  CMP_PAR_UNUSED, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         output_buf_size = cmp_cfg_icu_buffers(&cfg, data, samples, NULL, NULL,
                                               (uint32_t *)output_buf, samples);
         TEST_ASSERT_EQUAL_INT(samples*sizeof(uint16_t), output_buf_size);
         error = cmp_cfg_icu_imagette(&cfg, golomb_par, spill);
         TEST_ASSERT_FALSE(error);
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(66, cmp_size);
         TEST_ASSERT_EQUAL_HEX(0xDF6002AB, be32_to_cpu(output_buf[0]));
         TEST_ASSERT_EQUAL_HEX(0xFEB70000, be32_to_cpu(output_buf[1]));
         TEST_ASSERT_EQUAL_HEX(0x00000000, be32_to_cpu(output_buf[2]));
         /* test: icu_output_buf = NULL */
         cfg.icu_output_buf = NULL;
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(66, cmp_size);
 }
References be32_to_cpu, cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_imagette(), CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, cmp_cfg::golomb_par, icu_compress_data(), cmp_cfg::icu_output_buf, cmp_cfg::samples, and cmp_cfg::spill.