cmp_tool: test_cmp_ent_read_header_error_cases
test_cmp_ent_read_header_error_cases()
void test_cmp_ent_read_header_error_cases (void)
Test:
cmp_ent_read_header
Definition at line 1812 of file test_decmp.c.
 {
         int error;
         uint32_t size;
         struct cmp_entity *ent;
         struct cmp_cfg cfg;
         /* create a entity */
         size = cmp_ent_create(NULL, DATA_TYPE_IMAGETTE, 1, 10);
         TEST_ASSERT_EQUAL_UINT32(sizeof(struct cmp_entity), size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, DATA_TYPE_IMAGETTE, 1, 10);
         TEST_ASSERT_EQUAL_UINT32(sizeof(struct cmp_entity), size);
         /* ent = NULL */
         error = cmp_ent_read_header(NULL, &cfg);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_FALSE(error);
         /* cfg = NULL */
         error = cmp_ent_read_header(ent, NULL);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_FALSE(error);
         /* unknown data type */
         cmp_ent_set_data_type(ent, DATA_TYPE_UNKNOWN, 1);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_TRUE(error);
         cmp_ent_set_data_type(ent, (enum cmp_data_type)1000, 1);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_TRUE(error);
         /* unknown data type */
         cmp_ent_set_data_type(ent, DATA_TYPE_F_CAM_BACKGROUND+1, 1);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         cmp_ent_set_data_type(ent, DATA_TYPE_IMAGETTE, 1);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_FALSE(error);
         /* cmp_mode CMP_MODE_RAW and no raw data bit */
         cmp_ent_set_data_type(ent, DATA_TYPE_IMAGETTE, 0);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         cmp_ent_set_data_type(ent, DATA_TYPE_IMAGETTE, 1);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_FALSE(error);
         /* original_size and data product type not compatible */
         cmp_ent_set_original_size(ent, 11);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_TRUE(error);
         /* this should work */
         cmp_ent_set_original_size(ent, 12);
         error = cmp_ent_read_header(ent, &cfg);
         TEST_ASSERT_FALSE(error);
         free(ent);
 }
References cmp_ent_create(), cmp_ent_read_header(), cmp_ent_set_data_type(), cmp_ent_set_original_size(), DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, and malloc().