cmp_tool: test_unary_decoder
test_unary_decoder()
void test_unary_decoder (void)
Test:
unary_decoder
Definition at line 124 of file test_decmp.c.
 {
         uint32_t leading_ones;
         struct bit_decoder dec;
         uint32_t unused_1 = 0;
         uint32_t unused_2 = 0;
         uint32_t value;
         size_t ret;
         value = 0;
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(0, leading_ones);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(0, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         value = be32_to_cpu(0x7FFFFFFF);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(0, leading_ones);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(31, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         value = be32_to_cpu(0x80000000);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(1, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(0, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         value = be32_to_cpu(0xBFFFFFFF);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(1, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(30, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         value = be32_to_cpu(0xFFFF0000);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(16, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         value = be32_to_cpu(0xFFFF7FFF);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(16, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, bit_refill(&dec));
         value = be32_to_cpu(0xFFFFFFFE);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(31, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_ALL_READ_IN, bit_refill(&dec));
         value = be32_to_cpu(0xFFFFFFFF);
         ret = bit_init_decoder(&dec, &value, sizeof(value));
         TEST_ASSERT_EQUAL_size_t(sizeof(value), ret);
         leading_ones = unary_decoder(&dec, unused_1, unused_2);
         TEST_ASSERT_EQUAL_INT(32, leading_ones);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
         {
                 uint64_t value64 = ~0ULL;
                 ret = bit_init_decoder(&dec, &value64, sizeof(value64));
                 TEST_ASSERT_EQUAL_size_t(sizeof(value64), ret);
                 leading_ones = unary_decoder(&dec, unused_1, unused_2);
                 TEST_ASSERT_EQUAL_INT(64, leading_ones);
                 TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec));
                 value64 = be64_to_cpu(0xFFFFFFFF00000000);
                 ret = bit_init_decoder(&dec, &value64, sizeof(value64));
                 TEST_ASSERT_EQUAL_size_t(sizeof(value64), ret);
                 leading_ones = unary_decoder(&dec, unused_1, unused_2);
                 TEST_ASSERT_EQUAL_INT(32, leading_ones);
                 /* TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, bit_refill(&dec)); */
         }
 }
References be32_to_cpu, be64_to_cpu, BIT_ALL_READ_IN, BIT_END_OF_BUFFER, bit_init_decoder(), BIT_OVERFLOW, bit_refill(), and unary_decoder().