cmp_tool: test_cmp_decmp_s_fx_diff
test_cmp_decmp_s_fx_diff()
void test_cmp_decmp_s_fx_diff (void)
Definition at line 1086 of file test_decmp.c.
 {
         size_t s;
         int err, decmp_size;
         struct cmp_entity *ent;
         const uint32_t MAX_VALUE = ~(~0U << MAX_USED_BITS_V1.s_fx);
         struct s_fx data_entry[DATA_SAMPLES];
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE + sizeof(data_entry)];
         struct s_fx *decompressed_data = NULL;
         uint32_t compressed_data_len_samples = DATA_SAMPLES;
         struct cmp_cfg cfg;
         data_entry[0].exp_flags = 0;
         data_entry[0].fx = 0;
         data_entry[1].exp_flags = 1;
         data_entry[1].fx = 23;
         data_entry[2].exp_flags = 2;
         data_entry[2].fx = 42;
         data_entry[3].exp_flags = 3;
         data_entry[3].fx = MAX_VALUE;
         data_entry[4].exp_flags = 3;
         data_entry[4].fx = MAX_VALUE>>1;
         for (s = 0; s < MULTI_ENTRY_HDR_SIZE; s++)
                 data_to_compress[s] = (uint8_t)s;
         memcpy(&data_to_compress[MULTI_ENTRY_HDR_SIZE], data_entry, sizeof(data_entry));
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX, CMP_MODE_DIFF_MULTI,
                                  CMP_PAR_UNUSED, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         s = cmp_cfg_icu_buffers(&cfg, data_to_compress, DATA_SAMPLES, NULL, NULL,
                                 NULL, compressed_data_len_samples);
         TEST_ASSERT_TRUE(s);
         err = cmp_cfg_fx_cob(&cfg, 2, 6, 4, 14, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                              CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                              CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(err);
         s = icu_compress_data_entity(NULL, &cfg);
         TEST_ASSERT_TRUE(s);
         ent = malloc(s); TEST_ASSERT_TRUE(ent);
         s = icu_compress_data_entity(ent, &cfg);
         TEST_ASSERT_TRUE(s);
         /* now decompress the data */
         decmp_size = decompress_cmp_entiy(ent, NULL, NULL, decompressed_data);
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(cfg.samples, cfg.data_type), decmp_size);
         decompressed_data = malloc((size_t)decmp_size); TEST_ASSERT_TRUE(decompressed_data);
         decmp_size = decompress_cmp_entiy(ent, NULL, NULL, decompressed_data);
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(cfg.samples, cfg.data_type), decmp_size);
         TEST_ASSERT_EQUAL_HEX8_ARRAY(data_to_compress, decompressed_data, decmp_size);
         /* TEST_ASSERT_FALSE(memcmp(data_to_compress, decompressed_data, (size_t)decmp_size)); */
         /* for (i = 0; i < samples; ++i) { */
         /*      printf("%u == %u (round: %u)\n", data[i], decompressed_data[i], round); */
         /*      uint32_t mask = ~0U << round; */
         /*      if ((data[i]&mask) != (decompressed_data[i]&mask)) */
         /*              TEST_ASSERT(0); */
         /*      if (model_mode_is_used(cmp_mode)) */
         /*              if (up_model[i] != de_up_model[i]) */
         /*                      TEST_ASSERT(0); */
         /* } */
         free(ent);
         free(decompressed_data);
 }
References cmp_cal_size_of_data(), cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, CMP_PAR_UNUSED, DATA_SAMPLES, cmp_cfg::data_type, DATA_TYPE_S_FX, DATA_TYPE_UNKNOWN, decompress_cmp_entiy(), s_fx::exp_flags, s_fx::fx, icu_compress_data_entity(), malloc(), MAX_USED_BITS_V1, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::s_fx, and cmp_cfg::samples.