cmp_tool: generate_random_test_data
generate_random_test_data()
void* generate_random_test_data (uint32_t samples, enum cmp_data_type data_type, const struct cmp_max_used_bits * max_used_bits)
generate random test data
Parameters
samples number of random test samples
data_type compression data type of the test data
max_used_bits pointer to a max_used_bits structure
Returns
a pointer to the generated random test data
Definition at line 323 of file test_cmp_decmp.c.
 {
         size_t data_size = cmp_cal_size_of_data(samples, data_type);
         void *data = malloc(data_size);
         void *data_cpy = data;
         uint8_t *p = data;
         TEST_ASSERT_NOT_EQUAL_INT(data_size, 0);
         TEST_ASSERT(data_size < (CMP_ENTITY_MAX_SIZE - NON_IMAGETTE_HEADER_SIZE));
         TEST_ASSERT_NOT_NULL(data);
         if (!rdcu_supported_data_type_is_used(data_type)) {
                 int i;
                 TEST_ASSERT(data_size > MULTI_ENTRY_HDR_SIZE);
                 for (i = 0; i < MULTI_ENTRY_HDR_SIZE; ++i)
                         *p++ = (uint8_t)cmp_rand32();
                 data = p;
         }
         switch (data_type) {
         case DATA_TYPE_IMAGETTE:
         case DATA_TYPE_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_SAT_IMAGETTE:
         case DATA_TYPE_SAT_IMAGETTE_ADAPTIVE:
         case DATA_TYPE_F_CAM_IMAGETTE:
         case DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE:
                 gen_ima_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_OFFSET:
                 gen_nc_offset_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_BACKGROUND:
                 gen_nc_background_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_SMEARING:
                 gen_smearing_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_S_FX:
                 gen_s_fx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_S_FX_EFX:
                 gen_s_fx_efx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_S_FX_NCOB:
                 gen_s_fx_ncob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_S_FX_EFX_NCOB_ECOB:
                 gen_s_fx_efx_ncob_ecob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_L_FX:
                 gen_l_fx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_L_FX_EFX:
                 gen_l_fx_efx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_L_FX_NCOB:
                 gen_l_fx_ncob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_L_FX_EFX_NCOB_ECOB:
                 gen_l_fx_efx_ncob_ecob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_FX:
                 gen_f_fx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_FX_EFX:
                 gen_f_fx_efx_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_FX_NCOB:
                 gen_f_fx_ncob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_FX_EFX_NCOB_ECOB:
                 gen_f_fx_efx_ncob_ecob_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_CAM_OFFSET:
                 gen_fc_offset_data(data, samples, max_used_bits);
                 break;
         case DATA_TYPE_F_CAM_BACKGROUND:
                 gen_fc_background_data(data, samples, max_used_bits);
                 break;
         default:
                 TEST_FAIL();
         }
         return data_cpy;
 }
References cmp_cal_size_of_data(), CMP_ENTITY_MAX_SIZE, cmp_rand32(), data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_OFFSET, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, DATA_TYPE_SAT_IMAGETTE, DATA_TYPE_SAT_IMAGETTE_ADAPTIVE, DATA_TYPE_SMEARING, gen_f_fx_data(), gen_f_fx_efx_data(), gen_f_fx_efx_ncob_ecob_data(), gen_f_fx_ncob_data(), gen_fc_background_data(), gen_fc_offset_data(), gen_ima_data(), gen_l_fx_data(), gen_l_fx_efx_data(), gen_l_fx_efx_ncob_ecob_data(), gen_l_fx_ncob_data(), gen_nc_background_data(), gen_nc_offset_data(), gen_s_fx_data(), gen_s_fx_efx_data(), gen_s_fx_efx_ncob_ecob_data(), gen_s_fx_ncob_data(), gen_smearing_data(), malloc(), MULTI_ENTRY_HDR_SIZE, NON_IMAGETTE_HEADER_SIZE, and rdcu_supported_data_type_is_used().
Referenced by test_random_compression_decompression().