cmp_tool: test_cmp_ent_create
test_cmp_ent_create()
void test_cmp_ent_create (void)
Test:
cmp_ent_create
error cases
Definition at line 1684 of file test_cmp_entity.c.
 {
         uint32_t size;
         struct cmp_entity *ent;
         enum cmp_data_type data_type;
         int raw_mode_flag;
         uint32_t cmp_size_byte;
         /* create a empty compression entity */
         data_type = DATA_TYPE_IMAGETTE;
         raw_mode_flag = 0;
         cmp_size_byte = 0;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(sizeof(struct cmp_entity), size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(sizeof(struct cmp_entity), size);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_IMAGETTE, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_lossy_cmp_par(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_ima_spill(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_ima_golomb_par(ent));
         free(ent);
         /* create a compression entity */
         data_type = DATA_TYPE_IMAGETTE;
         raw_mode_flag = 0;
         cmp_size_byte = 100;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(IMAGETTE_HEADER_SIZE + cmp_size_byte, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(IMAGETTE_HEADER_SIZE + cmp_size_byte, size);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_IMAGETTE, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(100, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_lossy_cmp_par(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_ima_spill(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_ima_golomb_par(ent));
         free(ent);
         /* create a raw compression entity */
         data_type = DATA_TYPE_SMEARING;
         raw_mode_flag = 1;
         cmp_size_byte = 100;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(GENERIC_HEADER_SIZE + cmp_size_byte, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(GENERIC_HEADER_SIZE + cmp_size_byte, size);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_SMEARING, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(1, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(100, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_lossy_cmp_par(ent));
         free(ent);
         /** error cases **/
         /* unknown data type */
         data_type = DATA_TYPE_UNKNOWN;
         raw_mode_flag = 1;
         cmp_size_byte = 100;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(0, size);
         data_type = 0xFFF;
         raw_mode_flag = 1;
         cmp_size_byte = 100;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(0, size);
         /* cmp_size_byte to high */
         data_type = DATA_TYPE_S_FX;
         raw_mode_flag = 0;
         cmp_size_byte = CMP_ENTITY_MAX_SIZE+1;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(0, size);
         cmp_size_byte = CMP_ENTITY_MAX_SIZE;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(0, size);
         /* this should work */
         cmp_size_byte = CMP_ENTITY_MAX_SIZE - NON_IMAGETTE_HEADER_SIZE;
         size = cmp_ent_create(NULL, data_type, raw_mode_flag, cmp_size_byte);
         TEST_ASSERT_EQUAL_UINT32(NON_IMAGETTE_HEADER_SIZE + cmp_size_byte, size);
 }
References cmp_ent_create(), cmp_ent_get_cmp_data_size(), cmp_ent_get_cmp_mode(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), cmp_ent_get_lossy_cmp_par(), cmp_ent_get_max_used_bits_version(), cmp_ent_get_model_value(), cmp_ent_get_original_size(), CMP_ENTITY_MAX_SIZE, data_type, DATA_TYPE_IMAGETTE, DATA_TYPE_S_FX, DATA_TYPE_SMEARING, DATA_TYPE_UNKNOWN, GENERIC_HEADER_SIZE, IMAGETTE_HEADER_SIZE, malloc(), and NON_IMAGETTE_HEADER_SIZE.