cmp_tool: icu_compress_data_entity
icu_compress_data_entity()
size_t icu_compress_data_entity (struct cmp_entity * ent, const struct cmp_cfg * cfg)
returns the needed size of the compression entry header plus the max size of the compressed data if ent == NULL if ent is set the size of the compression entry (entity header + compressed data)
Definition at line 948 of file test_decmp.c.
 {
         uint32_t s;
         struct cmp_cfg cfg_cpy;
         int cmp_size_bits;
         if (!cfg)
                 return 0;
         if (cfg->icu_output_buf)
                 debug_print("Warning the set buffer for the compressed data is ignored! The compressed data are write to the compression entry.");
         s = cmp_cal_size_of_data(cfg->buffer_length, cfg->data_type);
         if (!s)
                 return 0;
         /* we round down to the next 4-byte allied address because we access the
          * cmp_buffer in uint32_t words
          */
         if (cfg->cmp_mode != CMP_MODE_RAW)
                 s &= ~0x3U;
         s = cmp_ent_create(ent, cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW, s);
         if (!ent || !s)
                 return s;
         cfg_cpy = *cfg;
         cfg_cpy.icu_output_buf = cmp_ent_get_data_buf(ent);
         if (!cfg_cpy.icu_output_buf)
                 return 0;
         cmp_size_bits = icu_compress_data(&cfg_cpy);
         if (cmp_size_bits < 0)
                 return 0;
         /* XXX overwrite the size of the compression entity with the size of the actual
          * size of the compressed data; not all allocated memory is normally used */
         s = cmp_ent_create(ent, cfg->data_type, cfg->cmp_mode == CMP_MODE_RAW,
                            cmp_bit_to_byte((unsigned int)cmp_size_bits));
         if (cmp_ent_write_cmp_pars(ent, cfg, cmp_size_bits))
                 return 0;
         return s;
 }
References cmp_cfg::buffer_length, cmp_bit_to_byte(), cmp_cal_size_of_data(), cmp_ent_create(), cmp_ent_get_data_buf(), cmp_ent_write_cmp_pars(), cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_cfg::data_type, debug_print, icu_compress_data(), and cmp_cfg::icu_output_buf.
Referenced by test_cmp_decmp_s_fx_diff().