cmp_tool: test_ent_end_timestamp
test_ent_end_timestamp()
void test_ent_end_timestamp (void)
Test:
cmp_ent_set_end_timestamp
cmp_ent_get_end_timestamp
Definition at line 313 of file test_cmp_entity.c.
 {
         int error;
         struct cmp_entity ent = {0};
         uint64_t end_timestamp;
         uint64_t end_timestamp_read;
         uint32_t coarse_end_timestamp_read;
         uint16_t fine_end_timestamp_read;
         uint8_t *entity_p = (uint8_t *)&ent;
         end_timestamp   = 0x123456789ABCULL;
         error = cmp_ent_set_end_timestamp(&ent, end_timestamp);
         TEST_ASSERT_FALSE(error);
         end_timestamp_read = cmp_ent_get_end_timestamp(&ent);
         TEST_ASSERT_EQUAL_HEX64(end_timestamp, end_timestamp_read);
         /* check the right position in the header */
         TEST_ASSERT_EQUAL_HEX(0x12, entity_p[16]);
         TEST_ASSERT_EQUAL_HEX(0x34, entity_p[17]);
         TEST_ASSERT_EQUAL_HEX(0x56, entity_p[18]);
         TEST_ASSERT_EQUAL_HEX(0x78, entity_p[19]);
         TEST_ASSERT_EQUAL_HEX(0x9A, entity_p[20]);
         TEST_ASSERT_EQUAL_HEX(0xBC, entity_p[21]);
         coarse_end_timestamp_read = cmp_ent_get_coarse_end_time(&ent);
         TEST_ASSERT_EQUAL_UINT64(0x12345678, coarse_end_timestamp_read);
         fine_end_timestamp_read = cmp_ent_get_fine_end_time(&ent);
         TEST_ASSERT_EQUAL_UINT64(0x9ABC, fine_end_timestamp_read);
         /* error cases */
         end_timestamp = 0x1000000000000ULL;
         error = cmp_ent_set_end_timestamp(&ent, end_timestamp);
         TEST_ASSERT_TRUE(error);
         error = cmp_ent_set_end_timestamp(NULL, end_timestamp);
         TEST_ASSERT_TRUE(error);
         end_timestamp_read = cmp_ent_get_end_timestamp(NULL);
         TEST_ASSERT_EQUAL_UINT32(0, end_timestamp_read);
 }
References cmp_ent_get_coarse_end_time(), cmp_ent_get_end_timestamp(), cmp_ent_get_fine_end_time(), cmp_ent_set_end_timestamp(), and end_timestamp.