cmp_tool: test_select_decoder
test_select_decoder()
void test_select_decoder (void)
Test:
select_decoder
Definition at line 611 of file test_decmp.c.
 {
         decoder_ptr decoder;
         uint32_t golomb_par;
         golomb_par = 1;
         decoder = select_decoder(golomb_par);
         TEST_ASSERT_EQUAL(unary_decoder, decoder);
         golomb_par = 0x80000000;
         decoder = select_decoder(golomb_par);
         TEST_ASSERT_EQUAL(rice_decoder, decoder);
         golomb_par = 3;
         decoder = select_decoder(golomb_par);
         TEST_ASSERT_EQUAL(golomb_decoder, decoder);
         golomb_par = 0x7FFFFFFF;
         decoder = select_decoder(golomb_par);
         TEST_ASSERT_EQUAL(golomb_decoder, decoder);
 #if 0
 this case is prevented by an assert
         golomb_par = 0;
         decoder = select_decoder(golomb_par);
         TEST_ASSERT_EQUAL(NULL, decoder);
 #endif
 }
References golomb_decoder(), rice_decoder(), select_decoder(), and unary_decoder().