cmp_tool: test_cmp_max_used_bits_list
test_cmp_max_used_bits_list()
void test_cmp_max_used_bits_list (void)
Test:
cmp_max_used_bits_list_add
cmp_max_used_bits_list_get
cmp_max_used_bits_list_delet
cmp_max_used_bits_list_empty
Definition at line 64 of file test_cmp_max_used_bits_list.c.
 {
         struct cmp_max_used_bits i_32, i_34, i_35, i_36, i_255, i_0;
         const struct cmp_max_used_bits *p;
         int return_val;
         /* set up max_used_bits item */
         memset(&i_32, 32, sizeof(struct cmp_max_used_bits));
         i_32.version = 32;
         memset(&i_34, 34, sizeof(struct cmp_max_used_bits));
         i_34.version = 34;
         memset(&i_35, 35, sizeof(struct cmp_max_used_bits));
         i_35.version = 35;
         memset(&i_36, 36, sizeof(struct cmp_max_used_bits));
         i_36.version = 36;
         memset(&i_255, 0xFF, sizeof(struct cmp_max_used_bits));
         i_255.version = 255;
         memset(&i_0, 0, sizeof(struct cmp_max_used_bits));
         i_0.version = 0;
         return_val = cmp_max_used_bits_list_add(&i_32);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         return_val = cmp_max_used_bits_list_add(&i_34);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         return_val = cmp_max_used_bits_list_add(&i_35);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         return_val = cmp_max_used_bits_list_add(&i_36);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         return_val = cmp_max_used_bits_list_add(&i_255);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         /* error cases */
         return_val = cmp_max_used_bits_list_add(NULL);
         TEST_ASSERT_EQUAL_INT(return_val, -1);
         return_val = cmp_max_used_bits_list_add(&i_0);
         TEST_ASSERT_EQUAL_INT(return_val, -1);
         i_0.version = CMP_MAX_USED_BITS_RESERVED_VERSIONS-1;
         return_val = cmp_max_used_bits_list_add(&i_0);
         TEST_ASSERT_EQUAL_INT(return_val, -1);
         p = cmp_max_used_bits_list_get(32);
         TEST_ASSERT_EQUAL_INT(p->version, 32);
         TEST_ASSERT(!memcmp(p, &i_32, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(36);
         TEST_ASSERT_EQUAL_INT(p->version, 36);
         TEST_ASSERT(!memcmp(p, &i_36, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(35);
         TEST_ASSERT_EQUAL_INT(p->version, 35);
         TEST_ASSERT(!memcmp(p, &i_35, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(255);
         TEST_ASSERT_EQUAL_INT(p->version, 255);
         TEST_ASSERT(!memcmp(p, &i_255, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(34);
         TEST_ASSERT_EQUAL_INT(p->version, 34);
         TEST_ASSERT(!memcmp(p, &i_34, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(0);
         TEST_ASSERT_EQUAL_INT(p->version, 0);
         TEST_ASSERT(!memcmp(p, &MAX_USED_BITS_SAFE, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(1);
         TEST_ASSERT_EQUAL_INT(p->version, 1);
         TEST_ASSERT(!memcmp(p, &MAX_USED_BITS_V1, sizeof(struct cmp_max_used_bits)));
         /* Try to get an element that is not in the list */
         p = cmp_max_used_bits_list_get(42);
         TEST_ASSERT_NULL(p);
         p = cmp_max_used_bits_list_get(3);
         TEST_ASSERT_NULL(p);
         /* overwrite a list item */
         memset(&i_35, 0x42, sizeof(struct cmp_max_used_bits));
         i_35.version = 35;
         return_val = cmp_max_used_bits_list_add(&i_35);
         TEST_ASSERT_EQUAL_INT(return_val, 1);
         p = cmp_max_used_bits_list_get(35);
         TEST_ASSERT_EQUAL_INT(p->version, 35);
         TEST_ASSERT(!memcmp(p, &i_35, sizeof(struct cmp_max_used_bits)));
         /* delete item */
         cmp_max_used_bits_list_delet(35);
         p = cmp_max_used_bits_list_get(35);
         TEST_ASSERT_NULL(p);
         cmp_max_used_bits_list_delet(34);
         p = cmp_max_used_bits_list_get(34);
         TEST_ASSERT_NULL(p);
         /* empty item */
         cmp_max_used_bits_list_empty();
         p = cmp_max_used_bits_list_get(36);
         TEST_ASSERT_NULL(p);
         cmp_max_used_bits_list_empty();
         p = cmp_max_used_bits_list_get(34);
         TEST_ASSERT_NULL(p);
         p = cmp_max_used_bits_list_get(0);
         TEST_ASSERT_EQUAL_INT(p->version, 0);
         TEST_ASSERT(!memcmp(p, &MAX_USED_BITS_SAFE, sizeof(struct cmp_max_used_bits)));
         p = cmp_max_used_bits_list_get(1);
         TEST_ASSERT_EQUAL_INT(p->version, 1);
         TEST_ASSERT(!memcmp(p, &MAX_USED_BITS_V1, sizeof(struct cmp_max_used_bits)));
         return_val = cmp_max_used_bits_list_add(&i_36);
         TEST_ASSERT_EQUAL_INT(return_val, 0);
         p = cmp_max_used_bits_list_get(36);
         TEST_ASSERT_EQUAL_INT(p->version, 36);
         TEST_ASSERT(!memcmp(p, &i_36, sizeof(struct cmp_max_used_bits)));
         cmp_max_used_bits_list_empty();
         /* error case */
 #if !defined(__sparc__) && !defined(_WIN32) && !defined(_WIN64)
         malloc_fail = 1;
         return_val = cmp_max_used_bits_list_add(&i_36);
         TEST_ASSERT_EQUAL_INT(return_val, -1);
         malloc_fail = 0;
 #endif
 }
References cmp_max_used_bits_list_add(), cmp_max_used_bits_list_delet(), cmp_max_used_bits_list_empty(), cmp_max_used_bits_list_get(), CMP_MAX_USED_BITS_RESERVED_VERSIONS, malloc_fail, MAX_USED_BITS_SAFE, MAX_USED_BITS_V1, and cmp_max_used_bits::version.