cmp_tool: test_compress_imagette_model
test_compress_imagette_model()
void test_compress_imagette_model (void)
Test:
compress_imagette
Definition at line 2364 of file test_cmp_icu.c.
 {
         uint16_t data[]  = {0x0000, 0x0001, 0x0042, 0x8000, 0x7FFF, 0xFFFF, 0xFFFF};
         uint16_t model[] = {0x0000, 0xFFFF, 0xF301, 0x8FFF, 0x0000, 0xFFFF, 0x0000};
         uint16_t model_up[7] = {0};
         uint32_t output_buf[3] = {~0U, ~0U, ~0U};
         uint32_t output_buf_size;
         struct cmp_cfg cfg = {0};
         uint32_t model_value = 8;
         uint32_t samples = 7;
         uint32_t buffer_length = 8;
         uint32_t golomb_par = 3;
         uint32_t spill = 8;
         int cmp_size, error;
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_MODEL_MULTI,
                                  model_value, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         output_buf_size = cmp_cfg_icu_buffers(&cfg, data, samples, model, model_up,
                                               output_buf, buffer_length);
         TEST_ASSERT_EQUAL_INT(buffer_length*sizeof(uint16_t), output_buf_size);
         error = cmp_cfg_icu_imagette(&cfg, golomb_par, spill);
         TEST_ASSERT_FALSE(error);
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(76, cmp_size);
         TEST_ASSERT_EQUAL_HEX(0x2BDB4F5E, be32_to_cpu(output_buf[0]));
         TEST_ASSERT_EQUAL_HEX(0xDFF5F9FF, be32_to_cpu(output_buf[1]));
         TEST_ASSERT_EQUAL_HEX(0xEC200000, be32_to_cpu(output_buf[2]));
         TEST_ASSERT_EQUAL_HEX(0x0000, model_up[0]);
         TEST_ASSERT_EQUAL_HEX(0x8000, model_up[1]);
         TEST_ASSERT_EQUAL_HEX(0x79A1, model_up[2]);
         TEST_ASSERT_EQUAL_HEX(0x87FF, model_up[3]);
         TEST_ASSERT_EQUAL_HEX(0x3FFF, model_up[4]);
         TEST_ASSERT_EQUAL_HEX(0xFFFF, model_up[5]);
         TEST_ASSERT_EQUAL_HEX(0x7FFF, model_up[6]);
         /* error case: model mode without model data */
         cfg.model_buf = NULL; /* this is the error */
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL(-1, cmp_size);
 }
References be32_to_cpu, cmp_cfg::buffer_length, cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_imagette(), CMP_LOSSLESS, CMP_MODE_MODEL_MULTI, cmp_cfg::data_type, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, cmp_cfg::golomb_par, icu_compress_data(), cmp_cfg::model_buf, cmp_cfg::model_value, cmp_cfg::samples, and cmp_cfg::spill.