cmp_tool: test_compress_s_fx_efx_ncob_ecob_error_cases
test_compress_s_fx_efx_ncob_ecob_error_cases()
void test_compress_s_fx_efx_ncob_ecob_error_cases (void)
Test:
compress_s_fx_efx_ncob_ecob
Definition at line 3206 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = 3;
         uint32_t spillover_exp_flags = 6;
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_ncob = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_ncob = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         uint32_t cmp_par_efx = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_efx =  cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         uint32_t cmp_par_ecob = 23;
         uint32_t spillover_ecob = cmp_icu_max_spill(23);
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct s_fx_efx_ncob_ecob)] = {0};
         uint8_t model_data[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct s_fx_efx_ncob_ecob)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct s_fx_efx_ncob_ecob)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct s_fx_efx_ncob_ecob *data_p = (struct s_fx_efx_ncob_ecob *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_EFX_NCOB_ECOB, CMP_MODE_MODEL_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob,
                                spillover_ncob, cmp_par_efx, spillover_efx,
                                cmp_par_ecob, spillover_ecob, CMP_PAR_UNUSED, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 3, model_data,
                                                    NULL, (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 21;
         my_max_used_bits.s_ncob = 31;
         my_max_used_bits.s_efx = 23;
         my_max_used_bits.s_ecob = 7;
         error = cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         TEST_ASSERT_FALSE(error);
         /* the compressed_data buffer is to small */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, cmp_bits);
         /* test if data are higher than max used bits value */
         data_p[2].exp_flags = 0x4;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].exp_flags = 0x3;
         data_p[2].fx = 0x200000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].fx = 0x1FFFFF;
         data_p[1].ncob_x = 0x80000000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ncob_x = 0x7FFFFFFF;
         data_p[1].ncob_y = 0x80000000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ncob_y = 0x7FFFFFFF;
         data_p[1].efx = 0x800000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].efx = 0x7FFFFF;
         data_p[1].ecob_y = 0x80;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ecob_y = 0x7F;
         /* error case exp_flag */
         my_max_used_bits.s_exp_flags = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case fx */
         my_max_used_bits.s_exp_flags = 32;
         my_max_used_bits.s_fx = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case efx */
         my_max_used_bits.s_fx = 32;
         my_max_used_bits.s_ncob = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.s_ncob = 32;
         my_max_used_bits.s_efx = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.s_efx = 32;
         my_max_used_bits.s_ecob = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.s_ecob = 32;
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_ERROR_SMALL_BUF, cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_MODEL_ZERO, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_ncob, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_UNKNOWN, s_fx_efx_ncob_ecob::ecob_y, s_fx_efx_ncob_ecob::efx, s_fx_efx_ncob_ecob::exp_flags, s_fx_efx_ncob_ecob::fx, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, s_fx_efx_ncob_ecob::ncob_x, s_fx_efx_ncob_ecob::ncob_y, cmp_max_used_bits::s_ecob, cmp_max_used_bits::s_efx, cmp_max_used_bits::s_exp_flags, cmp_max_used_bits::s_fx, and cmp_max_used_bits::s_ncob.