cmp_tool: test_bitstream
test_bitstream()
void test_bitstream (void)
Definition at line 33 of file test_decmp.c.
 {
         uint8_t i, data[12];
         struct bit_decoder dec;
         size_t ret;
         int status;
         uint32_t read_bits;
         for (i = 0; i < sizeof(data); ++i)
                 data[i] = i;
         ret = bit_init_decoder(&dec, data, sizeof(data));
         TEST_ASSERT_EQUAL_size_t(sizeof(data), ret);
         read_bits = bit_read_bits32(&dec, 31);
         TEST_ASSERT_EQUAL_HEX32(0x00010203>>1, read_bits);
         TEST_ASSERT_EQUAL_INT(31, dec.bits_consumed);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_UNFINISHED, status);
         TEST_ASSERT_EQUAL_INT(7, dec.bits_consumed);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_UNFINISHED, status);
         TEST_ASSERT_EQUAL_INT(7, dec.bits_consumed);
         TEST_ASSERT_FALSE(bit_end_of_stream(&dec));
         read_bits = bit_read_bits32(&dec, 32);
         TEST_ASSERT_EQUAL_HEX32(0x82028303, read_bits);
         TEST_ASSERT_EQUAL_INT(39, dec.bits_consumed);
         read_bits = bit_read_bits32(&dec, 1);
         TEST_ASSERT_EQUAL_HEX32(1, read_bits);
         TEST_ASSERT_EQUAL_INT(40, dec.bits_consumed);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, status);
         TEST_ASSERT_EQUAL_INT(32, dec.bits_consumed);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_END_OF_BUFFER, status);
         TEST_ASSERT_EQUAL_INT(32,dec.bits_consumed);
         TEST_ASSERT_FALSE(bit_end_of_stream(&dec));
         read_bits = bit_read_bits32(&dec, 32);
         TEST_ASSERT_EQUAL_HEX32(0x08090A0B, read_bits);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_ALL_READ_IN, status);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_ALL_READ_IN, status);
         TEST_ASSERT_TRUE(bit_end_of_stream(&dec));
         bit_read_bits32(&dec, 1);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, status);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, status);
         TEST_ASSERT_FALSE(bit_end_of_stream(&dec));
         bit_read_bits(&dec, 57);
         status = bit_refill(&dec);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, status);
         bit_read_bits(&dec, 57);
         bit_read_bits(&dec, 57);
         bit_read_bits(&dec, 57);
         bit_read_bits(&dec, 57);
         TEST_ASSERT_EQUAL_INT(BIT_OVERFLOW, status);
         {
                 uint8_t k, j;
                 uint8_t buf[9];
                 size_t s;
                 for (k = 0; k < 8; k++) {
                         memset(data, 0, sizeof(data));
                         for (j = 0; j < k; j++)
                                 buf[j] = j;
                         s = bit_init_decoder(&dec, buf, j);
                         TEST_ASSERT_EQUAL_size_t(j, s);
                         for (j = 0; j < k; j++)
                                 TEST_ASSERT_EQUAL_UINT(j, bit_read_bits(&dec, 8));
                         TEST_ASSERT_TRUE(bit_end_of_stream(&dec));
                         TEST_ASSERT_EQUAL_INT(BIT_ALL_READ_IN, bit_refill(&dec));
                 }
         }
 }
References BIT_ALL_READ_IN, BIT_END_OF_BUFFER, bit_end_of_stream(), bit_init_decoder(), BIT_OVERFLOW, bit_read_bits(), bit_read_bits32(), bit_refill(), BIT_UNFINISHED, and bit_decoder::bits_consumed.