cmp_tool: test_encode_value_multi
test_encode_value_multi()
void test_encode_value_multi (void)
Test:
encode_value_multi
Definition at line 2120 of file test_cmp_icu.c.
 {
         uint32_t data, model;
         int stream_len;
         struct encoder_setupt setup = {0};
         uint32_t bitstream[4] = {0};
         /* setup the setup */
         setup.encoder_par1 = 1;
         setup.encoder_par2 = ilog_2(setup.encoder_par1);
         setup.spillover_par = 16;
         setup.max_data_bits = 32;
         setup.generate_cw_f = golomb_encoder;
         setup.bitstream_adr = bitstream;
         setup.max_stream_len = sizeof(bitstream) * CHAR_BIT;
         stream_len = 0;
         data = 0; model = 0;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(1, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[3]);
         data = 0; model = 1;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(3, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x40000000, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[3]);
         data = 1+23; model = 0+23;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(6, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x58000000, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[3]);
         /* highest value without multi outlier encoding */
         data = 0+42; model = 8+42;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(22, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x5BFFF800, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[3]);
         /* lowest value with multi outlier encoding */
         data = 8+42; model = 0+42;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(41, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x5BFFFBFF, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0xFC000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[3]);
         /* highest value with multi outlier encoding */
         data = (uint32_t)INT32_MIN; model = 0;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(105, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x5BFFFBFF, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0xFC7FFFFF, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0xFF7FFFFF, bitstream[2]);
         TEST_ASSERT_EQUAL_HEX(0xF7800000, bitstream[3]);
         /* small buffer error */
         data = 0; model = 38;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, stream_len);
         /* small buffer error when creating the multi escape symbol*/
         bitstream[0] = 0;
         bitstream[1] = 0;
         setup.max_stream_len = 32;
         stream_len = 32;
         data = 31; model = 0;
         stream_len = encode_value_multi(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, stream_len);
         TEST_ASSERT_EQUAL_HEX(0, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0, bitstream[1]);
 }
References encoder_setupt::bitstream_adr, CMP_ERROR_SMALL_BUF, encode_value_multi(), encoder_setupt::encoder_par1, encoder_setupt::encoder_par2, encoder_setupt::generate_cw_f, golomb_encoder(), ilog_2(), encoder_setupt::max_data_bits, encoder_setupt::max_stream_len, and encoder_setupt::spillover_par.