cmp_tool: test_random_compression_decompression
test_random_compression_decompression()
void test_random_compression_decompression (void)
random compression decompression test
We generate random data and compress them with random parameters. After that we put the data in a compression entity. We decompress the compression entity and compare the decompressed data with the original data.
Test:
icu_compress_data
decompress_cmp_entiy
Definition at line 578 of file test_cmp_decmp.c.
 {
         enum cmp_data_type data_type;
         enum cmp_mode cmp_mode;
         struct cmp_cfg cfg;
         uint32_t cmp_buffer_size;
         for (data_type = 1; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 /* printf("%s\n", data_type2string(data_type)); */
                 /* generate random data*/
                 uint32_t samples = cmp_rand_between(1, 430179/CMP_BUFFER_FAKTOR);
                 uint32_t model_value = cmp_rand_between(0, MAX_MODEL_VALUE);
                 void *data_to_compress1 = generate_random_test_data(samples, data_type, &MAX_USED_BITS_V1);
                 void *data_to_compress2 = generate_random_test_data(samples, data_type, &MAX_USED_BITS_V1);
                 void *updated_model = calloc(1, cmp_cal_size_of_data(samples, data_type));
                 /* for (cmp_mode = CMP_MODE_RAW; cmp_mode <= CMP_MODE_STUFF; cmp_mode++) { */
                 for (cmp_mode = CMP_MODE_RAW; cmp_mode <= CMP_MODE_DIFF_MULTI; cmp_mode++) {
                         /* printf("cmp_mode: %i\n", cmp_mode); */
                         cfg = cmp_cfg_icu_create(data_type, cmp_mode, model_value,
                                                  CMP_LOSSLESS);
                         TEST_ASSERT_NOT_EQUAL_INT(cfg.data_type, DATA_TYPE_UNKNOWN);
                         generate_random_cmp_par(&cfg);
                         if (!model_mode_is_used(cmp_mode))
                                 cmp_buffer_size = cmp_cfg_icu_buffers(&cfg, data_to_compress1,
                                         samples, NULL, NULL, NULL, samples*CMP_BUFFER_FAKTOR);
                         else
                                 cmp_buffer_size = cmp_cfg_icu_buffers(&cfg, data_to_compress2,
                                         samples, data_to_compress1, updated_model, NULL, samples*CMP_BUFFER_FAKTOR);
                         TEST_ASSERT_EQUAL_UINT(cmp_buffer_size, cmp_cal_size_of_data(CMP_BUFFER_FAKTOR*samples, data_type));
                         compression_decompression(&cfg);
                 }
                 free(data_to_compress1);
                 free(data_to_compress2);
                 free(updated_model);
         }
         compression_decompression(NULL);
 }
References CMP_BUFFER_FAKTOR, cmp_cal_size_of_data(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, CMP_MODE_RAW, cmp_rand_between(), compression_decompression(), data_type, cmp_cfg::data_type, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_UNKNOWN, generate_random_cmp_par(), generate_random_test_data(), MAX_MODEL_VALUE, MAX_USED_BITS_V1, model_mode_is_used(), cmp_cfg::model_value, and cmp_cfg::samples.