cmp_tool: test_compress_background_error_cases
test_compress_background_error_cases()
void test_compress_background_error_cases (void)
Test:
compress_background
Definition at line 4085 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_mean = 1;
         uint32_t spillover_mean = 2;
         uint32_t cmp_par_variance = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_variance = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         uint32_t cmp_par_pixels_error = 23;
         uint32_t spillover_pixels_error = 42;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct background)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct background)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct background *data_p = (struct background *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_BACKGROUND, CMP_MODE_DIFF_MULTI, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 3, NULL, NULL,
                                                    (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.nc_background_mean = 1;
         my_max_used_bits.nc_background_variance = 31;
         my_max_used_bits.nc_background_outlier_pixels = 2;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         /* value is to big for the max used bits values */
         data_p[0].mean = 0x2;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].mean = 0x1;
         data_p[1].variance = 0x80000000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].variance = 0x80000000-1;
         data_p[1].outlier_pixels = 0x4;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].outlier_pixels = 0x3;
         my_max_used_bits.nc_background_mean = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.nc_background_mean = 32;
         my_max_used_bits.nc_background_variance = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.nc_background_variance = 32;
         my_max_used_bits.nc_background_outlier_pixels = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         cfg.data_type = DATA_TYPE_F_CAM_BACKGROUND;
         my_max_used_bits.fc_background_mean = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.fc_background_mean = 32;
         my_max_used_bits.fc_background_variance = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.fc_background_variance = 32;
         my_max_used_bits.fc_background_outlier_pixels = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_aux(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_UNKNOWN, cmp_max_used_bits::fc_background_mean, cmp_max_used_bits::fc_background_outlier_pixels, cmp_max_used_bits::fc_background_variance, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, background::mean, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::nc_background_mean, cmp_max_used_bits::nc_background_outlier_pixels, cmp_max_used_bits::nc_background_variance, background::outlier_pixels, and background::variance.