cmp_tool: test_cmp_cfg_aux
test_cmp_cfg_aux()
void test_cmp_cfg_aux (void)
Test:
cmp_cfg_aux
Definition at line 1071 of file test_cmp_icu.c.
 {       struct cmp_cfg cfg;
         uint32_t cmp_par_mean = 2;
         uint32_t spillover_mean = 2;
         uint32_t cmp_par_variance = 2;
         uint32_t spillover_variance = 2;
         uint32_t cmp_par_pixels_error = 2;
         uint32_t spillover_pixels_error = 2;
         int error;
         enum cmp_data_type data_type;
         /* wrong data type test */
         for (data_type = 0; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 cfg = cmp_cfg_icu_create(data_type, CMP_MODE_MODEL_ZERO, 16, CMP_LOSSLESS);
                 error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                                     cmp_par_variance, spillover_variance,
                                     cmp_par_pixels_error, spillover_pixels_error);
                 if (data_type == DATA_TYPE_OFFSET ||
                     data_type == DATA_TYPE_BACKGROUND ||
                     data_type == DATA_TYPE_SMEARING ||
                     data_type == DATA_TYPE_F_CAM_OFFSET ||
                     data_type == DATA_TYPE_F_CAM_BACKGROUND
                     ) {
                         TEST_ASSERT_FALSE(error);
                         TEST_ASSERT_EQUAL_INT(data_type, cfg.data_type);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_mean);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_mean);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_variance);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_variance);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_pixels_error);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_pixels_error);
                 } else {
                         TEST_ASSERT_TRUE(error);
                 }
         }
         /* cfg == NULL test */
         error = cmp_cfg_aux(NULL, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_OFFSET */
         cfg = cmp_cfg_icu_create(DATA_TYPE_OFFSET, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_mean = MIN_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MIN_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = ~0U;
         spillover_pixels_error = ~0U;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MIN_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(2, cfg.spill_variance);
         /* This should fail */
         cmp_par_mean = MIN_NON_IMA_GOLOMB_PAR-1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_BACKGROUND */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_CAM_OFFSET, CMP_MODE_DIFF_MULTI, 7, CMP_LOSSLESS);
         cmp_par_mean = MIN_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MIN_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = ~0U;
         spillover_pixels_error = ~0U;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MIN_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(2, cfg.spill_variance);
         /* This should fail */
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR-1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         cfg = cmp_cfg_icu_create(DATA_TYPE_BACKGROUND, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_mean = MAX_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = 42;
         spillover_pixels_error = 23;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MAX_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_SPILL, cfg.spill_variance);
         TEST_ASSERT_EQUAL_INT(42, cfg.cmp_par_pixels_error);
         TEST_ASSERT_EQUAL_INT(23, cfg.spill_pixels_error);
         /* This should fail */
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR-1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_BACKGROUND */
         cfg = cmp_cfg_icu_create(DATA_TYPE_BACKGROUND, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_mean = MAX_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = 42;
         spillover_pixels_error = 23;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MAX_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_SPILL, cfg.spill_variance);
         TEST_ASSERT_EQUAL_INT(42, cfg.cmp_par_pixels_error);
         TEST_ASSERT_EQUAL_INT(23, cfg.spill_pixels_error);
         /* This should fail */
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR-1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_F_CAM_BACKGROUND */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_CAM_BACKGROUND, CMP_MODE_DIFF_MULTI, 7, CMP_LOSSLESS);
         cmp_par_mean = MAX_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = 42;
         spillover_pixels_error = 23;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MAX_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_SPILL, cfg.spill_variance);
         TEST_ASSERT_EQUAL_INT(42, cfg.cmp_par_pixels_error);
         TEST_ASSERT_EQUAL_INT(23, cfg.spill_pixels_error);
         /* This should fail */
         cmp_par_pixels_error = MIN_NON_IMA_GOLOMB_PAR-1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_SMEARING */
         cfg = cmp_cfg_icu_create(DATA_TYPE_SMEARING, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_mean = MAX_NON_IMA_GOLOMB_PAR;
         spillover_mean = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         cmp_par_variance = MIN_NON_IMA_GOLOMB_PAR;
         spillover_variance = MIN_NON_IMA_SPILL;
         cmp_par_pixels_error = 42;
         spillover_pixels_error = 23;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(MAX_NON_IMA_GOLOMB_PAR, cfg.cmp_par_mean);
         TEST_ASSERT_EQUAL_INT(cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR), cfg.spill_mean);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_GOLOMB_PAR, cfg.cmp_par_variance);
         TEST_ASSERT_EQUAL_INT(MIN_NON_IMA_SPILL, cfg.spill_variance);
         TEST_ASSERT_EQUAL_INT(42, cfg.cmp_par_pixels_error);
         TEST_ASSERT_EQUAL_INT(23, cfg.spill_pixels_error);
         /* This should fail */
         spillover_pixels_error = cmp_icu_max_spill(42)+1;
         error = cmp_cfg_aux(&cfg, cmp_par_mean, spillover_mean,
                             cmp_par_variance, spillover_variance,
                             cmp_par_pixels_error, spillover_pixels_error);
         TEST_ASSERT_TRUE(error);
 }
References cmp_cfg_aux(), cmp_cfg_icu_create(), cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_ZERO, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, data_type, cmp_cfg::data_type, DATA_TYPE_BACKGROUND, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_OFFSET, DATA_TYPE_OFFSET, DATA_TYPE_SMEARING, MAX_NON_IMA_GOLOMB_PAR, MIN_NON_IMA_GOLOMB_PAR, MIN_NON_IMA_SPILL, cmp_cfg::spill_mean, cmp_cfg::spill_pixels_error, and cmp_cfg::spill_variance.