cmp_tool: test_compress_imagette_stuff
test_compress_imagette_stuff()
void test_compress_imagette_stuff (void)
Test:
compress_imagette
Definition at line 2415 of file test_cmp_icu.c.
 {
         uint16_t data[] = {0x0, 0x1, 0x23, 0x42, 0x8000, 0x7FFF, 0xFFFF};
         uint32_t output_buf[4] = {0};
         struct cmp_cfg cfg = {0};
         int cmp_size, error;
         uint8_t output_buf_exp[] = {
                 0x00, 0x00, 0x00, 0x01,
                 0x00, 0x23, 0x00, 0x42,
                 0x80, 0x00, 0x7F, 0xFF,
                 0xFF, 0xFF, 0x00, 0x00};
         uint32_t *output_buf_exp_32;
         uint32_t samples = 7;
         uint32_t buffer_length = 8;
         uint32_t cmp_par = 16; /* how many used bits has the maximum data value */
         uint32_t output_buf_size;
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_STUFF,
                                  CMP_PAR_UNUSED, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         output_buf_size = cmp_cfg_icu_buffers(&cfg, data, samples, NULL, NULL,
                                               output_buf, buffer_length);
         TEST_ASSERT_EQUAL_INT(buffer_length*sizeof(uint16_t), output_buf_size);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         cmp_size = icu_compress_data(&cfg);
         output_buf_exp_32 = (uint32_t *)output_buf_exp;
         TEST_ASSERT_EQUAL_INT(7*16, cmp_size);
         TEST_ASSERT_EQUAL_HEX16(output_buf_exp_32[0], output_buf[0]);
         TEST_ASSERT_EQUAL_HEX16(output_buf_exp_32[1], output_buf[1]);
         TEST_ASSERT_EQUAL_HEX16(output_buf_exp_32[2], output_buf[2]);
         TEST_ASSERT_EQUAL_HEX16(output_buf_exp_32[3], output_buf[3]);
 }
References cmp_cfg::buffer_length, cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_imagette(), CMP_LOSSLESS, CMP_MODE_STUFF, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, icu_compress_data(), and cmp_cfg::samples.