cmp_tool: test_encode_value_zero
test_encode_value_zero()
void test_encode_value_zero (void)
Test:
encode_value_zero
Definition at line 1998 of file test_cmp_icu.c.
 {
         uint32_t data, model;
         int stream_len;
         struct encoder_setupt setup = {0};
         uint32_t bitstream[3] = {0};
         /* setup the setup */
         setup.encoder_par1 = 1;
         setup.encoder_par2 = ilog_2(setup.encoder_par1);
         setup.spillover_par = 32;
         setup.max_data_bits = 32;
         setup.generate_cw_f = rice_encoder;
         setup.bitstream_adr = bitstream;
         setup.max_stream_len = sizeof(bitstream) * CHAR_BIT;
         stream_len = 0;
         data = 0; model = 0;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(2, stream_len);
         TEST_ASSERT_EQUAL_HEX(0x80000000, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         data = 5; model = 0;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(14, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xBFF80000, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         data = 2; model = 7;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(25, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xBFFBFF00, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         /* zero escape mechanism */
         data = 100; model = 42;
         /* (100-42)*2+1=117 -> cw 0 + 0x0000_0000_0000_0075 */
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(58, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xBFFBFF00, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00001D40, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         /* test overflow */
         data = (uint32_t)INT32_MIN; model = 0;
         /* (INT32_MIN)*-2-1+1=0(overflow) -> cw 0 + 0x0000_0000_0000_0000 */
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(91, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xBFFBFF00, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x00001D40, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0x00000000, bitstream[2]);
         /* small buffer error */
         data = 23; model = 26;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, stream_len);
         /* reset bitstream to all bits set */
         bitstream[0] = ~0U;
         bitstream[1] = ~0U;
         bitstream[2] = ~0U;
         stream_len = 0;
         /* we use now values with maximum 6 bits */
         setup.max_data_bits = 6;
         /* lowest value before zero encoding */
         data = 53; model = 38;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(32, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFE, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, bitstream[2]);
         /* lowest value with zero encoding */
         data = 0; model = 16;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(39, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFE, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x41FFFFFF, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, bitstream[2]);
         /* maximum positive value to encode */
         data = 31; model = 0;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(46, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFE, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x40FFFFFF, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, bitstream[2]);
         /* maximum negative value to encode */
         data = 0; model = 32;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(53, stream_len);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFE, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0x40FC07FF, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFF, bitstream[2]);
         /* small buffer error when creating the zero escape symbol*/
         bitstream[0] = 0;
         bitstream[1] = 0;
         bitstream[2] = 0;
         stream_len = 32;
         setup.max_stream_len = 32;
         data = 31; model = 0;
         stream_len = encode_value_zero(data, model, stream_len, &setup);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, stream_len);
         TEST_ASSERT_EQUAL_HEX(0, bitstream[0]);
         TEST_ASSERT_EQUAL_HEX(0, bitstream[1]);
         TEST_ASSERT_EQUAL_HEX(0, bitstream[2]);
 }
References encoder_setupt::bitstream_adr, CMP_ERROR_SMALL_BUF, encode_value_zero(), encoder_setupt::encoder_par1, encoder_setupt::encoder_par2, encoder_setupt::generate_cw_f, ilog_2(), encoder_setupt::max_data_bits, encoder_setupt::max_stream_len, rice_encoder(), and encoder_setupt::spillover_par.