cmp_tool: test_compress_s_fx_ncob_error_cases
test_compress_s_fx_ncob_error_cases()
void test_compress_s_fx_ncob_error_cases (void)
Test:
compress_s_fx_ncob
Definition at line 3122 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = 3;
         uint32_t spillover_exp_flags = 6;
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_ncob = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_ncob = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct s_fx_ncob)] = {0};
         uint8_t model_data[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct s_fx_ncob)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct s_fx_ncob)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct s_fx_ncob *data_p = (struct s_fx_ncob *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 21;
         my_max_used_bits.s_ncob = 31;
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_NCOB, CMP_MODE_MODEL_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         error = cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 3, model_data,
                                                    NULL, (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         /* the compressed_data buffer is to small */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, cmp_bits);
         /* test if data are higher than max used bits value */
         data_p[2].exp_flags = 0x4; /* has more than 2 bits (my_max_used_bits.s_exp_flags) */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].exp_flags = 0x3;
         data_p[1].fx = 0x200000; /* value to high */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].fx = 0x1FFFFF; /* value to high */
         data_p[0].ncob_y = 0x80000000; /* value to high */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].ncob_y = 0x7FFFFFFF; /* value to high */
         /* error case exp_flag */
         my_max_used_bits.s_exp_flags = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case fx */
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case efx */
         my_max_used_bits.s_fx = 21;
         my_max_used_bits.s_ncob = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_ERROR_SMALL_BUF, cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_MODEL_ZERO, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_ncob, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_S_FX_NCOB, DATA_TYPE_UNKNOWN, s_fx_ncob::exp_flags, s_fx_ncob::fx, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, s_fx_ncob::ncob_y, cmp_max_used_bits::s_exp_flags, cmp_max_used_bits::s_fx, and cmp_max_used_bits::s_ncob.