cmp_tool: test_compress_s_fx_staff
test_compress_s_fx_staff()
void test_compress_s_fx_staff (void)
Definition at line 2820 of file test_cmp_icu.c.
 {
         struct s_fx data[5];
         struct cmp_cfg cfg = {0};
         int cmp_size, cmp_size_exp;
         struct multi_entry_hdr *hdr;
         uint32_t *cmp_data;
         /* setup configuration */
         cfg.data_type = DATA_TYPE_S_FX;
         cfg.cmp_mode = CMP_MODE_STUFF;
         cfg.samples = 5;
         cfg.input_buf = malloc(cmp_cal_size_of_data(cfg.samples, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.input_buf);
         cfg.buffer_length = 5;
         cfg.icu_output_buf = malloc(cmp_cal_size_of_data(cfg.buffer_length, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.icu_output_buf);
         cfg.cmp_par_exp_flags = 2;
         cfg.cmp_par_fx = 21;
         cfg.max_used_bits = &MAX_USED_BITS_V1;
         /* generate input data */
         hdr = cfg.input_buf;
         /* use dummy data for the header */
         memset(hdr, 0x42, sizeof(struct multi_entry_hdr));
         data[0].exp_flags = 0x0;
         data[0].fx = 0x0;
         data[1].exp_flags = 0x1;
         data[1].fx = 0x1;
         data[2].exp_flags = 0x2;
         data[2].fx = 0x23;
         data[3].exp_flags = 0x3;
         data[3].fx = 0x42;
         data[4].exp_flags = 0x0;
         data[4].fx = 0x001FFFFF;
         memcpy(hdr->entry, data, sizeof(data));
         cmp_size = icu_compress_data(&cfg);
         cmp_size_exp = 5 * (2 + 21) + MULTI_ENTRY_HDR_SIZE * CHAR_BIT;
         TEST_ASSERT_EQUAL_INT(cmp_size_exp, cmp_size);
         TEST_ASSERT_FALSE(memcmp(cfg.input_buf, cfg.icu_output_buf, MULTI_ENTRY_HDR_SIZE));
         hdr = (void *)cfg.icu_output_buf;
         cmp_data = calloc(4, sizeof(*cmp_data));
         memcpy(cmp_data, hdr->entry, 4 * sizeof(*cmp_data));
         TEST_ASSERT_EQUAL_HEX(0x00000080, be32_to_cpu(cmp_data[0]));
         TEST_ASSERT_EQUAL_HEX(0x00060001, be32_to_cpu(cmp_data[1]));
         TEST_ASSERT_EQUAL_HEX(0x1E000423, be32_to_cpu(cmp_data[2]));
         TEST_ASSERT_EQUAL_HEX(0xFFFFE000, be32_to_cpu(cmp_data[3]));
         free(cmp_data);
         free(cfg.input_buf);
         free(cfg.icu_output_buf);
 }
References be32_to_cpu, cmp_cfg::buffer_length, cmp_cal_size_of_data(), cmp_data, cmp_cfg::cmp_mode, CMP_MODE_STUFF, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::data_type, DATA_TYPE_S_FX, multi_entry_hdr::entry, s_fx::exp_flags, s_fx::fx, icu_compress_data(), cmp_cfg::icu_output_buf, cmp_cfg::input_buf, malloc(), cmp_cfg::max_used_bits, MAX_USED_BITS_V1, MULTI_ENTRY_HDR_SIZE, and cmp_cfg::samples.