cmp_tool: test_compress_l_fx_efx_ncob_ecob_error_cases
test_compress_l_fx_efx_ncob_ecob_error_cases()
void test_compress_l_fx_efx_ncob_ecob_error_cases (void)
Test:
compress_l_fx_efx_ncob_ecob
Definition at line 3870 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_ncob = 2;
         uint32_t spillover_ncob = 10;
         uint32_t cmp_par_efx = 3;
         uint32_t spillover_efx = 44;
         uint32_t cmp_par_ecob = 5;
         uint32_t spillover_ecob = 55;
         uint32_t cmp_par_fx_cob_variance = 30;
         uint32_t spillover_fx_cob_variance = 8;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+3*sizeof(struct l_fx_efx_ncob_ecob)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct l_fx_efx_ncob_ecob)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct l_fx_efx_ncob_ecob *data_p = (struct l_fx_efx_ncob_ecob *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_L_FX_EFX_NCOB_ECOB, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 3, NULL, NULL,
                                                    (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.l_exp_flags = 23;
         my_max_used_bits.l_fx = 31;
         my_max_used_bits.l_ncob = 2;
         my_max_used_bits.l_efx = 1;
         my_max_used_bits.l_ecob = 3;
         my_max_used_bits.l_fx_variance = 23;
         my_max_used_bits.l_cob_variance = 11;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         /* value is to big for the max used bits values */
         data_p[2].exp_flags = 0x800000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].exp_flags = 0x800000-1;
         data_p[2].fx = 0x80000000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].fx = 0x80000000-1;
         data_p[2].ncob_x = 0x4;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].ncob_x = 0x3;
         data_p[2].ncob_y = 0x4;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].ncob_y = 0x3;
         data_p[1].efx = 0x2;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].efx = 0x1;
         data_p[1].ecob_x = 0x8;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ecob_x = 0x7;
         data_p[1].ecob_y = 0x8;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ecob_y = 0x7;
         data_p[0].fx_variance = 0x800000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].fx_variance = 0x800000-1;
         data_p[2].cob_x_variance = 0x800;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].cob_x_variance = 0x800-1;
         data_p[2].cob_y_variance = 0x800;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].cob_y_variance = 0x800-1;
         my_max_used_bits.l_exp_flags = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_exp_flags = 32;
         my_max_used_bits.l_fx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_fx = 32;
         my_max_used_bits.l_ncob = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_ncob = 32;
         my_max_used_bits.l_efx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_efx = 32;
         my_max_used_bits.l_ecob = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_ecob = 32;
         my_max_used_bits.l_fx_variance = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.l_fx_variance = 32;
         my_max_used_bits.l_cob_variance = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, l_fx_efx_ncob_ecob::cob_x_variance, l_fx_efx_ncob_ecob::cob_y_variance, cmp_cfg::data_type, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_UNKNOWN, l_fx_efx_ncob_ecob::ecob_x, l_fx_efx_ncob_ecob::ecob_y, l_fx_efx_ncob_ecob::efx, l_fx_efx_ncob_ecob::exp_flags, l_fx_efx_ncob_ecob::fx, l_fx_efx_ncob_ecob::fx_variance, icu_compress_data(), cmp_max_used_bits::l_cob_variance, cmp_max_used_bits::l_ecob, cmp_max_used_bits::l_efx, cmp_max_used_bits::l_exp_flags, cmp_max_used_bits::l_fx, cmp_max_used_bits::l_fx_variance, cmp_max_used_bits::l_ncob, MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, l_fx_efx_ncob_ecob::ncob_x, and l_fx_efx_ncob_ecob::ncob_y.