cmp_tool: test_cmp_cfg_fx_cob
test_cmp_cfg_fx_cob()
void test_cmp_cfg_fx_cob (void)
Test:
cmp_cfg_fx_cob
Definition at line 611 of file test_cmp_icu.c.
 {
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = 2;
         uint32_t spillover_exp_flags = 2;
         uint32_t cmp_par_fx = 2;
         uint32_t spillover_fx = 2;
         uint32_t cmp_par_ncob = 2;
         uint32_t spillover_ncob = 2;
         uint32_t cmp_par_efx = 2;
         uint32_t spillover_efx = 2;
         uint32_t cmp_par_ecob = 2;
         uint32_t spillover_ecob = 2;
         uint32_t cmp_par_fx_cob_variance = 2;
         uint32_t spillover_fx_cob_variance = 2;
         int error;
         enum cmp_data_type data_type;
         /* wrong data type test */
         for (data_type = 0; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 cfg = cmp_cfg_icu_create(data_type, CMP_MODE_MODEL_ZERO, 16, CMP_LOSSLESS);
                 error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                        cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                        cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                        cmp_par_fx_cob_variance, spillover_fx_cob_variance);
                 if (data_type == DATA_TYPE_S_FX ||
                     data_type == DATA_TYPE_S_FX_EFX ||
                     data_type == DATA_TYPE_S_FX_NCOB ||
                     data_type == DATA_TYPE_S_FX_EFX_NCOB_ECOB ||
                     data_type == DATA_TYPE_L_FX ||
                     data_type == DATA_TYPE_L_FX_EFX ||
                     data_type == DATA_TYPE_L_FX_NCOB ||
                     data_type == DATA_TYPE_L_FX_EFX_NCOB_ECOB ||
                     data_type == DATA_TYPE_F_FX ||
                     data_type == DATA_TYPE_F_FX_EFX ||
                     data_type == DATA_TYPE_F_FX_NCOB ||
                     data_type == DATA_TYPE_F_FX_EFX_NCOB_ECOB) {
                         TEST_ASSERT_FALSE(error);
                         TEST_ASSERT_EQUAL_INT(data_type, cfg.data_type);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_fx);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_fx);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_exp_flags);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_exp_flags);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_efx);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_efx);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_ncob);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_ncob);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_ecob);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_ecob);
                         TEST_ASSERT_EQUAL_INT(2, cfg.cmp_par_fx_cob_variance);
                         TEST_ASSERT_EQUAL_INT(2, cfg.spill_fx_cob_variance);
                 } else {
                         TEST_ASSERT_TRUE(error);
                 }
         }
         /* cfg == NULL test */
         error = cmp_cfg_fx_cob(NULL, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* test DATA_TYPE_S_FX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX, CMP_MODE_MODEL_ZERO, 16, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         /* invalid spillover_exp_flags parameter */
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags)+1;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* invalid cmp_par_fx parameter */
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR - 1;
         spillover_fx = MIN_NON_IMA_SPILL;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* test DATA_TYPE_S_FX_EFX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_EFX, CMP_MODE_MODEL_ZERO, 0, 1);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         /* invalid spillover_efx parameter */
         spillover_efx = 0;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* test DATA_TYPE_S_FX_NCOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_NCOB, CMP_MODE_MODEL_ZERO, 0, 1);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = 19;
         spillover_ncob = 5;
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         /* invalid cmp_par_ncob parameter */
         cmp_par_ncob = 0;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* test DATA_TYPE_S_FX_EFX_NCOB_ECOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_EFX_NCOB_ECOB, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = 19;
         spillover_ncob = 5;
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = MAX_NON_IMA_GOLOMB_PAR;
         spillover_ecob = MIN_NON_IMA_SPILL;
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         TEST_ASSERT_EQUAL_INT(cmp_par_ecob, cfg.cmp_par_ecob);
         TEST_ASSERT_EQUAL_INT(spillover_ecob, cfg.spill_ecob);
         /* invalid cmp_par_ecob parameter */
         cmp_par_ecob = -1U;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_L_FX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_L_FX, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = 30;
         spillover_fx_cob_variance = 8;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx_cob_variance, cfg.cmp_par_fx_cob_variance);
         TEST_ASSERT_EQUAL_INT(spillover_fx_cob_variance, cfg.spill_fx_cob_variance);
         /* invalid spillover_fx_cob_variance parameter */
         spillover_fx_cob_variance = 1;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_TRUE(error);
         /* DATA_TYPE_L_FX_EFX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_L_FX_EFX, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = 30;
         spillover_fx_cob_variance = 8;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx_cob_variance, cfg.cmp_par_fx_cob_variance);
         TEST_ASSERT_EQUAL_INT(spillover_fx_cob_variance, cfg.spill_fx_cob_variance);
         /* DATA_TYPE_L_FX_NCOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_L_FX_NCOB, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = 19;
         spillover_ncob = 5;
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = 30;
         spillover_fx_cob_variance = 8;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx_cob_variance, cfg.cmp_par_fx_cob_variance);
         TEST_ASSERT_EQUAL_INT(spillover_fx_cob_variance, cfg.spill_fx_cob_variance);
         /* DATA_TYPE_L_FX_EFX_NCOB_ECOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_L_FX_EFX_NCOB_ECOB, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = MAX_NON_IMA_GOLOMB_PAR;
         spillover_exp_flags = cmp_icu_max_spill(cmp_par_exp_flags);
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = 19;
         spillover_ncob = 5;
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = MAX_NON_IMA_GOLOMB_PAR;
         spillover_ecob = MIN_NON_IMA_SPILL;
         cmp_par_fx_cob_variance = 30;
         spillover_fx_cob_variance = 8;
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_exp_flags, cfg.cmp_par_exp_flags);
         TEST_ASSERT_EQUAL_INT(spillover_exp_flags, cfg.spill_exp_flags);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         TEST_ASSERT_EQUAL_INT(cmp_par_ecob, cfg.cmp_par_ecob);
         TEST_ASSERT_EQUAL_INT(spillover_ecob, cfg.spill_ecob);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx_cob_variance, cfg.cmp_par_fx_cob_variance);
         TEST_ASSERT_EQUAL_INT(spillover_fx_cob_variance, cfg.spill_fx_cob_variance);
         /* DATA_TYPE_F_FX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = ~0U; /* invalid parameter */
         spillover_exp_flags = ~0U; /* invalid parameter */
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         /* DATA_TYPE_F_FX_EFX */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_EFX, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = ~0U; /* invalid parameter */
         spillover_exp_flags = ~0U; /* invalid parameter */
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = ~0U; /* invalid parameter */
         spillover_ncob = ~0U; /* invalid parameter */
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         /* DATA_TYPE_F_FX_NCOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_NCOB, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = ~0U; /* invalid parameter */
         spillover_exp_flags = ~0U; /* invalid parameter */
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = MIN_NON_IMA_GOLOMB_PAR;
         spillover_ncob = cmp_icu_max_spill(cmp_par_ncob);
         cmp_par_efx = ~0U; /* invalid parameter */
         spillover_efx = ~0U; /* invalid parameter */
         cmp_par_ecob = ~0U; /* invalid parameter */
         spillover_ecob = ~0U; /* invalid parameter */
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         /* DATA_TYPE_F_FX_EFX_NCOB_ECOB */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_EFX_NCOB_ECOB, CMP_MODE_DIFF_ZERO, 7, CMP_LOSSLESS);
         cmp_par_exp_flags = ~0U; /* invalid parameter */
         spillover_exp_flags = ~0U; /* invalid parameter */
         cmp_par_fx = MIN_NON_IMA_GOLOMB_PAR;
         spillover_fx = MIN_NON_IMA_SPILL;
         cmp_par_ncob = MIN_NON_IMA_GOLOMB_PAR;
         spillover_ncob = cmp_icu_max_spill(cmp_par_ncob);
         cmp_par_efx = 23;
         spillover_efx = 42;
         cmp_par_ecob = MAX_NON_IMA_GOLOMB_PAR;
         spillover_ecob = MIN_NON_IMA_SPILL;
         cmp_par_fx_cob_variance = ~0U; /* invalid parameter */
         spillover_fx_cob_variance = ~0U; /* invalid parameter */
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                cmp_par_fx_cob_variance, spillover_fx_cob_variance);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cmp_par_fx, cfg.cmp_par_fx);
         TEST_ASSERT_EQUAL_INT(spillover_fx, cfg.spill_fx);
         TEST_ASSERT_EQUAL_INT(cmp_par_ncob, cfg.cmp_par_ncob);
         TEST_ASSERT_EQUAL_INT(spillover_ncob, cfg.spill_ncob);
         TEST_ASSERT_EQUAL_INT(cmp_par_efx, cfg.cmp_par_efx);
         TEST_ASSERT_EQUAL_INT(spillover_efx, cfg.spill_efx);
         TEST_ASSERT_EQUAL_INT(cmp_par_ecob, cfg.cmp_par_ecob);
         TEST_ASSERT_EQUAL_INT(spillover_ecob, cfg.spill_ecob);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_create(), cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_ZERO, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_ncob, data_type, cmp_cfg::data_type, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_FX, DATA_TYPE_F_FX_EFX, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_F_FX_NCOB, DATA_TYPE_L_FX, DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_EFX_NCOB_ECOB, DATA_TYPE_L_FX_NCOB, DATA_TYPE_S_FX, DATA_TYPE_S_FX_EFX, DATA_TYPE_S_FX_EFX_NCOB_ECOB, DATA_TYPE_S_FX_NCOB, MAX_NON_IMA_GOLOMB_PAR, MIN_NON_IMA_GOLOMB_PAR, MIN_NON_IMA_SPILL, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, and cmp_cfg::spill_ncob.