cmp_tool: test_cmp_decmp_n_imagette_raw
test_cmp_decmp_n_imagette_raw()
void test_cmp_decmp_n_imagette_raw (void)
Definition at line 994 of file test_decmp.c.
 {
         int cmp_size, decmp_size;
         size_t s, i;
         struct cmp_cfg cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 0, CMP_LOSSLESS);
         uint16_t data[] = {0, 1, 2, 0x42, (uint16_t)INT16_MIN, INT16_MAX, UINT16_MAX};
         uint32_t *compressed_data;
         uint16_t *decompressed_data;
         struct cmp_entity *ent;
         s = cmp_cfg_icu_buffers(&cfg, data, ARRAY_SIZE(data), NULL, NULL,
                                 NULL, ARRAY_SIZE(data));
         TEST_ASSERT_TRUE(s);
         compressed_data = malloc(s);
         TEST_ASSERT_TRUE(compressed_data);
         s = cmp_cfg_icu_buffers(&cfg, data, ARRAY_SIZE(data), NULL, NULL,
                                 compressed_data, ARRAY_SIZE(data));
         TEST_ASSERT_TRUE(s);
         cmp_size = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(sizeof(data)*CHAR_BIT, cmp_size);
         s = cmp_ent_build(NULL, 0, 0, 0, 0, 0, &cfg, cmp_size);
         TEST_ASSERT_TRUE(s);
         ent = malloc(s);
         TEST_ASSERT_TRUE(ent);
         s = cmp_ent_build(ent, 0, 0, 0, 0, 0, &cfg, cmp_size);
         TEST_ASSERT_TRUE(s);
         memcpy(cmp_ent_get_data_buf(ent), compressed_data, ((unsigned int)cmp_size+7)/8);
         decmp_size = decompress_cmp_entiy(ent, NULL, NULL, NULL);
         TEST_ASSERT_EQUAL_INT(sizeof(data), decmp_size);
         decompressed_data = malloc((size_t)decmp_size);
         TEST_ASSERT_TRUE(decompressed_data);
         decmp_size = decompress_cmp_entiy(ent, NULL, NULL, decompressed_data);
         TEST_ASSERT_EQUAL_INT(sizeof(data), decmp_size);
         for (i = 0; i < ARRAY_SIZE(data); ++i)
                 TEST_ASSERT_EQUAL_INT(data[i], decompressed_data[i]);
         free(compressed_data);
         free(ent);
         free(decompressed_data);
 }
References ARRAY_SIZE, cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_ent_build(), cmp_ent_get_data_buf(), CMP_LOSSLESS, CMP_MODE_RAW, DATA_TYPE_IMAGETTE, decompress_cmp_entiy(), icu_compress_data(), and malloc().