cmp_tool: test_compress_s_fx_efx_error_cases
test_compress_s_fx_efx_error_cases()
void test_compress_s_fx_efx_error_cases (void)
Test:
compress_s_fx_efx
Definition at line 3045 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_exp_flags = 2;
         uint32_t spillover_exp_flags = 6;
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_efx = MAX_NON_IMA_GOLOMB_PAR;
         uint32_t spillover_efx = cmp_icu_max_spill(MAX_NON_IMA_GOLOMB_PAR);
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+2*sizeof(struct s_fx_efx)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct s_fx_efx)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct s_fx_efx *data_p = (struct s_fx_efx *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_S_FX_EFX, CMP_MODE_DIFF_MULTI, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, cmp_par_exp_flags, spillover_exp_flags,
                                cmp_par_fx, spillover_fx, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, cmp_par_efx, spillover_efx,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 2, NULL,
                                                    NULL, (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 21;
         my_max_used_bits.s_efx = 16;
         error = cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         TEST_ASSERT_FALSE(error);
         /* test if data are higher than max used bits value */
         data_p[0].exp_flags = 0x4; /* has more than 2 bits (my_max_used_bits.s_exp_flags) */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].exp_flags = 0x3;
         data_p[1].fx = 0x200000; /* has more than 21 bits (my_max_used_bits.fx) */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].fx = 0x1FFFFF;
         data_p[1].efx = 0x100000; /* has more than 16 bits (my_max_used_bits.efx) */
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         /* error case exp_flag */
         my_max_used_bits.s_exp_flags = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case fx */
         my_max_used_bits.s_exp_flags = 2;
         my_max_used_bits.s_fx = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         /* error case efx */
         my_max_used_bits.s_fx = 21;
         my_max_used_bits.s_efx = 33;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, cmp_icu_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_S_FX_EFX, DATA_TYPE_UNKNOWN, s_fx_efx::efx, s_fx_efx::exp_flags, s_fx_efx::fx, icu_compress_data(), MAX_NON_IMA_GOLOMB_PAR, MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, cmp_max_used_bits::s_efx, cmp_max_used_bits::s_exp_flags, and cmp_max_used_bits::s_fx.