cmp_tool: test_cmp_cfg_icu_imagette
test_cmp_cfg_icu_imagette()
void test_cmp_cfg_icu_imagette (void)
Test:
cmp_cfg_icu_imagette
Definition at line 483 of file test_cmp_icu.c.
 {
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par;
         uint32_t spillover_par;
         enum cmp_data_type data_type;
         int error;
         /* lowest values 1d/model mode */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_MODEL_ZERO, 0, CMP_LOSSLESS);
         cmp_par = MIN_IMA_GOLOMB_PAR;
         spillover_par = MIN_IMA_SPILL;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, 1);
         TEST_ASSERT_EQUAL_INT(cfg.spill, 2);
         /* highest values 1d/model mode */
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_CAM_IMAGETTE, CMP_MODE_DIFF_MULTI, 16, CMP_LOSSLESS);
         cmp_par = MAX_IMA_GOLOMB_PAR;
         spillover_par = cmp_ima_max_spill(cmp_par);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, MAX_IMA_GOLOMB_PAR);
         TEST_ASSERT_EQUAL_INT(cfg.spill, cmp_ima_max_spill(MAX_IMA_GOLOMB_PAR));
         /* wrong data type  test */
         for (data_type = 0; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 cfg = cmp_cfg_icu_create(data_type, CMP_MODE_DIFF_MULTI, 16, CMP_LOSSLESS);
                 error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
                 if (data_type == DATA_TYPE_IMAGETTE ||
                     data_type == DATA_TYPE_SAT_IMAGETTE ||
                     data_type == DATA_TYPE_F_CAM_IMAGETTE) {
                         TEST_ASSERT_FALSE(error);
                         TEST_ASSERT_EQUAL_INT(data_type, cfg.data_type);
                         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, MAX_IMA_GOLOMB_PAR);
                         TEST_ASSERT_EQUAL_INT(cfg.spill, cmp_ima_max_spill(MAX_IMA_GOLOMB_PAR));
                 } else {
                         TEST_ASSERT_TRUE(error);
                 }
         }
         /* model/1d MODE tests */
         /* cmp_par to big */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_MODEL_MULTI, 16, CMP_LOSSLESS);
         cmp_par = MAX_IMA_GOLOMB_PAR + 1;
         spillover_par = MIN_IMA_SPILL;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* ignore in RAW MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 16, CMP_LOSSLESS);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         /* cmp_par to small */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_MODEL_MULTI, 16, CMP_LOSSLESS);
         cmp_par = MIN_IMA_GOLOMB_PAR - 1;
         spillover_par = MIN_IMA_SPILL;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* ignore in RAW MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 16, CMP_LOSSLESS);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         /* spillover_par to big */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_MODEL_MULTI, 16, CMP_LOSSLESS);
         cmp_par = MIN_IMA_GOLOMB_PAR;
         spillover_par = cmp_ima_max_spill(cmp_par)+1;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* ignore in RAW MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 16, CMP_LOSSLESS);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         /* spillover_par to small */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         cmp_par = MAX_IMA_GOLOMB_PAR;
         spillover_par = MIN_IMA_SPILL-1;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* ignore in RAW MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 16, CMP_LOSSLESS);
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         /* CMP_MODE_STUFF tests */
         spillover_par = ~0U; /* is ignored */
         /* highest values STUFF MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_STUFF, ~0U, CMP_LOSSLESS);
         cmp_par = MAX_STUFF_CMP_PAR;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, 32);
         /* lowest values STUFF MODE */
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_STUFF, ~0U, CMP_LOSSLESS);
         cmp_par = 0;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, 0);
         /* cmp_par to big */
         cfg = cmp_cfg_icu_create(DATA_TYPE_SAT_IMAGETTE, CMP_MODE_STUFF, ~0U, CMP_LOSSLESS);
         cmp_par = MAX_STUFF_CMP_PAR+1;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* cfg = NULL test*/
         error = cmp_cfg_icu_imagette(NULL, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
         /* invalid compression mode  test*/
         cfg = cmp_cfg_icu_create(DATA_TYPE_SAT_IMAGETTE, CMP_MODE_STUFF+1, ~0U, CMP_LOSSLESS);
         cmp_par = MAX_STUFF_CMP_PAR+1;
         error = cmp_cfg_icu_imagette(&cfg, cmp_par, spillover_par);
         TEST_ASSERT_TRUE(error);
 }
References cmp_cfg_icu_create(), cmp_cfg_icu_imagette(), cmp_ima_max_spill(), CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_MULTI, CMP_MODE_MODEL_ZERO, CMP_MODE_RAW, CMP_MODE_STUFF, data_type, cmp_cfg::data_type, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_F_CAM_IMAGETTE, DATA_TYPE_IMAGETTE, DATA_TYPE_SAT_IMAGETTE, cmp_cfg::golomb_par, MAX_IMA_GOLOMB_PAR, MAX_STUFF_CMP_PAR, MIN_IMA_GOLOMB_PAR, MIN_IMA_SPILL, and cmp_cfg::spill.