cmp_tool: test_zero_refill_needed
test_zero_refill_needed()
void test_zero_refill_needed (void)
Test:
decode_zero
Definition at line 717 of file test_decmp.c.
 {
         uint32_t decoded_value = ~0U;
         uint64_t cmp_data[] = {0x0000000200000003, 0xFFFFFFFC00000000};
         struct bit_decoder dec = {0};
         struct decoder_setup setup = {0};
         uint32_t spillover = 8;
         uint32_t m = 1<<30;
         int err;
         cpu_to_be64s(&cmp_data[0]);
         cpu_to_be64s(&cmp_data[1]);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_ZERO, m, spillover, CMP_LOSSLESS, 32);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(0, decoded_value);
         TEST_ASSERT_FALSE(err);
         err = decode_zero(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_HEX(0xFFFFFFFE, decoded_value);
         TEST_ASSERT_FALSE(err);
 }
References bit_init_decoder(), cmp_data, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, configure_decoder_setup(), cpu_to_be64s, decoder_setup::dec, and decode_zero().