cmp_tool: test_cmp_ent_get_cmp_data
test_cmp_ent_get_cmp_data()
void test_cmp_ent_get_cmp_data (void)
Test:
cmp_ent_get_cmp_data
Definition at line 1346 of file test_cmp_entity.c.
 {
         int32_t size;
         struct cmp_entity *ent;
         uint32_t *data_buf;
         uint32_t s;
         uint8_t i;
         uint8_t *data_p;
         /* setup compression entity */
         s = cmp_ent_create(NULL, DATA_TYPE_S_FX, 0, 12);
         TEST_ASSERT_EQUAL_INT(NON_IMAGETTE_HEADER_SIZE + 12, s);
         ent = malloc(s); TEST_ASSERT_NOT_NULL(ent);
         s = cmp_ent_create(ent, DATA_TYPE_S_FX, 0, 12);
         TEST_ASSERT_EQUAL_INT(NON_IMAGETTE_HEADER_SIZE + 12, s);
         data_p = cmp_ent_get_data_buf(ent);
         for (i = 0; i < 12 ; ++i)
                 data_p[i] = i;
         size = cmp_ent_get_cmp_data(ent, NULL, 0);
         TEST_ASSERT_EQUAL_INT(12, size);
         data_buf = malloc((size_t)size); TEST_ASSERT_NOT_NULL(data_buf);
         size = cmp_ent_get_cmp_data(ent, data_buf, 12);
         TEST_ASSERT_EQUAL_INT(12, size);
         TEST_ASSERT_EQUAL_HEX32(0x00010203, data_buf[0]);
         TEST_ASSERT_EQUAL_HEX32(0x04050607, data_buf[1]);
         TEST_ASSERT_EQUAL_HEX32(0x08090A0B, data_buf[2]);
         /* error cases */
         size = cmp_ent_get_cmp_data(NULL, data_buf, 12);
         TEST_ASSERT_EQUAL_INT(-1, size);
         cmp_ent_set_size(ent, NON_IMAGETTE_HEADER_SIZE + 11);
         size = cmp_ent_get_cmp_data(ent, NULL, 12);
         TEST_ASSERT_EQUAL_INT(-1, size);
         cmp_ent_set_size(ent, NON_IMAGETTE_HEADER_SIZE + 12);
         size = cmp_ent_get_cmp_data(ent, data_buf, 11);
         TEST_ASSERT_EQUAL_INT(-1, size);
         cmp_ent_set_data_type(ent, DATA_TYPE_UNKNOWN, 0);
         size = cmp_ent_get_cmp_data(ent, data_buf, 12);
         TEST_ASSERT_EQUAL_INT(-1, size);
         free(ent);
         free(data_buf);
 }
References cmp_ent_create(), cmp_ent_get_cmp_data(), cmp_ent_get_data_buf(), cmp_ent_set_data_type(), cmp_ent_set_size(), DATA_TYPE_S_FX, DATA_TYPE_UNKNOWN, malloc(), and NON_IMAGETTE_HEADER_SIZE.