cmp_tool: test_random_compression_decompression2
test_random_compression_decompression2()
void test_random_compression_decompression2 (void)
Definition at line 622 of file test_cmp_decmp.c.
 {
         struct cmp_cfg cfg;
         struct cmp_info info = {0};
         uint32_t cmp_buffer_size;
         int s, i, cmp_size_bits;
         void *compressed_data;
         uint16_t *decompressed_data;
         uint16_t data[N_SAMPLES] = {0, UINT16_MAX, INT16_MAX, 42, 23};
         cfg = cmp_cfg_icu_create(DATA_TYPE_IMAGETTE, CMP_MODE_RAW, 8, CMP_LOSSLESS);
         TEST_ASSERT_NOT_EQUAL_INT(cfg.data_type, DATA_TYPE_UNKNOWN);
         cmp_buffer_size = cmp_cfg_icu_buffers(&cfg, data, N_SAMPLES, NULL, NULL,
                                               NULL, N_SAMPLES*CMP_BUFFER_FAKTOR);
         compressed_data = malloc(cmp_buffer_size);
         cmp_buffer_size = cmp_cfg_icu_buffers(&cfg, data, N_SAMPLES, NULL, NULL,
                                               compressed_data, N_SAMPLES*CMP_BUFFER_FAKTOR);
         TEST_ASSERT_EQUAL_INT(cmp_buffer_size, cmp_cal_size_of_data(CMP_BUFFER_FAKTOR*N_SAMPLES, DATA_TYPE_IMAGETTE));
         cmp_size_bits = icu_compress_data(&cfg);
         TEST_ASSERT(cmp_size_bits > 0);
         info.cmp_size = (uint32_t)cmp_size_bits;
         info.cmp_mode_used = (uint8_t)cfg.cmp_mode;
         info.model_value_used = (uint8_t)cfg.model_value;
         info.round_used = (uint8_t)cfg.round;
         info.spill_used = cfg.spill;
         info.golomb_par_used = cfg.golomb_par;
         info.samples_used = cfg.samples;
         info.rdcu_new_model_adr_used = cfg.rdcu_new_model_adr;
         info.rdcu_cmp_adr_used = cfg.rdcu_buffer_adr;
         s = decompress_rdcu_data(compressed_data, &info, NULL, NULL, NULL);
         TEST_ASSERT(s > 0);
         decompressed_data = malloc((size_t)s);
         s = decompress_rdcu_data(compressed_data, &info, NULL, NULL, decompressed_data);
         TEST_ASSERT(s > 0);
         for (i = 0; i < N_SAMPLES; i++)
                 TEST_ASSERT_EQUAL_HEX16(data[i], decompressed_data[i]);
         free(compressed_data);
         free(decompressed_data);
 }
References CMP_BUFFER_FAKTOR, cmp_cal_size_of_data(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), CMP_LOSSLESS, cmp_cfg::cmp_mode, CMP_MODE_RAW, cmp_info::cmp_mode_used, cmp_info::cmp_size, cmp_cfg::data_type, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, decompress_rdcu_data(), cmp_cfg::golomb_par, cmp_info::golomb_par_used, icu_compress_data(), malloc(), cmp_cfg::model_value, cmp_info::model_value_used, N_SAMPLES, cmp_cfg::rdcu_buffer_adr, cmp_info::rdcu_cmp_adr_used, cmp_cfg::rdcu_new_model_adr, cmp_info::rdcu_new_model_adr_used, cmp_cfg::round, cmp_info::round_used, cmp_cfg::samples, cmp_info::samples_used, cmp_cfg::spill, and cmp_info::spill_used.