cmp_tool: test_compress_s_fx_raw
test_compress_s_fx_raw()
void test_compress_s_fx_raw (void)
Definition at line 2764 of file test_cmp_icu.c.
 {
         struct s_fx data[7];
         struct cmp_cfg cfg = {0};
         int cmp_size, cmp_size_exp;
         size_t i;
         struct multi_entry_hdr *hdr;
         cfg.data_type = DATA_TYPE_S_FX;
         cfg.model_buf = NULL;
         cfg.samples = 7;
         cfg.input_buf = malloc(cmp_cal_size_of_data(cfg.samples, cfg.data_type));
         cfg.buffer_length = 7;
         cfg.icu_output_buf = malloc(cmp_cal_size_of_data(cfg.buffer_length, cfg.data_type));
         TEST_ASSERT_NOT_NULL(cfg.icu_output_buf);
         TEST_ASSERT_NOT_NULL(cfg.input_buf);
         data[0].exp_flags = 0x0;
         data[0].fx = 0x0;
         data[1].exp_flags = 0x1;
         data[1].fx = 0x1;
         data[2].exp_flags = 0x2;
         data[2].fx = 0x23;
         data[3].exp_flags = 0x3;
         data[3].fx = 0x42;
         data[4].exp_flags = 0x0;
         data[4].fx = (uint32_t)INT32_MIN;
         data[5].exp_flags = 0x3;
         data[5].fx = INT32_MAX;
         data[6].exp_flags = 0x1;
         data[6].fx = UINT32_MAX;
         hdr = cfg.input_buf;
         memset(hdr, 0x42, sizeof(struct multi_entry_hdr));
         memcpy(hdr->entry, data, sizeof(data));
         cmp_size = icu_compress_data(&cfg);
         cmp_size_exp = (sizeof(data) + sizeof(struct multi_entry_hdr)) * CHAR_BIT;
         TEST_ASSERT_EQUAL_INT(cmp_size_exp, cmp_size);
         for (i = 0; i < ARRAY_SIZE(data); i++) {
                 struct s_fx *p;
                 hdr = (struct multi_entry_hdr *)cfg.icu_output_buf;
                 p = (struct s_fx *)hdr->entry;
                 TEST_ASSERT_EQUAL_HEX(data[i].exp_flags, p[i].exp_flags);
                 TEST_ASSERT_EQUAL_HEX(data[i].fx, cpu_to_be32(p[i].fx));
         }
         free(cfg.input_buf);
         free(cfg.icu_output_buf);
 }
References ARRAY_SIZE, cmp_cfg::buffer_length, cmp_cal_size_of_data(), cpu_to_be32, cmp_cfg::data_type, DATA_TYPE_S_FX, multi_entry_hdr::entry, exp_flags, s_fx::exp_flags, fx, s_fx::fx, icu_compress_data(), cmp_cfg::icu_output_buf, cmp_cfg::input_buf, malloc(), cmp_cfg::model_buf, and cmp_cfg::samples.