cmp_tool: test_cmp_ent_build
test_cmp_ent_build()
void test_cmp_ent_build (void)
Test:
cmp_ent_build
error cases
Definition at line 1795 of file test_cmp_entity.c.
 {
         size_t size;
         struct cmp_entity *ent;
         uint32_t version_id;
         uint64_t start_time, end_time;
         uint16_t model_id;
         uint8_t model_counter;
         struct cmp_cfg cfg;
         int cmp_size_bits;
         struct cmp_max_used_bits max_used_bits = {0};
         /* set up max used bit version */
         max_used_bits.version = 42;
         cfg.max_used_bits = &max_used_bits;
         version_id = 42;
         start_time = 100;
         end_time = 200;
         model_id = 12;
         model_counter = 23;
         cfg.data_type = DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE;
         cfg.cmp_mode = CMP_MODE_MODEL_MULTI;
         cfg.model_value = 11;
         cfg.round = 2;
         cfg.samples = 9;
         cfg.spill = MIN_IMA_SPILL;
         cfg.golomb_par = MAX_IMA_GOLOMB_PAR;
         cfg.ap1_spill = 555;
         cfg.ap1_golomb_par = 14;
         cfg.ap2_spill = 333;
         cfg.ap2_golomb_par = 43;
         cmp_size_bits = 60*8;
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+60, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+60, size);
         TEST_ASSERT_EQUAL_INT(version_id, cmp_ent_get_version_id(ent));
         TEST_ASSERT_EQUAL_INT(60, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(cfg.samples, cfg.data_type), cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(start_time, cmp_ent_get_start_timestamp(ent));
         TEST_ASSERT_EQUAL_INT(end_time, cmp_ent_get_end_timestamp(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(cfg.data_type, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(cfg.cmp_mode, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(cfg.model_value, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(model_id, cmp_ent_get_model_id(ent));
         TEST_ASSERT_EQUAL_INT(model_counter, cmp_ent_get_model_counter(ent));
         TEST_ASSERT_EQUAL_INT(max_used_bits.version, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(cfg.round, cmp_ent_get_lossy_cmp_par(ent));
         TEST_ASSERT_EQUAL_INT(cfg.spill, cmp_ent_get_ima_spill(ent));
         TEST_ASSERT_EQUAL_INT(cfg.golomb_par, cmp_ent_get_ima_golomb_par(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap1_spill, cmp_ent_get_ima_ap1_spill(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap1_golomb_par, cmp_ent_get_ima_ap1_golomb_par(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap2_spill, cmp_ent_get_ima_ap2_spill(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap2_golomb_par, cmp_ent_get_ima_ap2_golomb_par(ent));
         /* entity size is smaller than */
         cmp_size_bits = 2;
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+cmp_bit_to_byte((unsigned int)cmp_size_bits), size);
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+cmp_bit_to_byte((unsigned int)cmp_size_bits), size);
         /** error cases **/
         /* cfg = NULL */
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, NULL, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         /* cmp_size_bits negative */
         cmp_size_bits = -1;
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         cmp_size_bits = 60*8;
         /* unknown data type */
         cfg.data_type = DATA_TYPE_UNKNOWN;
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         cfg.data_type = DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE;
 #if 0
         /* version id to high */
         version_id = 0x100000000;
         size = cmp_ent_build(NULL, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
 #endif
         /* start_time to high */
         start_time = 0x1000000000000ULL;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         /* this should work */
         start_time = 0xFFFFFFFFFFFFULL;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+60, size);
         /* end_time to high */
         end_time = 0x1000000000000ULL;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         /* this should work */
         end_time = 0xFFFFFFFFFFFFULL;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+60, size);
         /* golomb_par to high */
         cfg.golomb_par = 0x100;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(0, size);
         /* this should work */
         cfg.golomb_par = 0xFF;
         size = cmp_ent_build(ent, version_id, start_time, end_time, model_id,
                              model_counter, &cfg, cmp_size_bits);
         TEST_ASSERT_EQUAL_UINT(IMAGETTE_ADAPTIVE_HEADER_SIZE+60, size);
         free(ent);
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_bit_to_byte(), cmp_cal_size_of_data(), cmp_ent_build(), cmp_ent_get_cmp_data_size(), cmp_ent_get_cmp_mode(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_get_end_timestamp(), cmp_ent_get_ima_ap1_golomb_par(), cmp_ent_get_ima_ap1_spill(), cmp_ent_get_ima_ap2_golomb_par(), cmp_ent_get_ima_ap2_spill(), cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), cmp_ent_get_lossy_cmp_par(), cmp_ent_get_max_used_bits_version(), cmp_ent_get_model_counter(), cmp_ent_get_model_id(), cmp_ent_get_model_value(), cmp_ent_get_original_size(), cmp_ent_get_start_timestamp(), cmp_ent_get_version_id(), cmp_cfg::cmp_mode, CMP_MODE_MODEL_MULTI, cmp_cfg::data_type, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_UNKNOWN, end_time, cmp_cfg::golomb_par, IMAGETTE_ADAPTIVE_HEADER_SIZE, malloc(), MAX_IMA_GOLOMB_PAR, cmp_cfg::max_used_bits, MIN_IMA_SPILL, model_counter, model_id, cmp_cfg::model_value, cmp_cfg::round, cmp_cfg::samples, cmp_cfg::spill, start_time, cmp_max_used_bits::version, and version_id.