cmp_tool: test_compress_f_fx_efx_ncob_ecob
test_compress_f_fx_efx_ncob_ecob()
void test_compress_f_fx_efx_ncob_ecob (void)
Test:
compress_f_fx_efx_ncob_ecob
Definition at line 3500 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_ncob = 2;
         uint32_t spillover_ncob = 10;
         uint32_t cmp_par_efx = 3;
         uint32_t spillover_efx = 44;
         uint32_t cmp_par_ecob = 5;
         uint32_t spillover_ecob = 55;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+4*sizeof(struct f_fx_efx_ncob_ecob)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct f_fx_efx_ncob_ecob)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct f_fx_efx_ncob_ecob *data_p = (struct f_fx_efx_ncob_ecob *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_EFX_NCOB_ECOB, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                cmp_par_fx, spillover_fx, cmp_par_ncob, spillover_ncob,
                                cmp_par_efx, spillover_efx, cmp_par_ecob, spillover_ecob,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 4, NULL, NULL,
                                                    (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         my_max_used_bits.f_fx = 31;
         my_max_used_bits.f_ncob = 3;
         my_max_used_bits.f_efx = 16;
         my_max_used_bits.f_ecob = 8;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         /* value is to big for the max used bits values */
         data_p[3].fx = 0x80000000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[3].fx = 0x80000000-1;
         data_p[2].ncob_x = 0x8;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].ncob_x = 0x7;
         data_p[1].ncob_y = 0x8;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[1].ncob_y = 0x7;
         data_p[0].efx = 0x10000;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].efx = 0x10000-1;
         data_p[2].ecob_x = 0x100;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[2].ecob_x = 0x100-1;
         data_p[3].ecob_y = 0x100;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[3].ecob_y = 0x100-1;
         my_max_used_bits.f_fx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.f_fx = 32;
         my_max_used_bits.f_ncob = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.f_ncob = 32;
         my_max_used_bits.f_efx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.f_efx = 32;
         my_max_used_bits.f_ecob = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_ncob, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_F_FX_EFX_NCOB_ECOB, DATA_TYPE_UNKNOWN, f_fx_efx_ncob_ecob::ecob_x, f_fx_efx_ncob_ecob::ecob_y, f_fx_efx_ncob_ecob::efx, cmp_max_used_bits::f_ecob, cmp_max_used_bits::f_efx, cmp_max_used_bits::f_fx, cmp_max_used_bits::f_ncob, f_fx_efx_ncob_ecob::fx, icu_compress_data(), MAX_USED_BITS_SAFE, MULTI_ENTRY_HDR_SIZE, f_fx_efx_ncob_ecob::ncob_x, and f_fx_efx_ncob_ecob::ncob_y.