cmp_tool: test_cmp_ent_write_rdcu_cmp_pars
test_cmp_ent_write_rdcu_cmp_pars()
void test_cmp_ent_write_rdcu_cmp_pars (void)
Test:
cmp_ent_write_rdcu_cmp_pars
error cases
Definition at line 1428 of file test_cmp_entity.c.
 {
         int error;
         uint32_t size;
         struct cmp_entity *ent;
         struct cmp_info info;
         struct cmp_cfg cfg;
         info.cmp_mode_used = CMP_MODE_DIFF_ZERO;
         info.spill_used = 42;
         info.golomb_par_used = 23;
         info.samples_used = 9;
         info.cmp_size = 96;
         info.model_value_used = 6;
         info.round_used = 1;
         info.cmp_err = 0;
         /* create a imagette compression entity */
         size = cmp_ent_create(NULL, DATA_TYPE_IMAGETTE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, DATA_TYPE_IMAGETTE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, NULL);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_IMAGETTE, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(12, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(info.samples_used, DATA_TYPE_IMAGETTE), cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(info.cmp_mode_used, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(info.model_value_used, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(info.round_used, cmp_ent_get_lossy_cmp_par(ent));
         TEST_ASSERT_EQUAL_INT(info.spill_used, cmp_ent_get_ima_spill(ent));
         TEST_ASSERT_EQUAL_INT(info.golomb_par_used, cmp_ent_get_ima_golomb_par(ent));
         free(ent);
         /* raw mode test */
         /* create a raw imagette compression entity */
         info.cmp_mode_used = CMP_MODE_RAW;
         size = cmp_ent_create(NULL, DATA_TYPE_IMAGETTE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, DATA_TYPE_IMAGETTE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, NULL);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_IMAGETTE, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(1, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(12, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(info.samples_used, DATA_TYPE_IMAGETTE), cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(info.cmp_mode_used, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(info.model_value_used, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(info.round_used, cmp_ent_get_lossy_cmp_par(ent));
         free(ent);
         /* adaptive configuration */
         info.cmp_mode_used = CMP_MODE_MODEL_MULTI;
         cfg.ap1_golomb_par = 0xFF;
         cfg.ap1_spill = 1;
         cfg.ap2_golomb_par = 0x32;
         cfg.ap2_spill = 201;
         /* create a adaptive imagette compression entity */
         size = cmp_ent_create(NULL, DATA_TYPE_IMAGETTE_ADAPTIVE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         ent = malloc(size); TEST_ASSERT_NOT_NULL(ent);
         size = cmp_ent_create(ent, DATA_TYPE_IMAGETTE_ADAPTIVE, info.cmp_mode_used == CMP_MODE_RAW, 12);
         TEST_ASSERT_NOT_EQUAL_INT(0, size);
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(DATA_TYPE_IMAGETTE_ADAPTIVE, cmp_ent_get_data_type(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_data_type_raw_bit(ent));
         TEST_ASSERT_EQUAL_INT(12, cmp_ent_get_cmp_data_size(ent));
         TEST_ASSERT_EQUAL_INT(cmp_cal_size_of_data(info.samples_used, DATA_TYPE_IMAGETTE_ADAPTIVE), cmp_ent_get_original_size(ent));
         TEST_ASSERT_EQUAL_INT(info.cmp_mode_used, cmp_ent_get_cmp_mode(ent));
         TEST_ASSERT_EQUAL_INT(info.model_value_used, cmp_ent_get_model_value(ent));
         TEST_ASSERT_EQUAL_INT(0, cmp_ent_get_max_used_bits_version(ent));
         TEST_ASSERT_EQUAL_INT(info.round_used, cmp_ent_get_lossy_cmp_par(ent));
         TEST_ASSERT_EQUAL_INT(info.spill_used, cmp_ent_get_ima_spill(ent));
         TEST_ASSERT_EQUAL_INT(info.golomb_par_used, cmp_ent_get_ima_golomb_par(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap1_spill, cmp_ent_get_ima_ap1_spill(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap1_golomb_par, cmp_ent_get_ima_ap1_golomb_par(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap2_spill, cmp_ent_get_ima_ap2_spill(ent));
         TEST_ASSERT_EQUAL_INT(cfg.ap2_golomb_par, cmp_ent_get_ima_ap2_golomb_par(ent));
         /** error cases **/
         /* ent = NULL */
         error = cmp_ent_write_rdcu_cmp_pars(NULL, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         /* info = NULL */
         error = cmp_ent_write_rdcu_cmp_pars(ent, NULL, &cfg);
         TEST_ASSERT_TRUE(error);
         /* cfg = NULL and adaptive data type */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, NULL);
         TEST_ASSERT_TRUE(error);
         /* compressed data are to big for the compression entity */
         info.cmp_size = 12*8 + 1;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.cmp_size = 1;
         /* wrong data_type */
         cmp_ent_set_data_type(ent, DATA_TYPE_S_FX, 0);
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cmp_ent_set_data_type(ent, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, 0);
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* original_size to high */
         info.samples_used = 0x800000;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.samples_used = 0x7FFFFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* cmp_mode to high */
         info.cmp_mode_used = 0x100;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.cmp_mode_used = 0xFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         TEST_ASSERT_EQUAL_INT(1, sizeof(info.model_value_used));
         TEST_ASSERT_EQUAL_INT(1, sizeof(info.round_used));
 #if 0
         /* max model_value to high */
         info.model_value_used = 0x100;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.model_value_used = 0xFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* max lossy_cmp_par to high */
         info.round = 0x10000;
         error = cmp_ent_write_cmp_pars(ent, &cfg, cmp_size_bits);
         TEST_ASSERT_TRUE(error);
         info.round = 0xFFFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
 #endif
         /* spill to high */
         info.spill_used = 0x10000;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.spill_used = 0xFFFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* golomb_par to high */
         info.golomb_par_used = 0x100;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.golomb_par_used = 0xFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* adaptive 1 spill to high */
         cfg.ap1_spill = 0x10000;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cfg.ap1_spill = 0xFFFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* adaptive 1  golomb_par to high */
         cfg.ap1_golomb_par = 0x100;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cfg.ap1_golomb_par = 0xFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* adaptive 2 spill to high */
         cfg.ap2_spill = 0x10000;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cfg.ap2_spill = 0xFFFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* adaptive 2  golomb_par to high */
         cfg.ap2_golomb_par = 0x100;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cfg.ap2_golomb_par = 0xFF;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* The entity's raw data bit is not set, but the configuration contains raw data */
         info.cmp_mode_used = CMP_MODE_RAW;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.cmp_mode_used = CMP_MODE_MODEL_MULTI;
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* The entity's raw data bit is set, but the configuration contains no raw data */
         cmp_ent_set_data_type(ent, DATA_TYPE_IMAGETTE_ADAPTIVE, 1); /* set raw bit */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         cmp_ent_set_data_type(ent, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, 0);
         /* this should work */
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_FALSE(error);
         /* compression error set */
         info.cmp_err = 1;
         error = cmp_ent_write_rdcu_cmp_pars(ent, &info, &cfg);
         TEST_ASSERT_TRUE(error);
         info.cmp_err = 0;
         free(ent);
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_cal_size_of_data(), cmp_ent_create(), cmp_ent_get_cmp_data_size(), cmp_ent_get_cmp_mode(), cmp_ent_get_data_type(), cmp_ent_get_data_type_raw_bit(), cmp_ent_get_ima_ap1_golomb_par(), cmp_ent_get_ima_ap1_spill(), cmp_ent_get_ima_ap2_golomb_par(), cmp_ent_get_ima_ap2_spill(), cmp_ent_get_ima_golomb_par(), cmp_ent_get_ima_spill(), cmp_ent_get_lossy_cmp_par(), cmp_ent_get_max_used_bits_version(), cmp_ent_get_model_value(), cmp_ent_get_original_size(), cmp_ent_set_data_type(), cmp_ent_write_cmp_pars(), cmp_ent_write_rdcu_cmp_pars(), cmp_info::cmp_err, CMP_MODE_DIFF_ZERO, CMP_MODE_MODEL_MULTI, CMP_MODE_RAW, cmp_info::cmp_mode_used, cmp_info::cmp_size, DATA_TYPE_F_CAM_IMAGETTE_ADAPTIVE, DATA_TYPE_IMAGETTE, DATA_TYPE_IMAGETTE_ADAPTIVE, DATA_TYPE_S_FX, cmp_info::golomb_par_used, malloc(), cmp_info::model_value_used, cmp_info::round_used, cmp_info::samples_used, and cmp_info::spill_used.