cmp_tool: test_cmp_ent_cal_hdr_size
test_cmp_ent_cal_hdr_size()
void test_cmp_ent_cal_hdr_size (void)
Test:
cmp_ent_cal_hdr_size
Definition at line 40 of file test_cmp_entity.c.
 {
         uint32_t hdr_size;
         enum cmp_data_type data_type;
         int raw_mode_flag;
         /* raw_mode test */
         raw_mode_flag = 1;
         for (data_type = DATA_TYPE_IMAGETTE; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
                 TEST_ASSERT_EQUAL_INT(GENERIC_HEADER_SIZE, hdr_size);
         }
         /* non raw_mode test */
         raw_mode_flag = 0;
         for (data_type = DATA_TYPE_IMAGETTE; data_type <= DATA_TYPE_F_CAM_BACKGROUND; data_type++) {
                 hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
                 if (cmp_imagette_data_type_is_used(data_type)) {
                         if (cmp_ap_imagette_data_type_is_used(data_type))
                                 TEST_ASSERT_EQUAL_INT(IMAGETTE_ADAPTIVE_HEADER_SIZE, hdr_size);
                         else
                                 TEST_ASSERT_EQUAL_INT(IMAGETTE_HEADER_SIZE, hdr_size);
                 } else {
                         TEST_ASSERT_EQUAL_INT(NON_IMAGETTE_HEADER_SIZE, hdr_size);
                 }
         }
         /* error case raw_mode*/
         raw_mode_flag = 1;
         data_type = DATA_TYPE_UNKNOWN;
         hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
         TEST_ASSERT_EQUAL_INT(0, hdr_size);
         data_type = (enum cmp_data_type)~0;
         hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
         TEST_ASSERT_EQUAL_INT(0, hdr_size);
         /* error case non raw_mode*/
         raw_mode_flag = 0;
         data_type = DATA_TYPE_UNKNOWN;
         hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
         TEST_ASSERT_EQUAL_INT(0, hdr_size);
         data_type = (enum cmp_data_type)~0;
         hdr_size = cmp_ent_cal_hdr_size(data_type, raw_mode_flag);
         TEST_ASSERT_EQUAL_INT(0, hdr_size);
 }
References cmp_ap_imagette_data_type_is_used(), cmp_ent_cal_hdr_size(), cmp_imagette_data_type_is_used(), data_type, DATA_TYPE_F_CAM_BACKGROUND, DATA_TYPE_IMAGETTE, DATA_TYPE_UNKNOWN, GENERIC_HEADER_SIZE, IMAGETTE_ADAPTIVE_HEADER_SIZE, IMAGETTE_HEADER_SIZE, and NON_IMAGETTE_HEADER_SIZE.