cmp_tool: generate_random_cmp_par
generate_random_cmp_par()
void generate_random_cmp_par (struct cmp_cfg * cfg)
generate random compression configuration
Parameters
cfg pointer to a compression configuration
Definition at line 418 of file test_cmp_decmp.c.
 {
         cfg->golomb_par = cmp_rand_between(MIN_IMA_GOLOMB_PAR, MAX_IMA_GOLOMB_PAR);
         cfg->ap1_golomb_par = cmp_rand_between(MIN_IMA_GOLOMB_PAR, MAX_IMA_GOLOMB_PAR);
         cfg->ap2_golomb_par = cmp_rand_between(MIN_IMA_GOLOMB_PAR, MAX_IMA_GOLOMB_PAR);
         cfg->cmp_par_exp_flags = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_fx = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_ncob = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_efx = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_ecob = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_fx_cob_variance = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_mean = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_variance = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->cmp_par_pixels_error = cmp_rand_between(MIN_NON_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR);
         cfg->spill = cmp_rand_between(MIN_IMA_SPILL, cmp_ima_max_spill(cfg->golomb_par));
         cfg->ap1_spill = cmp_rand_between(MIN_IMA_SPILL, cmp_ima_max_spill(cfg->ap1_golomb_par));
         cfg->ap2_spill = cmp_rand_between(MIN_IMA_SPILL, cmp_ima_max_spill(cfg->ap2_golomb_par));
         cfg->spill_exp_flags = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_exp_flags));
         cfg->spill_fx = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_fx));
         cfg->spill_ncob = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_ncob));
         cfg->spill_efx = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_efx));
         cfg->spill_ecob = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_ecob));
         cfg->spill_fx_cob_variance = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_fx_cob_variance));
         cfg->spill_mean = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_mean));
         cfg->spill_variance = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_variance));
         cfg->spill_pixels_error = cmp_rand_between(MIN_NON_IMA_SPILL, cmp_icu_max_spill(cfg->cmp_par_pixels_error));
 #if 0
         if (cfg->cmp_mode == CMP_MODE_STUFF) {
                 /* cfg->golomb_par = cmp_rand_between(16, MAX_STUFF_CMP_PAR); */
                 cfg->golomb_par = 16;
                 cfg->ap1_golomb_par = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->ap2_golomb_par = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_exp_flags = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_fx = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_ncob = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_efx = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_ecob = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_fx_cob_variance = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_mean = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_variance = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 cfg->cmp_par_pixels_error = cmp_rand_between(0, MAX_STUFF_CMP_PAR);
                 return;
         }
 #endif
 }
References cmp_cfg::ap1_golomb_par, cmp_cfg::ap1_spill, cmp_cfg::ap2_golomb_par, cmp_cfg::ap2_spill, cmp_icu_max_spill(), cmp_ima_max_spill(), cmp_cfg::cmp_mode, CMP_MODE_STUFF, cmp_cfg::cmp_par_ecob, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_exp_flags, cmp_cfg::cmp_par_fx, cmp_cfg::cmp_par_fx_cob_variance, cmp_cfg::cmp_par_mean, cmp_cfg::cmp_par_ncob, cmp_cfg::cmp_par_pixels_error, cmp_cfg::cmp_par_variance, cmp_rand_between(), cmp_cfg::golomb_par, MAX_IMA_GOLOMB_PAR, MAX_NON_IMA_GOLOMB_PAR, MAX_STUFF_CMP_PAR, MIN_IMA_GOLOMB_PAR, MIN_IMA_SPILL, MIN_NON_IMA_GOLOMB_PAR, MIN_NON_IMA_SPILL, cmp_cfg::spill, cmp_cfg::spill_ecob, cmp_cfg::spill_efx, cmp_cfg::spill_exp_flags, cmp_cfg::spill_fx, cmp_cfg::spill_fx_cob_variance, cmp_cfg::spill_mean, cmp_cfg::spill_ncob, cmp_cfg::spill_pixels_error, and cmp_cfg::spill_variance.
Referenced by test_random_compression_decompression().