cmp_tool: test_compress_f_fx_efx_error_cases
test_compress_f_fx_efx_error_cases()
void test_compress_f_fx_efx_error_cases (void)
Test:
compress_f_fx_efx
Definition at line 3366 of file test_cmp_icu.c.
 {
         int error, cmp_bits;
         uint32_t compressed_data_size;
         struct cmp_cfg cfg = {0};
         uint32_t cmp_par_fx = 1;
         uint32_t spillover_fx = 8;
         uint32_t cmp_par_efx = 1;
         uint32_t spillover_efx = 8;
         uint8_t data_to_compress[MULTI_ENTRY_HDR_SIZE+2*sizeof(struct f_fx_efx)] = {0};
         uint8_t compressed_data[MULTI_ENTRY_HDR_SIZE+1*sizeof(struct f_fx_efx)] = {0};
         struct cmp_max_used_bits my_max_used_bits = MAX_USED_BITS_SAFE;
         struct f_fx_efx *data_p = (struct f_fx_efx *)&data_to_compress[MULTI_ENTRY_HDR_SIZE];
         my_max_used_bits.f_fx = 23;
         my_max_used_bits.f_efx = 31;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cfg = cmp_cfg_icu_create(DATA_TYPE_F_FX_EFX, CMP_MODE_DIFF_ZERO, 0, CMP_LOSSLESS);
         TEST_ASSERT(cfg.data_type != DATA_TYPE_UNKNOWN);
         error = cmp_cfg_fx_cob(&cfg, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                cmp_par_fx, spillover_fx, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED, cmp_par_efx, spillover_efx,
                                CMP_PAR_UNUSED, CMP_PAR_UNUSED, CMP_PAR_UNUSED,
                                CMP_PAR_UNUSED);
         TEST_ASSERT_FALSE(error);
         compressed_data_size = cmp_cfg_icu_buffers(&cfg, data_to_compress, 2, NULL, NULL,
                                                    (uint32_t *)compressed_data, 1);
         TEST_ASSERT_EQUAL_INT(sizeof(compressed_data), compressed_data_size);
         /* compressed data are to small for the compressed_data buffer */
         data_p[0].fx = 42;
         data_p[0].efx = 42;
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_SMALL_BUF, cmp_bits);
         /* fx value is to big for the max used bits values */
         data_p[0].fx = 0x800000;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].fx = 0x7FFFFF;
         /* efx value is to big for the max used bits values */
         data_p[0].efx = 0x80000000;
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(CMP_ERROR_HIGH_VALUE, cmp_bits);
         data_p[0].efx = 0x7FFFFFFF;
         my_max_used_bits.f_fx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
         my_max_used_bits.f_fx = 32;
         my_max_used_bits.f_efx = 33; /* more than 32 bits are not allowed */
         cmp_cfg_icu_max_used_bits(&cfg, &my_max_used_bits);
         cmp_bits = icu_compress_data(&cfg);
         TEST_ASSERT_EQUAL_INT(-1, cmp_bits);
 }
References cmp_cfg_fx_cob(), cmp_cfg_icu_buffers(), cmp_cfg_icu_create(), cmp_cfg_icu_max_used_bits(), CMP_ERROR_HIGH_VALUE, CMP_ERROR_SMALL_BUF, CMP_LOSSLESS, CMP_MODE_DIFF_ZERO, cmp_cfg::cmp_par_efx, cmp_cfg::cmp_par_fx, CMP_PAR_UNUSED, cmp_cfg::data_type, DATA_TYPE_F_FX_EFX, DATA_TYPE_UNKNOWN, f_fx_efx::efx, cmp_max_used_bits::f_efx, cmp_max_used_bits::f_fx, f_fx_efx::fx, icu_compress_data(), MAX_USED_BITS_SAFE, and MULTI_ENTRY_HDR_SIZE.