cmp_tool: test_decode_multi
test_decode_multi()
void test_decode_multi (void)
Test:
decode_multi
Definition at line 745 of file test_decmp.c.
 {
         uint32_t decoded_value = ~0U;
         uint32_t cmp_data[] = {0x16B66DF8, 0x84360000};
         struct decoder_setup setup = {0};
         struct bit_decoder dec = {0};
         int err;
         cpu_to_be32s(&cmp_data[0]);
         cpu_to_be32s(&cmp_data[1]);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_MULTI, 3, 8, CMP_LOSSLESS, 16);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(0, decoded_value);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(1, decoded_value);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(7, decoded_value);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(8, decoded_value);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(9, decoded_value);
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         TEST_ASSERT_EQUAL_HEX(0x4223, decoded_value);
         /* TEST_ASSERT_EQUAL_INT(47, stream_pos); */
         /* error cases unencoded_len > 32 */
         configure_decoder_setup(&setup, &dec, CMP_MODE_DIFF_MULTI, 3, 8, CMP_LOSSLESS, 16);
         /* 0xFF -> 24 = spill(8)+16 -> unencoded_len = 34 bits */
         cmp_data[0] = cpu_to_be32(0xFF000000);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
         /* 0xFA -> 16 = spill(8)+8 -> unencoded_len = 17 bits -> larger than
          * 16 bit max_used_bits*/
         cmp_data[0] = cpu_to_be32(0xFA000000);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
         /* this should work */
         cmp_data[0] = cpu_to_be32(0xF9000200);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_FALSE(err);
         /* TEST_ASSERT_EQUAL_INT(7+16, stream_pos); */
         TEST_ASSERT_EQUAL_HEX(0x8001+8, decoded_value);
         /* error cases unencoded_val is not plausible */
         /* unencoded_len = 4; unencoded_val =0b0011 */
         cmp_data[0] = cpu_to_be32(0xEC000000);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
         /* unencoded_len = 16; unencoded_val =0x3FFF */
         cmp_data[0] = cpu_to_be32(0xF87FFE00);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
         /* unencoded_len = 16; unencoded_val =0x3FFF */
         cmp_data[0] = cpu_to_be32(0xF87FFE00);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
         /* decoded value smaller that outlier */
         cmp_data[0] = cpu_to_be32(0xF9FFFE00);
         cmp_data[1] = cpu_to_be32(0x00000000);
         bit_init_decoder(&dec, cmp_data, sizeof(cmp_data));
         err = decode_multi(&setup, &decoded_value);
         TEST_ASSERT_EQUAL_INT(-1, err);
 }
References bit_init_decoder(), cmp_data, CMP_LOSSLESS, CMP_MODE_DIFF_MULTI, configure_decoder_setup(), cpu_to_be32, cpu_to_be32s, and decode_multi().