cmp_tool: test_cmp_ent_get_cmp_data_size
test_cmp_ent_get_cmp_data_size()
void test_cmp_ent_get_cmp_data_size (void)
Test:
cmp_ent_get_cmp_data_size
Definition at line 1400 of file test_cmp_entity.c.
 {
         uint32_t cmp_data_size;
         struct cmp_entity ent;
         cmp_ent_set_data_type(&ent, DATA_TYPE_L_FX_EFX, 0);
         cmp_ent_set_size(&ent, 100);
         cmp_data_size = cmp_ent_get_cmp_data_size(&ent);
         TEST_ASSERT_EQUAL_UINT(100-NON_IMAGETTE_HEADER_SIZE, cmp_data_size);
         /* raw mode test */
         cmp_ent_set_data_type(&ent, DATA_TYPE_L_FX_EFX, 1);
         cmp_data_size = cmp_ent_get_cmp_data_size(&ent);
         TEST_ASSERT_EQUAL_UINT(100-GENERIC_HEADER_SIZE, cmp_data_size);
         /* error case */
         cmp_ent_set_data_type(&ent, DATA_TYPE_L_FX_NCOB, 0);
         cmp_ent_set_size(&ent, NON_IMAGETTE_HEADER_SIZE-1);
         cmp_data_size = cmp_ent_get_cmp_data_size(&ent);
         TEST_ASSERT_EQUAL_UINT(0, cmp_data_size);
 }
References cmp_ent_get_cmp_data_size(), cmp_ent_set_data_type(), cmp_ent_set_size(), DATA_TYPE_L_FX_EFX, DATA_TYPE_L_FX_NCOB, GENERIC_HEADER_SIZE, and NON_IMAGETTE_HEADER_SIZE.